### ISSUE TITLE
Code-push Internal Server Error

### ISSUE THREAD

**Issue by 15982153332** [Microsoft/react-native-code-push#1487] opened 2018-12-24 06:27 UTC
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.mac linux :Code-push release-react
2. Internal Server Error

### Environment

* react-native-code-push version:5.5.0
* react-native version:0.57.3
* iOS/Android/Windows version:ios
* Does this reproduce on a debug build or release build?    release
* Does this reproduce on a simulator, or only on a physical device?   device

(The more info the faster we will be able to address it!)

**Comment by Mikelulu** [comment] 2018-12-24 07:10
+1

**Comment by Mikelulu** [comment] 2018-12-24 07:10
[Error]  Internal Server Error

**Comment by minhphung210** [comment] 2018-12-24 07:17
same issue

**Comment by hxx1197411446** [comment] 2018-12-24 08:16
me too

**Comment by Mikelulu** [comment] 2018-12-24 08:17
Now, I can already use it.

**Comment by yuri-kulikov** [comment] 2018-12-24 17:18
Hi everyone, thanks for reporting!
Yes, we had problems with CodePush service, but now it works fine. I'll close the issue for now, but we will continue monitoring this. We really appreciate your feedback.

**Closed by yuri-kulikov** 2018-12-24 17:18 UTC

**Comment by zcmgyu** [comment] 2019-02-27 02:15
Same here

**Comment by alokRamteke** [comment] 2019-03-04 10:06
I am facing the same error.
[Error] Internal Server Error

**Comment by yuri-kulikov** [comment] 2019-03-04 14:03
Hey @zcmgyu, @alokRamteke,
Thanks for reporting and sorry for the delay!

Are you still experiencing this problem? Or how long did it last?
I can't reproduce it at the moment.

**Comment by xwartz** [comment] 2019-03-23 15:04
I'm getting the same issue

**Comment by DCbryant** [comment] 2019-04-16 11:26
I'm getting the same issue!!!

**Comment by Grohden** [comment] 2019-05-02 20:21
I'm getting the same issue :P
is there any log that we can get that can help?

**Comment by andy-io** [comment] 2019-05-02 20:36
i have the issue now

**Comment by J-Cat** [comment] 2019-05-02 20:48
Me too

**Comment by Dnld** [comment] 2019-05-02 20:52
Us too. Unfortunately, the status page has not been updated to reflect the disruption: https://status.appcenter.ms

**Comment by HY1221** [comment] 2019-06-10 17:35
Oct 6, 2019
code-push 2.1.9
node 10.15.3

Internal Server Error

**Comment by salaaar** [comment] 2019-07-14 14:51
Same error

**Comment by hengkx** [comment] 2020-07-06 08:07
+1
