### ISSUE TITLE
Should I generate a native build when i add native libraries in react native 0.61+?

### ISSUE THREAD

**Issue by HannanShaik** [microsoft/react-native-code-push#1870] opened 2020-06-03 19:02 UTC
I have been using RN 0.61.+ for my android and ios app with Codepush for remote JS updates.

With react native auto-linking enabled in 0.60+. When we add a native library, there is no native code added in the android and ios folders except that we need to do a pod install for iOS.

Does this mean I can simply do update to users with JS Bundle on codepush and it will pick up? Or do I have to create native builds and release on stores?

**Comment by alexandergoncharov** [comment] 2020-06-04 09:33
Hi @HannanShaik ,
Thanks for reporting!

Our recommendation is to do a new native build if you make any changes in the native part. But the main thing here that your new js bundle should works correctly with the old native part. It depends on changes. I think that in your case all will be corrected for Android but I'm not sure about IOS as you had to do a `pod install`. You can just tested it manually to ensure.

**Comment by andreidubov** [comment] 2020-06-11 11:36
Since there is no answer and we cannot reproduce it I’m going to close this issue for now. Please feel free to reopen it if you have any questions or issues.

**Closed** 2020-06-11 11:35 UTC
Labels: question, waiting-for-clarification
