### ISSUE TITLE
Problem with restartApp and Modal is showing

### ISSUE THREAD

**Issue by nighttiger1990** [microsoft/react-native-code-push#1745] opened 2019-12-20 12:13 UTC
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Show Modal
2. call Codepush.restartApp
3. App restart with Modal has still showing and can't hidden

### Expected Behavior
What you expected to happen?
App really restart

### Actual Behavior
What actually happens?
```
 Im making CustomDialog for UpdateDialog. sometime, after calling Codepush.restartApp, app restart with Dialog is still showing. This behavior is incorrect. 
```

### Environment

* react-native-code-push version: 6.0.0
* react-native version: 0.61.5
* iOS/Android/Windows version: iOS 11.4
* Does this reproduce on a debug build or release build? Debug
* Does this reproduce on a simulator, or only on a physical device? Physical Device

(The more info the faster we will be able to address it!)

**Comment by alexandergoncharov** [comment] 2020-02-11 10:53
Hi @nighttiger1990,

Unfortunately I can't reproduce your issue. All works correctly. 
Could you please provide you code example or reprosteps?
I'm going to close this issue for now. Please feel free to reopen it when you provide code example or if you have any questions.

Here is my code example:
```


import React, { Component } from 'react';
import { Modal, Text, TouchableHighlight, View, Alert } from 'react-native';
import CodePush from "react-native-code-push";

class App extends Component {
    state = {
        modalVisible: false,
    };
    setModalVisible(visible) {
        this.setState({ modalVisible: visible });
    }
    render() {
        return (
            <View style={{ marginTop: 250, marginLeft: 50 }}>
                <Modal
                    animationType="slide"

                    transparent={false}
                    visible={this.state.modalVisible}
                    onRequestClose={() => {
                        Alert.alert('Modal has been closed.');
                    }}>
                    <View style={{ marginTop: 250, marginLeft: 50 }}>
                        <View>
                            <Text>Stubs</Text>
                            <TouchableHighlight
                                onPress={() => {
                                    CodePush.sync({ installMode: CodePush.InstallMode.IMMEDIATE, updateDialog: true });
                                }}>
                                <Text>CodePush CheckStatus</Text>
                            </TouchableHighlight>
                            <TouchableHighlight
                                onPress={() => {
                                    this.setModalVisible(!this.state.modalVisible);
                                }}>
                                <Text>Hide Modal</Text>
                            </TouchableHighlight>
                        </View>
                    </View>
                </Modal>
                <TouchableHighlight
                    onPress={() => {
                        this.setModalVisible(true);
                    }}>
                    <Text>Show Modal</Text>
                </TouchableHighlight>
            </View>
        );
    }
}

let codePushOptions = { checkFrequency: CodePush.CheckFrequency.MANUAL };

App = CodePush(codePushOptions)(App);

export default App; 
```

**Closed by alexandergoncharov** 2020-02-11 10:53 UTC

**Comment by thuan-nguyen-js** [comment] 2020-02-12 09:39
@alexandergoncharov  this problem only in Android. iOS work correctly. When you restart app in react native with <Modal isVisible={true} /> in Android. Modal keep showing and can not interact

**Comment by gitSirzh** [comment] 2021-05-24 05:46
I have the same problem, the Android platform.

**Comment by aurangs7** [comment] 2023-10-04 10:13
Same issue still 2023
