### ISSUE TITLE
Android showing updateDialog even though there are no updates targeted for the current binary

### ISSUE THREAD

**Issue by RuanFluid** [Microsoft/react-native-code-push#984] opened 2017-08-31 11:35 UTC
Good day,

I recently changed (in dev) my codepush settings as I am using redux-persist and need to be able to clear a users state on demand, thus enabling mandatory updates to be immediate and show the user a dialog. This all works fine on iOS. On android however, the dialog is consistently showing up on multiple devices. 

If I had prepped/released a codepush version targeting the specific binary (in my case 3.0.0) the this would be fine, below please see prod and staging release history.

Can you please advise on what could be causing this? CodeSync code below:

Production Release History:
![image](https://user-images.githubusercontent.com/19907212/29921254-dd551d86-8e48-11e7-809f-b642d09ab424.png)

Staging Release History:
![image](https://user-images.githubusercontent.com/19907212/29921273-e947f9f6-8e48-11e7-83b9-48a8b78019f6.png)

### Expected Behavior
Not show the dialog on android

### Actual Behavior
Show the updateDialog on android
```javascript
codePush.sync({
            installMode: codePush.InstallMode.ON_NEXT_SUSPEND,
            mandatoryInstallMode: codePush.InstallMode.IMMEDIATE,
            updateDialog: {
                title: "An update is available!"
            },
        }, (status) => {
            switch (status) {
                case codePush.SyncStatus.CHECKING_FOR_UPDATE:
                    console.log("Checking for updates.");
                    break;
                case codePush.SyncStatus.DOWNLOADING_PACKAGE:
                    console.log("Downloading package.");
                    break;
                case codePush.SyncStatus.INSTALLING_UPDATE:
                    console.log("Installing update.");
                    break;
                case codePush.SyncStatus.UP_TO_DATE:
                    console.log("Up-to-date.");
                    break;
                case codePush.SyncStatus.UPDATE_INSTALLED: // Once package has been installed
                    // DO SOME MAGIC SHIT
                    
                    // Hide "downloading" modal
                    break;
            }
        }, ({ receivedBytes, totalBytes, }) => {
          /* Update download modal progress */
        });
```
### Environment
* "react-native-code-push": "^1.17.4-beta"
* react-native version:
  * react-native-cli: 2.0.1
  * react-native: 0.42.3
* Android version: Multiple devices and versions
* Does this reproduce on a debug build or release build?
So far only on Debug (Beta) versions
* Does this reproduce on a simulator, or only on a physical device?
Simulator and physical device

**Comment by RuanFluid** [comment] 2017-08-31 11:37
Please see the logs from accepting/installing the download:

![image](https://user-images.githubusercontent.com/19907212/29921337-1fe05882-8e49-11e7-8818-fffb84b443dc.png)

**Comment by sergey-akhalkov** [comment] 2017-08-31 11:56
Hi @RuanFluid, thanks for reaching us!

There are some items we need to clarify, they should help us avoid some problems and determine the root cause of the issue:

1. Are you using different CodePush apps to release updates? From official docs:
>As with all other React Native plugins, the integration experience is different for iOS and Android, so perform the following setup steps depending on which platform(s) you are targeting. Note, if you are targeting both platforms it is recommended to create separate CodePush applications for each platform.

2. You should not test CodePush update in Debug mode, from official docs: 
>NOTE: CodePush updates should be tested in modes other than Debug mode. In Debug mode, React Native app always downloads JS bundle generated by packager, so JS bundle downloaded by CodePush does not apply.

3. What CodePush command are you using to release updates for Android and iOS apps?

**Comment by RuanFluid** [comment] 2017-08-31 12:05
Hi Sergey,

Please see comments below:
#1: We have not updated to use separate apps (please not that this was not an issue before)
#2: We were not testing debug mode, but realised it was happening, more importantly this is happening on actual devices (Play Store Beta), so it would not be considered DEBUG mode.
#3: As per point 1, this was never an issue before, but below are the 2 lines we use to release updates:
code-push release-react Fluid-iOS ios --targetBinaryVersion “x.x.x”
code-push release-react Fluid-iOS android --targetBinaryVersion “x.x.x”

**Comment by sergey-akhalkov** [comment] 2017-08-31 12:24
@RuanFluid, thanks for the response. 
I believe the issue happens because of you are using the same CodePush app `Fluid-iOS` both for Android and iOS, please let me explain. When you release an update - react-native compile all your js files into the single js bundle, this bundle has different names for Android and iOS platforms: 
1. For Android - `index.android.bundle`
2. For iOS - `main.jsbundle`

That the reason why you are receiving this error ![image](https://user-images.githubusercontent.com/19907212/29921337-1fe05882-8e49-11e7-8818-fffb84b443dc.png)
Android app tries to download CodePush update that has been release for iOS, so this update contains `main.jsbundle` inside, not `index.android.bundle`

To fix the issue you should add another CodePush app for Android and use it further to release udpates.

Please let me know if you have any questions.

**Comment by RuanFluid** [comment] 2017-08-31 12:25
Hi Sergey,

I understand that logic, my bigger concern really is that I have no codepush releases targeting a 3.0.0 binary (or any variation thereof), so why would it so why would it find that there is an update?

**Comment by sergey-akhalkov** [comment] 2017-08-31 12:31
@RuanFluid, as I can see you are using `targetBinaryVersion` parameter, is there a chance if you have released an update that may also target to `3.0.0`? 

Could you please share full release history?

**Comment by RuanFluid** [comment] 2017-08-31 12:34
Hi Sergey, 

I had to zoom out a bit, you'll see above it shows back to v67, v86 was the last one on prod. Below you will see none for staging and up to v70 for prod, none ever target 3.0.0

![image](https://user-images.githubusercontent.com/19907212/29923356-2a089e3e-8e51-11e7-9f3b-d998c479cfea.png)

**Comment by sergey-akhalkov** [comment] 2017-08-31 13:21
@RuanFluid, got it, could you please debug or just add `console.log(queryPackage)` and   `console.log(update)` lines of code just after https://github.com/Microsoft/react-native-code-push/blob/master/CodePush.js#L53 in your `/node_modules/react-native-code-push/CodePush.js` file and share me with output?

**Comment by RuanFluid** [comment] 2017-08-31 13:35
@sergey-akhalkov any ideas?

**Comment by RuanFluid** [comment] 2017-08-31 13:39
Hi Sergey,

Please see screenshot below:

![image](https://user-images.githubusercontent.com/19907212/29926053-31103918-8e5a-11e7-83ba-126a66e9fa85.png)

**Comment by sergey-akhalkov** [comment] 2017-08-31 13:50
@RuanFluid, great, thank you! 
From this output I can see that there is exist update in Production deployment with `label: "v12"` that probably may target to `3.0.0` by semver rules that CodePush server uses. Unfortunately, due to CodePush server design we able to see only last 50 deployment, so probably there is no way to determine `targetBinaryVersion` value in `v12` release.
To fix the issue you can execute `code-push patch Fluid-iOS Production -l v12 --disabled` command to disable this release. Also I would recommend you to create separate CodePush apps for Android and iOS.

Please let me know if you have any questions or see any issues.

**Comment by RuanFluid** [comment] 2017-08-31 13:56
Hi @sergey-akhalkov, 

I tried to run the line you supplied and this was the response:

code-push patch Fluid-iOS Production -l v12 --disabled
[Error]  Release not found for given label.

Please advise?

P.S I will be looking at creating a separate CodePush app going forward.

**Comment by sergey-akhalkov** [comment] 2017-08-31 14:08
@RuanFluid, looks weird, I'm going to investigate why CodePush server allows to download such old release but doesn't allow to disable it.
Seems like the only (and right) way for you now is to create separate CodePush Android app, sorry for the inconvenience.

Please let me know if you have any questions.

**Comment by RuanFluid** [comment] 2017-08-31 14:14
:( Will have to do it I suppose

**Comment by sergey-akhalkov** [comment] 2017-08-31 14:22
@RuanFluid, so I'm closing the issue for now, please feel free to reopen or create new one if you have new questions.

**Closed by sergey-akhalkov** 2017-08-31 14:22 UTC
Labels: android
