### ISSUE TITLE
after installing code push packager is not starting, terminating with error code 11

### ISSUE THREAD

**Issue by ranvirgorai** [Microsoft/react-native-code-push#1090] opened 2017-11-26 07:02 UTC
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. react-native init rnCodepush
2. npm install react-native-code-push --save 
3. rnpm link
4. npm start

### Expected Behavior
packager should start

What you expected to happen?

### Actual Behavior
What actually happens?

 But is crash with the following log
```
Metro Bundler ready.

 ERROR  watch /home/ranvir/myProjects/react-expo/rnCodePush/node_modules/test-exclude/node_modules/path-type ENOSPC
Loading dependency graph...npm ERR! code ELIFECYCLE
npm ERR! errno 11
npm ERR! rnCodePush@0.0.1 start: `node node_modules/react-native/local-cli/cli.js start "--reset-cache"`
npm ERR! Exit status 11
npm ERR! 
npm ERR! Failed at the rnCodePush@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ranvir/.npm/_logs/2017-11-26T06_56_07_357Z-debug.log

```

### Environment

* react-native-code-push version:
* react-native version:
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by max-mironov** [comment] 2017-11-27 08:02
Hey @ranvirgorai, looks odd, can you try to do the following and let me know the results:
```
1) react-native init rnIssue1090
2) cd rnIssue1090
3) npm i
4) npm i react-native-code-push --save
5) react-native link react-native-code-push
6) react-native run-android
```

**Comment by ranvirgorai** [comment] 2017-11-27 12:14
Thanks it working as expected, I Think there is an issue with my code.

**Comment by max-mironov** [comment] 2017-11-27 12:26
@ranvirgorai thanks for updating, good to know that the issue is fixed. I'm closing the current one, please feel free to reach us if you need any help going further!

**Closed by max-mironov** 2017-11-27 12:26 UTC
Labels: waiting-for-clarification
