### ISSUE TITLE
Crash when installing update: TypeError: expected dynamic type double but had type boolean

### ISSUE THREAD

**Issue by damathryx** [Microsoft/react-native-code-push#1014] opened 2017-09-25 03:13 UTC
This only happens on Production android platform. Works fine on iOS

![screen shot 2017-09-25 at 11 06 05 am](https://user-images.githubusercontent.com/14576761/30790934-b34840fc-a1e1-11e7-8743-159e0b68ffda.png)
```
@codePush({
  mandatoryInstallMode: true,
  mandatoryContinueButtonLabel: 'proceed',
  installMode: codePush.InstallMode.ON_NEXT_RESUME,
  checkFrequency: codePush.CheckFrequency.ON_APP_RESUME,
})
```

happens when I make a mandatory update `-m`

it crashes while installing then if you reopen it will download the update again and crash.

### Environment

* react-native-code-push version:2.0.2-beta 
* react-native version:0.46.4 
* iOS/Android/Windows version: any
* Does this reproduce on a debug build or release build? release
* Does this reproduce on a simulator, or only on a physical device? physical

**Comment by max-mironov** [comment] 2017-09-25 06:46
Hi there @damathryx, it looks like RNCP 2.0.2-beta [is incompatible](https://github.com/Microsoft/react-native-code-push#supported-react-native-platforms) with RN 0.46.4 for Android.
Could you please update to RNCP v4.0+ and try again?
Also just to double check - you should use different deployment keys for each platform.

**Comment by damathryx** [comment] 2017-09-26 06:58
@max-mironov  still happens after updating to 5.0.0beta

**Comment by max-mironov** [comment] 2017-09-26 07:02
@damathryx could you please try upgrade to e.g. [5.1.0-beta](https://github.com/Microsoft/react-native-code-push/releases/tag/v5.1.0-beta), because we've restored compatibility with RN46 starting with this version (sorry for confusion here).

**Comment by damathryx** [comment] 2017-09-26 12:57
@max-mironov after upgrading to 5.1.1-beta it still happens when I pushed another mandatory update

**Comment by max-mironov** [comment] 2017-09-26 13:03
@damathryx thanks for reply!
So several questions to clarify:
1) You are using two different apps with different deployment keys, one for iOS and one for Android?
2) Can you confirm that the issue reproduces only with Mandatory install mode and works fine without it?

**Comment by damathryx** [comment] 2017-09-26 13:38
@max-mironov  
1.) yes I am using different deployment keys.
2.) yes, heres my deployment history. after mandatory I the app crashes and other updates doesnt work
![screen shot 2017-09-26 at 9 37 29 pm](https://user-images.githubusercontent.com/14576761/30863179-f83ec448-a302-11e7-9e3b-94a2609b30be.png)

**Comment by max-mironov** [comment] 2017-09-26 14:04
@damathryx thanks!
So looks like you are using incorrect syntaxis here:
```
@codePush({
  mandatoryInstallMode: true,
  mandatoryContinueButtonLabel: 'proceed',
  installMode: codePush.InstallMode.ON_NEXT_RESUME,
  checkFrequency: codePush.CheckFrequency.ON_APP_RESUME,
})
```
Please use it as following for mandatoryInstallMode:
`mandatoryInstallMode: CodePush.InstallMode.IMMEDIATE,` instead. 
Let me know if it helps.

**Comment by HananeAlSamrout** [comment] 2017-09-26 14:28
same issue, didn't work

**Comment by max-mironov** [comment] 2017-09-26 14:31
Hey @HananeAlSamrout, are you also getting `TypeError: expected dynamic type double but had type boolean` in stacktrace?

**Comment by HananeAlSamrout** [comment] 2017-09-26 15:02
no i got com.facebook.react.uimanager.IllegalViewOperationException: Trying to remove a view index above child count 0 view tag: 1

**Comment by max-mironov** [comment] 2017-09-26 15:21
@HananeAlSamrout that is definitely another kind of issue we are hunting for.
You can look at this thread for more details: https://github.com/Microsoft/react-native-code-push/issues/995
Probably some info from this could be helpful.
Also it would be better to move our conversation regarding this to #995. And we would be very grateful if you can help us to reproduce this issue on our side!

**Comment by HananeAlSamrout** [comment] 2017-09-26 16:42
okay @max-mironov  i'll send you the stack trace and the code so you can reproduce it

**Comment by max-mironov** [comment] 2017-09-26 16:46
@HananeAlSamrout awesome, thank you so much!

**Comment by HananeAlSamrout** [comment] 2017-09-26 17:14
okay @max-mironov the solution was the same in #995, i was updating the state in 'UPDATE_INSTALLED', i removed that line and no more crashes, thank you

**Comment by max-mironov** [comment] 2017-09-26 17:21
@HananeAlSamrout thanks for reply. That is good that the issue is fixed for you. I've tried to reproduce it as described [here](https://github.com/Microsoft/react-native-code-push/issues/995#issuecomment-331887103) but it was working for me. If you have some clues what I'm missing it would be much appreciated.

**Comment by TrustTheBoy** [comment] 2017-09-27 11:29
I have this problem, too
 Samsung  Galaxy Note3, android 5.0

```
09-27 19:17:13.337 17209-17209/com.mobilegovernment E/unknown:React: Exception in native call
                                                                     java.lang.IndexOutOfBoundsException: index=1 count=0
                                                                         at android.view.ViewGroup.addInArray(ViewGroup.java:4303)
                                                                         at android.view.ViewGroup.addViewInner(ViewGroup.java:4234)
                                                                         at android.view.ViewGroup.addView(ViewGroup.java:4065)
                                                                         at android.view.ViewGroup.addView(ViewGroup.java:4010)
                                                                         at com.facebook.react.uimanager.ViewGroupManager.addView(ViewGroupManager.java:47)
                                                                         at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:395)
                                                                         at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:179)
                                                                         at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:768)
                                                                         at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:824)
                                                                         at com.facebook.react.uimanager.UIViewOperationQueue.access$1600(UIViewOperationQueue.java:48)
                                                                         at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:870)
                                                                         at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
                                                                         at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136)
                                                                         at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
                                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:775)
                                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:590)
                                                                         at android.view.Choreographer.doFrame(Choreographer.java:559)
                                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:145)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5942)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
09-27 19:17:13.347 17209-17209/com.mobilegovernment E/unknown:React: Tried to remove non-existent frame callback
09-27 19:17:13.347 17209-17209/com.mobilegovernment W/unknown:React: Not flushing pending UI operations because of previously thrown Exception
09-27 19:17:13.357 17209-17209/com.mobilegovernment W/unknown:React: Packager connection already open, nooping.
09-27 19:17:13.357 17209-17209/com.mobilegovernment W/unknown:React: Inspector connection already open, nooping.
````

**Comment by max-mironov** [comment] 2017-09-27 12:00
Folks - I believe that it is not a good idea to mix all your problems in one issue. All your 3 crashes have nothing in common and should be discussed in separate threads. 

@damathryx - I'm pretty sure that your issue will be fixed as described here: https://github.com/Microsoft/react-native-code-push/issues/1014#issuecomment-332208906 so I'm closing the current one, please let me know if you still experience any problems or have any questions.

@TrustTheBoy As far as your problem is not related to the topic starter issue please create a separate one so we can continue discussion of it in another thread. 

Please fill all the relevant fields, specifically:
* react-native-code-push version:
* react-native version:
* Does this reproduce on a debug build or release build?
* How do you initialize your code push within your app
* Do you have any special aspects about your app
* Were you able to update your app previously using the same steps, in other words your app was working well before or you have not tried this before?
* Are you able to reproduce your issue with our [sample app](https://github.com/Microsoft/react-native-code-push/tree/master/Examples/CodePushDemoApp)?

**Closed by max-mironov** 2017-09-27 12:00 UTC
Labels: android, waiting-for-clarification
