### ISSUE TITLE
CodePush.InstallMode.ON_NEXT_RESTART not working properly

### ISSUE THREAD

**Issue by SimchaShats** [Microsoft/react-native-code-push#618] opened 2016-11-23 11:48 UTC
Hi I'm trying to install update after next restart like this: 

```
CodePush.sync({
        installMode: CodePush.InstallMode.ON_NEXT_RESTART,
        mandatoryInstallMode: CodePush.InstallMode.ON_NEXT_RESTART
      },
      (syncStatus) => {
        store.dispatch(appActions.syncCodePush(syncStatus));
      }, (progress) => {
        store.dispatch(appActions.updateCodePush(progress));
      });

```

But it any way does restart for application immediately after downloading updates... I'm doing something wrong? RN-0.37, thanks...

**Comment by vonovak** [comment] 2016-11-23 13:50
duplicate of #617

**Closed** 2016-11-23 19:44 UTC
