### ISSUE TITLE
can only update jsbundle or can only update some assets not all assets

### ISSUE THREAD

**Issue by godf4ther** [microsoft/react-native-code-push#1623] opened 2019-07-12 07:16 UTC

**Comment by andreidubov** [comment] 2020-02-13 09:56
Hi @godf4ther,
Thank you for reporting!

Unfortunately I can't reproduce this issue. Could you please provide detailed reprosteps or test project?

I'm going to close this issue for now. Please feel free to reopen it if you have any questions or issues.

**Closed by andreidubov** 2020-02-13 09:56 UTC
Labels: waiting-for-clarification
