### ISSUE TITLE
cookie can't be kept after restartApp or InstallMode=IMMEDIATE

### ISSUE THREAD

**Issue by kiliwalk** [Microsoft/react-native-code-push#287] opened 2016-04-13 17:37 UTC
version: `"react-native-code-push": "^1.10.0-beta"`.
platform: android
problem: after calling restartApp or syncing a mandatory update(which installmode is IMMEDIATE default),requests to my api server will not take the cookie. but when i quit the app and open manually, everything is ok now.

**Comment by silhouettes** [comment] 2016-04-13 18:01
Hi @kiliwalk, that's an interesting issue. I will try to reproduce it, but in the meantime, it might help to know a few things about your setup:

What Android version are you running?
Is this on a debug/release build, and on an emulator or a physical device?
What API are you using for network requests? e.g. Fetch

**Comment by kiliwalk** [comment] 2016-04-14 02:43
thanks for the response @silhouettes .
* android version: 4.2.2 and 6.0, both tested
* debug and release build, both tested
* physical device
* i'm using the `fetch` api, and set `credentials: 'same-origin'` in the options

**Comment by kiliwalk** [comment] 2016-04-14 02:46
and react native version: `"react-native": "^0.23.0-rc4",`

**Comment by lostintangent** [comment] 2016-04-14 02:52
Interesting. So it doesn't appear to be an Android OS or build config related issue. By any chance, were you able to repro this on the emulator? It would be valuable to know if this is a device only issue. I highly doubt it, but I have to ask :)

**Comment by kiliwalk** [comment] 2016-04-14 07:01
@lostintangent 
test with emulator, same probleam:(
genymotion version: 2.6.0
android version: 6.0.0 API 23

**Comment by silhouettes** [comment] 2016-04-16 01:14
Hi @kiliwalk, so I was able to reproduce your issue with `react-native@0.23.0-rc4` and `react-native-code-push@1.10.0-beta`. However, I was able to fix it by doing both of the following:

1. Upgrade CodePush to the latest (react-native-code-push@1.10.2-beta)
1. Upgrade React Native to the latest (react-native@0.23.1)

The life-cycle of the cookie manager in react-native is a little complex, and it doesn't seem to be handled correctly by the hard restart mechanism we were using in 1.10.0. Since 1.10.0, we've switched to a more lightweight restart mechanism that is quicker and less obtrusive for the end user, however it seems to suffer from a different issue that was fixed as a side effect of the latest version of react-native.

So, upgrading both should fix it for you. Please let me know if that works!

**Comment by kiliwalk** [comment] 2016-04-16 02:36
thank you @silhouettes .
i'd checked the 1.10.1 used mechanism, it used the similar steps as the react native's `Reload JS`.
so, i have to upgrade the native code. ok, though it's a tough thing.
by the way, could u suggest some proper ways to guide the end user to upgrade when native code changes? i'd like code-push to supply some kind of ways to work on this situation. for example, add an option(like --download-url), let the user download the upgraded app. or even we can do an app-level diff to make the upgrade more lightweight. never mind, its just my suggestion:D

**Comment by silhouettes** [comment] 2016-04-16 23:03
I'm so sorry about the inconvenience, and we'd definitely like to make the native upgrade experience smoother. Also, we absolutely love suggestions and are always looking to improve! If you don't mind I have a few questions:

1. With the `--download-url` flag, would that be the URL of the release in the play store? We definitely have the capability to notify of available store updates - would it be sufficient to display a dialogue that simply directs the user to the app store to get whatever is the latest release, or is it important to have a specific URL?
1. By app-level diff, do you mean a diff that includes the native code? We do already have diffing of the script and assets we currently push over the air, although patching native code is very technically challenging.

**Comment by kiliwalk** [comment] 2016-04-17 04:11
* say android(i have no experience on ios publish yet), the `--download-url` may refer to the apk file in my own file server, or an url in the third-party store. or even we can push the apk file in code-push:)
* i have no more know about the app-level diff, but some third-party android stores can supply an incremental update for the native app. i guess its maybe native code patching

**Comment by lostintangent** [comment] 2016-04-17 18:48
@kiliwalk Right now, we're trying to optimize CodePush for use with any binary distribution "store" (e.g. Google Play, App Store, folder share, InTune, MobileIron, etc.). What you're referring to sounds like a good use case of HockeyApp, which would allow releasing new APKs and checking for and downloading updates from them much in the same way as you would using the CodePush SDK (e.g. `hockeyApp.checkForUpdate()`). We're working on better integration between HockeyApp and CodePush, so it's possible that we could do something smarter here long term.

That said, we do plan to support notifying the CodePush client that an update is available that requires a new binary version. For example, if the end user is running `v1.0.0` of your app, and when the app calls `sync` it discovers an update that is targeting `v1.1.0`, we want to let the app know so that it could choose to do something with that information (e.g. display an update prompt). We don't currently do this today, but we want to add this soon.

**Comment by lostintangent** [comment] 2016-04-18 21:16
@kiliwalk I'm going to close this bug for now since the issue appears to be fixed once you upgrade React Native and CodePush. Please let us know if you run into this same issue after you upgrade, and apologies again for the inconvenience!

**Closed by lostintangent** 2016-04-18 21:16 UTC
