### ISSUE TITLE
CodePushDeploymentKey react-native link bug when using firebase

### ISSUE THREAD

**Issue by Yox2l** [Microsoft/react-native-code-push#661] opened 2017-01-05 06:55 UTC
* react-native-code-push version:  1.16.1-beta
* react-native version: 0.39.2

I'm using firebase in my react-native app and therefore I have a **GoogleService-Info.plis**t in my project now when I run the "react-native link" command the **CodePushDeploymentKey** added to  **GoogleService-Info.plist** instead of the **Info.plist** file.

**Comment by axemclion** [comment] 2017-01-05 23:55
Looks like it is due to this line - https://github.com/Microsoft/react-native-code-push/blob/master/scripts/postlink/ios/postlink.js#L52

We need to look for Info.plist, not *Info.plist. 


cc @vladimir-kotikov

**Comment by max-mironov** [comment] 2017-02-22 08:48
Closed it for now as a pull request with fixes has been already merged.

**Closed by max-mironov** 2017-02-22 08:48 UTC

**Comment by jordanmkoncz** [comment] 2017-04-03 02:44
Has this fix made it into a release yet? I've just followed the CodePush setup instructions from scratch, with `"react-native-code-push": "^1.17.3-beta"` being installed, and I had this same issue happen.

**Comment by max-mironov** [comment] 2017-04-03 06:43
@jordanmkoncz hello - yes, that fix should be present in recent [1.17.3 beta](url) version. 
If you still see the issue is it possible for you to open another ticket and fill as much details as possible [here](https://github.com/Microsoft/react-native-code-push/issues/new) and we will look at?

**Comment by jordanmkoncz** [comment] 2017-04-03 08:30
@max-mironov Done :)
