### ISSUE TITLE
Question: Possible to grab bundle from build app?

### ISSUE THREAD

**Issue by D1no** [Microsoft/react-native-code-push#904] opened 2017-06-25 15:25 UTC
We have a CI Set-Up where the react-native code base is build from our repo for iOS and Android. In the same machine we run after that the `code-push release-react ios-app ios` command. This will run another react-native bundle command.

My question: Can we grab the completed js bundle from the android and iOS build directly, so the CI build does not take as long and to make 100% sure that the js payload is definitely the same in the binary and on code push servers?

**Comment by max-mironov** [comment] 2017-07-03 11:13
Hey @D1no, thanks for reaching us. 
So if I correctly get your point the issue is that you have to run `code-push release-react ios-app ios` twice and this causes two separate `react-native bundle` calls which produce the same output?

So this way is it possible for you to use [general release ](https://github.com/Microsoft/code-push/tree/master/cli#releasing-updates-general)command? This will allow you to avoid calling `react-native bundle` each time, you just need to create a bundle once before and then you need to specify the location of the updated app code and assets you want to release. Please let us know if this can work for you?

**Comment by sergey-akhalkov** [comment] 2017-07-05 12:32
@D1no, just a friendly ping.

**Comment by sergey-akhalkov** [comment] 2017-07-07 08:14
Closing this for now, please feel free to reopen.

**Closed by sergey-akhalkov** 2017-07-07 08:14 UTC
Labels: question, waiting-for-clarification

**Comment by D1no** [comment] 2017-07-11 12:22
Sorry, I was on vacation 😇

@max-mironov yes, we we build the app continuously in our CI. Based on ENV variables, the CI system also run the code-push command. My question is simply, if its possible to simply point code-push to the generated js file from the normal CI run. (main.js?)
