### ISSUE TITLE
[Android] Codepush installs the update even when running in debug mode on physical device

### ISSUE THREAD

**Issue by chirag04** [Microsoft/react-native-code-push#439] opened 2016-07-25 15:06 UTC
Code push is trying to install the update from server even when i'm running my app in debug mode on my physical device. I'm using the react-native master branch as of today. I have started seeing this after rn 30 update i guess.

Let me know if i can provide more info.

**Comment by silhouettes** [comment] 2016-07-26 00:28
@chirag04: RN 0.30.0 was just released a few days ago with some breaking changes, and we haven't validated its compatibility with CodePush yet, so it's certainly possible that some features have been broken. Just a few questions to help us diagnose this:

- Are you running on Android or iOS? Are you running the latest `react-native-code-push` version?
- Just to double-check, you've followed these instructions: https://github.com/Microsoft/react-native-code-push#plugin-configuration-ios?
- This was working for you before RN 30, and then got broken after you updated?

Thanks heaps for this report - we will likely validate RN 0.30.0 tomorrow, perform any fixes if needed, and update our [compatibility chart](https://github.com/Microsoft/react-native-code-push#supported-react-native-platforms).

**Comment by chirag04** [comment] 2016-07-26 01:00
- running on android. iOS works fine. Using the latest npm release of code-push.
- yep, follow those instructions correctly.
- yep, it was working fine before RN 30.

Other noticeable change was we change the app version to  v1.0 because of a change in bundle Id. Before changing the bundle Id, app was using v1.5. App name is still the same and using the same deployment keys. Not sure if this is y it's not working correctly.

**Comment by geof90** [comment] 2016-07-29 18:16
@chirag04 Installing the update from the server has always been expected behaviour whether its 0.30 or below. CodePush only doesn't install the update if one of the conditions are met:

1. The targetBinaryVersion of the update doesn't apply to the binary version of your app
2. The packageHash of the update is the same as the one that your app's binary is running
3. The update has already been downloaded on disk. In a debug build, if you make a change and re-run `react-native run-android` with a new change, even though the app already downloaded a CodePush update, the new binary's JS bundle will take precedence. I have personally verified that this still works even in 0.30.

Perhaps you are suggesting that we shouldn't be installing updates at all in debug, or we should have some way to send a timestamp of the binary's build contents to the server so that  the server won't return an older update. We've had a similar request on the Cordova side https://github.com/Microsoft/cordova-plugin-code-push/issues/157. I'm interested to know what your thoughts are.

Will relabel this as "enhancement" since it isn't actually a bug.

**Comment by chirag04** [comment] 2016-07-29 18:22
it seems like it's not installing the update in debug on ios but does install on android. Ideally i would expect code-push to not do anything in debug mode.

**Comment by sergey-akhalkov** [comment] 2017-01-31 15:44
I suppose the docs should be improved to pay attention on the fact, that CodePush updates should not be tested in Debug mode, so I've created #682
Closing this for now, please feel free to reopen it if needed.

**Closed by sergey-akhalkov** 2017-01-31 15:44 UTC
Labels: enhancement
