### ISSUE TITLE
A JS bundle file named "null" could not be found within the downloaded contents. Please check that you are releasing your CodePush updates using the exact same JS bundle file name that was shipped with your app's binary.

### ISSUE THREAD

**Issue by anbingyang** [microsoft/react-native-code-push#1862] opened 2020-05-25 08:54 UTC
![image](https://user-images.githubusercontent.com/28379143/82796565-4f477980-9ea8-11ea-888f-3bd7520c5c35.png)
![image](https://user-images.githubusercontent.com/28379143/82796577-553d5a80-9ea8-11ea-841e-fa3f8b2f0b05.png)

**Comment by alexandergoncharov** [comment] 2020-06-04 10:41
Hi @anbingyang ,
Thanks for reporting!

Could you please provide some demo project with producing issue and reprostes? I would like to reproduce this issue and investigate it.

**Comment by andreidubov** [comment] 2020-06-10 08:34
Since there is no answer and we cannot reproduce it I’m going to close this issue for now. Please feel free to reopen it if you have any questions or issues.

**Closed by andreidubov** 2020-06-10 08:34 UTC
Labels: bug, waiting-for-clarification
