### ISSUE TITLE
IOS failed to replace local failure with new success

### ISSUE THREAD

**Issue by flyjennyetn** [Microsoft/react-native-code-push#938] opened 2017-07-24 03:34 UTC
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Description
ios 跟新成功，替换本地失败
IOS failed to replace local failure with new success

### Additional Information

  "react-native": "0.46.2",
  "react-native-code-push": "^4.0.0-beta",
* iOS version:   Newest

**Comment by sergey-akhalkov** [comment] 2017-07-24 08:03
Hi @flyjennyetn, thanks for reaching us. Could you please fill out all points from the [new issue](https://github.com/Microsoft/react-native-code-push/issues/new) template - repro steps, stack trace and etc. so we would be able to help you.

**Comment by flyjennyetn** [comment] 2017-07-24 08:34
@sergey-akhalkov   I according to this step
 https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-ios.md

https://github.com/Microsoft/react-native-code-push/blob/master/README.md#multi-deployment-testing

**Comment by sergey-akhalkov** [comment] 2017-07-24 08:41
@flyjennyetn, could you please clarify what the issue is? (provide us stack trace, screenshot or so). Also please provide us exact repro steps how we could reproduce it.

**Comment by flyjennyetn** [comment] 2017-07-25 01:55
@sergey-akhalkov  https://github.com/flyjennyetn/test/tree/master/codePushTest

**Comment by sergey-akhalkov** [comment] 2017-07-25 10:31
Hi @flyjennyetn, thanks for providing us with source codes, could you please clarify how could we reproduce the issue and what the issue is? Also I can see that your `index.ios.js` file is not CodePush'ified.

**Comment by flyjennyetn** [comment] 2017-07-26 02:36
@sergey-akhalkov  I'm sorry  ， I uploaded the wrong project  ，Now has been updated

**Comment by sergey-akhalkov** [comment] 2017-07-26 11:20
Hi @flyjennyetn, if I get it right, you are trying to configure your initial project with CodePush.
So, you could follow this steps:
1. `code-push app add myapp-ios ios react-antive`
1. `react-native init myapp`
2. `cd myapp`
3. `npm i --save react-native-code-push`
4. `react-native link react-native-code-push`
5. replace index.android.js and index.ios.js files from your project with related files from [here](https://github.com/Microsoft/react-native-code-push/tree/master/Examples/CodePushDemoApp). Also copy and past `images` folder and `demo.js` file.
6. `react-native run-ios`

Please also take a look at https://github.com/Microsoft/react-native-code-push/issues/893#issuecomment-317648454, there you can find configured project (that using multi-deployment-testing feature for iOS)  and use it as an example.

So I'm closing this for now, please feel free to reopen if you have any questions. In case you have any issues, please create new one and do important thing - please use [the following template](https://github.com/Microsoft/react-native-code-push/issues/new) to create the issue, otherwise, we'll mark it as incomplete and close.

**Closed by sergey-akhalkov** 2017-07-26 11:20 UTC
Labels: incomplete, no-repro

**Comment by wuyunqiang** [comment] 2017-07-28 07:21
@flyjennyetn  hi 我也遇到这个问题 请问你是怎么解决的啊 还有本地的文件会不会在重新loading后 覆盖codepush更新的文件啊？

**Comment by flyjennyetn** [comment] 2017-07-28 07:38
@wuyunqiang   还没有解决 ，ios都覆盖不了

**Comment by wuyunqiang** [comment] 2017-07-28 07:40
你不是说是你上传错了么？ 你是直接run ios么? 打包后可以么？我不太懂iOS的

**Comment by sergey-akhalkov** [comment] 2017-07-28 07:44
Hi @wuyunqiang, thanks for reaching us. If I get it right we can continue the discussion here https://github.com/Microsoft/react-native-code-push/issues/941, I'll take a look at the issue you've created and let you know if I have any questions.

**Comment by zhangyi5628** [comment] 2018-02-05 02:51
@wuyunqiang  你们问题有解决吗？我的项目也是安卓成功，iOS第一个热更新成功，后边的都会失败，我看download请求成功了

**Comment by wuyunqiang** [comment] 2018-02-05 03:05
我的问题已经解决 我是在debug模式下更新后本地文件后替换掉下载后的文件因此看不到结果 release是正常的。具体参考：https://github.com/Microsoft/react-native-code-push/issues/941
安卓成功 证明服务器配置是没有问题 
iOS第一次更新成功 后面失败 可能是你更新后的代码有问题吧或者看一下你iOS的配置@zhangyi5628 
也可以参考：https://github.com/wuyunqiang/ReactNativeUtil/issues/26
