### ISSUE TITLE
App crashing with OutOfMemoryError Error

### ISSUE THREAD

**Issue by bharadwajagali** [microsoft/react-native-code-push#1789] opened 2020-02-11 07:04 UTC
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
Saw this error in Firebase

### Expected Behavior
App should not crash.

### Actual Behavior
App is crashing with the following error in firebase.

Caused by java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:731)
       at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:941)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1348)
       at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:623)
       at com.microsoft.codepush.react.CodePushNativeModule.getUpdateMetadata(CodePushNativeModule.java:367)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
       at android.os.Looper.loop(Looper.java:154)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
       at java.lang.Thread.run(Thread.java:762)

**For reference adding detailed log's:**

Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
       at android.os.Looper.loop(Looper.java:154)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
       at java.lang.Thread.run(Thread.java:762)

------------------------------------------------------------------------------------------------
Fatal Exception: java.lang.RuntimeException: Could not invoke CodePush.getUpdateMetadata
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:383)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
       at android.os.Looper.loop(Looper.java:154)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version:
  ---- 5.7.0
* react-native version:
  ---- 0.59.10.
* iOS/Android/Windows version: 
   --- Android - Pie
* Does this reproduce on a debug build or release build? 
   --- Release
* Does this reproduce on a simulator, or only on a physical device?
-- Physical Device

(The more info the faster we will be able to address it!)

**Comment by alexandergoncharov** [comment] 2020-02-13 12:42
Hi @bharadwajagali,
Thakns for reporting!

Could you please provide detailed reprosteps or test project with reproducing issue? It isn't clear how we can reproduce this issue.

I'm going to close this issue for now. Please feel free to reopen it if you have any questions or provide more details.

**Closed by alexandergoncharov** 2020-02-13 12:42 UTC

**Comment by abhishekgoel101** [comment] 2023-06-01 04:55
Unable to reproduce, happening for a lot of users as reported in firebase
