### ISSUE TITLE
App becomes very slow when updating source code thanks to codePush

### ISSUE THREAD

**Issue by thibautguedou3** [Microsoft/react-native-code-push#1145] opened 2018-01-15 16:25 UTC
### Steps to Reproduce
1. Update code-push from 5.1.3-beta to 5.2.1
2. Try to update app source code thanks to new version of code-push
3. App becomes real slow

### Expected Behavior
Normal app speed compared to previous

### Actual Behavior
What actually happens?
It takes now several seconds (3 to 10 seconds) to navigate through tabs (we are using react-navigation). When we download the same source code from hockeyapp, the app is performing normally. When we use the update through CodePush, it becomes real slow.

### Environment

* react-native-code-push version: 5.2.1
* react-native version: 0.51.0
* iOS/Android/Windows version: 10.3.1 / 11.2
* Does this reproduce on a debug build or release build? No
* Does this reproduce on a simulator, or only on a physical device? Only on physical device, not on simulator

**Comment by max-mironov** [comment] 2018-01-16 12:32
Hello @thibautguedou3, that looks odd as it seems that there were no significant changes that could affect performance in two latest releases. 
However have you tried to rollback to v.5.1.3 again to see if the issue would be fixed by downgrading react-native-code-push?

**Comment by thibautguedou3** [comment] 2018-01-16 15:18
Hi @max-mironov yes I've just downgraded code-push and in fact the problem goes away. We had updated code push using yarn. No changes where needed in our source code normaly. Any thoughts on what could have happened?

**Comment by max-mironov** [comment] 2018-01-16 15:44
@thibautguedou3 
Looking for the [2 latest releases](https://github.com/Microsoft/react-native-code-push/releases) I don't see any significant changes that could affect performance dramatically, also we've not received more complains regarding this. 
Is it possible for you to share with us working example where this happens so we could investigate it more to get out the reason of the issue?

**Comment by sergey-akhalkov** [comment] 2018-01-19 08:31
@thibautguedou3, I'm closing this for now, but please feel free to reopen the issue and provide us working example where this happens.

**Closed by sergey-akhalkov** 2018-01-19 08:31 UTC
Labels: no-repro, waiting-for-clarification

**Comment by infostreams** [comment] 2018-03-28 07:01
I'm just commenting to say that this issue is probably real. 

My app (react-navigation with a tab navigator, code-push version 5.2.1) would take up to 10 seconds before it became interactive. Basically, I would start the app, have to wait about 10 seconds, and only then did anything respond to user input. My app was completely unresponsive for that period of time. After these 10 seconds, code-push (whatever it was doing) was done, and I could use the app normally at normal speeds. If I disabled/removed code-push the app would be interactive almost instantaneously. I am using codePush.CheckFrequency.ON_APP_RESUME, but the same happened with ON_APP_START.

However, if I downgrade to 5.1.3-beta as @thibautguedou3 did, the issue disappears. My app becomes interactive almost instantaneously.

My environment is exactly identical to thibautguedou3's:
react-native-code-push version: 5.2.1
react-native version: 0.51.0
(react-navigation: 1.0.0-beta.21)
iOS version: 11.2
Does this reproduce on a debug build or release build? No
Does this reproduce on a simulator, or only on a physical device? Only on physical device, not on simulator

**Comment by infostreams** [comment] 2018-03-28 07:38
Possibly related: react-native-code-push v5.1.3-beta depends on code-push 2.0.4, while the older one depends on code-push 1.11.2-beta. Perhaps there's a breaking change or other big change in behaviour between code-push 1.11.2 and 2.0? Just guessing.

**Comment by himanshuzeptonow** [comment] 2023-11-08 18:29
facing similar issue with latest version
