### ISSUE TITLE
Getting codepush working in a RN TypeScript project

### ISSUE THREAD

**Issue by inakianduaga** [Microsoft/react-native-code-push#822] opened 2017-05-02 23:22 UTC
### Description

When bundling the application in a TypeScript codebase, the updates are deployed to codepush servers successfully but the packaged application fails to apply the updates, crashing upon restart 

### Reproduction

Running either

https://github.com/inakianduaga/react-native-demo/blob/master/package.json#L10

(probably expected since Typescript is not run by default by codepush using `release-react` task I guess)

or manually 

https://github.com/inakianduaga/react-native-demo/blob/master/package.json#L11

runs `TypeScript compiler -> RN build to target bundle -> codepush upload of bundle`

React native logs show

```
05-03 01:04:02.615  8498  8514 D ReactNative: [CodePush] Unable to get the hash of the binary's bundled resources - "codepush.gradle" may have not been added to the build definition.
05-03 01:04:03.080  8498  8518 I ReactNativeJS: Running application "ReactNativeTS" with appParams: {"initialProps":{},"rootTag":1}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
05-03 01:04:03.155  8498  8518 I ReactNativeJS: [CodePush] Checking for update.
05-03 01:04:05.799  8498  8518 I ReactNativeJS: [CodePush] Downloading package.
```

So codepush is fetching the updated and downloading it, when app restart it crashes 

### Additional Information

* react-native-code-push version: 2.0.2-beta
* react-native version: 0.43.3
* iOS/Android/Windows version: Android API 25
* Does this reproduce on a debug build or release build? release build
* Does this reproduce on a simulator, or only on a physical device? Android simulator

**Comment by inakianduaga** [comment] 2017-05-02 23:37
Here are more details about the stack trace captured in Android Studio when codepush right after codepush runs the download

```
05-03 01:35:55.321 11433-11464/com.reactnativets W/ResourceType: No package identifier when getting value for resource number 0x00000000
05-03 01:35:55.338 11433-11464/com.reactnativets E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
                                                                   Process: com.reactnativets, PID: 11433
                                                                   java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                       at android.os.AsyncTask$3.done(AsyncTask.java:325)
                                                                       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                       at java.lang.Thread.run(Thread.java:761)
                                                                    Caused by: com.microsoft.codepush.react.CodePushUnknownException: Error in getting binary resources modified time
                                                                       at com.microsoft.codepush.react.CodePush.getBinaryResourcesModifiedTime(CodePush.java:113)
                                                                       at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:232)
                                                                       at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:227)
                                                                       at android.os.AsyncTask$2.call(AsyncTask.java:305)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                       at java.lang.Thread.run(Thread.java:761) 
                                                                    Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0
                                                                       at android.content.res.Resources.getText(Resources.java:335)
                                                                       at android.content.res.Resources.getString(Resources.java:381)
                                                                       at com.microsoft.codepush.react.CodePush.getBinaryResourcesModifiedTime(CodePush.java:110)
                                                                       at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:232) 
                                                                       at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:227) 
                                                                       at android.os.AsyncTask$2.call(AsyncTask.java:305) 
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                       at java.lang.Thread.run(Thread.java:761) 
05-03 01:35:56.103 11433-11433/com.reactnativets I/Choreographer: Skipped 37 frames!  The application may be doing too much work on its main thread.
```

**Comment by inakianduaga** [comment] 2017-05-02 23:43
Upon further investigation it could be the same problem as this issue #771, note that my 

`react-native link react-native-code-push` failed to complete cleanly with an error

```
rnpm-install info Android module react-native-code-push is already linked
rnpm-install info iOS module react-native-code-push is already linked
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/ianduaga/Downloads/react-native-typescript/ios/"ReactNativeTS-tvOSTests/Info.plist"'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.<anonymous> (/Users/ianduaga/Downloads/react-native-typescript/node_modules/react-native-code-push/scripts/postlink/ios/postlink.js:63:24)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
/Users/ianduaga/Downloads/react-native-typescript/node_modules/react-native/local-cli/core/makeCommand.js:29
        throw new Error(`Error occured during executing "${command}" command`);
        ^

Error: Error occured during executing "node node_modules/react-native-code-push/scripts/postlink/run" command
    at ChildProcess.prelink (/Users/ianduaga/Downloads/react-native-typescript/node_modules/react-native/local-cli/core/makeCommand.js:29:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

not sure that would be related

**Comment by sergey-akhalkov** [comment] 2017-05-04 10:37
Hello @inakianduaga, thanks for reaching us. I believe that the issue is the same as in #771. You need to remove and install React Native module manually using this articles: [iOS Setup](https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-ios.md), [Android Setup](https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-android.md)
Please let me know if it helps or if you have any difficulties.

**Comment by inakianduaga** [comment] 2017-05-04 10:45
@sergey-akhalkov Thanks, I looked through that before (manual Android setup) but I'll give it a shot one more time. One thing I didn't have clear is if the 

```
        // 2. Override the getJSBundleFile method in order to let
        // the CodePush runtime determine where to get the JS
        // bundle location from on each app start
        @Override
        protected String getJSBundleFile() {
            return CodePush.getJSBundleFile();
        }
```

is really necessary or not on the latest version? Because the `react-native link react-native-code-push` added the other things and not that one, and the codepush download & so on seemed to be working without it (in fact adding that was breaking things I believe)

**Comment by sergey-akhalkov** [comment] 2017-05-04 10:58
@inakianduaga, it is very important to override `getJSBundleFile` method, so you need to add this code to make React Native able to receive non default JS bundle path, but provided by CodePush instead.

**Comment by sergey-akhalkov** [comment] 2017-05-10 08:36
@inakianduaga, just a friendly ping.

**Comment by inakianduaga** [comment] 2017-05-10 19:54
@sergey-akhalkov I gave it another shot and now it's sort of working (I had a missing line in the gradle push configuration).

I mean "sort of working" because I don't really understand how codepush should work in dev mode vs release mode. What I would imagine is that in dev mode codepush checks nothing & package is fetched from dev server as usual. In prod mode, it should do the checking and update if new version is found.

This is not what I'm seeing however, even when running in dev mode I see the codepush "checking updates", "downloading update" (if I made a deploy) and so on. While in release mode (building the signed apk and pushing it to the device) I see no codepush logs at all on android logcat. 

Here's a small screen grab showing what happens in dev mode

![codepush-demo](https://cloud.githubusercontent.com/assets/4490289/25916209/23588a12-35c4-11e7-92f2-d83cc9c27ceb.gif)

**Comment by sergey-akhalkov** [comment] 2017-05-11 08:20
Hi @inakianduaga, please take a look at the note from the docs:
>NOTE: CodePush updates should be tested in modes other than Debug mode. In Debug mode, React Native app always downloads JS bundle generated by packager, so JS bundle downloaded by CodePush does not apply.

Please let me know if you have any questions.

**Comment by sergey-akhalkov** [comment] 2017-05-17 08:49
Closing this for now, please feel free to reopen if needed.

**Closed by sergey-akhalkov** 2017-05-17 08:49 UTC
Labels: question, waiting-for-clarification
