### ISSUE TITLE
 Sending `CodePushDownloadProgress` with no listeners registered

### ISSUE THREAD

**Issue by sagardeveloper** [microsoft/react-native-code-push#2586] opened 2023-09-20 10:43 UTC
### Steps to Reproduce
1. Installed [react-native-code-push](https://github.com/microsoft/react-native-code-push) into react native app
2.  Reinstall application 
3. Error occurs 

### Expected Behavior
Inside the function of downloadProgressCallback, we should get the percentage, but this function never calls. 

### Actual Behavior
downloadProgressCallback never calls, and I noticed that I am getting this warning into the console logs **Sending `CodePushDownloadProgress` with no listeners registered**
```
  STACK TRACE AND/OR SCREENSHOTS
![Screenshot 2023-09-20 at 4 05 50 PM](https://github.com/microsoft/react-native-code-push/assets/49883415/307f4eee-2825-47a4-a653-055ee8071a35)
![Screenshot 2023-09-20 at 4 05 33 PM](https://github.com/microsoft/react-native-code-push/assets/49883415/fc38ba55-92d3-4153-ab10-5381ad52455f)

<img width="984" alt="Screenshot 2023-09-20 at 4 05 03 PM" src="https://github.com/microsoft/react-native-code-push/assets/49883415/24b4c00c-677b-4077-a022-faa96d480765">



```

### Environment

* react-native-code-push version: I tried, 8.1.0, 8.0.2,7,1,0 and  7.0.5
* react-native version: 0.66.0
* iOS/Android/Windows version: IOS
* Does this reproduce on a debug build or release build? ANSWER: debug for now 
* Does this reproduce on a simulator, or only on a physical device? ANSWER: Both

I have already tried previous solutions for this problem but nothing is working for me, I have checked each and every solution: 
https://github.com/microsoft/react-native-code-push/issues/978
https://github.com/microsoft/react-native-code-push/issues/2508
https://stackoverflow.com/questions/61483614/bridge-is-not-set-this-is-probably-because-youve-explicitly-synthesized-the-br
https://github.com/microsoft/react-native-code-push/pull/526/commits/6dc1fb8487da565d99b5e7aebffe1b76115f0112

**Comment by DmitriyKirakosyan** [comment] 2023-10-06 07:55
Hi @sagardeveloper, thanks for reaching out! Can you share a code snippet on how you set up code push? Also, if you can provide a demo app for reference, that would be helpful.

**Comment by sagardeveloper** [comment] 2023-10-06 08:22
The codepush progress event does not work in the function-based component @DmitriyKirakosyan , but after changing the component to class-based, it started working. 
This is function based code which I am not using as it was not working 
`//   React.useEffect(() => {
//     LogBox.ignoreLogs(['VirtualizedLists should never be nested']);
//     showNoInternet();
//     createEventsAndBlogsDB()
//     perf();
//     // getConfig()
//     if (Text.defaultProps == null) Text.defaultProps = {};
//        Text.defaultProps.allowFontScaling = false;
//   }, []);

//   const getConfig=async()=>{
//     try {
//       await remoteConfig().fetchAndActivate().then(()=>{
//         const welcomeMessage = remoteConfig().getValue('ios_version').asString();
//         console.log('remoteConfig==>> :',JSON.parse(welcomeMessage));
//       });
     
//     } catch (error) {
//       console.error('Error remoteConfig==>>:', error);
//     }

//   }


//   React.useEffect(() => {
//     console.log('codepsh==>>>>>> useefect')
//     const codePushOptions = {
//       updateDialog: true,
//       installMode: CodePush.InstallMode.IMMEDIATE,
//     };

//     const codePushStatusDidChange = (syncStatus) => {
//       switch(syncStatus) {
//         case CodePush.SyncStatus.CHECKING_FOR_UPDATE:
//           console.log("Checking for update.");
//           break;
//         case CodePush.SyncStatus.DOWNLOADING_PACKAGE:
//           console.log("Downloading package.");
//           break;
//         case CodePush.SyncStatus.AWAITING_USER_ACTION:
//           console.log("Awaiting user action.");
//           break;
//         case CodePush.SyncStatus.INSTALLING_UPDATE:
//           console.log("Installing update.");
//           break;
//         case CodePush.SyncStatus.UP_TO_DATE:
//           console.log("App up to date.");
//           setProgress(null);
//           break;
//         case CodePush.SyncStatus.UPDATE_IGNORED:
//           console.log("Update cancelled by user.");
//           setProgress(null);
//           break;
//         case CodePush.SyncStatus.UPDATE_INSTALLED:
//           console.log("Update installed and will be applied on restart.");
//           setProgress(null);
//           break;
//         case CodePush.SyncStatus.UNKNOWN_ERROR:
//           console.log("An unknown error occurred.");
//           setProgress(null);
//           break;
//       }
//     };
  

//     const downloadProgressCallback = (progress) => {
//       try {
//         console.log(` codepsh==>>>>> Download Progress: ${progress.receivedBytes} / ${progress.totalBytes}`);
//       } catch (error) {
//         console.log('codepsh==>>>> Error in downloadProgressCallback:', error);
//       }
//     };

//     const codePushSync = CodePush.sync(codePushOptions, codePushStatusDidChange, downloadProgressCallback);

//     return () => {
//       // Cleanup code if needed
//       codePushSync?.cancel();
//     };
//   }, []);`


But for those who are still suffering with this problem, convert component function to class and use this code, it will work. 
`  this.codePushStatusDidChange.bind(this),
        this.codePushDownloadDidProgress.bind(this)`

`  codePushStatusDidChange(syncStatus) {
    switch(syncStatus) {
      case CodePush.SyncStatus.CHECKING_FOR_UPDATE:
        this.setState({ syncMessage: "Checking for update." });
        break;
      case CodePush.SyncStatus.DOWNLOADING_PACKAGE:
        this.setState({ syncMessage: "Downloading package." });
        break;
      case CodePush.SyncStatus.AWAITING_USER_ACTION:
        this.setState({ syncMessage: "Awaiting user action." });
        break;
      case CodePush.SyncStatus.INSTALLING_UPDATE:
        this.setState({ syncMessage: "Installing update." });
        break;
      case CodePush.SyncStatus.UP_TO_DATE:
        this.setState({ syncMessage: "App up to date." });
        break;
      case CodePush.SyncStatus.UPDATE_IGNORED:
        this.setState({ syncMessage: "Update cancelled by user." });
        break;
      case CodePush.SyncStatus.UPDATE_INSTALLED:
        this.setState({ syncMessage: "Update installed and will be applied on restart.", progress: false });
        break;
      case CodePush.SyncStatus.UNKNOWN_ERROR:
        this.setState({ syncMessage: "An unknown error occurred." });
        break;
    }
  }

  codePushDownloadDidProgress(progress) {
    this.setState({ progress });
  }
`

**Comment by DmitriyKirakosyan** [comment] 2023-10-06 08:56
@sagardeveloper , I'm glad the issue is resolved for you. Closing.

**Closed by DmitriyKirakosyan** 2023-10-06 08:56 UTC

**Comment by hungnd6282** [comment] 2024-03-30 16:12
Same me. My app downloaded new version by OTA (code-push). I taped reload my app. After that I downloaded newest version by OTA. My console log show "CodePushDownloadProgress with no listeners registered". Pls, Support me

**Comment by DmitriyKirakosyan** [comment] 2024-06-11 05:42
@hungnd6282 , Have you tried solution from https://github.com/microsoft/react-native-code-push/issues/2586/#issuecomment-1750181817?
If it doesn't help, please share more information about your environment. If you could create a demo app reproducing the issue, it would help a lot.
