### ISSUE TITLE
[CodePush bundleURL] result to "no dimension set for key window" crash

### ISSUE THREAD

**Issue by xiaoyongchen** [Microsoft/react-native-code-push#947] opened 2017-08-03 09:38 UTC
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Description
react-native@0.43.3 ->react-native@0.45.1 
[FILL THIS OUT: Explain what you did, what you expected to happen, and what actually happens. Also exact reproduction steps and stack trace will be much appreciated.]

### Reproduction

[FILL THIS OUT: If possible try to reproduce your bug on our basic sample: https://github.com/Microsoft/react-native-code-push/tree/master/Examples/CodePushDemoApp. If you can't reproduce the bug on it, provide us as much info as possible about your project.]

### Additional Information

* react-native-code-push version:"react-native-code-push": "^4.1.0-beta"
* react-native version: "react-native": "0.46.4",
* iOS/Android/Windows version:iOS
* Does this reproduce on a debug build or release build?debug
* Does this reproduce on a simulator, or only on a physical device?
simulator
(The more info the faster we will be able to address it!)
 Unhandled JS Exception: Module AppRegistry is not a registered callable module (calling runApplication)

**Comment by sergey-akhalkov** [comment] 2017-08-03 09:59
Hi @xiaoyongchen, thanks for reaching us. Could you please clarify what the issue is and provide us more details - repro steps, stack trace, actual and expected result and etc? Thanks

**Comment by max-mironov** [comment] 2017-08-06 20:39
Closing this item as a duplicate of #954 as the latter has at least some additional information

**Closed by max-mironov** 2017-08-06 20:39 UTC
Labels: duplicate, incomplete, iOS, no-repro
