### ISSUE TITLE
Android: An update check must include a valid deployment key

### ISSUE THREAD

**Issue by bicitech** [Microsoft/react-native-code-push#867] opened 2017-05-31 09:41 UTC
### Description

[CodePush] 400: An update check must include a valid deployment key - please check that your app has been configured correctly. To view available deployment keys, run 'code-push deployment ls <appName> -k'.

Use BuildConfig to config CODEPUSH_KEY is not working. Replace BuildConfig.CODEPUSH_KEY to specific key or give deploymentKey to sync both works.

### Reproduction

MainApplication.java
```
package com.bicisims.gtgj;

import java.util.Arrays;
import java.util.List;

import com.facebook.react.ReactPackage;
import com.reactnativenavigation.NavigationApplication;
import com.oblador.vectoricons.VectorIconsPackage;
import com.lwansbrough.RCTCamera.RCTCameraPackage;
import com.microsoft.codepush.react.CodePush;

public class MainApplication extends NavigationApplication {

    @Override
    public boolean isDebug() {
        return BuildConfig.DEBUG;
    }

    @Override
    public String getJSBundleFile() {
        return CodePush.getJSBundleFile();
    }

    @Override
    public List<ReactPackage> createAdditionalReactPackages() {
        return Arrays.<ReactPackage>asList(
            new VectorIconsPackage(),
            new RCTCameraPackage(),
            new CodePush(BuildConfig.CODEPUSH_KEY, MainApplication.this, BuildConfig.DEBUG)
        );
    }
}
```

build.gradle
```
...
    buildTypes {
        debug {
            buildConfigField "String", "CODEPUSH_KEY", '""'
        }

        releaseStaging {
            buildConfigField "String", "CODEPUSH_KEY", '"..."'
        }
        
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
            buildConfigField "String", "CODEPUSH_KEY", '"..."'
        }
    }
...
```

```
...
        codePush.sync(
            {
                // deploymentKey: '...',
                installMode: codePush.InstallMode.IMMEDIATE,
                updateDialog: {
                    title: '版本更新',
                    optionalUpdateMessage: '检查到新版，是否立即更新？',
                    optionalInstallButtonLabel: '更新',
                    optionalIgnoreButtonLabel: '暂不',
                    mandatoryUpdateMessage: '有一个重要更新需要立即安装',
                    mandatoryContinueButtonLabel: '确认',
                },
            },
            status => {
                switch (status) {
                    case codePush.SyncStatus.CHECKING_FOR_UPDATE:
                        dispatch(actions.errorFlash('正在检查更新'));
                        break;
                    case codePush.SyncStatus.AWAITING_USER_ACTION:
                        break;
                    case codePush.SyncStatus.DOWNLOADING_PACKAGE:
                        dispatch(actions.errorFlash('开始下载更新'));
                        break;
                    case codePush.SyncStatus.INSTALLING_UPDATE:
                        dispatch(actions.errorFlash('正在安装更新'));
                        break;
                    case codePush.SyncStatus.UP_TO_DATE:
                        dispatch(actions.errorFlash('当前版本已是最新'));
                        break;
                    case codePush.SyncStatus.UPDATE_INSTALLED:
                        dispatch(actions.errorFlash('更新已安装，即将重启应用'));
                        break;
                    case codePush.SyncStatus.SYNC_IN_PROGRESS:
                        dispatch(actions.errorFlash('更新正在进行中，请勿重复操作'));
                        break;
                    case codePush.SyncStatus.UNKNOWN_ERROR:
                        dispatch(actions.errorFlash('未知错误'));
                        break;
                }
            },
            ({receivedBytes, totalBytes}) => {
                if (receivedBytes < totalBytes) {
                    let progress = Math.round((receivedBytes * 100) / totalBytes);
                    dispatch(actions.processingTask(`已下载更新 ${progress}%`));
                } else {
                    dispatch(actions.processingTask(''));
                }
            },
        );
...
```
### Additional Information

* react-native-code-push version: 1.17.4-beta
* react-native version: 0.42.3
* iOS/Android/Windows version: Android 5.1
* Does this reproduce on a debug build or release build? debug
* Does this reproduce on a simulator, or only on a physical device? simulator

**Comment by max-mironov** [comment] 2017-05-31 11:44
Hi @bicitech, thank you for reaching us.
So as you noted in **Additional information** you have tested it in debug build. I believe this may be the root cause of the issue. 

By default, the react-native run-android command builds and deploys the debug version of your app, so if you want to test out a release/production build, simply run `react-native run-android --variant release. Refer to the React Native docs for details about how to configure and create release builds for your Android apps.

Aslo there are some more information about it in our [docs](https://github.com/Microsoft/react-native-code-push#android). 

Please let us know if it helps you to resolve the issue.

**Comment by max-mironov** [comment] 2017-06-02 03:40
@bicitech - just a friendly ping :) Please let us know if you still experience an issue.

**Comment by jaggerwang** [comment] 2017-06-02 04:10
Got it, it works!

**Comment by max-mironov** [comment] 2017-06-02 04:21
@jaggerwang thank you for your reply, if you don't mind I'm closing the issue. Feel free to reach us if any questions.

**Closed by max-mironov** 2017-06-02 04:21 UTC
Labels: waiting-for-clarification
