### ISSUE TITLE
when I Run code-push command，error occured

### ISSUE THREAD

**Issue by hlglhw002** [microsoft/react-native-code-push#1803] opened 2020-03-02 06:44 UTC
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
 I want to code-push a new ios version, but it's failed…

the script is:
code-push release-react ckysmall-ios ios --t 4.0.0 --d Production --m true

D:\ReactNative\Project\ckysmallapp>npm run code-push-ios-release

> ckysMall@0.0.1 code-push-ios-release D:\ReactNative\Project\ckysmallapp
> code-push release-react ckysmall-ios ios --t 4.0.0 --d Production --m true --des '20200302凌晨ios第10次正式热更新'

Running "react-native bundle" command:

node node_modules\react-native\local-cli\cli.js bundle --assets-dest C:\Users\MRLUO~1\AppData\Local\Temp\CodePush\CodePush --bundle-output C:\Users\MRLUO~1\AppData\Local\Temp\CodePush\CodePush\main.jsbun
dle --dev false --entry-file index.js --platform ios
Loading dependency graph, done.

error Cannot read property 'map' of undefined. Run CLI with --verbose flag for more details.
[Error]  "react-native bundle" command exited with code 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ckysMall@0.0.1 code-push-ios-release: `code-push release-react ckysmall-ios ios --t 4.0.0 --d Production --m true --des '20200302凌晨ios第10次正式热更新'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ckysMall@0.0.1 code-push-ios-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Program Files\nodejs\node_cache\_logs\2020-03-02T05_46_30_502Z-debug.log

In the morning, after I finished pushing the new Android version with code push, during the process of pushing the new IOS version, my computer rebooted with a blue screen. After I rebooted my computer, I tried to push the new IOS version again, but when I executed the code push command, NPM still prompted the above error. I tried to push Android again, there is no problem. But as long as I try to code push IOS, I start to report errors again. I don't know what's the reason. Before I use code push to update my app, there is no problem. This problem has appeared since this morning. Please help to see this problem. Thank you!

### Expected Behavior
What you expected to happen?

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version:5.6.0
* react-native version:0.59.10
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by hlglhw002** [comment] 2020-03-02 09:02
2020-03-02T05_46_30_502Z-debug.log  ：

0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'code-push-ios-release' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'precode-push-ios-release',
4 verbose run-script   'code-push-ios-release',
4 verbose run-script   'postcode-push-ios-release' ]
5 info lifecycle ckysMall@0.0.1~precode-push-ios-release: ckysMall@0.0.1
6 info lifecycle ckysMall@0.0.1~code-push-ios-release: ckysMall@0.0.1
7 verbose lifecycle ckysMall@0.0.1~code-push-ios-release: unsafe-perm in lifecycle true
8 verbose lifecycle ckysMall@0.0.1~code-push-ios-release: PATH: D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\ReactNative\Project\ckysmallapp\node_modules\.bin;D:\ReactNative\Project\ckysmallapp\node_modules\.bin;D:\Program Files\Python27\;D:\Program Files\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;D:\Program Files\Java\jdk1.8.0_91\bin;D:\Program Files\Java\jdk1.8.0_91\jre\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;D:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;D:\Program Files\Android\android-sdk\tools;D:\Program Files\Android\android-sdk\platform-tools;E:\apache-maven-3.3.9-bin\apache-maven-3.3.9\bin;C:\Program Files\Lenovo\Fingerprint Manager Pro\;D:\Program Files\TortoiseSVN\bin;D:\Studio\Android Studio\gradle\gradle-2.10\bin;D:\Program Files\nodejs\;D:\Program Files (x86)\Git\cmd;D:\Program Files\TortoiseGit\bin;D:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;D:\Program Files\nodejs\node_global;D:\Program Files\JetBrains\WebStorm2019.2.4\bin;
9 verbose lifecycle ckysMall@0.0.1~code-push-ios-release: CWD: D:\ReactNative\Project\ckysmallapp
10 silly lifecycle ckysMall@0.0.1~code-push-ios-release: Args: [ '/d /s /c',
10 silly lifecycle   'code-push release-react ckysmall-ios ios --t 4.0.0 --d Production --m true --des \'20200302凌晨ios第10次正式热更新\'' ]
11 silly lifecycle ckysMall@0.0.1~code-push-ios-release: Returned: code: 1  signal: null
12 info lifecycle ckysMall@0.0.1~code-push-ios-release: Failed to exec code-push-ios-release script
13 verbose stack Error: ckysMall@0.0.1 code-push-ios-release: `code-push release-react ckysmall-ios ios --t 4.0.0 --d Production --m true --des '20200302凌晨ios第10次正式热更新'`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid ckysMall@0.0.1
15 verbose cwd D:\ReactNative\Project\ckysmallapp
16 verbose Windows_NT 6.3.9600
17 verbose argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "code-push-ios-release"
18 verbose node v10.15.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error ckysMall@0.0.1 code-push-ios-release: `code-push release-react ckysmall-ios ios --t 4.0.0 --d Production --m true --des '20200302凌晨ios第10次正式热更新'`
22 error Exit status 1
23 error Failed at the ckysMall@0.0.1 code-push-ios-release script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by alexandergoncharov** [comment] 2020-05-28 13:04
Hi @hlglhw002,
Thanks for reporting!

If I see correctly there is some issue in `react-native bundle` command. Could you please ensure that `react-native bundle` command works correctly?

Thanks,
Alexander

**Comment by andreidubov** [comment] 2020-06-10 07:59
Since there is no answer and we cannot reproduce it I'm going to close this issue for now. Please feel free to reopen it if you have any questions or issues.

**Closed by andreidubov** 2020-06-10 07:59 UTC
Labels: bug, waiting-for-clarification
