### ISSUE TITLE
Can't figure out the version user is currently running.

### ISSUE THREAD

**Issue by avishayil** [Microsoft/react-native-code-push#395] opened 2016-06-23 14:19 UTC
Hi,
I tried in several ways, but couldn't get a stable label of the update user is currently running.
Not downloading, not updating, running.

The flow should be like this:

``` javascript
PSUEDO

Check if an update exists -->
--- If update exists -->
--- --- check if the user has the right Android / iOS version code to download the update --> get current RUNNING CodePush label  --> display it --> sync().

--- If it doesnt exist -->
--- --- get current RUNNING CodePush label --> display it.
```

I tried to use the following code but got unstable results (sometimes the right version, sometimes empty object).

``` javascript
CodePush.getUpdateMetadata(CodePush.UpdateState.RUNNING).then((update) => {
    console.log(update.label);
});
```

**Comment by lostintangent** [comment] 2016-06-23 15:10
The `getUpdateMetadata` method will only ever return information about a CodePush update, not the binary. Therefore, it will return `null` if you aren't currently running a CodePush update (or if there isn't a pending update, depending on what `UpdateState` you specify).

Are you seeing different behavior? Or are you requesting that it returns information about the binary if the user is running the binary-bundled content, as opposed to a CodePush update?

Apologies if I'm misunderstanding you. We haven't heard any issues with the `getUpdateMetdata` method, so we'll definitely try to figure out how to unblock you here.

**Comment by avishayil** [comment] 2016-06-24 13:35
Yes, that's what I'm trying to achieve. 
Thanks for the quick response.

**Comment by lostintangent** [comment] 2016-06-24 23:24
@avishayil What do you think about us adding a new method called `getAppVersion` (or something similar) that would return the version of the binary, with the running CodePush label appended to it, if there is one?

```javascript
// This would return "1.0.0" if the app is running the binary, and
// "1.0.0.1", "1.0.0.2", etc. if the app was running a CodePush update
const version = await codePush.getAppVersion();
```

If possible, I'd prefer to keep the behavior of `getUpdateMetadata` as it is, as opposed to trying to overload it to expose binary information as well.

**Comment by avishayil** [comment] 2016-06-25 20:23
Yeah, that could work, thanks!

**Comment by lostintangent** [comment] 2016-06-30 16:59
@avishayil Did that proposed solution end up working for you? We'd like to add this capability to the core plugin, and it would be great to get your feedback on how well it worked.

**Comment by avishayil** [comment] 2016-07-03 12:58
Actually it did. Thanks!

**Comment by panarasi** [comment] 2017-02-01 23:45
This information is actually a part of the native bundle and making Async calls would be the only way this can be accessed. We do not save this information in the JS bundle that is sent back.

Looks like the issue is solved for you, so closing this issue. Please re-open if you have questions

**Closed** 2017-02-02 06:46 UTC
Labels: enhancement

**Comment by SudoPlz** [comment] 2017-03-01 19:53
I was looking for that exact code.
Works for me, thank you..!

**Comment by alzalabany** [comment] 2020-02-16 19:10
latest version doesnot export getConfiguration function anymore, "Property 'getConfiguration' does not exist on type 'typeof CodePush'.ts(2339)"

**Comment by arafatzahan** [comment] 2020-07-16 00:14
@alzalabany the code still works. Just add a ts-ignore to suppress the warning.

**Comment by rapaktech** [comment] 2022-10-19 14:36
@lostintangent please help. latest version doesn't export getConfiguration. Using React Native 0.6.4 and CodePush 7.0.4
