### ISSUE TITLE
undefined is not an object (evaluating \'this._serverUrl.slice\')

### ISSUE THREAD

**Issue by israrwz** [Microsoft/react-native-code-push#1059] opened 2017-10-25 09:12 UTC
First off the example provided in the documentation for the plugin usage in react-native does not work with react-native-navigation module because with this module there is no root component. So I used this https://github.com/Microsoft/react-native-code-push/issues/875#issuecomment-306776606 method which essentially says that we create a component that's code-pushified, by rendering that component in the main screen code-push will start doing its work.

but I get the following error in the xcode debug logs:

```
2017-10-25 13:34:12.501275+0430 zootzoot[9729:3032931] [CodePush] Checking for update.
2017-10-25 13:34:12.625 [info][tid:com.facebook.react.JavaScript] [CodePush] An unknown error occurred.
2017-10-25 13:34:12.624941+0430 zootzoot[9729:3032931] [CodePush] An unknown error occurred.
2017-10-25 13:34:12.625 [info][tid:com.facebook.react.JavaScript] [CodePush] undefined is not an object (evaluating 'this._serverUrl.slice')
```

### Environment

* react-native-code-push version: ^5.1.3-beta
* react-native version: ^0.49.2
* iOS/Android/Windows version: iOS 11
* Does this reproduce on a debug build or release build? both
* Does this reproduce on a simulator, or only on a physical device? both

**Comment by sergey-akhalkov** [comment] 2017-10-25 11:33
Hi @israrwz, please take a look at this https://github.com/Microsoft/react-native-code-push/issues/790#issuecomment-294148452 and let me know if it helps

**Comment by israrwz** [comment] 2017-10-25 18:45
Unfortunately https://github.com/Microsoft/react-native-code-push/issues/790#issuecomment-294148452 didn't help either.

**Comment by tkiefhaber** [comment] 2017-10-25 21:59
not exactly the same error, but experiencing something simlar.

```
import React from 'react';
// import CodePush from 'react-native-code-push';

import Tabs from '../Tabs';

import Wrapper from './Wrapper.js';

const CodePush = require('react-native-code-push');

const codePushOptions = {
  checkFrequency: CodePush.CheckFrequency.ON_APP_RESUME,
  updateDialog: false,
  installMode: CodePush.InstallMode.IMMEDIATE,
};

export default class App extends React.Component {

  componentDidMount() {
    CodePush.sync(codePushOptions);

  };

  render() {
    return (
      <Wrapper>
        <Tabs />
      </Wrapper>
    );
  };
}
```

have also tried a different variation:
```
import React from 'react';
import codePush from 'react-native-code-push';

import Tabs from '../Tabs';

import Wrapper from './Wrapper.js';

const codePushOptions = {
  checkFrequency: codePush.CheckFrequency.ON_APP_RESUME
};

function App() {
  return (
    <Wrapper>
      <Tabs />
    </Wrapper>
  );
};

export default codePush(codePushOptions)(App);
```

both end up with the same errors in Android and iOS.

![screenshot_1508968723](https://user-images.githubusercontent.com/1302793/32025454-32912d90-b9ae-11e7-9b3b-00e74fb655d3.png)
![simulator screen shot - iphone 6 - 2017-10-25 at 17 58 37](https://user-images.githubusercontent.com/1302793/32025455-329fe9de-b9ae-11e7-8613-13ce4851f824.png)

**Comment by sergey-akhalkov** [comment] 2017-10-26 06:49
Hi guys @israrwz, @tkiefhaber, do I get it right if the demo app provided in https://github.com/Microsoft/react-native-code-push/issues/790#issuecomment-294148452 works well for you, but your app still doesn't work? If so, please provide me with the minimum version of your app where the issue is reproduced.

**Comment by sergey-akhalkov** [comment] 2017-10-27 10:29
Hey guys, I'm closing this for now, please feel free to reopen the issue or create new one and provide us with exact repro steps that we could follow to configure the app that uses codepush and react-native-navigation modules in the same manner as your's app does it. Or just provide us the minimum versions of your apps where the issue is reproduced.

**Closed by sergey-akhalkov** 2017-10-27 10:29 UTC
Labels: question, waiting-for-clarification

**Comment by israrwz** [comment] 2017-10-27 12:41
with further debugging, I was able to find a detailed version of the exception:

```
TypeError: Cannot read property 'slice' of undefined
    at new AcquisitionManager (http://192.168.0.80.xip.io:8081/index.bundle?platform=ios&dev=true&minify=false:129592:29)
    at getPromisifiedSdk (http://192.168.0.80.xip.io:8081/index.bundle?platform=ios&dev=true&minify=false:128960:13)
    at checkForUpdate$ (http://192.168.0.80.xip.io:8081/index.bundle?platform=ios&dev=true&minify=false:128805:17)
    at tryCatch (http://192.168.0.80.xip.io:8081/index.bundle?platform=ios&dev=true&minify=false:12910:40)
    at Generator.invoke [as _invoke] (http://192.168.0.80.xip.io:8081/index.bundle?platform=ios&dev=true&minify=false:13098:22)
    at Generator.prototype.(anonymous function) [as next] (http://192.168.0.80.xip.io:8081/index.bundle?platform=ios&dev=true&minify=false:12935:21)
    at tryCatch (http://192.168.0.80.xip.io:8081/index.bundle?platform=ios&dev=true&minify=false:12910:40)
    at invoke (http://192.168.0.80.xip.io:8081/index.bundle?platform=ios&dev=true&minify=false:12968:20)
    at http://192.168.0.80.xip.io:8081/index.bundle?platform=ios&dev=true&minify=false:12976:13
    at tryCallOne (http://192.168.0.80.xip.io:8081/index.bundle?platform=ios&dev=true&minify=false:12266:12)
logging.js:3 [CodePush] Cannot read property 'slice' of undefined
```

But I have no idea how to fix it.

**Comment by sergey-akhalkov** [comment] 2017-10-27 13:05
@israrwz, I believe the issue happens here https://github.com/Microsoft/code-push/blob/7557fcffe808a4fa2e0b17dab717ed95911272bd/sdk/script/acquisition-sdk.ts#L73
Is there a chance if you somehow changed/override `CodePushServerURL` config value in your  `info.plist` file?

**Comment by israrwz** [comment] 2017-10-27 14:19
No.
The only Codepush related values in my info.plist are:

```
	<key>CodePushDeploymentKey</key>
	<string>**********************************my key</string>
```

and 
```
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSExceptionDomains</key>
		<dict>
			<key>codepush.azurewebsites.net</key>
			<string/>
			<key>codepush.blob.core.windows.net</key>
			<string/>
			<key>codepushupdates.azureedge.net</key>
			<string/>
			<key>localhost</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
		</dict>
	</dict>
```

**Comment by sergey-akhalkov** [comment] 2017-10-27 14:26
@israrwz, it is really hard to say what goes wrong here without having the demo version of your app where the issue reproduces - could you please share it with us so we would be able to help you in this case?

**Comment by israrwz** [comment] 2017-10-27 14:29
Unfortunately our project is a huge one and we added code-push at the end of our project development. 

Initially I had manually integrated codepush in Xcode, I thought that could have been the issue. But the issue persists even when I installed using CocoaPods.

**Comment by sergey-akhalkov** [comment] 2017-10-27 14:45
@israrwz, the only thing we can probably do in this case - it's try to debug the app. I believe that the root cause of the issue is in https://github.com/Microsoft/react-native-code-push/blob/751bf02836f6af652cbd2d9f5a499444a5964a00/ios/CodePush/CodePush.m#L687 method that returns empty/undefined value for `serverUrl` prop. 

Could you please set the breakpoint here 
https://github.com/Microsoft/react-native-code-push/blob/751bf02836f6af652cbd2d9f5a499444a5964a00/ios/CodePush/CodePush.m#L690
and confirm that `ServerURLConfigKey/serverUrl` has value other than null/empty-string?

**Comment by israrwz** [comment] 2017-10-27 16:48
First off that code in my version of CodePush.m is at line 685
and it doesn't seem to have any configuration data.

attached is the screenshot of breakpoint:

<img width="1443" alt="screen shot 2017-10-27 at 9 15 13 pm" src="https://user-images.githubusercontent.com/3380485/32115469-33b887e0-bb5c-11e7-88cc-b8c0b2ee00e4.png">

**Comment by israrwz** [comment] 2017-10-29 13:44
So what could be the reason for this function not picking the serverUrl value?

**Comment by israrwz** [comment] 2017-10-29 21:07
Finally fixed it :)

The issue was that I had only set the Version number but not the Build string in the identity settings of general pane in xcode.

It is working fine now.

**Comment by sergey-akhalkov** [comment] 2017-10-30 06:59
@israrwz, good to know, thanks for the update!
