### ISSUE TITLE
Codepush installs a new update only when I reinstall the APK

### ISSUE THREAD

**Issue by thisisyatendra** [microsoft/react-native-code-push#2732] opened 2024-07-28 09:41 UTC
I'm facing this issue with Codepush where I push a new update on Codepush but the Application on my phone doesn't install it. Only when I uninstall and reinstall the app, it downloads the update from Codepush and then proceeds with installing it.

So no matter what update I'm push to the codepush, i'd have to uninstall and reinstall the application every single time. Any idea and feedback on why it must be happening would be much appreciated.

I push the update on Codepush and then opened the installed application on android. It asked me to install a new update. When I clicked on the install button, nothing happened and there was also no update about the total downloads and installs on the codepush dashboard.

But as soon as I uninstalled and reinstalled the application, a similar dialog popped up and as soon as i clicked on the install button, the updated was downloaded and installed successfully and then I was able to notice the updated changes.

### Expected Behavior
Expected the new updates to be installed as soon as I click install button on app start.

### Actual Behavior
Even if i click the install button, no updates are installed.

### stack
react-native-code-push 8.3.0

**Comment by DmitriyKirakosyan** [comment] 2024-07-29 07:29
@thisisyatendra this looks like a duplicate of #2725, which was fixed in v8.3.1. Please try updating CodePush to latest version and let us know if it works.

**Comment by thisisyatendra** [comment] 2024-07-29 11:49
@DmitriyKirakosyan It worked like a charm. Thanks a lot for the help :)

**Comment by DordeDimitrijev** [comment] 2024-07-30 09:56
Closing as the issue was resolved.

**Closed by DordeDimitrijev** 2024-07-30 09:56 UTC
