### ISSUE TITLE
RuntimeException only on release build Android

### ISSUE THREAD

**Issue by DavideValdo** [Microsoft/react-native-code-push#1469] opened 2018-12-09 15:59 UTC
Following #1464 

### Steps to Reproduce
1. Configure CodePush as code shown

### Expected Behavior
Application starts normally.

### Actual Behavior
`RuntimeException` happens and app crashes.

### MainApplication.java
```
public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    private CallbackManager mCallbackManager = CallbackManager.Factory.create();

    protected CallbackManager getCallbackManager() {
        return mCallbackManager;
    }

    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @SuppressLint("MissingPermission")
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.asList(
        new MainReactPackage(),
        new FBSDKPackage(mCallbackManager),
         ...
        new MapsPackage(),
        new CodePush(BuildConfig.CODEPUSH_KEY, MainApplication.this, BuildConfig.DEBUG, R.string.CodePushPublicKey)
      );
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }

    @Override
    protected String getJSBundleFile() {
        return CodePush.getJSBundleFile();
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  private ReactInstanceHolder instanceHolder = new ReactInstanceHolder() {
    @Override
    public ReactInstanceManager getReactInstanceManager() {
      return mReactNativeHost.getReactInstanceManager();
    }
  };

  @Override
  public void onCreate() {
     CodePush.setReactInstanceHolder(instanceHolder);
     super.onCreate();
  }
}

```

### MainActivity.java
```
public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "HappyIn";
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        MainApplication.getCallbackManager().onActivityResult(requestCode, resultCode, data);
    }
}
```

### Stacktrace
```
java.lang.RuntimeException: Unable to load script from assets 'index.android.bundle'. Make sure your bundle is packaged correctly or you're running a packager server.
 at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromAssets(Native Method)
 at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromAssets(CatalystInstanceImpl.java:216)
 at com.facebook.react.bridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:32)
 at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:243)
 at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1114)
 at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:116)
 at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:913)
 at java.lang.Thread.run(Thread.java:760)
```

### Environment

* react-native-code-push version: ^5.4.2
* react-native version: 0.57.1

**Comment by yuri-kulikov** [comment] 2018-12-11 12:42
Hi @DavideValdo,
Thanks for the report!

Сan you, please, clarify which version of `gradle` you are using?

**Comment by DavideValdo** [comment] 2018-12-12 16:40
`distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip`

**Comment by yuri-kulikov** [comment] 2018-12-12 20:55
@DavideValdo that's supposed to be a compatibility issue between `react-native 0.57.1` and `gradle-plugin v3.2+`. Please check [this message](https://github.com/Microsoft/react-native-code-push/issues/1427#issuecomment-430913598), I think that's the reason.

Please write to us if this has helped you in resolving the issue and feel free to ask if you have any further questions!

**Comment by DavideValdo** [comment] 2018-12-13 04:04
I solved by upgrading `react-native 0.57.2` to `0.57.2.`, with `0.57.7` I was getting compilation errors.

**Comment by yuri-kulikov** [comment] 2018-12-13 07:54
@DavideValdo glad to hear the problem is solved, but I will definitely investigate the issue with `react-native 0.57.7`, thanks for that information.

I'll close the issue, but if you can add some details about your problem with `rn 0.57.7`, it would be very helpful!

**Closed by yuri-kulikov** 2018-12-13 07:54 UTC
Labels: android

**Comment by yuri-kulikov** [comment] 2018-12-13 11:33
Tested `react-native 0.57.7` with `gradle plugin 3.2.1`, no compilation errors so far. Maybe it was something specific for your app. But now we know that such a problem can happen and we will be ready for it. Thanks again!

**Comment by DavideValdo** [comment] 2018-12-16 15:08
Sorry for being in a hurry and not taking the time to fully report logs, the error was exactly as described in https://github.com/facebook/react-native/issues/21150 but it complained about the full `scheduler` module. I can try reproducing the full error again if it can help.

**Comment by yuri-kulikov** [comment] 2018-12-17 07:49
@DavideValdo, don't worry, I just thought it might be related to the CodePush, but it looks like it's a react-native issue, so I think that there is no need to investigate it here. Anyway, thanks for your responsiveness!
