### ISSUE TITLE
APP restart update successful, restart again (update failed)

### ISSUE THREAD

**Issue by JonsonHI** [Microsoft/react-native-code-push#1530] opened 2019-02-26 03:58 UTC
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
APP restart update successful, restart again (update failed)(read local bundle)

This problem only happens with ios

log:
2019-02-26 11:47:09.880 [info][tid:com.facebook.react.JavaScript] [CodePush] Sync already in progress.
2019-02-26 11:47:09.880 [info][tid:com.facebook.react.JavaScript] [CodePush] Sync already in progress.
2019-02-26 11:47:09.885 [info][tid:com.facebook.react.JavaScript] [CodePush] Checking for update.
]2019-02-26 11:47:11.365 [info][tid:com.facebook.react.JavaScript] [CodePush] Downloading package.
2019-02-26 11:47:12.770 [info][tid:com.facebook.react.JavaScript] [CodePush] Installing update.
2019-02-26 11:47:12.777 [info][tid:com.facebook.react.JavaScript] [CodePush] Restarting app
2019-02-26 11:47:13.190 [info][tid:com.facebook.react.JavaScript] [CodePush] Sync already in progress.
2019-02-26 11:47:13.191 [info][tid:com.facebook.react.JavaScript] [CodePush] Sync already in progress.
2019-02-26 11:47:13.195 [info][tid:com.facebook.react.JavaScript] [CodePush] Reporting CodePush update success (v93)
2019-02-26 11:47:13.207 [info][tid:com.facebook.react.JavaScript] [CodePush] Checking for update.
]2019-02-26 11:47:14.894 [info][tid:com.facebook.react.JavaScript] [CodePush] App is up to date.
2019-02-26 11:47:19.823 [info][tid:com.facebook.react.JavaScript] [CodePush] Sync already in progress.
2019-02-26 11:47:19.824 [info][tid:com.facebook.react.JavaScript] [CodePush] Checking for update.
2019-02-26 11:47:20.050 [info][tid:com.facebook.react.JavaScript] [CodePush] App is up to date.

ios
```
 jsCodeLocation = [CodePush bundleURL];
 RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                        moduleName:@"screen"
                                                 initialProperties:nil
                                                     launchOptions:launchOptions];
```

bundle
```
react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios/test

code-push release-react <name> ios -t "1.4.5" --des "asd" -m true --d Production
```

* react-native-code-push version: 5.3.4     
* react-native version: 0.55.4
* iOS/Android/Windows version: ios 12.1      xcode 10
* Does this reproduce on a debug build or release build?  release 
* Does this reproduce on a simulator, or only on a physical device?  simulator & physical device

**Comment by JonsonHI** [comment] 2019-02-26 06:23
What's the jsbundle path?
my main.jsbundle  path   ios/main.jsbundle

codepush   main.jsbundle   Can I replace it?

**Comment by alexandergoncharov** [comment] 2019-02-26 06:32
Hi @JonsonHI,
Thanks for reporting!

I just tested your case with your versions and successfully got update even after reload app.
Could you please share your logs during update? There should be logs with `[CodePush]` tags.

**Comment by alexandergoncharov** [comment] 2019-02-26 06:36
> codepush main.jsbundle Can I replace it?
Yeah, you can. You should just put the other path to your bundle for `--bundle-output` arfument.

**Comment by JonsonHI** [comment] 2019-02-26 06:53
> Yeah, you can. You should just put the other path to your bundle for `--bundle-output` argument.


I have Shared the log

```
2019-02-26 11：47：09.880 [info] [tid：com.facebook.react.JavaScript] [CodePush]同步已在进行中。
2019-02-26 11：47：09.880 [info] [tid：com.facebook.react.JavaScript] [CodePush]同步已在进行中。
2019-02-26 11：47：09.885 [info] [tid：com.facebook.react.JavaScript] [CodePush]检查更新。
] 2019-02-26 11：47：11.365 [info] [tid：com.facebook.react.JavaScript] [CodePush]正在下载包。
2019-02-26 11：47：12.770 [info] [tid：com.facebook.react.JavaScript] [CodePush]安装更新。
2019-02-26 11：47：12.777 [info] [tid：com.facebook.react.JavaScript] [CodePush]重启应用程序
2019-02-26 11：47：13.190 [info] [tid：com.facebook.react .JavaScript] [CodePush]同步已在进行中。
2019-02-26 11：47：13.191 [info] [tid：com.facebook.react.JavaScript] [CodePush]同步已在进行中。
2019-02-26 11：47：13.195 [info] [tid：com.facebook.react.JavaScript] [CodePush]报告CodePush更新成功（v93）
2019-02-26 11：47：13.207 [info] [tid： com.facebook.react.JavaScript] [CodePush]检查更新。
] 2019-02-26 11：47：14.894 [info] [tid：com.facebook.react.JavaScript] [CodePush]应用程序是最新的。
2019-02-26 11：47：19.823 [info] [tid：com.facebook.react.JavaScript] [CodePush]同步已在进行中。
2019-02-26 11：47：19.824 [info] [tid：com.facebook.react.JavaScript] [CodePush]检查更新。
2019-02-26 11：47：20.050 [info] [tid：com.facebook.react.JavaScript] [CodePush]应用程序是最新的。
```

Asking for help, I've been confused for days

**Comment by JonsonHI** [comment] 2019-02-26 06:58
> > codepush main.jsbundle Can I replace it?
> 
> Yeah, you can. You should just put the other path to your bundle for `--bundle-output` argument.

Can the path to a jsbundle file be anywhere?

Conflict with codepush

**Comment by alexandergoncharov** [comment] 2019-02-26 07:47
oh, yeah, sorry, missed logs. I don't see any issues. It looks like your update was installed but path to update was broken after reopen. It is strange.

I'm not sure that path to your jsbundle can conflict with CodePush as `release-react` command make new own bundle and release it.
If you would like to release exactly your generated bundle you should use `release`  command.

Could you please provide some dummy project with reproducing issue and reprosteps? I would like to debug it.

**Comment by JonsonHI** [comment] 2019-02-27 14:17
> oh, yeah, sorry, missed logs. I don't see any issues. It looks like your update was installed but path to update was broken after reopen. It is strange.
> 
> I'm not sure that path to your jsbundle can conflict with CodePush as `release-react` command make new own bundle and release it.
> If you would like to release exactly your generated bundle you should use `release` command.
> 
> Could you please provide some dummy project with reproducing issue and reprosteps? I would like to debug it.


I created the project demo  
codepus  is works
I found the following log
```
Loading JS bundle from file:///Users/ms/Library/Developer/CoreSimulator/Devices/638C363A-8EDA-49C8-98A3-BC7788925732/data/Containers/Bundle/Application/4EE6A98D-E231-403C-8D66-F94D9A810053/codepush.app/main.jsbundle

```
But my formal project doesn't have this log

**Comment by alexandergoncharov** [comment] 2019-03-04 03:31
Hi @JonsonHI,

I'm going to close this issue for now as you confirmed that this issue was resolved.
https://github.com/Microsoft/react-native-code-push/issues/1533#issuecomment-468506926
Please feel free to reopen it if you have any questions.

Thanks,
Alexander

**Closed by alexandergoncharov** 2019-03-04 03:31 UTC
Labels: bug, iOS, waiting-for-clarification

**Comment by CHANDRAMOHANnegi** [comment] 2021-08-02 13:31
this happens only in debug mode
