### ISSUE TITLE
Staging build: 'CodePush/CodePush.h' file not found

### ISSUE THREAD

**Issue by Amurmurmur** [Microsoft/react-native-code-push#688] opened 2017-02-04 14:47 UTC
* react-native-code-push version: 1.17.0-beta
* react-native version: 0.41
* iOS/Android/Windows version: iOS 10.2
* Does this reproduce on a debug build or release build? Staging build
* Does this reproduce on a simulator, or only on a physical device? Doesnt even build the project
* Repro steps and/or stack trace: 

Followed instructions exactly, for multi deployment ([https://github.com/Microsoft/react-native-code-push#ios](https://github.com/Microsoft/react-native-code-push#ios))

Problem only happens when trying to build Staging.
`
AppDelegate.m:11:9: 'CodePush/CodePush.h' file not found
`

**Comment by sergey-akhalkov** [comment] 2017-02-06 09:52
@Amurmurmur, I've got the same issue and resolved it like this: 
![image](https://cloud.githubusercontent.com/assets/4928157/22642157/9955f3d8-ec6a-11e6-9b65-d66845994668.png)
So I've changed Staging `Build Products Path` value from `$(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)` to `$(BUILD_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)`
Could you please verify if it works for you? If so, we should probably update the documentation to workaround the issue.

**Comment by Amurmurmur** [comment] 2017-02-06 09:57
@sergey-akhalkov Yep that worked!! Thank you so much.
However I guess its just a workaround and the team has to fix it anyway, or add this in the documentation?!

Cheeers

**Comment by sergey-akhalkov** [comment] 2017-02-06 10:18
@Amurmurmur, thanks for the response. I've reproduced and fixed the issue in the same way without using CodePush. So initial react-native app (created by `react-native init myapp` command) also has this issue, we should probably investigate it to find more suitable solution or at least update the documentation.

**Comment by sergey-akhalkov** [comment] 2017-02-07 15:32
Closing this, please feel free to reopen if needed

**Closed by sergey-akhalkov** 2017-02-07 15:32 UTC

**Comment by almadsen** [comment] 2017-02-07 23:57
I was still getting this, my work around for it was/is:

<img width="976" alt="skarmavbild 2017-02-08 kl 00 54 10" src="https://cloud.githubusercontent.com/assets/1423040/22717061/439fe270-ed99-11e6-85df-0102a6f0d9f7.png">

I first tried putting the search link in the target but that still got me a file not found, but in the project part it stoped giving me the error.

**Comment by Amurmurmur** [comment] 2017-02-08 10:56
@almadsen That didnt work for me :/ Only the solution suggested by @sergey-akhalkov did work. :/

**Comment by SamMatthewsIsACommonName** [comment] 2017-02-20 02:46
Hi @sergey-akhalkov  I'm having this issue but I don't think I have any 'multi deployment testing' setup, it's just when I go to run the release scheme. i've tried all solutions i.e manually importing codepush.h, adding the library from scratch etc. I'm running react native 0.40.0 and react-native-code-push 1.16.1-beta. The weird thing was it was working fine and I'd created a build and submitted it to the app store, but then I changed a google services.plist file and suddenly the build broke... I've tried restarting computer etc etc... Also in your solution above I can't actually find the 'Build Locations' settings anywhere, I'm using xcode 8.2

**Comment by neopit** [comment] 2017-03-30 05:01
I have a similar error but now with a POD.

The trick with $(BUILD_DIR)/Release$(EFFECTIVE_PLATFORM_NAME) seems to work but when there is a dependency that does not work anymore in particularly with GoogleToolboxForMac.

I tried to make some change on the PODS_CONFIGURATION_BUILD_DIR with the value $PODS_BUILD_DIR/Release$(EFFECTIVE_PLATFORM_NAME) but that does not work !

Someone as a solution when we use a POD ?

**Comment by jinxac** [comment] 2017-06-19 18:43
@neopit working with pods with answer provided by @almadsen

**Comment by xxsnakerxx** [comment] 2017-07-27 06:02
Try to add Staging configuration to CodePush and React projects... works for me

**Comment by wprater** [comment] 2017-11-19 01:45
This issue is persisting for me when I try to build on Buddy Build.  anyone else encounter this?

**Comment by baotoan1905** [comment] 2020-01-06 15:12
I can't find Go to Build Location -> Per-configuration Build Products Path. Any idea ?

**Comment by EhsanSarshar** [comment] 2020-10-10 15:23
this issue still exist
