### ISSUE TITLE
Building for "Generic iOS device" fails

### ISSUE THREAD

**Issue by jk7f** [microsoft/react-native-code-push#1705] opened 2019-10-22 12:21 UTC
I'm trying to implement CodePush in our iOS app but I can't get the project to build afterwards.   

### Steps to Reproduce
1. react-native init test
2. yarn add react-native-code-push
3. update AppDelegate.m
4. Try to build

### Expected Behavior
The build completes without warnings

### Actual Behavior
Xcode throws 2 errors. Weirdly, the builds pass when building for a specific device.
```
  /node_modules/react-native-code-push/ios/CodePush/CodePushDownloadHandler.m:97:5: Implicit declaration of function 'assert' is invalid in C99

/node_modules/react-native-code-push/ios/CodePush/CodePushDownloadHandler.m:123:9: Implicit declaration of function 'assert' is invalid in C99

```
### Environment

Building both locally and in appcenter.ms:
* react-native-code-push version: 5.7.0
* react-native version: 0.61.1
* iOS/Android/Windows version: Xcode 11.1

**Comment by samie820** [comment] 2020-01-08 03:36
@jk7f Not quite sure of the cause but I think that there is a probability it has to do with the version compatibility, for `RN >= v0.60` you should use `react-native-code-push >= v6.0`. You can check it out [here](https://github.com/microsoft/react-native-code-push#supported-react-native-platforms)

**Comment by alexandergoncharov** [comment] 2020-02-13 08:14
Hi @jk7f ,
Thanks for reporting!

Yeah, @samie820 is right. Thanks!

Could you please upgrade your `react-native-code-push` version to the latest and follow this docs for setup:  https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-ios.md#plugin-installation-and-configuration-for-react-native-060-version-and-above-ios

I'm going to close this issue for now. Please feel free to reopen it if you have any questions.

**Closed by alexandergoncharov** 2020-02-13 08:14 UTC

**Comment by kp47** [comment] 2020-03-25 07:18
Hi @alexandergoncharov ,

I am getting the same issue.

Environment

react-native-code-push version: 6.1.1
react-native version: 0.61.5
iOS/Android/Windows version: Xcode 11.3.1

<img width="259" alt="Screenshot 2020-03-25 at 12 39 14 PM" src="https://user-images.githubusercontent.com/12131195/77511375-f56e0780-6e96-11ea-9671-50c1a5e65c13.png">

**Comment by yogeshwarnair-gep** [comment] 2020-08-04 12:38
please reopen this bug it still exist

**Comment by tradebulls** [comment] 2021-03-12 09:06
+1
