### ISSUE TITLE
codepush update will rollback on ios , but not  on android.

### ISSUE THREAD

**Issue by sunny635533** [Microsoft/react-native-code-push#1408] opened 2018-09-19 06:20 UTC
codepush update has rollback in ios , but not in android.
![image](https://user-images.githubusercontent.com/4737071/45734223-553a8100-bc16-11e8-94b4-8a47bc907874.png)
![image](https://user-images.githubusercontent.com/4737071/45734245-74391300-bc16-11e8-88a5-e88037d1513f.png)

CodePush updates perfectly on android, but why always rollback  on ios?
my codes:
![image](https://user-images.githubusercontent.com/4737071/45734626-b9aa1000-bc17-11e8-8412-83d5a8d4b745.png)
I will call it when app start and app onResume .

### Expected Behavior
ios When is there a rollback, the percentage should be lower！

### Environment

* react-native-code-push : 5.3.4
* react-native : 0.55.4

**Comment by sunny635533** [comment] 2018-09-19 08:38
@NickToropov 
1. I don't have that code in my hight-component. I will try to add it next time, then verify the problem whether is  because of it?
2. call checkForHotpatch method at hight-component's componentWillMount and also call  when app lifecycle is “active” 
![image](https://user-images.githubusercontent.com/4737071/45738205-638e9a00-bc22-11e8-8938-a372b2f43061.png)
3. 
![image](https://user-images.githubusercontent.com/4737071/45740096-02b59080-bc27-11e8-9b5f-e3b4941c6d40.png)
4. From getUpdateMetadata() , seems to get "failedInstall:true".
5. this occur in Debug and Release.
6. one of iOS version is 8.4.

wait for me, I will provide demo to you.

**Comment by NickToropov** [comment] 2018-09-20 14:00
Hi @sunny635533, thanks for demo! unfortunately I wasn't able to reproduce the issue. I made the following steps:
- `git clone https://github.com/sunny635533/TestCodePush.git`
- `cd TestCodePush`
- `yarn`
- `code-push app add issue1408-ios ios react-native`
- changed deployment keys in `TestCodePush/src/model/env-config.tsx`
- commented `get Navigator()` in `./node_modules/react-native/Libraries/react-native/react-native-implementation.js`
- `react-native start`
- `tsc -w`
- `cd ios`
- `pod install`
- opened `HongSiRN.xcworkspace` in XCode 10
- fixed compile error in `TestCodePush/ios/Pods/ReactiveCocoa/ReactiveCocoa/NSObject+Intercepting.swift` line 218
- run app from XCode
- `code-push release-react issue1408-ios ios --p ./ios/HongSiRN/Staging.plist`
- triggered code-push sync. Result - changes were applied,  no rollback.
repeated last two steps several times - changes were applied, no rollbacks.

Tested on iOS emulators 12 and 8.4

Please check my steps if I missed something? Is the issue reproduced stably for demo repository in your case?

Also rollbacks can be related to different binary versions. For example one of your users haven't updated binary version of application and tried to apply updates from CodePush. In this case new js code can fail as it isn't compatible with old native code.

**Comment by sunny635533** [comment] 2018-09-21 06:05
Hi, @NickToropov your step is right. Maybe you could try that:
code-push release-react issue1408-ios ios -m true -d Staging --des "change add route button style" -t "*"
I think the rollback happens occasionally. Sometimes When downloading updates, the progress bar of the update unchanged, for example 23% , then the  page stays there for a long time and could not do anything! So I have to shut down App。Finally  I can see a rollback in code-push history. 

I tried to disconnect the network or quit the app when I tried to update it midway. It still updated the lastest normally and didnt rollback. So i dont understand what the rollback would happen under what conditions??

**Comment by sunny635533** [comment] 2018-11-12 15:54
@NickToropov I get a log with xcode!!!!


2018-11-12 21:28:30.560 [info][tid:com.facebook.react.JavaScript] ========= env ==========Staging ,sessionId:20181112hsKrVymF2fkbsqh ,role:cz ,userId:A0000001141005A000 , routeName:TransportAccountNavigator
2018-11-12 21:28:30.719 [info][tid:com.facebook.react.JavaScript] ========== getUpdateMetadata ======={"isPending":false,"binaryDate":"1540967334.858006","isMandatory":true,"label":"v9","bundlePath":"CodePush/main.jsbundle","failedInstall":false,"packageHash":"1613688c38da08fb6df38e4a11ef64dcf5e817d619a6d573a934ce468975fe6f","downloadUrl":"https://codepushupdates.azureedge.net/storagev2/NcTGTQIWIvgQgkoi70zJ0WWYgElw080db430-e919-421b-b0c5-16a7302cb692","description":"test code-push update66","packageSize":617008,"appVersion":"2.9.4","deploymentKey":"Q_QxtfpH7ZsWgioSgV0nwJKixxX4080db430-e919-421b-b0c5-16a7302cb692","isFirstRun":false}
…….
2018-11-12 21:29:27.266076+0800 Staging[20648:1980311] [] nw_connection_get_connected_socket 79 Connection has no connected handler
2018-11-12 21:29:28.076899+0800 Staging[20648:1980111] Could not successfully update network info during initialization.
2018-11-12 21:29:28.077784+0800 Staging[20648:1980111] Could not successfully update network info during initialization.
2018-11-12 21:29:28.303478+0800 Staging[20648:1980598] [] nw_connection_get_connected_socket 83 Connection has no connected handler
2018-11-12 21:29:28.602114+0800 Staging[20648:1980111] [Snapshotting] Snapshotting a view (0x7fe118321400, UIKeyboardImpl) that is not in a visible window requires afterScreenUpdates:YES.
2018-11-12 21:29:29.596947+0800 Staging[20648:1981054] Task <87B66155-69B6-4739-86C9-A9385B4C1058>.<1> finished with error - code: -999
2018-11-12 21:29:29.859 [info][tid:com.facebook.react.JavaScript] ======= checkForHotpatch =======Q_QxtfpH7ZsWgioSgV0nwJKixxX4080db430-e919-421b-b0c5-16a7302cb692
2018-11-12 21:29:29.859610+0800 Staging[20648:1980643] ======= checkForHotpatch =======Q_QxtfpH7ZsWgioSgV0nwJKixxX4080db430-e919-421b-b0c5-16a7302cb692
2018-11-12 21:29:29.862 [info][tid:com.facebook.react.JavaScript] [CodePush] Disallowing restarts
2018-11-12 21:29:29.862347+0800 Staging[20648:1980643] [CodePush] Disallowing restarts
2018-11-12 21:29:30.310197+0800 Staging[20648:1981313] TIC TCP Conn Failed [86:0x60400016dc80]: 3:-9802 Err(-9802)
2018-11-12 21:29:30.336113+0800 Staging[20648:1981312] [] nw_connection_get_connected_socket 88 Connection has no connected handler
2018-11-12 21:29:30.758328+0800 Staging[20648:1981312] TIC TCP Conn Failed [87:0x604000172c00]: 3:-9802 Err(-9802)
2018-11-12 21:29:31.142669+0800 Staging[20648:1981312] TIC TCP Conn Failed [81:0x600000176980]: 12:8 Err(-65554)
2018-11-12 21:29:31.147724+0800 Staging[20648:1981054] Task <5AC47CE1-8B2A-4B61-A855-9422EE10EA35>.<0> HTTP load failed (error code: -1003 [12:8])
2018-11-12 21:29:31.147982+0800 Staging[20648:1981312] NSURLConnection finished with error - code -1003

2018-11-12 21:29:32.659 [info][tid:com.facebook.react.JavaScript] ==== code-push onHotpatchDownloadStart! ===
2018-11-12 21:29:32.659326+0800 Staging[20648:1980643] ==== code-push onHotpatchDownloadStart! ===

2018-11-12 21:29:33.362 [info][tid:com.facebook.react.JavaScript] code-push onHotpatchDownloadProgress done is 17771,total is 432451

2018-11-12 21:29:33.562566+0800 Staging[20648:1980643] code-push onHotpatchDownloadProgress done is 392781,total is 432451
2018-11-12 21:29:33.590 [info][tid:com.facebook.react.JavaScript] code-push onHotpatchDownloadProgress done is 432451,total is 432451
2018-11-12 21:29:33.591706+0800 Staging[20648:1980643] code-push onHotpatchDownloadProgress done is 432451,total is 432451
2018-11-12 21:29:33.673753+0800 Staging[20648:1981311] 
[CodePush] Applying diff update.
2018-11-12 21:29:33.674093+0800 Staging[20648:1981311] 
[CodePush] Verifying hash for folder path: /Users/sunny/Library/Developer/CoreSimulator/Devices/C16E983C-5107-4573-A32C-B54E52912DEC/data/Containers/Data/Application/3A97B5A2-1155-4ACF-9C4D-EE56D77DAE5E/Library/Application Support/CodePush/d2b14883a7983a6b91ea233e27b731bfb50a47c7ef1507f978521ed62da73941
2018-11-12 21:29:33.729352+0800 Staging[20648:1981311] 
[CodePush] Manifest string: (
    "CodePush/main.jsbundle.meta:831730b045b941c1067b0b3e6bd21110e08f85bbf8fdd1f723792fa8910791da",
    "CodePush/main.jsbundle:e1f93412f15931b8040b1971b6d72e0d6da81ed6d4a8ce2eb6e8d3935f439086",
    "CodePush/assets/node_modules/react-native-ratings/src/images/bell.png:315749213623d6d0f095ed3a2bea7c205a7c85a1799014f7831bb30df73d0188",
    "CodePush/assets/node_modules/react-native-ratings/src/images/airbnb-star-selected.png:cc272529e7576ef8f86b1b758c2610f53d6ceb5f39698cacce7d060c00a39cd3",
    "CodePush/assets/node_modules/react-native-ratings/src/images/heart.png:bf6adfcc3b77fdc0e224a8dd84ff1e8ee109645daae9bb32486b70cce6fc0316",
    "CodePush/assets/node_modules/react-native-ratings/src/images/airbnb-star.png:a15b007aa47fa315c13854a02cabdeef989138ae781ff267ddfe756f8003b0c8",
    "CodePush/assets/node_modules/react-native-ratings/src/images/rocket.png:202386b813319debcf2a4a5307f01ae42e451c619dc25ad53df888a6045f7aa9",
    "CodePush/assets/node_modules/react-native-ratings/src/im
2018-11-12 21:29:33.730289+0800 Staging[20648:1981311] 
[CodePush] Expected hash: d2b14883a7983a6b91ea233e27b731bfb50a47c7ef1507f978521ed62da73941, actual hash: 9fc0946d2a8d0c3ea9a7a5f4158208b2eb3126e4513c139bfa337630b9c499d8
2018-11-12 21:29:33.730421+0800 Staging[20648:1981311] 
[CodePush] The update contents failed the data integrity check.
2018-11-12 21:29:33.750 [info][tid:com.facebook.react.JavaScript] ===== code-push onHotpatchDownloadFinish! ====
2018-11-12 21:29:33.750579+0800 Staging[20648:1980643] ===== code-push onHotpatchDownloadFinish! ====
2018-11-12 21:29:33.751 [info][tid:com.facebook.react.JavaScript] [CodePush] The update contents failed the data integrity check.2018-11-12 21:33:20.464273+0800 Staging[20648:1981553] [] nw_connection_get_connected_socket 314 Connection has no connected handler

2018-11-12 21:33:22.563590+0800 Staging[20648:1984648] [] nw_connection_get_connected_socket 317 Connection has no connected handler
2018-11-12 21:33:24.037142+0800 Staging[20648:1980111] Could not successfully update network info during initialization.

2018-11-12 21:33:24.390978+0800 Staging[20648:1981054] TIC TCP Conn Failed [319:0x604000173740]: 12:8 Err(-65554)
2018-11-12 21:33:24.393449+0800 Staging[20648:1984648] Task <D7330843-70C6-43A5-A2FC-C1C732421378>.<0> HTTP load failed (error code: -1003 [12:8])
2018-11-12 21:33:24.398786+0800 Staging[20648:1984648] NSURLConnection finished with error - code -1003
2018-11-12 21:33:24.509977+0800 Staging[20648:1984648] [] nw_connection_get_connected_socket 321 Connection has no connected handler
2018-11-12 21:33:24.726024+0800 Staging[20648:1984648] [] nw_connection_get_connected_socket 322 Connection has no connected handler
2018-11-12 21:33:24.772737+0800 Staging[20648:1980111] [Snapshotting] Snapshotting a view (0x7fe118080e00, UIKeyboardImpl) that has not been rendered at least once requires afterScreenUpdates:YES.

2018-11-12 21:29:33.751530+0800 Staging[20648:1980643] [CodePush] The update contents failed the data integrity check.
2018-11-12 21:29:33.959276+0800 Staging[20648:1981311] [] nw_connection_get_connected_socket 95 Connection has no connected handler
2018-11-12 21:29:34.420172+0800 Staging[20648:1981311] [] nw_connection_get_connected_socket 96 Connection has no connected handler
2018-11-12 21:29:35.772 [info][tid:com.facebook.react.JavaScript] [CodePush] Re-allowing restarts
2018-11-12 21:29:35.772507+0800 Staging[20648:1980643] [CodePush] Re-allowing restarts

**Comment by NickToropov** [comment] 2018-11-13 10:53
Hi @sunny635533! Thanks for logs! The error here says that your packageHash in CodePush update differs from calculated hash after install this update. So something is wrong in hash calculation. Also I've noticed that there is a mention of `react-native-ratings` package in your logs. But there is no such package in demo repository. Could you update the repo that I could try to reproduce your issue once again?

**Comment by sunny635533** [comment] 2018-11-13 11:59
ok，[https://github.com/sunny635533/TestCodePush](https://github.com/sunny635533/TestCodePush)

**Comment by NickToropov** [comment] 2018-11-13 16:06
Am I right that you run `code-push release-react` from `ios` folder?

**Comment by sunny635533** [comment] 2018-11-14 02:33
@NickToropov , I run **code-push release-react** from TestCodePush folder,not ios. The issue didnt  reproduced from my demo repository. In my real project, sometimes the issue will occur.

**Comment by NickToropov** [comment] 2018-11-14 08:05
Are you using [code singing](https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-ios.md#code-signing-setup) feature for your real project?

**Comment by sunny635533** [comment] 2018-11-15 01:31
In ios , I didnt add CodePushPublicKey in info.list . Android also didnt add the CodePushPublicKey. I just add it in js codes. 
If ios does not add this key, is there a chance that the hash key will not match and roll back?

**Comment by NickToropov** [comment] 2018-11-15 10:29
`CodePushPublicKey` is not the same as `codePushDeploymentKey`. [Code singing](https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-ios.md#code-signing-setup) feature uses `CodePushPublicKey`. `codePushDeploymentKey` is used for checking necessary updates (Int/Staging/Production).
 
You mentioned that your real app stays at update's progress page but demo project has no such progress. Could you add such progress dialog/page into demo project or describe how to call it if it already exists there?

**Comment by sunny635533** [comment] 2018-11-15 15:55
In my demo project, also has progress dialog when app get a new update from code-push,it will show.I think i should try add CodePushPublicKey in my project, and check the problem whether still occur.

**Comment by NickToropov** [comment] 2018-11-16 16:45
If you don't use `--privateKeyPath` option in `release-react` command then it's not necessary to add `CodePushPublicKey` in your project. 

It seems I've finally reproduced the issue. I've got logs similar to yours:
```
...
2018-11-16 19:28:05.925 [info][tid:com.facebook.react.JavaScript] code-push onHotpatchDownloadProgress done is 209265,total is 343209
2018-11-16 19:28:06.063 [info][tid:com.facebook.react.JavaScript] code-push onHotpatchDownloadProgress done is 343209,total is 343209
2018-11-16 19:28:14.724 HongSiRN[10796:1624755] 
[CodePush] Applying diff update.
2018-11-16 19:28:14.725 HongSiRN[10796:1624755] 
[CodePush] Verifying hash for folder path: /var/mobile/Containers/Data/Application/BE373089-CCE7-40CC-94CB-4F1403017475/Library/Application Support/CodePush/8b0594563f5cdd806c9d9b87a10c3d7b2c83fc2510dd8b3a22a20965e1e5d28b
2018-11-16 19:28:18.411 HongSiRN[10796:1624755] 
[CodePush] Manifest string: (
    "CodePush/assets/assets/chezhu/1.png:8ef9b3cec3eb2f675821eb148c25f81afca41bbee1c9b901afd0bc05e82b08f4",
    "CodePush/assets/assets/chezhu/10.png:8ef9b3cec3eb2f675821eb148c25f81afca41bbee1c9b901afd0bc05e82b08f4",
    "CodePush/assets/assets/chezhu/11.png:8ef9b3cec3eb2f675821eb148c25f81afca41bbee1c9b901afd0bc05e82b08f4",
    "CodePush/assets/assets/chezhu/12.png:8ef9b3cec3eb2f675821eb148c25f81afca41bbee1c9b901afd0bc05e82b08f4",
    "CodePush/assets/assets/chezhu/13.png:8ef9b3cec3eb2f675821eb148c25f81afca41bbee1c9b901afd0bc05e82b08f4",
    "CodePush/assets/assets/chezhu/14.png:8ef9b3cec3eb2f675821eb148c25f81afca41bbee1c9b901afd0bc05e82b08f4",
    "CodePush/assets/assets/chezhu/15.png:8ef9b3cec3eb2f675821eb148c25f81afca41bbee1c9b901afd0bc05e82b08f4",
    "CodePush/assets/assets/chezhu/16.png:8ef9b3cec3eb2f675821eb148c25f81afca41bbee1c9b901afd0bc05e82b08f4",
    "CodePush/assets/assets/chezhu/17.png:8ef9b3cec3eb2f675821eb148c25f81afca41bbee1c9b901afd0bc05e82b08f4",
    "CodePush/assets/assets/chezhu/18.png:8ef9b3cec3eb2f675821eb148c25f81afca41bbee1c9b901afd0bc05e82b08f4",
    "CodePush/assets/assets/chezhu/19.png:8ef9b3cec3eb2f675821eb148c25f81afca41bbee1c9b901afd0bc05e82b08f4",
    "CodePush/assets/assets/chezhu/2.png:8ef9b3cec3eb2f675821eb148c25f81afca41bbee1c9b901afd0bc05e82b08f4",
    "CodePush/assets/assets/chezhu/20.png:8ef9b3cec3eb2f675821eb148c25f81afca41bbee1c9b901afd0bc05e82b08f4",
    "CodePush/assets/assets/chezhu/21.png:8ef9b3cec3eb2f675821eb148c25f81afca41bbee1c9b901afd0bc05e82b08f4",
    "CodePush/assets/assets/chezhu/3.png:8ef9b3cec3eb2f675821eb148c25f81afca41bbee1c9b901afd0bc05e82b08f4",
    "CodePush/assets/assets/chezhu/4.png:8ef9b3cec3eb2f675821eb148c25f81afca41bbee1c9b901afd0bc05e82b08f4",
    "CodePush/assets/assets/chezhu/5.png:a7a55db50913873fdf6d10ca6790763c9ab196a22d0878517829272b507fac6b",
    "CodePush/assets/assets/chezhu/back@2x.png:1d92f28b9ed1aed0110d2d41fd891c0e1a196d2b74dd9380e04e3b49194dd764",
    "CodePush/assets/assets/chezhu/back@3x.png:438c3970aaaee38198d4f2d6315778225caedd63ba7b85cee0ab76f124ae1199",
    "CodePush/main.jsbundle:73b8579ef08451d50792a95f8463a15b5d3ce817594d5eee74227566fe63a119",
    "CodePush/main.jsbundle.meta:563c6f75adb58c3864484c1450196f6895aeaa601102d9e2c97369f186c9eb5a"
)
2018-11-16 19:28:18.423 HongSiRN[10796:1624755] 
[CodePush] Expected hash: 8b0594563f5cdd806c9d9b87a10c3d7b2c83fc2510dd8b3a22a20965e1e5d28b, actual hash: 21cb26eaee413f32c17f7c532993950bf39d43fd7972373ac9def972020758fc
2018-11-16 19:28:18.423 HongSiRN[10796:1624755] 
[CodePush] The update contents failed the data integrity check.
```

The cause of the problem is that there is no enough space on device. As we can see in logs CodePush plugin tries `Applying diff update`. Diff update has small size and contains only files that were changed in comparison with previous release. All other necessary files plugin tries to copy from previous update and fails because of insufficient space. So not all required files were copied. Then plugin calculates hash of new update and compare it with hash calculated on server. As hashes are different update process fails and rolls back to previous version.

**Comment by sunny635533** [comment] 2018-11-18 06:06
@NickToropov   Always keep in touch with me, thank you for your patience so much !!! You help me find the cuase of the problem that I really want to know！

But, is there a way to tell me when the user device space is not enough?

**Comment by NickToropov** [comment] 2018-11-19 09:02
I'm glad to hear that I could help you ) 

To check available space I think you can use a RN plugin (something similar to [this](https://github.com/joltup/rn-fetch-blob)) or implement similar logic in your app by yourself.

**Comment by sunny635533** [comment] 2018-11-19 09:19
@NickToropov OK. I will consider what you said.

**Comment by NickToropov** [comment] 2018-11-19 11:22
@sunny635533 do you have any other questions?

**Comment by sunny635533** [comment] 2018-11-20 07:00
@NickToropov No. thanks!

**Comment by NickToropov** [comment] 2018-11-20 07:02
I'll close the issue as it seems to be resolved, feel free to reach us if you need any help. 
Thanks for using CodePush!

**Closed by NickToropov** 2018-11-20 07:02 UTC
Labels: iOS, investigating
