### ISSUE TITLE
Release on all platforms with one command 

### ISSUE THREAD

**Issue by jr-k** [Microsoft/react-native-code-push#692] opened 2017-02-06 22:53 UTC
Hello,

I've a question about releasing process.  I developed an application with react-native for both ios and android and for now when I need to send an update I'm doing that:

`code-push release-react myApp android -d Production -m true --des "some improvements"`

Then when I type `code-push deployment ls myApp` I see "Label v10" with my comments and so on. But now I want to send an update for ios too so I'm doing that:

`code-push release-react myApp ios -d Production -m true --des "some improvements"`

Now  when I type `code-push deployment ls myApp` I see "Label v11". But It makes no sense because it is the same package with same code. Is it possible to call a command which would look like `code-push release-react both` or somethin?

What is the correct way to deploy an unique package on multiple platforms ? 
Thanks !

**Comment by max-mironov** [comment] 2017-02-07 08:40
Closed as an exact duplicate of https://github.com/Microsoft/code-push/issues/386

**Closed by max-mironov** 2017-02-07 08:40 UTC
Labels: duplicate
