### ISSUE TITLE
How to build a releaseStaging apk?

### ISSUE THREAD

**Issue by jaggerwang** [Microsoft/react-native-code-push#991] opened 2017-09-08 08:17 UTC
The apk build by do "Build => Generate signed apk => Choose releaseStaging" in Android Studio can not run in device. And I don't know how to build releaseStaging apk in command line, the release apk can be build using command "./gradlew assembleRelease".

By the way, code push already worked for our release apk.

### Steps to Reproduce
1. build apk using releaseStaging config in Android Studio.
2. install apk on device.
3. run app.

### Expected Behavior
Run app ok.

### Actual Behavior
App crash.

### Environment

* react-native-code-push version: 2.1.0-beta
* react-native version:  0.44.3
* iOS/Android/Windows version: Android 5.1
* Does this reproduce on a debug build or release build? release
* Does this reproduce on a simulator, or only on a physical device? device

### app/build.gradle
![image](https://user-images.githubusercontent.com/1255011/30202373-d0d5ff80-94b0-11e7-917b-7d19165541d2.png)

**Comment by jaggerwang** [comment] 2017-09-08 10:18
And build iOS staging package also failed. I'm using pods, it's ok to build with release config.

![2017-09-08 18 17 14](https://user-images.githubusercontent.com/1255011/30207367-e2f68ce6-94c1-11e7-88e8-b4bed856714b.png)
![2017-09-08 18 11 29](https://user-images.githubusercontent.com/1255011/30207290-966acf90-94c1-11e7-93fa-f095a8bbc3ee.png)
![2017-09-08 18 14 46](https://user-images.githubusercontent.com/1255011/30207291-96a93762-94c1-11e7-98e3-4e612232e5c2.png)

**Comment by sergey-akhalkov** [comment] 2017-09-08 11:01
Hi @jaggerwang, thanks for reaching us.

To build your app in `releaseStaging` build type do the following:
1. go to `android` folder 
2. execute `./gradlew assembleReleaseStaging` command. It will produce `/android/app/build/outputs/apk/app-releaseStaging-unsigned.apk` file.
3. Open Android Studio -> Build -> Generate signed apk -> Build Type: releaseStaging -> Finish. It will produce `/android/app/app-releaseStaging.apk` file

Here is Android sample app I've configured: [rncp991.zip](https://github.com/Microsoft/react-native-code-push/files/1287628/rncp991.zip)

For iOS please take a loot at this https://github.com/Microsoft/react-native-code-push/issues/893#issuecomment-317648454

**Comment by jaggerwang** [comment] 2017-09-09 09:01
@sergey-akhalkov For android, your solution is not working for me. And I found another solution, set releaseStaging config to the same with release, except the code-push key.
![image](https://user-images.githubusercontent.com/1255011/30238758-2cfa813a-9580-11e7-8209-d49e0b54106c.png)

For iOS, I'm already did as your screenshot, and it not work for me. The staging config is copy from release, and config exactly as the "Multi-Deployment Testing" in README doc.

**Comment by sergey-akhalkov** [comment] 2017-09-11 07:08
Hi @jaggerwang, 
1. Regarding Android - got it.
2. Regarding iOS - have you downloaded the sample app (to verify if it works for you?) and paid attention to the second screenshot I made here https://github.com/Microsoft/react-native-code-push/issues/893#issuecomment-317648454 ?

**Comment by sergey-akhalkov** [comment] 2017-09-12 10:53
@jaggerwang, I've not changed `Per-configuration Intermediate Build Files Path` option, but `Per-configuration Build Products Path` only, the same I've done for Pods project, please pay attention to the second screenshot from my comment. You could also try to download the sample app I've provided in the comment or share with me minimum version of your app so I could try to spend some time on it and probably fix the issue you have.

**Comment by jaggerwang** [comment] 2017-09-12 11:43
@sergey-akhalkov Sorry, I'm not noticed than the config is against Pods project. I modified the config as follow, but still got error.

![2017-09-12 19 38 51](https://user-images.githubusercontent.com/1255011/30324127-8909d20e-97f2-11e7-86c7-9f5b6659e7c7.png)
![2017-09-12 19 39 08](https://user-images.githubusercontent.com/1255011/30324129-890dbd2e-97f2-11e7-82f8-db5f63903503.png)
![2017-09-12 19 39 31](https://user-images.githubusercontent.com/1255011/30324130-894bacf6-97f2-11e7-8971-1c19101c822c.png)
![2017-09-12 19 32 37](https://user-images.githubusercontent.com/1255011/30324142-8fb4a250-97f2-11e7-9fce-609ee76da206.png)

**Comment by sergey-akhalkov** [comment] 2017-09-12 12:19
@jaggerwang, it's really hard to say what goes wrong here with the `charts.framework` you are using in your project without the real app. If you share it with me - I could try to spend some time on it and try to fix the issue.

**Comment by sergey-akhalkov** [comment] 2017-09-15 09:23
Closing this, please feel free to reopen if you have source code or exact repro steps that could help me to reproduce the issue.

**Closed by sergey-akhalkov** 2017-09-15 09:23 UTC
Labels: question, waiting-for-clarification

**Comment by youngjuning** [comment] 2018-11-14 06:14
https://github.com/youngjuning/youngjuning.github.io/issues/187

**Comment by mohamedadel1994825** [comment] 2022-10-20 06:13
Aslamo Alikm,
hello guys, as @jaggerwang say that solution is work for me but it's crashed due to hermes issue , i used .64 react native version.
so for staging we should add this 
@sergey-akhalkov For android, your solution is not working for me. And I found another solution, set releaseStaging config to the same with release, except the code-push key.
image
<img width="809" alt="Screen Shot 2022-10-20 at 8 11 01 AM" src="https://user-images.githubusercontent.com/54745774/196869649-cae0f912-f3bc-422c-9f6d-64dd2d03a383.png">
add this         releaseStagingImplementation files(hermesPath + "hermes-debug.aar")
and you can bundle a staging release by this command 
cd android && ./gradlew assembleReleaseStaging
or set in package.json like this 
<img width="809" alt="Screen Shot 2022-10-20 at 8 12 55 AM" src="https://user-images.githubusercontent.com/54745774/196869978-37e2798a-5caa-435a-b78b-f5b5a4a31d60.png">
and to run write yarn releaseStaging it wile generate staging bundle release.
