### ISSUE TITLE
IOS Won't build -  CodePush.build/Debug-iphonesimulator/CodePush.build/Objects-normal/x86_64/CodePushUtils.o /Users/yosef/Desktop/HiVoltsApp/node_modules/react-native-code-push/ios/CodePush/CodePushUtils.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

### ISSUE THREAD

**Issue by YosefOberlander** [microsoft/react-native-code-push#1841] opened 2020-04-14 21:47 UTC
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.
2. 
3.

### Expected Behavior
build successfully 
### Actual Behavior
fails to build
```
 CodePush.build/Debug-iphonesimulator/CodePush.build/Objects-normal/x86_64/CodePushUtils.o /Users/yosef/Desktop/HiVoltsApp/node_modules/react-native-code-push/ios/CodePush/CodePushUtils.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

```

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version: 6.2.0
* react-native version: 0.59.10
* iOS/Android/Windows version: OSX Mojave V 10.14.6
* Does this reproduce on a debug build or release build? both
* Does this reproduce on a simulator, or only on a physical device? yes

(The more info the faster we will be able to address it!)

**Comment by spiandorello** [comment] 2020-04-15 02:42
same error!!!

**Comment by alexandergoncharov** [comment] 2020-06-05 10:45
Hi @YosefOberlander and @spiandorello ,
Thanks for reporting!

Unfortunately, I can't reproduce it. Could you please provide some demo app with reproducing issue and reprosteps? I would like to reproduce and investigate it.

**Comment by andreidubov** [comment] 2020-06-11 11:37
Since there is no answer and we cannot reproduce it I’m going to close this issue for now. Please feel free to reopen it if you have any questions or issues.

**Closed by andreidubov** 2020-06-11 11:37 UTC
Labels: bug, no-repro, waiting-for-clarification
