### ISSUE TITLE
i got an UNKNOWN_ERROR ，It only happens in the Android release

### ISSUE THREAD

**Issue by ceressteven** [microsoft/react-native-code-push#1825] opened 2020-03-28 16:29 UTC
I can't see any error messages from the log, but it works  on IOS and android debug  successful

and  can get the update and install it, but it only got UNKNOWN_ERROR on Android release  it seems that an error occurred before the update was requested

**Comment by alexandergoncharov** [comment] 2020-06-05 10:51
Hi @ceressteven ,
Thanks for reporting!

It also can be related to network issues. Could you please provide some demo app with reproducing issue and reprosteps? I would like to reproduce and investigate it.

**Comment by andreidubov** [comment] 2020-06-10 07:59
Since there is no answer and we cannot reproduce it I'm going to close this issue for now. Please feel free to reopen it if you have any questions or issues.

**Closed by andreidubov** 2020-06-10 07:59 UTC
Labels: android, bug, no-repro, waiting-for-clarification

**Comment by mengbimao** [comment] 2023-01-30 01:57
I have the same problem. Have you solved it?

**Comment by riamon-v** [comment] 2023-02-03 14:28
Same issue here too using React-Native 69.0 and react-native-code-push 7.1.0.
Any news ?

**Comment by riamon-v** [comment] 2023-02-05 20:15
This fixed my issue:
https://github.com/microsoft/react-native-code-push/issues/1961#issuecomment-710698621
