### ISSUE TITLE
Calling sync twice in a row

### ISSUE THREAD

**Issue by JAStanton** [Microsoft/react-native-code-push#110] opened 2015-12-15 23:23 UTC
if I call:
```js
CodePush.sync({ installMode: installMode: CodePush.InstallMode.ON_NEXT_RESUME })
```
and it finds an update and downloads it but before I restart or resume the app the app I call:
```js
CodePush.sync({ installMode: installMode: CodePush.InstallMode.IMMEDIATE })
```

Would you expect it to immediately restart or no-op?
Because right now nothing happens, and I expected it to restart immediately.

**Comment by lostintangent** [comment] 2015-12-16 00:50
The expected behavior would be to no-op, since the "pending" update from the first call to sync is already downloaded, and therefore, the second call to sync would resolve its promise as no update available. Sync doesn't currently check for pending updates, which is why this behavior exists. That said, we've discussed modifying this behavior, so just because it's the currently expected behavior, doesn't mean it's the right behavior :)

If you're interested in "artificially" restarting the app in order to apply a previously downloaded update, you could call the restartApp module-level method as a workaround. If however, you want to restart the app only if there is a pending update, there isn't currently a way to do that.

We've discussed doing three different things that might help your scenario, and I'd be interested if any of them sound sufficient:

1. Adding an isPending property to the LocalPackage object that is returned when calling getCurrentPackage. This could be used to query the current package and if the latest update is still pending, restart the app. This might make sense to do in general, but it's probably a roundabout way of solving this scenario specifically.

2. Add a parameter to restartApp that specifies you only want to restart if there is a pending update. Semantically, I feel like this solution is pretty decent if you want to call sync at one point, and then "force" a pending update in another. 

3. Modify sync to look for pending updates, and effectively overwrite the previously specified install mode. The only reason I'm not in love with this one is that the only thing I can imagine people wanting to use this solution for is to apply a pending update sooner, and I'm not sure if this is the most intuitive way to solve it. Maybe it is, I'm not sure.

What are your thoughts? Doing the first or second items would be super straight forward and not breaking changes, so we could address them pretty quickly.

**Comment by JAStanton** [comment] 2015-12-16 00:54
Yeah the first two solutions would work best actually. I think `isPending` on the LocalPackage would probably make the most sense. Thats the first place I looked :)

**Comment by lostintangent** [comment] 2015-12-16 00:59
OK cool. I'll send a PR out for this tonight. Stay tuned and thanks for the feedback!

**Comment by JAStanton** [comment] 2015-12-16 00:59
Thanks!

**Comment by nevir** [comment] 2015-12-16 01:01
> The expected behavior would be to no-op, since the "pending" update from the first call to sync is already downloaded, and therefore, the second call to sync would resolve its promise as no update available.

Hmm, that's counterintuitive to me - I would expect the _download_ to no-op, but not the entire `sync` process.

It seems like it might be worth also having `sync` check for new versions always, even if there's a downloaded copy; but only download if the downloaded one differs from the remote version.

Similar edge case:

1. `sync` is called (in `ON_NEXT_RESTART` mode). Update 1 is downloaded.
2. `sync` is called (in `ON_NEXT_RESTART` mode) some time later; update 2 is available.
  * Under this current logic, it would never download, right?
  * Seems like it would be ideal to download update 2 and blow away the cached copy of 1
3. On restart, apply update 2; skipping over 1.

**Comment by nevir** [comment] 2015-12-16 01:02
`isPending` is awesome either way though :)  :+1:  to that

**Comment by lostintangent** [comment] 2015-12-16 02:24
@nevir I agree with you. The sync method is entirely implemented in JS, and so in order to make it support restarting pending updates, we would need to implement isPending anyways. So that seems like a win-win feature to implement :) I'll send out a PR for that change, which should unblock this scenario, and then we can easily layer further API improvements on top of it. 

This is such awesome feedback guys! Thank you both so much.

**Comment by lostintangent** [comment] 2015-12-17 05:09
I just submitted PR #113 to address the `isPending` feedback. Check it out! Once that is in, we can discuss the `sync` improvements.

**Comment by lostintangent** [comment] 2015-12-18 06:29
Just merged the isPending support into master. @geof90 was working on another bug fix that I'd like to get in the next release, but we should be able to get that out tomorrow or so.

I'll keep this bug open to track the changes to sync that we discussed above. Thanks!

**Comment by geof90** [comment] 2015-12-22 21:44
> The expected behavior would be to no-op, since the "pending" update from the first call to sync is already downloaded, and therefore, the second call to sync would resolve its promise as no update available.

If there was no update released between the first and second call to sync, sync would return SyncStatus.UP_TO_DATE in the second call, which in my opinion, makes sense because the latest package is indeed installed in the first call and it is up to date. Unless you think we should return SyncStatus.UPDATE_INSTALLED in the second call instead. I have no preference over either.

If there WAS an update released between the first and second call to sync, then yes, I agree, it should download and remove the first update. Under the current implementation, it does that, but it would wrongly assume that the first update is a verified one, i.e. if the second one fails, it would roll back to the first one. This is a problem because we have not yet verified the first one, so that could be a potential cause of the app going into an irrecoverable state. I think this should be fixed.

**Closed** 2016-02-08 21:22 UTC
Labels: bug
