### ISSUE TITLE
Android app fails to download package from CodePush

### ISSUE THREAD

**Issue by aceisScope** [Microsoft/react-native-code-push#983] opened 2017-08-30 13:40 UTC
### Steps to Reproduce
Launch the staging version of the Android app and monitor via Android Studio LogCat. 

### Expected Behavior
The app should download the update package.

### Actual Behavior
What actually happens?

Package downloading failed.
Android Studio Logs are as below:
```
08-30 16:33:06.877 32650-32672/? W/System.err: java.io.FileNotFoundException: https://codepushupdates.azureedge.net/storagev2/SOME_UNIQUE_ID_OF_THE_PACKAGE
08-30 16:33:06.879 32650-32672/? W/System.err:     at com.microsoft.codepush.react.CodePushUpdateManager.downloadPackage(CodePushUpdateManager.java:169)
08-30 16:33:06.879 32650-32672/? W/System.err:     at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:232)
08-30 16:33:06.879 32650-32672/? W/System.err:     at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:226)
08-30 16:33:06.891 32650-32692/? I/ReactNativeJS: [CodePush] An unknown error occurred.
```

### Reproducible Demo

* https://codepushupdates.azureedge.net/storagev2/SOME_UNIQUE_ID_OF_THE_VERSION is not accessible. If necessary I can provide the `SOME_UNIQUE_ID_OF_THE_PACKAGE`.

### Environment

* react-native-code-push version:  1.17.4-beta
* react-native version: 0.42.3
* iOS/Android/Windows version: Android 7.1.2
* Does this reproduce on a debug build or release build? It's a staging build, which is basically a duplication of the release build, with a staging Code Push key.
* Does this reproduce on a simulator, or only on a physical device?
On a physical device Nexus 5X

**Comment by sergey-akhalkov** [comment] 2017-08-30 14:05
Hi @aceisScope, thanks for reaching us and sorry for the inconvenience. We've just received an email from another customer with the same issue and as of now I can see that it's gone. Seems like there was a temporary server side issue, so could you please verify if everything work for you and let us know if the issue is still reproduced?

**Comment by max-mironov** [comment] 2017-08-31 05:56
I believe we could close the issue at that moment, probably a service blip. 
Please let us know if you see something suspicious.

**Closed by max-mironov** 2017-08-31 05:56 UTC
Labels: android

**Comment by afshin-hoseini** [comment] 2019-03-06 18:34
Same Error. What you have done @aceisScope  ?
