### ISSUE TITLE
undefined is not an object (evaluating \'this._serverUrl.slice\')'

### ISSUE THREAD

**Issue by deju** [Microsoft/react-native-code-push#144] opened 2016-01-11 04:59 UTC
[CodePush] An unknown error occurred.'
 '[CodePush] undefined is not an object (evaluating \'this._serverUrl.slice\')'

how can i fix it?

**Comment by lostintangent** [comment] 2016-01-11 06:01
Hey @deju, thanks for reporting this! Two questions: is this happening on iOS and/or Android, and what version of React Native are you running?

**Comment by deju** [comment] 2016-01-11 06:20
@lostintangent  iOS, and the version of React Native is 0.14.2.

**Comment by lostintangent** [comment] 2016-01-11 06:30
Which version of the CodePush plugin are you using? Anything newer then 1.4.0 requires React Native 0.15.0+, so it's possible that there might be an issue with the JS being compiled correctly.

**Comment by deju** [comment] 2016-01-11 06:56
@lostintangent  The CodePush version is 1.5.2-beta. i will update the React Native ang try it. thank you!

**Comment by lostintangent** [comment] 2016-01-11 07:00
Sounds good, thanks for giving CodePush a try!

**Comment by lostintangent** [comment] 2016-01-12 02:51
@deju Any luck after the upgrade? Make sure after you upgrade React Native versions that you also run "react-native upgrade" as well, since that can be the source of subtle issues of you forget to do it.

**Comment by deju** [comment] 2016-01-12 03:11
Yes, i updating. I will let you know the result after trying it!  Thank you!

**Comment by lostintangent** [comment] 2016-01-14 02:03
Any luck @deju? I tried reproing this issue again and couldn't, so I want to make sure we validate that once you upgrade to a supported version of React native

**Comment by deju** [comment] 2016-01-14 05:22
@lostintangent sorry, i have updated the latest version of RN and occur some problems, so i need fix it. I am fixing now... I were in hospital yesterday. sorry

**Comment by deju** [comment] 2016-01-14 08:54
@lostintangent It is OK now. The error was disappered. RN(v0.14->0.17), Node(v4.x-> v5.x), npm(v2.x->3.x). I am testing the function now.

**Comment by lostintangent** [comment] 2016-01-14 16:36
Oh man I'm so sorry to hear about your hospital visit. I hope everything is OK!

Thanks for confirming your experience. I'm going to close this bug since it doesn't repro for you once you upgraded to a supported RN version. If you run into any new issues, let us know. Thanks!

**Closed by lostintangent** 2016-01-14 16:36 UTC

**Comment by israrwz** [comment] 2017-10-24 21:13
I'm still getting this error with following versions:

		"react-native": "^0.49.2",
		"react-native-code-push": "^5.1.3-beta",

**Comment by sergey-akhalkov** [comment] 2017-10-25 07:16
Hi @israrwz, please feel free to create new issue and provide us repro steps/reproducible demo
