### ISSUE TITLE
Cannot promote staging to prod on Android

### ISSUE THREAD

**Issue by ebaynaud** [Microsoft/react-native-code-push#1004] opened 2017-09-15 14:37 UTC
That's rather a question than an issue. Anyway.

### Expected Behavior
Be able to promote update from Staging to Production on Android.

### Actual Behavior
What actually happens?
My Staging build is on Hockey App (app-releaseStaging.apk v3.1.0) and my Production build is on Google Play (app-release.apk v3.1.1). I can't see update dialog on Production after promoting. That's working well with iOS (not same app: MyApp-iOS).

```
$ code-push deployment ls MyApp-Android -k
┌────────────┬──────────────────────────────────────────────────────────────────┬─────────────────────────────────┬───────────────────────┐
│ Name       │ Deployment Key                                                   │ Update Metadata                 │ Install Metrics       │
├────────────┼──────────────────────────────────────────────────────────────────┼─────────────────────────────────┼───────────────────────┤
│ Production │ <MY PROD CODEPUSH KEY>                                           │ Label: v1                       │ No installs recorded  │
│            │                                                                  │ App Version: ~3.1.0             │                       │
│            │                                                                  │ Mandatory: No                   │                       │
│            │                                                                  │ Release Time: a day ago         │                       │
│            │                                                                  │ Released By: me@gmail.com       │                       │
├────────────┼──────────────────────────────────────────────────────────────────┼─────────────────────────────────┼───────────────────────┤
│ Staging    │<MY STAGING CODEPUSH KEY>                                         │ Label: v4                       │ Active: 100% (1 of 1) │
│            │                                                                  │ App Version: ~3.1.0             │ Total: 1              │
│            │                                                                  │ Mandatory: No                   │                       │
│            │                                                                  │ Release Time: a day ago         │                       │
│            │                                                                  │ Released By: me@gmail.com       │                       │
└────────────┴──────────────────────────────────────────────────────────────────┴─────────────────────────────────┴───────────────────────┘
```

### Reproducible Demo
```
code-push release-react MyApp-Android android -t ~3.1.0 -d Staging
```
=> OK, update is proposed on Staging app (from Hockey App). 
```
code-push promote MyApp-Android Staging Production
```
=> Not OK, update is not proposed on Production app (from Google play). 

My package.json related stuff:
```
    "android:build:integration": "rm -f android/app/build/outputs/apk/app-releaseStaging.apk; cd android && ENVFILE=.env.integration ./gradlew assembleReleaseStaging; cd ..",
    "android:build:production": "rm -f android/app/build/outputs/apk/app-release.apk; cd android && ENVFILE=.env.production ./gradlew assembleRelease; cd ..",
```

My build.gradle related stuff:
```
    buildTypes {
        debug {
            // Note: CodePush updates should not be tested in Debug mode as they are overriden by the RN packager. However, because CodePush checks for updates in all modes, we must supply a key.
            buildConfigField "String", "CODEPUSH_KEY", '""'
        }
        releaseStaging {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
            buildConfigField "String", "CODEPUSH_KEY", '"<MY STAGING CODEPUSH KEY>"'
        }
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
            buildConfigField "String", "CODEPUSH_KEY", '"<MY PROD CODEPUSH KEY>"'
        }
    }
```

### Environment

* react-native-code-push version: 5.0.0-beta
* react-native version: 0.48.3
* Does this reproduce on a debug build or release build? Release
* Does this reproduce on a simulator, or only on a physical device? Physical device

**Comment by sergey-akhalkov** [comment] 2017-09-19 09:35
Hi @ebaynaud, thanks for reaching us and sorry for the delayed response. 
We have several points to clarify:
1. What is the binary version of your app running in prod now?
2. Could you please share production deployment history with us?
3. Do I get it right if update dialog properly shows for staging version of your app?
4. Could you please share with us the way you are initializing CodePush in java? ( i.e. `new CodePush(...)` )

**Comment by ebaynaud** [comment] 2017-09-19 10:23
Thanks @sergey-akhalkov for the time you take to help me.

_1. What is the binary version of your app running in prod now?_
v3.1.1

_2. Could you please share production deployment history with us?_
What kind of history? Let me try: I created v3.1.0 (staging) for iOS and Android and pushed them to HockeyApp. I created v3.1.1 (production) for iOS and Android and pushed them to stores. When I push an update to staging, update dialog is ok everywhere. When I promote this update to production, update dialog is ok on iOS but not on Android where nothing happens.

_3. Do I get it right if update dialog properly shows for staging version of your app?_
Yes, as said upper ;)

_4. Could you please share with us the way you are initializing CodePush in java? ( i.e. new CodePush(...) )_
`new CodePush(BuildConfig.CODEPUSH_KEY, MainApplication.this, BuildConfig.DEBUG),`

**Comment by sergey-akhalkov** [comment] 2017-09-19 11:14
@ebaynaud, thanks for the response. From your answers I cannot see any stranges or issues, so I'll try to create demo app and reproduce/fix the issue, in case the issue will not reproduce for me - I'll share with you generated demo app so you'll be able to review it.

PS by deployment history I meant output for `code-push deployment history <appName> <deploymentName>`

**Comment by sergey-akhalkov** [comment] 2017-09-19 12:04
I've tried to reproduce the issue but with no luck, here are repro steps:
1. prepare android app to use multi-deployment-testing feature
2. change app versionName to 1.0.5
3. `code-push release-react rncp1004-android android -d Staging -t ~1.0.0`
4. `code-push promote rncp1004-android Staging Production`
5. `./gradlew assembleRelease` & `adb install app-release.apk`
6. Successfully install update from Production deployment: 
![screenshot 2017-09-19_15-03-17](https://user-images.githubusercontent.com/4928157/30591491-c095b086-9d4b-11e7-8587-78e6d4530eb9.png)


Here is app source code: [rncp1004.zip](https://github.com/Microsoft/react-native-code-push/files/1314118/rncp1004.zip)

**Comment by ebaynaud** [comment] 2017-09-19 12:51
What I did after having edited local.properties:
```
cd ~/Downloads/rncp1004/
yarn
code-push app add rncp1004-android android react-native
cd android/
./gradlew assembleReleaseStaging
./gradlew assembleRelease
adb install app/build/outputs/apk/app-releaseStaging.apk
code-push release-react rncp1004-android android -d Staging -t ~1.0.0
```
=> here it's working, then:

**Comment by ebaynaud** [comment] 2017-09-19 15:11
What I did after having edited local.properties with my sdk path:
```
cd ~/Downloads/rncp1004/
yarn
code-push app add 1004-android android react-native
```
Copying keys in build.gradle, then:
```
cd android/
./gradlew assembleReleaseStaging
./gradlew assembleRelease
adb install app/build/outputs/apk/app-releaseStaging.apk
```
I change versionName to 1.0.6 in build.gradle and then:
```
cd ..
code-push release-react 1004-android android -d Staging -t ~1.0.0
code-push deployment history 1004-android Staging
┌───────┬──────────────┬─────────────┬───────────┬─────────────┬──────────────────────┐
│ Label │ Release Time │ App Version │ Mandatory │ Description │ Install Metrics      │
├───────┼──────────────┼─────────────┼───────────┼─────────────┼──────────────────────┤
│ v1    │ a minute ago │ ~1.0.0      │ No        │             │ No installs recorded │
└───────┴──────────────┴─────────────┴───────────┴─────────────┴──────────────────────┘
```
**=> update was not proposed**

I change versionName to 1.0.7 in build.gradle **AND** I do a JS modification and then:
```
code-push release-react 1004-android android -d Staging -t ~1.0.0
code-push deployment history 1004-android Staging
┌───────┬────────────────┬─────────────┬───────────┬─────────────┬───────────────────────┐
│ Label │ Release Time   │ App Version │ Mandatory │ Description │ Install Metrics       │
├───────┼────────────────┼─────────────┼───────────┼─────────────┼───────────────────────┤
│ v1    │ 19 minutes ago │ ~1.0.0      │ No        │             │ No installs recorded  │
├───────┼────────────────┼─────────────┼───────────┼─────────────┼───────────────────────┤
│ v2    │ 14 minutes ago │ ~1.0.0      │ No        │             │ Active: 100% (1 of 1) │
│       │                │             │           │             │ Total: 1              │
└───────┴────────────────┴─────────────┴───────────┴─────────────┴───────────────────────┘
```
**=> update was proposed**

=> From what I understand until here, first `code-push release-react` of 1.0.6 creates v1 even if no changes were made to the code because code-push has no reference version to compare to. However, as there is finally no difference, first update is not proposed. It's confirmed with another test where I perform a code update before pushing the v1 and there the updated was proposed directly.
=> Hope I'm clear, I think there is something buggy or undocumented there as: *either v1 creation should not be released if no change, either update should be proposed...*.

Now, after deleting staging app from device:
```
cd android
adb install app/build/outputs/apk/app-release.apk
cd ..
code-push promote 1004-android Staging Production
code-push deployment history 1004-android Production
┌───────┬──────────────────────────────┬─────────────┬───────────┬─────────────┬───────────────────────┐
│ Label │ Release Time                 │ App Version │ Mandatory │ Description │ Install Metrics       │
├───────┼──────────────────────────────┼─────────────┼───────────┼─────────────┼───────────────────────┤
│ v1    │ a minute ago                 │ ~1.0.0      │ No        │             │ Active: 100% (1 of 1) │
│       │ (Promoted v2 from "Staging") │             │           │             │ Total: 1              │
└───────┴──────────────────────────────┴─────────────┴───────────┴─────────────┴───────────────────────┘
```
**=> update was proposed**

Not reproducing  my issue indeed... And I don't see any difference with my project.

Could my issue be related to a previous`code-push deployment clear <appName> <deploymentName>`
Not sure to understand documentation about the consequences of this command. I know I tested this before, either on Staging and Production environments to erase previous tests.

I think I'll start from scratch now removing my code-push apps then creating them again. I'll tell you whether my issue is solved after that now that I'm comfortable with code-push use.

**Comment by ebaynaud** [comment] 2017-09-19 15:36
Can you explain which key should be in android/app/src/main/res/values/strings.xml? When is it used?

**Comment by ebaynaud** [comment] 2017-09-19 16:51
I may have an explanation to what happened to me, that could reproduce what I did:
- Change A to B in the code
- code-push release to Staging (v1 staging)
- Change B to A in the code
- code-push release to Staging (v2 staging)
- code-push promote to Production (v1 prod = v2 staging)

No changes because changes from v1 staging were reverted in v2 staging so v1 prod does not propose update... Possible?

**Comment by sergey-akhalkov** [comment] 2017-09-20 07:43
@ebaynaud, 
> I think I'll start from scratch now removing my code-push apps then creating them again. I'll tell you whether my issue is solved after that now that I'm comfortable with code-push use.

Got it, let me know if any updates.

>EDIT: My guess is nothing in multi-deployment setup because I can use the whole process without it.

Correct!

>No changes because changes from v1 staging were reverted in v2 staging so v1 prod does not propose update... Possible?

Yes, that sounds like a truth and could be the reason of that behavior. 

By the way, please let me know if you have any updates regarding this issue and find out stable repro steps, as for now I'm closing the issue, please feel free to ask questions here if any and reopen the issue.

**Closed by sergey-akhalkov** 2017-09-20 07:43 UTC
Labels: android, no-repro, waiting-for-clarification
