### ISSUE TITLE
CodePush android did not update, iOS crashes after release

### ISSUE THREAD

**Issue by vdlindenmark** [Microsoft/react-native-code-push#1225] opened 2018-03-05 21:57 UTC
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Followed the steps to setup codePush. Have made sure the keys are correct codepush staging and release keys.
2. Running staging build on both an iOS simulator and an Android device
3. Uploaded a codepush update for each platform
4. Can see the update on AppCenter -> CodePush -> Staging
5. Restarted staging apps multiple times but apps didn't receive updates. In AppCenter it shows null installs too.

### Expected Behavior
What you expected to happen?
Apps should update after restart without a crash

### Actual Behavior
What actually happens?
Nothing happens on Android, iOS crashed after restarting the app.

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version: 5.2.2
* react-native version: 0.54.0
* iOS/Android/Windows version: iOS: 11.2.6 Android: i.d.k.
* Does this reproduce on a debug build or release build? both
* Does this reproduce on a simulator, or only on a physical device? simulators.

(The more info the faster we will be able to address it!)

**Comment by temitope** [comment] 2018-03-07 04:26
happens for me only on release

**Comment by temitope** [comment] 2018-03-07 08:23
Success. I realized that I had upgraded my react-native to a new version since my last push of a release via CodePush (which was mandatory and possibly from a different version of react-native). This was causing the crash it seems.

It worked once I re-pushed the latest version of my code to CodePush servers (without the mandatory `-m` flag, and it worked. Makes sense kind of. I wish it would have simply failed more gracefully if possible. Double checking results now. Confirmed.

This perhaps explains why it was only happening on Release, rather than Debug. Pernicious bug that took me almost a week to find the culprit and now a few hours for the solution.

**Comment by temitope** [comment] 2018-03-08 00:47
Note: I found that it also helped that I removed `index.ios.js` and `index.android.js` entirely from my root folder. I also removed Codepush from my `Podfile` and relegated it to `package.json` only.  Wishing anyon else ending up here look in closing the issue.

**Comment by iTOYS** [comment] 2018-03-13 14:01
Hi guys, sorry for delay!
Could you please provide some additional info how do you use codepush:
1. How did you install plugin?
2. What codepush options do you use?
3. You run sync manually or just wrap root component?
Would be great if you can create a simple app that I could repeat the error

**Closed** 2018-03-14 21:11 UTC
Labels: android, bug, iOS

**Comment by GonzaloRecioG** [comment] 2018-05-04 12:31
@temitope wow thanks! same problem happened to us but we didn't realise that was the issue until we read your comment 🤦‍♂️ , thanks!!

**Comment by edritech93** [comment] 2020-03-09 03:04
any update ?
