### ISSUE TITLE
MapView.Marker Image resizes 3x bigger after CodePush

### ISSUE THREAD

**Issue by GonzaloRecioG** [Microsoft/react-native-code-push#1276] opened 2018-05-10 12:23 UTC
### Steps to Reproduce
1. Have a `<MapView.marker />` (react-native-maps) and pass an image as a prop:
`image={require("ourproject/src/images/1.png")}`

### Expected Behavior

Images should maintain same size with and without Codepush update.

### Actual Behavior

After Codepush update the MapView images get resized like 3-4x times bigger.

_See screenshots comparison:_
**Fresh release without CodePush: 👇**

![simulator screen shot - iphone x - 2018-05-10 at 14 19 02](https://user-images.githubusercontent.com/15191394/39869299-4782400a-545d-11e8-91a9-2fd5867cd176.png)

**CodePush update: 👇**

![img_5012](https://user-images.githubusercontent.com/15191394/39869316-577441c0-545d-11e8-8b32-a714a1ebb760.PNG)

### Environment

* react-native-code-push version: 5.3.2
* react-native version: 0.55 (tested also on 0.50.4)
* iOS/Android/Windows version: Tested on different iOS and Android, same problem.
* Does this reproduce on a debug build or release build? 
Happens on Staging + Production
* Does this reproduce on a simulator, or only on a physical device?
Both

Thanks! Would be awesome to know how to fix this.

**Comment by alexandergoncharov** [comment] 2018-05-10 15:36
Hi @GonzaloRecioG 

Thanks for reporting!
Could you please provide some test project with reproducing issue with repo steps?  This would really help to understand the reason of the issue and find approach for fixing it.

Thanks,
Alexander

**Comment by GonzaloRecioG** [comment] 2018-05-11 07:37
Hi @alexandergoncharov ! thanks for answering.

Unfortunately, we're not able to create a test project (configure react-native-maps + configure react-native-code-push with new keys etc) since it will take several hours and we don't that time right now.

The issue is related **only** with the prop `image` of the `<MapView.Marker/>`, since other local images on the project are not resizing. 

Until is fixed, is there any way to 'ignore' assets or certain code to not be updated via code-push?  Because we can't use code-push since it makes **Maps** unusable and we really want to use it.

Thanks again @alexandergoncharov and team!

**Comment by GonzaloRecioG** [comment] 2018-05-11 12:55
If it helps: we found that if we pass an `<Image/>` as a children of the Marker, code-push update doesn't change the size afterwards. The only problem is when using `image` prop on the marker.

Unfortunately we can not use this since **react-native-maps** has a [known bug](https://github.com/react-community/react-native-maps/issues/1870) that on Android if you pass an `<Image/>` as a children of the Marker, it doesn't render it, it only works with the `image` prop.

So we can only use the image prop for rendering marker custom images. Thanks!

**Comment by KasparasGud** [comment] 2018-05-12 20:02
+1.
This issue along with the react-native-maps android bug makes code-push not usable for now with projects that use react-native-maps. 
Any workarounds warmly welcomed

**Comment by poojapi** [comment] 2018-05-18 12:52
We are facing same issue.

**Comment by NickToropov** [comment] 2018-05-18 13:27
Hi guys,
I reproduced similar issue and was able to fix it by adding @2x and @3x images (as discussed in https://github.com/react-community/react-native-maps/issues/725).

directory structure after adding images:
-projectRoot
|--images
    |--img.png
    |--img@2x.png
    \--img@3x.png

For more info about react-native images please check docs: https://facebook.github.io/react-native/docs/images.html

Please, try the solution and let us know if it was helpful.

**Comment by PackZhang** [comment] 2018-05-23 12:38
react-native-code-push version: 5.2.1

**Comment by PackZhang** [comment] 2018-05-23 12:38
react-native-code-push version: 5.3.2

**Comment by PackZhang** [comment] 2018-05-23 12:39
react-native-code-push version: 5.3.2

**Comment by PackZhang** [comment] 2018-05-23 12:39
1. react-native-code-push version: 5.3.2
2

**Comment by PackZhang** [comment] 2018-05-23 12:52
I have got into the same trouble
- react-native-code-push: 5.3.2  (tested also on 5.3.3, 5.2.1)
- react-native: 0.55.4
![1111](https://user-images.githubusercontent.com/16917648/40425503-2539b33e-5ecb-11e8-8c4b-6d67a54240f4.png)

**Comment by PackZhang** [comment] 2018-05-24 02:16
Hi @NickToropov 

Thanks for reporting!

yes! I've added  @2x and @3X images.  it's not helpful.

**Comment by NickToropov** [comment] 2018-05-24 10:16
@PackZhang could you please provide us with sample app that reproduces the issue?

**Comment by NickToropov** [comment] 2018-05-29 07:06
Hi guys, @PackZhang, @GonzaloRecioG, can anyone create a sample app that reproduces this issue?

**Comment by phatlaunchdeck** [comment] 2018-05-31 23:04
I confirm myself having the exact same problem when pushing to Production. 

And yes I do have the proper @2x and @3x image files.

Any help would be very much appreciated :D

**Comment by NickToropov** [comment] 2018-06-04 09:32
Hi all! I've created a demo app -
[Issue1276.zip](https://github.com/Microsoft/react-native-code-push/files/2067585/Issue1276.zip)
Please try to play with it:
 - extract the zip and go to Issue1276 folder, 
 - run `yarn`,  
 - insert your own `YOUR_GOOGLE_MAPS_API_KEY` and `reactNativeCodePush_androidDeploymentKey` keys,
 - run `react-native run-android` or build  release apk and install it on device
 - publish changes with `code-push release-react <AppName> android` and update the app on device with `Press to sync` link.

Expected: image on map should remain its sizes

Please, let me know if the issue is reproduced on the demo or make changes in it to reproduce the issue.

**Comment by keung7251** [comment] 2018-06-12 09:52
+1

**Comment by NickToropov** [comment] 2018-06-13 10:42
Hi guys, @PackZhang, @GonzaloRecioG, could you let me know if you have a chance to look at my [comment above](https://github.com/Microsoft/react-native-code-push/issues/1276#issuecomment-394293289)

**Comment by phatlaunchdeck** [comment] 2018-06-13 10:44
> Hi all! I've created a demo app - Issue1276.zip
Please try to play with it:

extract the zip and go to Issue1276 folder,
run yarn,
insert your own YOUR_GOOGLE_MAPS_API_KEY and reactNativeCodePush_androidDeploymentKey keys,
run react-native run-android or build release apk and install it on device
publish changes with code-push release-react <AppName> android and update the app on device with Press to sync link.
Expected: image on map should retain its sizes

Please, let me know if the issue is reproduced on the demo or make changes in it to reproduce the issue.

@NickToropov Does this one work for iOS as well? Because I copied your code over my project and it still produce the same error on Production of iOS.

**Comment by NickToropov** [comment] 2018-06-13 11:19
@phatlaunchdeck, I tested on Android as @GonzaloRecioG specified that issue is reproduced on both Android and iOS. Will test it with iOS and come back a bit later.

**Comment by NickToropov** [comment] 2018-06-18 12:06
Hi guys! try to use the following workaround.:
```
class MapMarker extends Component {
  state = {
    initialRender: true
  }
  render() {
    return (
      <MapView.Marker 
        coordinate={this.props.coordinate}>
        <Image
          source={this.props.source}
          onLayout={() => this.setState({ initialRender: false })}
          key={`${this.state.initialRender}`}
        />
      </MapView.Marker>
    )
  }
}

...
<MapView>
  <PinMarker
    coordinate={{
      latitude: 37.78825,
      longitude: -122.4324
    }}
    source={require('./images/1.png')}/>
</MapView>
```
It should work for both iOS and Android.

Please let me know if it works for you.

**Comment by NickToropov** [comment] 2018-06-25 07:45
Hi all, I'll close this issue for now as there is no activity here. If anyone still faces the issue and suggested workaround doesn't solve the problem please reopen this one.

**Comment by phatlaunchdeck** [comment] 2018-06-27 06:42
Hi @NickToropov , I tried the above solution with <Image/> component you gave us. It did work on Android but only in Debug mode, not Release.

**Comment by deehuey** [comment] 2018-07-04 17:32
Hey, just did a fresh reinstall of our application, and am getting this issue as well. 

```json
    "react-native": "0.56.0-rc.3",
    "react-native-maps": "0.21.0",
    "react-native-code-push": "5.3.5",
```

This is definitely a new bug as it did not happen before our rebuild. I have confirmed i have @2x and @3x respective resolutions of the marker images.

**Comment by deehuey** [comment] 2018-07-04 18:46
Okay, so in this thread I see a few people report they have issues with Android-production-only Image marker fix not working.

Now first lemme say I don't like this solution, and hope that this isn't the accepted fix, but a solution that works for me:

In the production build, Android doesn't seem to know that the files are being referenced as source for the marker images when inside a marker component.

```javascript
        <Image source={require('./icons/emptypin.png')} style={{ width: 0, height: 0 }} />
        <Image source={require('./icons/greenpin.png')} style={{ width: 0, height: 0 }} />
        <Image source={require('./icons/youarehere.png')} style={{ width: 0, height: 0 }} />
```

Putting every marker we used as a regular ol' image in the app near our map view (anywhere really) gets the job done on Production Android build. 

Then on my marker components I was able to reference them as usual:

```javascript

      <Marker onPress={this.handlePress} coordinate={coordinate}>
        <ImageBackground style={{ width: 30, height: 30 }} source={icons[active ? 'active' : 'inactive']}>
          <Text style={styles.text} white={!active}>{children}</Text>
        </ImageBackground>
      </Marker>
```

Both the ImageBackground component and the Image component seemed to work 👌

**Comment by sercanov** [comment] 2018-07-09 15:58
Any development or workarounds ? 

I tried with bundling manually without assets and releasing update with --update-contents-path but that removed all images from app.

**Comment by EvianZhow** [comment] 2018-07-20 08:31
Might related to images' `resizeMode: 'center'` property. Encountered this issue and removed this style props works for me.

**Comment by yuri-kulikov** [comment] 2018-09-26 13:43
Hi @GonzaloRecioG, @sercanov, @deehuey,
I've created a simple app to reproduce the issue (_only iOS side_): [simpleMap.zip](https://github.com/Microsoft/react-native-code-push/files/2419536/simpleMap.zip)
And then I've tried to use one [workaround](https://github.com/Microsoft/react-native-code-push/issues/1222#issuecomment-414118064) from another similar issue, and it works!

### My Steps to reproduce:
1. Unzip the archive
1. `cd ./simpleMap`
1. `yarn`
1. `cd ios`
1. `pod install`
1. `code-push app add simpleMap-ios ios react-native`
1. Copy the **Staging deployment key** and paste it in `/simpleMap/ios/simpleMap/Info.plist`:
   ```
   <key>CodePushDeploymentKey</key>
   <string>PUT_YOUR_DEPLOYMENT_KEY_HERE</string>
   ```
1. Open `/simpleMap/ios/simpleMap.xcworkspace` with **Xcode**
1. Go to `Edit Scheme...`, change `Build Configuration` to **Release**
1. Go to the project settings and set the **Signing team** in `simpleMap` and `simpleMapTests` targets
1. Run the project
   (_Optional_) If you have this problem:
      `Error: Cannot find module '@babel/runtime/helpers/builtin/interopRequireDefault'`
      you can fix it by this: 
      ```
      cd /simpleMap/
      yarn add @babel/runtime
      ```
1. If everything is ok you'll see map with a marker (_normal size_) on it.
1. Made a change in `App.js` 
   `<Text style={styles.welcome}>Simple Map v2</Text>`
1. `code-push release-react simpleMap-ios ios`
1. Click on the button `Press to sync`
1. Press `Install` in dialog, app will be reloaded. Marker is **huge** now! 

### Solution:
1. Go to `/simpleMap/node_modules/react-native/React/Base/RCTUtils.m`
1. Replace:
   ```image = [UIImage imageWithData:fileData];```
   (line ~715) with the following:
   ```CGFloat scale = 1.0;
   if ([[imageURL absoluteString] hasSuffix: @"@3x.png"]) {
     scale = 3.0;
   } else if ([[imageURL absoluteString] hasSuffix: @"@2x.png"]) {
     scale = 2.0;
   }
   image = [UIImage imageWithData:fileData scale: scale];```
1. Run the app again
1. Made a change in `App.js` 
   `<Text style={styles.welcome}>Simple Map v3</Text>`
1. `code-push release-react simpleMap-ios ios`
1. Click on the button `Press to sync`
1. Press `Install` in dialog, app will be reloaded. 
   **Marker is normal now!**

Can you guys try this solution and reply if it helped?

**Comment by sercanov** [comment] 2018-10-08 07:29
Hi @yuri-kulikov 

I tried the solution and it worked perfectly. Thanks. Is there any open PR or discussion on react-native side ?

P.S. I also used [patch-package](https://github.com/ds300/patch-package) to simplify the patching process

**Comment by yuri-kulikov** [comment] 2018-10-11 12:57
Hi @sercanov,
Sadly we couldn’t find any similar issues in the react-native repo, and we are also unable to reproduce this bug without codepush in order to create an issue in their repo.

**Comment by NickToropov** [comment] 2018-11-09 07:35
Hi guys! I'm going to close this issue for now as it's not related to CodePush and there is a [workaround](https://github.com/Microsoft/react-native-code-push/issues/1276#issuecomment-424720093) provided by @yuri-kulikov.

**Closed by NickToropov** 2018-11-09 07:35 UTC
Labels: bug, external

**Comment by MichielDeMey** [comment] 2019-02-15 10:55
Hey guys, a fix has been merged into master in the React Native project.
(cfr. https://github.com/facebook/react-native/issues/22383 & https://github.com/facebook/react-native/pull/23446)

You can create a patch file from the following diff: https://patch-diff.githubusercontent.com/raw/facebook/react-native/pull/23446.diff
