### ISSUE TITLE
iOS Data Protection issues

### ISSUE THREAD

**Issue by adbl** [Microsoft/react-native-code-push#1109] opened 2017-12-19 09:33 UTC
I suspect code push is not handling iOS Data Protection properly. (https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/StrategiesforImplementingYourApp/StrategiesforImplementingYourApp.html#//apple_ref/doc/uid/TP40007072-CH5-SW21). When the app goes to background, all it's data becomes locked and it cannot read/write the sandbox data until it becomes active again. All file operations need to be aware of this and handle certain read/write errors.

### Steps to Reproduce
1. Enable iOS Data Protection `NSFileProtectionComplete` 
2. Deploy code push upgrades to hundreds of devices

### Expected Behavior
That it always works.

### Actual Behavior

Me and members of my team often observe that our app restarts when becoming active even though it was running previously and there was no upgrade at the time. We have extensive logging from our app but in these cases I see only that the app went to background (some time ago) and the next entry will be as if the app just launched. I can't be too sure about this but I suspect that if code push is syncing while the app is placed in background (and data protection locks the files) something can break which causes:

- app gets restarted (same code push version as before)
- code push upgrade fails/app gets reverted to an earlier version, (rollback?)

We often see errors related to this, although these examples just shows that certain files couldn't be accessed (due to Data Protection), not that the app gets restarted/rolled back.

`"You don’t have permission to save the file “app.json” in the folder “a7b9bf7b4dbb3517f4939091ca7834b70274974c25a8b301c44131a98614207a”."` 

`"Filen ”codepush.json” kunde inte öppnas eftersom du inte har behörighet att visa den."` (we see the localized error, in english is would be something like: `"The file ”codepush.json” couldn't be opened since you don't have permission to show it."`

### Reproducible Demo

Nope.

### Environment

* react-native-code-push version: 5.1.3-beta
* react-native version: 0.50.4
* iOS/Android/Windows version: iOS 10/11
* Does this reproduce on a debug build or release build? release
* Does this reproduce on a simulator, or only on a physical device? physical device, simulator doesn't support data protection

**Comment by sergey-akhalkov** [comment] 2017-12-22 11:51
Hi @adbl, thanks for your request and sorry for the late reply. 
Could you please clarify - do I get it right that your app restarts when becoming active even if CodePush does not install any update? If so, could you please confirm/make sure if `iOS Data Protection` properly works for regular React Native app that does not use CodePush at all?

**Comment by adbl** [comment] 2017-12-22 12:31
Hi Sergey!

Yes, that’s one of the issues that I believe is related to this. I cannot
be completely sure that this is caused by code push, but I know that code
push does things with the sandbox file system so it’s my suspicion. These
issues only happen sporadically and in production so I can’t easily confirm
that it’s working without Code Push.

I’ll think about if we can make an internal release without code push but
everything else the same. If we do that and find that it’s working
properly, no random restarts, will you then look into how Data Protection
could be causing issues with code push?

**Comment by sergey-akhalkov** [comment] 2017-12-22 12:57
@adbl,
>will you then look into how Data Protection could be causing issues with code push?

Sure! We'll try to determine the root cause of the issue and fix it if possible.

>I’ll think about if we can make an internal release without code push

Thanks, that would be great, we'll wait for your response.

**Comment by sergey-akhalkov** [comment] 2017-12-27 08:50
Hi @adbl, I'm closing this for now, please feel free to reopen if you have any updates.

**Closed by sergey-akhalkov** 2017-12-27 08:50 UTC
Labels: iOS, waiting-for-clarification
