### ISSUE TITLE
Support react native v0.76 and New Architecture

### ISSUE THREAD

**Issue by eduardo-santos-tribia** [microsoft/react-native-code-push#2774] opened 2024-10-30 16:19 UTC
I know that App Center and Code Push will stop working in March 2025, but is there any plan to at least support v0.76 which comes with the New Architecture by default? If not, is there any workaround or something we can do to upgrade to v0.76 and still use this library until March 2025?

**Comment by DordeDimitrijev** [comment] 2024-10-31 14:41
Duplicate of https://github.com/microsoft/react-native-code-push/issues/2696 - we are not going to support new architecture, as a workaround you can still [opt out](https://reactnative.dev/blog/2024/10/23/the-new-architecture-is-here#opt-out) from new arch in v.076.

**Closed by DordeDimitrijev** 2024-10-31 14:41 UTC

**Comment by eduardo-santos-tribia** [comment] 2024-10-31 16:24
@DordeDimitrijev what do you think about adding this info to Readme? I'm pretty sure in a near future more people will crate an issue specifically because they want v0.76 and new architecture support.

Something like would be enough there: 

> we are not going to support new architecture, as a workaround you can still [opt out](https://reactnative.dev/blog/2024/10/23/the-new-architecture-is-here#opt-out) from new arch in v.076.

**Comment by DordeDimitrijev** [comment] 2024-11-06 14:01
We've updated the readme as you proposed, thank you for the suggestion. Here is the updated [readme](https://github.com/microsoft/react-native-code-push?tab=readme-ov-file#react-native-module-for-codepush).

**Comment by esbenvb** [comment] 2024-11-26 16:11
> I know that App Center and Code Push will stop working in March 2025, but is there any plan to at least support v0.76 which comes with the New Architecture by default? If not, is there any workaround or something we can do to upgrade to v0.76 and still use this library until March 2025?

Microsoft has provided a standalone code push server that you can install and use codepush after march 2025. So I guess it's pretty relevant to get support for NA at some point soon

**Comment by DordeDimitrijev** [comment] 2024-11-29 11:36
Hello [@esbenvb](https://github.com/esbenvb) thank you for reaching out. Standalone code-push server is released so everyone can keep using codepush services after appcenter retires, as for the RNCP plugin we don't plan to support NA. We advise customers which want to use RNCP with NA to fork the repo and implement the changes themself or opt out from NA as stated [here](https://github.com/microsoft/react-native-code-push?tab=readme-ov-file#react-native-module-for-codepush)

**Comment by martinjeret** [comment] 2025-01-29 10:19
we're interested to fund the new architecture support work at Codemagic. We were expecting to start work this week, but our partner notified us yesterday that they will not able to continue any longer. 

Can you recommend a react native shop to do the work? We're already aware of Invertase, Software Mansion and Infinite Red.
