### ISSUE TITLE
Upload progress:[=====      ] 10% 0.0s[Error]  read ECONNRESET

### ISSUE THREAD

**Issue by lfq1514** [microsoft/react-native-code-push#1685] opened 2019-09-20 09:49 UTC
When I publish an application using code-push, the error alert'[Error] read ECONNRESET‘
![err](https://user-images.githubusercontent.com/50662295/65317721-f57f0900-dbce-11e9-9552-7e87e57525ea.png)

**Comment by alexandergoncharov** [comment] 2020-02-13 08:08
Hi @lfq1514 ,
Thanks for reporting!

Looks like this is issue occured becasue we were updating CodePush server side. We are sorry for that. :disappointed:
It works correctly now.

I'm going to close this issue for now. Please feel free to reopen it if you have any questions or if you faced this issue again.

**Closed by alexandergoncharov** 2020-02-13 08:08 UTC

**Comment by amirhosein5858** [comment] 2023-04-04 08:26
i just got this error:
`Command 'codepush release-react -a walletifai-gmail.com/Walletifai-1 -d Production' failed with exception "read ECONNRESET"`

any suggestions ?

**Comment by HungDoTuan** [comment] 2023-05-10 04:07
**@amirhosein5858** maybe the cause is related to your nework connection
