### ISSUE TITLE
Updated the latest release too, is this a bug?

### ISSUE THREAD

**Issue by afilp** [Microsoft/react-native-code-push#553] opened 2016-10-05 09:36 UTC
I did the following **yesterday**:
code-push release-react myApp android --targetBinaryVersion * -d Production --mandatory

So, all installations are being updated.

**Today** I released a new Build, using an increased "versionCode" and installed this to my Android mobile phone.

The strange thing is that after some seconds **it updated due to Code Push to the yesterday's javascript code!**

Is this normal? Do I have to **also** code push after a normal release with increased "versionCode" number?

**Comment by silhouettes** [comment] 2016-10-05 18:33
Hi @afilp - this is expected behavior. For it to do what you want you can do one of two things:

 * If you never want updates from past builds to be applied to newer builds, use the `targetBinaryVersion` flag. For example, you could set it to `<= 1.0.0` or just `1.0.0`, and then just make sure the `versionName` on your older build is `1.0.0` and the `versionName` on your newer build is something like `1.0.1`
 * If you want to sometimes share CodePush updates between multiple builds, but your issue is that the build that you released is *newer* than what was already on CodePush, then what you should do is push a CodePush release of the contents of your newer build before you publish it to the store. Then, when your newer build checks for an update, it will see that the hash of the update is the same as what it already has, and not apply it. We recommend doing this regardless of anything else, because by uploading the version that is shipped with your binary, the server has something to diff against when you push your next update.

This should be mentioned in the documentation somewhere, but it may not be clear - if you can think of any way to make this more clear to new users, please let me know! Going to close this for now but please let me know if this helped.

**Closed by silhouettes** 2016-10-05 18:33 UTC

**Comment by afilp** [comment] 2016-10-10 10:13
Thanks. And what about iOS releases where the **targetBInaryVersion** option is not available?

I am using this for iOS:
code-push release-react Exclusivi-iOS ios -d Production --mandatory

Will the JS part of a NEW build be downgraded to what the CodePush server has? (this would be a "bug" IMHO) OR this is automatically smart and works with a "<=" logic bedinf the scenes?

**Comment by silhouettes** [comment] 2016-10-10 17:45
Hi @afilp - on iOS the `targetBinaryVersion` option is also available, and refers to the `CFBundleShortVersionString` in your `Info.plist`. Due to potential issues with clocks being mismatched, CodePush doesn't attempt to compare the timestamp of a binary with an update to see if it was published 'before' or 'after', and only relies on what you explicitly specify using binary versions. Does that help?

**Comment by afilp** [comment] 2016-11-11 11:41
@silhouettes Thanks!

I think that the following code **does not work as an AND** and causes the latest released app to be updated by an older code-push release:

--targetBinaryVersion ">=1.2.0 <1.5.3"

Note: "1.5.3" is the latest release which does not need any code push, HOWEVER the above line seems to work as an OR?

Can you please show us the correct syntax?

Thanks!

**Comment by silhouettes** [comment] 2016-11-14 21:21
Hi @afilp - that's strange, we have never seen this problem. Do you mind emailing us at codepush@microsoft.com with your deploymentKey, and we will attempt to verify this issue?
