### ISSUE TITLE
disallowRestart not working

### ISSUE THREAD

**Issue by claykohut** [microsoft/react-native-code-push#788] opened 2017-04-10 16:07 UTC
Disallow restart doesn't seem to be working for me.

I have installMode set to ON_NEXT_RESUME and am setting disallowRestart in a componentDidMount. The app is logging the disallow restart but still restarts on resume after disallowRestart is called.

Can anyone please help?

### Additional Information

* react-native-code-push version: 1.17.2-beta (same issue with 2.0.1-beta)
* react-native version: 0.39.0
* iOS version: 10.3
* Does this reproduce on a debug build or release build? Both
* Does this reproduce on a simulator, or only on a physical device? Both

**Comment by sergey-akhalkov** [comment] 2017-04-11 08:50
Hi @claykohut, I've investigated the issue, seems like there is a mismatch between the documentation and implementation. [Documentation says](https://microsoft.github.io/code-push/docs/react-native.html#codepushdisallowrestart) that `disallowRestart` works with `InstallMode.ON_NEXT_RESUME`, but from the source code I can see the following:
1. `disallowRestart` method [affects ](https://github.com/Microsoft/react-native-code-push/blob/392189fad09bd2d243f93c2a3894aa30b06cee4a/RestartManager.js#L25) `RestartManager.restartApp` method
2. `RestartManager.restartApp` is [used by install method](https://github.com/Microsoft/react-native-code-push/blob/392189fad09bd2d243f93c2a3894aa30b06cee4a/package-mixins.js#L48) only in case `InstallMode.IMMEDIATE` is in use
3. App restarts programmatically via native side both for [Android](https://github.com/Microsoft/react-native-code-push/blob/392189fad09bd2d243f93c2a3894aa30b06cee4a/package-mixins.js#L48) and [iOS](https://github.com/Microsoft/react-native-code-push/blob/392189fad09bd2d243f93c2a3894aa30b06cee4a/ios/CodePush/CodePush.m#L561) due to `_allowed` flag does not used by native side. 

As result `disallowRestart` feature works for `InstallMode.IMMEDIATE` only. For now we are working on [Support Brownfield React Native apps](https://github.com/Microsoft/code-push/issues/423) feature, so we'll move `_allowed` flag to the native side and use it further for `ON_NEXT_RESUME`, `ON_NEXT_SUSPEND` https://github.com/Microsoft/react-native-code-push/pull/770 and `IMMEDIATE` installation modes, so the issue will be fixed.

Please let me know if you have any questions.

**Comment by joeferraro** [comment] 2017-05-24 23:52
@sergey-akhalkov any idea when this might make it into a release?

**Comment by sergey-akhalkov** [comment] 2017-05-25 14:21
Hi @joeferraro, thanks for reaching us. We've already implemented "Support for Brownfield React Native apps" feature that also includes this improvement, here you can find [my fork](https://github.com/Microsoft/react-native-code-push/compare/master...sergey-akhalkov:master). Here is you can see [native RestartManager](https://github.com/sergey-akhalkov/react-native-code-push/blob/master/android/app/src/main/java/com/microsoft/codepush/react/managers/CodePushRestartManager.java) where the issue is fixed. 
The main issue why we aren't merging this is that we need to test "Support for Brownfield React Native apps" very carefully and deeply to avoid as much issues as possible. So currently we are testing this, so we will be very grateful if you could help us to test it if possible.

**Comment by amardeepranu** [comment] 2017-10-03 15:57
Any idea when this will make it into a release? @sergey-akhalkov

**Comment by ruslan-bikkinin** [comment] 2017-10-03 16:26
@amardeepranu thanks for the interest, we are planning to release a new version including fix for that during this month.

**Comment by MrLoh** [comment] 2017-11-04 15:24
Has this been release yey, and does it also apply to ON_NEXT_SUSPEND, the docs only mention ON_NEXT_RESUME at the moment.

**Comment by sergey-akhalkov** [comment] 2017-11-07 08:59
Hi @MrLoh, thanks for reaching us. 

>Has this been release yey

Unfortunately, no, currently we have other priorities, but we'll back to this asap.

>and does it also apply to ON_NEXT_SUSPEND, the docs only mention ON_NEXT_RESUME at the moment.

after releasing "support for brownfield apps" feature it will support both `ON_NEXT_RESUME` and `ON_NEXT_SUSPEND`

**Comment by kevinresol** [comment] 2018-10-25 10:14
Any updates? This has been idle for almost an year.

**Comment by canyara** [comment] 2019-01-18 09:36
not fix yet

**Comment by ashokadichill** [comment] 2019-04-03 07:10
Please have a Look at this 
https://github.com/Microsoft/react-native-code-push/issues/1550

**Comment by achou11** [comment] 2019-11-04 18:18
I think I'm noticing this issue for my app as well. Commented on https://github.com/microsoft/react-native-code-push/issues/1667#issuecomment-549440553 with the context but I'll repeat it here:

This is happening on React Native 0.61.3 with installMode set to `ON_NEXT_RESUME` on Android. 

1. CodePush installs an update on app start.
2. Opens an in-app-browser for auth. `disallowRestart` is called and the `Disallowing restarts` log is present.
3. After entering credentials successfully, redirects to the app but CodePush causes a restart even though `allowRestart` hasn't been called.

**Comment by andreidubov** [comment] 2020-07-10 10:40
Hi @achou11 @claykohut @kevinresol 
Sorry for the delay.

We have prepared a PR (#1894) to solve this problem, if you have the time and desire, you can take a look at [it](https://github.com/microsoft/react-native-code-push/pull/1894).

**Comment by andreidubov** [comment] 2020-07-17 07:16
Hi @achou11 @claykohut @kevinresol

We made a new release with this feature, thanks for your participation.

**Closed by andreidubov** 2020-07-17 07:16 UTC
Labels: bug, investigating, prioritized
