### ISSUE TITLE
undefined is not an object (evaluating '_reactNativeCodePush2.default.CheckFrequency') 

### ISSUE THREAD

**Issue by WhynoChinese** [Microsoft/react-native-code-push#754] opened 2017-03-14 08:18 UTC
I have a problem that 'defined is not an object (evaluating '_reactNativeCodePush2.default.CheckFrequency') '.
What should I do for this?

![image](https://cloud.githubusercontent.com/assets/11802308/23891539/e56d7e0c-08d1-11e7-9f12-0b144e751359.png)

**Comment by max-mironov** [comment] 2017-03-14 09:00
Hello @WhynoChinese, thank you for reaching us the issue. Can you please answer several questions below to help us to determine the problem:
1) Can you try to reproduce this with our [sample app](https://github.com/Microsoft/react-native-code-push/tree/master/Examples/CodePushDemoApp.)? If you can't reproduce the bug on it, provide us as much info as possible about your project (it would be best if you could share with us minimal of your app code where we can reproduce the issue this way)
2) What are react-native/react-native-code-push versions you are using?
3) Can you verify that your native part of the plugin is linked correctly? Do you use react-native link for this?
4) Is it possible that you have the same problem as it was described here https://github.com/Microsoft/react-native-code-push/issues/505

**Comment by sergey-akhalkov** [comment] 2017-03-14 10:01
Hello @WhynoChinese, please also look at the same issue here: https://github.com/Microsoft/react-native-code-push/issues/457, it also may help you to figure out what goes wrong.

**Comment by max-mironov** [comment] 2017-03-21 05:13
@WhynoChinese, do you have a chance to look at this?

**Comment by WhynoChinese** [comment] 2017-03-22 02:40
@max-mironov  This time I was so busy that I did not notice your reply to this I was sorry.Now my team has solved it, I have reworked it and it works.

**Comment by max-mironov** [comment] 2017-03-22 05:10
@WhynoChinese thank you for your reply! If you don't mind I'm closing the issue now if you have resolved it, please feel free to reopen or create a new one of needed.

**Closed by max-mironov** 2017-03-22 05:10 UTC
Labels: waiting-for-clarification

**Comment by qilin55** [comment] 2017-08-21 01:45
@WhynoChinese 这个问题怎么解决的可以告诉我一下吗？遇到同样的问题，多谢

**Comment by AyubaMakoa** [comment] 2018-12-17 03:35
> @max-mironov This time I was so busy that I did not notice your reply to this I was sorry.Now my team has solved it, I have reworked it and it works.

please can you help explain how you fixed it?

**Comment by ramiasg** [comment] 2019-12-29 20:06
same issue
