### ISSUE TITLE
image disappear when use code push

### ISSUE THREAD

**Issue by MrZhaoCn** [microsoft/react-native-code-push#1853] opened 2020-05-07 09:00 UTC
when use  code push ,the code is updated,but all image disappear,it just appear once,not open.
I cannot recurrent this issue,and now i do not dare to use code push,it very danger。

step:
1. release a package v1
2. release a package just change code not change image v2
3. rollback to v1
after rollback to v1, some user image disappear,and we monitor error:

"uri:"/data/user/0/com.shopdiary/files/CodePush/abbb6f9cc77012f3e131d7dfe69305e6aee96ea0d102b32a241d0dccdf30d553/CodePush/drawable-xxhdpi/src_resource_img_msg_center.png: open failed: ENOENT (No such file or directory)"

react-native-code-push version: 0.54.2
react-native version: 0.59.9
Android 9 Android 10
release build，physical device

who can help me ????

**Comment by alexandergoncharov** [comment] 2020-06-05 08:16
Hi @vinoth-am and @MrZhaoCn ,
Thanks for reporting!

Unfortunately, I can't reproduce the issue. Could you please provide some demo project with reproducing issue and reprosteps? I would like to reproduce issue and investigate it?

**Comment by andreidubov** [comment] 2020-06-10 08:32
Since there is no answer and we cannot reproduce it I’m going to close this issue for now. Please feel free to reopen it if you have any questions or issues.

**Closed by andreidubov** 2020-06-10 08:32 UTC
Labels: bug, waiting-for-clarification
