### ISSUE TITLE
[ios] include of non-modular header inside framework module 'CodePush.CodePush'

### ISSUE THREAD

**Issue by igrayson** [Microsoft/react-native-code-push#645] opened 2016-12-16 21:30 UTC
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

* react-native-code-push version: 0.15.0-beta (and all later versions)
* react-native version: 0.38
* iOS/Android/Windows version: iphonesimulator10.2
* Does this reproduce on a debug build or release build? yes, both
* Does this reproduce on a simulator, or only on a physical device? just tried simulator
* Repro steps and/or stack trace:

1) Build a project with the cocoapods configuration below (or any cocoapods configuration?)

Notes:

- This does _not_ fail on `0.14.6-beta`. Only `0.15.x` and higher fail.
- This [stackoverflow workaround](http://stackoverflow.com/a/32080491) did not work for us.

Build failure:

```
▸ Compiling ReactViewController.m

❌  /Users/ian/myworkspace/build/development/_intermediates/ios/Build/Products/development-iphonesimulator/CodePush/CodePush.framework/Headers/CodePush.h:1:9: include of non-modular header inside framework module 'CodePush.CodePush' [-Werror,-Wnon-modular-include-in-framework-module]

#import "RCTEventEmitter.h"
        ^

❌  /Users/ian/myworkspace/ios/Driver/ViewControllers/ReactViewController.m:3:9: could not build module 'CodePush'

#import <CodePush/CodePush.h>
 ~~~~~~~^
** BUILD FAILED **
```

Podfile:

```
platform :ios, '8.0'

use_frameworks!
inhibit_all_warnings!

project 'Driver.xcodeproj', {
  'development' => :debug,
  'demo'        => :release,
  'production'  => :release,
}

target 'Driver' do
  pod 'DDVersion'
  pod 'SentrySwift'
  pod 'IntentKit', git: 'https://github.com/convoyinc/IntentKit', commit: 'af32c96', subspecs: [
    'Core',
    'Maps',
  ]
  pod 'CodePush', path: '../node_modules/react-native-code-push'
  pod 'RNBackgroundGeolocation', path: '../node_modules/react-native-background-geolocation'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'ReactNativePermissions', path: '../node_modules/react-native-permissions'
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  pod 'react-native-mixpanel', path: '../node_modules/react-native-mixpanel'
  pod 'react-native-orientation', path: '../node_modules/react-native-orientation'
  pod 'react-native-camera', path: '../node_modules/react-native-camera'
  pod 'react-native-image-picker', path: '../node_modules/react-native-image-picker'
  pod 'react-native-audioplayer', path: '../node_modules/react-native-audioplayer'
  pod 'react-native-sqlite-storage', path: '../node_modules/react-native-sqlite-storage'
  pod 'react-native-cookies', path: '../node_modules/react-native-cookies'
  pod 'RNFS', path: '../node_modules/react-native-fs'

  pod 'React', path: '../node_modules/react-native', subspecs: [
    'ART',
    'Core',
    'RCTAnimation',
    'RCTActionSheet',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
end
```

xcodebuild -version
```
Xcode 8.2
Build version 8C38
```

xcodebuild -showsdks
```
iOS SDKs:
	iOS 10.2                      	-sdk iphoneos10.2

iOS Simulator SDKs:
	Simulator - iOS 10.2          	-sdk iphonesimulator10.2
...
```

**Comment by vladimir-kotikov** [comment] 2016-12-19 11:24
@igrayson, have you tried to upgrade to [react-native-code-push@1.16.1-beta](https://github.com/Microsoft/react-native-code-push/releases/tag/v1.16.1-beta)? Your problem sounds very similar to https://github.com/Microsoft/react-native-code-push/issues/583, which has been fixed in that release.

**Comment by igrayson** [comment] 2016-12-19 16:40
Yes, 1.16.1-beta was where I first saw this. I rolled back until I hit
1.14.6

**Comment by igrayson** [comment] 2016-12-19 16:50
Manually fudging the top of `CodePush.h`, and leaving it as 

```objc
#import "React/RCTEventEmitter.h"   // Required when used as a Pod in a Swift project
```

makes my problem go away.

**Comment by sergey-akhalkov** [comment] 2016-12-26 11:12
Hello @igrayson. I've tried to reproduce provided issue with following repro steps:
1. Create new react-native `myapp` using `react-native@0.38.0` and `react-native-code-push@1.15.0-beta` packages, then install several node packages from provided podfile.
2. Execute `pod init` command and replace created `Podfile` content with provided, then execute `pod install` command.
3. Open `myapp` project using `myapp.xcworkspace` file, then successfully lunch application on simulator.
4. Replace `react-native-code-push@1.15.0-beta` with `react-native-code-push@1.16.1-beta`
5. Update pod dependencies and make sure that `Pods` using new version of `react-native-code-push` package.
5. Successfully repeat step 3.
So, I haven't faced any issues with building and running the app using provided pod file, so please let me know if you have any ideas (xcode configuration, project setting and etc.)

**Comment by panarasi** [comment] 2017-01-26 18:49
@igrayson Pinging you to see if this issue was resolved. Closing this issue for now, but please re-open it if this is still an issue.

**Comment by Igor1201** [comment] 2017-03-21 16:49
I've recently found that this error start to happen when you have `use_frameworks!` declared on the Podfile

```diff
 NODE_MODULES = '../node_modules' 

 target 'MyApp' do
   pod 'Yoga', :path => "#{NODE_MODULES}/react-native/ReactCommon/yoga"
   pod 'React', :path => "#{NODE_MODULES}/react-native", :subspecs => [
         'Core',
         'RCTText',
         'RCTImage',
         'RCTActionSheet',
         'RCTAnimation',
         'RCTNetwork',
         'RCTWebSocket', # remove from here in the production binary
         'RCTLinkingIOS'
       ]

+  use_frameworks!
   pod 'CodePush', :path => "#{NODE_MODULES}/react-native-code-push"  

   target 'MyAppUI' do
     inherit! :search_paths
   end

   target 'MyAppUITests' do
     inherit! :search_paths

     use_frameworks!
     pod 'KIF', '~> 3.0', :configurations => ['Debug']
   end
 end
```

Without this line, the app builds normally.

**Comment by panarasi** [comment] 2017-03-21 19:18
@sergey-akhalkov Can we investigate this ?

**Comment by sergey-akhalkov** [comment] 2017-03-31 08:44
@Igor1201, I've created swift app using Xcode, then I've performed `pod install` command to install dependencies using provided by you `podfile` (including `use_frameworks!` line) and I've got no errors while building the swift app. So, could you please provide me with minimal version of your's react-native swift app where the issue reproduces? It would be very helpful, so I'll able to determine the root cause of the issue.

**Comment by Igor1201** [comment] 2017-04-05 17:26
@sergey-akhalkov I'm sorry about the late reply too.
We've tried to reproduce this issue again without luck, even in your main project (which we'd removed CodePush from it, two weeks ago).
If we find something valuable on this issue again, I'll ping you.
Thanks for you time.

**Comment by sergey-akhalkov** [comment] 2017-04-05 20:12
@Igor1201, no problem! So I'm closing this for now, please feel free to reopen.

**Closed by sergey-akhalkov** 2017-04-05 20:12 UTC
Labels: no-repro, waiting-for-clarification
