### ISSUE TITLE
[Android] App become slow when doing fresh install with up-to-date code-push

### ISSUE THREAD

**Issue by adrianha** [Microsoft/react-native-code-push#739] opened 2017-03-04 15:17 UTC
### Description

Hi, i got strange issue when doing fresh install and up-to-date code push app version, animation become slower. After i release some update to code push and then the app sync the update, it will be working normally. Animation become smooth. Any idea about this?
PS: Its running on Android with Release build.
Currently using: react-native-code-push@1.17.0-beta

**Comment by coutliuxing** [comment] 2017-03-28 04:25
@adrianha hi,Your problem solved?

**Comment by sergey-akhalkov** [comment] 2017-03-29 10:31
Hello @coutliuxing, @WhynoChinese, thank you for reaching us the issue. Could you please answer several questions below to help us to determine the problem:
1) Can you try to reproduce this with our [sample app](https://github.com/Microsoft/react-native-code-push/tree/master/Examples/CodePushDemoApp.)? If you can't reproduce the bug on it, provide us as much info as possible about your project (it would be best if you could share with us minimal of your app code where we can reproduce the issue this way)
2) What is `react-native` version you are using?

**Comment by coutliuxing** [comment] 2017-03-29 10:50
react-native-code-push:1.17.3-beta
react-native:0.42.0

MainApplication.java
![image](https://cloud.githubusercontent.com/assets/8907930/24451043/d4b9a56a-14af-11e7-8935-2f51e3f0921f.png)

build.gradle:
![image](https://cloud.githubusercontent.com/assets/8907930/24451075/f69dedd0-14af-11e7-9703-d005e86bf946.png)

commod:
![image](https://cloud.githubusercontent.com/assets/8907930/24451218/78b2c9d0-14b0-11e7-884c-49e5b29fa609.png)

Just the normal configuration, just have a problem of the interface is more complex, but I use assembleRelease generated apk installation is no problem, just updated will be out of the question

**Comment by coutliuxing** [comment] 2017-03-29 11:07
Performance is a imageView, respectively in onPressIn and onPressOut change image, switching between will be delayed

**Comment by sergey-akhalkov** [comment] 2017-03-29 11:09
@coutliuxing, yeah, I could see that you've successfully released CodePush update and that your app is properly configured, except the `buildToolsVersion: "25.0.0"`, we and React Native are officially supporting  `buildToolsVersion: "23.0.1"`. 
Could you please describe me what actually goes wrong (actual behavior)  and what you are expecting instead (expected behavior). Could you please also share me with your client side code (js files), it would be very helpful for me due to I'll figure out which way you are using animations.

**Comment by sergey-akhalkov** [comment] 2017-03-29 11:56
@adrianha, @coutliuxing, could you please also confirm if the issue reproduces only in Release build?

**Comment by coutliuxing** [comment] 2017-03-29 14:07
I didn't quite understand you the meaning of this passage, what do you mean I have set up like this before?

`new CodePush(BuildConfig.CODEPUSH_KEY, MainApplication.this, BuildConfig.DEBUG)`

**Comment by sergey-akhalkov** [comment] 2017-03-29 14:16
@corymsmith, could you please share your `index.android.js/index.ios.js` file contents? I just want to clarify how you are using `ImageView` and `onPressIn/onPressOut` events. Could you please also confirm if the the issue reproduces in Debug build on emulator too?

**Comment by coutliuxing** [comment] 2017-03-29 14:27
![36e7a3f0-b751-4d8a-be01-76799d7c3c3c](https://cloud.githubusercontent.com/assets/8907930/24459713/c52dbb44-14ce-11e7-949d-911fe9b1dd5a.png)
![9ea73f5e-b3fd-4425-8fe7-163fd42d627f](https://cloud.githubusercontent.com/assets/8907930/24459744/d86d0bc4-14ce-11e7-9383-2f6796bc9335.png)

**Comment by coutliuxing** [comment] 2017-03-29 14:30
@sergey-akhalkov No attempt at debug mode.In the simulator also has this problem

**Comment by adrianha** [comment] 2017-03-29 15:25
Yes, its occured when i run on `release` mode on real device @sergey-akhalkov .
When i run on `releaseStaging` mode, everything is alright even after fresh install.

I'm using react-native@0.41.2 and react-native-code-push@1.17.2-beta

**Comment by coutliuxing** [comment] 2017-03-29 15:34
@adrianha `releaseStaging` mode？？Can you share how this mode works?

**Comment by sergey-akhalkov** [comment] 2017-03-29 15:35
@adrianha, do you experiencing the same issue as in https://github.com/Microsoft/react-native-code-push/issues/739#issuecomment-290057696?
If I get it right you've got following repro steps: 
1. Your app uses binary version, so animation is smooth.
2. You've released an CodePush update
3. Your app downloads and installs the CodePush update
4. After app restarts animations becomes slower

Could you please also provide me with `index.android.js/index.ios.js` file contents just to make it clear for me what kind of animation you are using?

**Comment by adrianha** [comment] 2017-03-29 15:43
@sergey-akhalkov i think mine is different.
My app become slower when using binary version. It will be back to normal state after restart and applying the update from code push.
So, its the step:
1. Fresh install => using binary version (Animation is slow)
2. Got an update from code-push and downloading the updates in the background
3. Restart app to apply the update from code-push (Animation became normal)

Here's my index.js:
![screen shot 2017-03-29 at 10 41 08 pm](https://cloud.githubusercontent.com/assets/5382429/24463387/d762dc70-14d0-11e7-9d2a-9f09b9e450ab.png)

To make it clear: What i describe as animation is when i was trying to show modal from @expo/ex-navigation

**Comment by coutliuxing** [comment] 2017-03-30 02:42
@sergey-akhalkov One can reproduce the problem example
[patchTest.zip](https://github.com/Microsoft/react-native-code-push/files/880896/patchTest.zip)

**Comment by sergey-akhalkov** [comment] 2017-03-30 07:38
@adrianha,
>My app become slower when using binary version. It will be back to normal state after restart and applying the update from code push.
>When i run on releaseStaging mode, everything is alright even after fresh install.

It is really weird, have you tried to test `Fresh install` without CodePush module (remove it from js and java files), does the issue reproduce in this case? Is it possible that the root cause of the issue could be in your `release` build type configuration? Please try to use remove `minifyEnabled` and `proguardFiles` options from `release` build type and verify if the issue is reproduces. Please let me know if any updates.

**Comment by sergey-akhalkov** [comment] 2017-03-31 07:36
@coutliuxing, thanks for the example app. I was able to reproduce the issue and I could see, that animation becomes a little bit slower after installing CodePush update than before, but I could not see huge impact.
I've found here http://stackoverflow.com/a/9563467 that `internal storage` (including `assets` directory) mush slower to access a file inside it, than `res` folder. CodePush SDK uses `internal storage` to store update contents inside it, so this is a most likely reason why you've got animation performance impact. I don't sure if there is exists easy way to avoid the issue, I'll let you know if I find it, please also let me know if you have any ideas.

**Comment by coutliuxing** [comment] 2017-04-05 08:18
Okay , thank you very much ~

**Comment by sergey-akhalkov** [comment] 2017-04-05 21:19
@adrianha, just a friendly ping.

**Comment by adrianha** [comment] 2017-04-06 08:39
hi @sergey-akhalkov ,
i'll investigate this weekend. sorry for incovenience.

**Comment by sergey-akhalkov** [comment] 2017-04-06 08:44
@adrianha, no problem, I'm closing this for now, please feel free to reopen in case of any updates!

**Closed by sergey-akhalkov** 2017-04-06 08:44 UTC
Labels: investigating

**Comment by adrianha** [comment] 2017-04-06 09:39
Thanks @sergey-akhalkov !
