### ISSUE TITLE
There are some question with config step

### ISSUE THREAD

**Issue by xhacker5000** [Microsoft/react-native-code-push#200] opened 2016-02-17 11:10 UTC
# something I already do and worked
1.using code-push-cli register account and add app
2.copy the app Staging key to info.plist
3.link codepush libs
4.add ``#import "codepush.h" ``
5.Project build succeeded

# something I have question 
1.should I commit my project code to code-push server ?  and how to do that?
is that using this command ?
``sh 
code-push release <appName> <updateContents> <targetBinaryVersion>
[--deploymentName <deploymentName>]
[--description <description>]
[--mandatory]
``
I think if have a exist project example will be better to understand how to perform the command

2.should I need to add some code to the ``index.ios.js ``like this
```javascript
import codePush from "react-native-code-push";
codePush.sync( //need any arg? );
```
and the app will get the code from Microsoft code-push server ?
is need any arg in ``.sync``?

thanks for any reply

**Comment by xhacker5000** [comment] 2016-02-17 11:28
code-push 1.6.0beta without command ``code-push release-react`` ?

**Comment by dtivel** [comment] 2016-02-17 16:08
Hi, xhacker5000.

1.  Yes, to make an update available to your app, you would upload your update (build output) to the CodePush service.  The CodePush CLI's `release` command does exactly this.  Here is some additional documentation on how to release an update:  http://microsoft.github.io/code-push/docs/react-native.html#link-6

2.  Yes, you can put the `sync()` call wherever you like, but often it is put in app startup (e.g.:  in componentDidMount()).  `sync()` does accept some optional arguments, but the API was intended to address the most common scenarios without any additional arguments.  The optional arguments allow you to customize `sync()`'s behavior.  For example, if you prefer app updates to be applied immediately after download instead of on the next app restart (which is the default), then you can pass options to `sync()`, like so:

        codePush.sync({ updateDialog: true, installMode: codePush.InstallMode.IMMEDIATE });

    The API documentation for `sync()` has more details.  See https://github.com/Microsoft/react-native-code-push#codepushsync for a full description of the API.

    When an app calls `sync()`, it results in a query to the CodePush service.  If an update is available, it will be downloaded to the device and applied (by default) on app restart, unless you've customized the behavior of `sync()` to apply the update at some other time.

3.  The code-push 1.6.0-beta release does not have the `release-react` command.  The `release-react` feature was committed yesterday and will be in the next code-push release, which I anticipate to be soon.  To be clear, the `release-react` command is not required for you to release your update now; you can still use the `release` command to release your update.  The `release-react` command just simplifies the React Native release scenario by making it a little less error prone.  If you are eager to try out the `release-react` command now, you could sync to tip the CodePush repo, and build and run it locally.

**Comment by xhacker5000** [comment] 2016-02-18 05:22
# my version info is this
```
┌───────┬───────────────────┬─────────────┬───────────┬───────────────────────────────┬──────────────────────┐
│ Label │ Release Time      │ App Version │ Mandatory │ Description                   │ Install Metrics      │
├───────┼───────────────────┼─────────────┼───────────┼───────────────────────────────┼──────────────────────┤
│ v1    │ an hour ago       │ 1.0.0       │ No        │                               │ No installs recorded │
├───────┼───────────────────┼─────────────┼───────────┼───────────────────────────────┼──────────────────────┤
│ v2    │ an hour ago       │ 1.0.1       │ No        │                               │ No installs recorded │
├───────┼───────────────────┼─────────────┼───────────┼───────────────────────────────┼──────────────────────┤
│ v3    │ a few seconds ago │ 1.0.1       │ Yes       │ add version show in homescene │ No installs recorded │
└───────┴───────────────────┴─────────────┴───────────┴───────────────────────────────┴──────────────────────┘
```
I call ``codePush.sync()`` on ``componentWillMount()``

log is:
```
2016-02-18 13:20:11.126 [trace][tid:com.facebook.React.JavaScript] [CodePush] Checking for update.
2016-02-18 13:20:12.794 [trace][tid:com.facebook.React.JavaScript] [CodePush] An unknown error occurred.
2016-02-18 13:20:12.795 [trace][tid:com.facebook.React.JavaScript] [CodePush] 404: The specified resource does not exist.

```

why...

**Comment by xhacker5000** [comment] 2016-02-18 05:22
shoud I call some other API to install the latest version ?

**Comment by lostintangent** [comment] 2016-02-18 05:33
Getting a 404 when calling sync typically indicates that the deployment key you're using doesn't exist. Could you check the "CodePushDeploymentKey" setting in your Info.plist file and compare it with the key of deployment you displayed the history above for (run "code-push deployment ls APP_NAME -k" to see it)

**Comment by xhacker5000** [comment] 2016-02-18 05:34
Yes I put the deployment key which value of name "Staging" into this , should I change it to Production's

this is my deployment info 
```
┌────────────┬────────────────────────────────────────────┬──────────────────────┐
│ Name       │ Update Metadata                            │ Install Metrics      │
├────────────┼────────────────────────────────────────────┼──────────────────────┤
│ Production │ No updates released                        │ No installs recorded │
├────────────┼────────────────────────────────────────────┼──────────────────────┤
│ Staging    │ Label: v3                                  │ No installs recorded │
│            │ App Version: 1.0.1                         │                      │
│            │ Mandatory: Yes                             │                      │
│            │ Release Time: 14 minutes ago               │                      │
│            │ Released By: 17599228@qq.com               │                      │
│            │ Description: add version show in homescene │                      │
└────────────┴────────────────────────────────────────────┴──────────────────────┘
```

**Comment by lostintangent** [comment] 2016-02-18 05:38
Are you sure you didn't put the value "Staging" in your Info.plist? You need to specify the key not the name. If you run "code-push deployment ls APP_NAME -k" (note the "-k" flag) you will see this value.

**Comment by xhacker5000** [comment] 2016-02-18 05:38
Yes , it's my mistake , I copy error key into it , sorry .
and this is the correct log:
``
2016-02-18 13:37:43.180 [trace][tid:com.facebook.React.JavaScript] [CodePush] Checking for update.
2016-02-18 13:37:45.524 [trace][tid:com.facebook.React.JavaScript] [CodePush] App is up to date.
2016-02-18 13:38:24.196 [trace][tid:com.facebook.React.JavaScript] { name: 'launch' }
``

**Comment by xhacker5000** [comment] 2016-02-18 05:41
When I restart the App ,that's is the newest version , it's cool 

But I wanna restart app when download finish , should I write some code for that ?
maybe : ``codePush.InstallMode.IMMEDIATE``

**Comment by lostintangent** [comment] 2016-02-18 05:42
Yep, if you want to immediately install the update after downloading it, that is the install mode to specify to the call to sync.

BTW, make sure to pass the EXACT binary version you are targeting when you call the CodePush release command. If your Info.plist is configured as 1.0.0, then you need to pass 1.0.0 to the release command, not 1.0.1.

**Comment by xhacker5000** [comment] 2016-02-18 05:46
``codePush.sync()``
I want call this when object-c level which function is 
``
- (void)applicationDidBecomeActive:(UIApplication *)application
``

Is there any object-c API in there ?

thanks for you reply timely

**Comment by lostintangent** [comment] 2016-02-18 05:50
We don't currently have an Obj-C API equivalent of the sync method. Much of it is written in JS so that we can share he code between iOS and Android.

If you want to also call sync when the app is resumed (as opposed to just started for the first time), you could use the AppState API to do that: https://facebook.github.io/react-native/docs/appstate.html#content.

Would that work?

**Comment by lostintangent** [comment] 2016-02-18 15:44
I'm going to close this since it seems like your issue was addressed :) If you'd like to request we make an Obj-C API equivalent for sync, let's open a seperate issue for that. Otherwise, let us know any other questions you may have. Thanks!

**Closed by lostintangent** 2016-02-18 15:44 UTC

**Comment by xhacker5000** [comment] 2016-02-19 09:56
Thank you for your nice work , I am really enjoy code-push to bring my convenience
