### ISSUE TITLE
No updates firing to release or staging 

### ISSUE THREAD

**Issue by mrkhan2** [Microsoft/react-native-code-push#575] opened 2016-10-20 19:09 UTC
- react-native-code-push version: 1.15.0-beta
- react-native version: 0.34
- iOS version
- Happens on Staging and Release builds
- No updates are happening in simulator or on Test Flight builds

I am new to Code push and am having troubles getting this set up. 

In my index.ios.js file, I have the following:

```
import { AppRegistry } from 'react-native';
import React from 'react';
import { Provider } from 'react-redux';
import store from './redux/store';
import codePush from "react-native-code-push";

import CoincastRouter from './Coincast';

class Coincast extends React.Component{

  componentWillMount() {
    codePush.sync({ updateDialog: true, installMode: codePush.InstallMode.IMMEDIATE });

  }
  render(){
    return(
      <Provider store={store}>
        <CoincastRouter />
      </Provider>
    )
  }
}


AppRegistry.registerComponent('Coincast', () => Coincast);
```

When I run code-push debug iOS, I always get the same event firing, which says:

> "Loading JS bundle from file:///Users......"

 and then a long string going to a hidden folder on my computer.

It never moves past that message on the debug logs. Even when I hard reset it, the same message reappears.

**Comment by silhouettes** [comment] 2016-10-25 18:58
Hi @mrkhan2, I'm assuming you ran `react-native link react-native-code-push`. Could you maybe run through the manual install steps and verify that everything is correct? https://github.com/Microsoft/react-native-code-push#plugin-installation-ios---manual

**Comment by mrkhan2** [comment] 2016-11-07 18:34
@silhouettes thanks for the suggestion. Yes, I've already ran that link command. 

I've been going through the install steps and followed them very closely, yet same result. 

My problem is very similar to #573 but when I try to run `code-push debug ios` on debug mode, I get the following output:

> [12:22:12] Sync already in progress.
> [12:22:12] Checking for update.
> [12:22:13] An unknown error occurred.
> [12:22:13] 404: The specified resource does not exist.

**Comment by mrkhan2** [comment] 2016-11-07 20:30
I created a new react-native project from scratch (`react-native init newProj`) just to check how if the process of adding code-push  is the problem here.  Here is step by step breakdown, please let me know if this is correct @silhouettes 

1. I am logged into code-push, app registered, etc.
2. `npm install --save react-native-code-push@latest` in the project folder
3. `react-native link react-native-code-push`
4. add the staging key to my iOS project when prompted in terminal 
5.  In my index.ios.js file, I add` import codePush from "react-native-code-push";` and `MyApp = codePush(MyApp);`
6. I turn on my code-push debug ios
7. run the project in xcode

in debug mode the console shows me:

> Checking for update.
> An unknown error occurred.
> 404: The specified resource does not exist.


in release mode, I get:
[CodePush] Loading JS bundle from file:///Users/username/Library/Developer/CoreSimulator/Devices/25E29483-4724-44DE-B423-08EB491003BD/data/Containers/Bundle/Application/2C2D49B3-6187-466D-9781-BBFF3C103F6F/AppName.app/main.jsbundle

NO changes happen after I do `code-push release-react newProj ios`

Am I doing this correctly?

**Comment by silhouettes** [comment] 2016-11-14 21:25
Hi @mrkhan2, could you copy-paste the code that you used for your main component/entry file here? Alternatively, if you pushed your newly created React Native project to GitHub, perhaps we could have a look at it.

**Comment by levic92** [comment] 2016-11-18 18:08
I started having the same issue with my project. When I deployed the app to some test devices last week codepush was working fine, but in my new builds it will only download updates while in debug mode. I will do some more investigating this weekend and report my findings back here.

**Comment by levic92** [comment] 2016-11-19 02:16
Not sure exactly what fixed it, I didn't change any of the code and it's working now.
There was an issue when I tried to run the app today because my lodash node module went missing, but before reinstalling that I ran ```watchman watch-del-all```. I don't know if that had any effect on it but that is the only thing that has really changed since yesterday.

**Comment by levic92** [comment] 2016-11-19 03:57
Update (on iOS):

Somehow I got it working on my device again (didn't change any code), but then I went to install the app fresh after deleting it off my device and now it won't install updates again.

If I install the debug build to the simulator and device it downloads and installs the update fine. In the release build it works properly on the simulator, but will not work on my iPhone. I know there is a debug command, but as far as I understand that only works for the simulator, is there any debugging tools that could help me on my iPhone?

**Comment by mrkhan2** [comment] 2016-11-19 23:45
@silhouettes Here is the main component file (index.ios.js) of that newProj I created:

```
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';
import codePush from "react-native-code-push";

export default class newProj extends Component {

  componentDidMount() {
  codePush.sync();
}
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
        index.ios.js
        </Text>
        <Text style={styles.instructions}>
          Press Cmd+R to reload,{'\n'}
          Cmd+D or shake for dev menu
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('newProj', () => newProj);

```



my appdelegate.m file looks as the following:


```
#import "AppDelegate.h"
#import "CodePush.h"

#import "RCTBundleURLProvider.h"
#import "RCTRootView.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;

  
#ifdef DEBUG
  jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios&dev=true"];
#else
  jsCodeLocation = [CodePush bundleURL];
#endif
  
  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"newProj"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

@end

```

**Comment by rt2zz** [comment] 2016-12-14 03:42
@silhouettes I am seeing similar behavior. 

```
CodePushDeploymentKey ***** [its correct]
[CodePush] Sync already in progress.
[CodePush] Checking for update.
[CodePush] An unknown error occurred.
[CodePush] 400: An update check must include a valid deployment key - please check that your app has been configured correctly. To view available deployment keys, run 'code-push deployment ls <appName> -k'.
```

**Comment by sergey-akhalkov** [comment] 2016-12-26 15:44
Hi @mrkhan2. To make sure that iOS react-native app works properly in release mode you could try to enable logging like this: [http://stackoverflow.com/a/39091109](http://stackoverflow.com/a/39091109) (please let me know if you can see any errors in console while debug).
To push updates in release mode I've done following steps:

0. Change deployment key to production in `info.plist` file then build and run the app.
1. Make changes in `index.ios.js` file.
2. Release updates like this: `code-push release-react MyApp ios -d Production`
3. Relaunch the app twice: first time for download updates, second - for install.
4. Make sure there is no errors and updates installed successfully.

As for me - I haven't faced any issues both for staging and release builds, so please let me know if you have any updates or ideas.

**Comment by sergey-akhalkov** [comment] 2016-12-26 15:45
Hi @rt2zz. Could you please verify your deployment key (`CodePushDeploymentKey` prop in the `info.plist` file)? Seems like it has wrong format - probably space chars at the end of the string or smth else. Please let me know if you still see this issue.

**Comment by sergey-akhalkov** [comment] 2017-01-31 15:28
@mrkhan2, @rt2zz - is the issue still reproduces for you? Please let me know if I could help you.

**Comment by mrkhan2** [comment] 2017-01-31 17:06
Problem was solved for me, the issue was due to a bad production key

**Comment by sergey-akhalkov** [comment] 2017-01-31 17:09
@mrkhan2 - thank you for response, I close the issue for now, feel free to reopen it if needed.

**Closed by sergey-akhalkov** 2017-01-31 17:09 UTC
