### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by qq326646683** [Microsoft/react-native-code-push#1458] opened 2018-11-21 02:49 UTC
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.crash log show this error

### Expected Behavior
no crash

### Actual Behavior
crashed

### Environment

* react-native-code-push version:5.3.2
* react-native version:0.55.4
* iOS/Android/Windows version: android
* Does this reproduce on a debug build or release build? release
* Does this reproduce on a simulator, or only on a physical device? physical device

**Comment by qq326646683** [comment] 2018-11-21 02:49
Attempt to get length of null array

com.microsoft.codepush.react.FileUtils.deleteFileOrFolderSilently(FileUtils.java:75)

**Comment by yz1311** [comment] 2018-11-21 03:35
same issues.It occurs in HUAWEI P20 & Mate10

react-native-code-push version:5.3.2

**Comment by yz1311** [comment] 2018-11-21 04:30
same issues.It occurs in Huawei p20 & mate10.

[FileUtils.java:75](https://github.com/Microsoft/react-native-code-push/blob/3144c916018fab077231e88d8718ad3a1cb0a7d8/android/app/src/main/java/com/microsoft/codepush/react/FileUtils.java)
<pre>
 File[] files = file.listFiles();
            for (File fileEntry : files) {
</pre>

I find the package is downloaded to internal storage,so in theory,this issues is not related to the android Permission.
[CodePush.java:64](https://github.com/Microsoft/react-native-code-push/blob/09883dd6f1507975e93aa674905109d60f9f57bf/android/app/src/main/java/com/microsoft/codepush/react/CodePush.java)
<pre>
CodePushUpdateManager(context.getFilesDir().getAbsolutePath());
</pre>

**Comment by NickToropov** [comment] 2018-11-21 10:48
Hi @qq326646683! Thanks for reporting it. Do you have detailed repro steps or demo project that I could try to reproduce your issue and help to solve it. Also please share logs from LogCat with this exception.

**Comment by yz1311** [comment] 2018-11-25 03:07
> Hi @qq326646683! Thanks for reporting it. Do you have detailed repro steps or demo project that I could try to reproduce your issue and help to solve it. Also please share logs from LogCat with this exception.

<pre>
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:365)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:784)
Caused by: java.lang.NullPointerException: Attempt to get length of null array
	at com.microsoft.codepush.react.FileUtils.copyDirectoryContents(FileUtils.java:25)
	at com.microsoft.codepush.react.FileUtils.copyDirectoryContents(FileUtils.java:27)
	at com.microsoft.codepush.react.FileUtils.copyDirectoryContents(FileUtils.java:27)
	at com.microsoft.codepush.react.CodePushUpdateUtils.copyNecessaryFilesFromCurrentPackage(CodePushUpdateUtils.java:100)
	at com.microsoft.codepush.react.CodePushUpdateManager.downloadPackage(CodePushUpdateManager.java:227)
	at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:210)
	at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:204)
	at android.os.AsyncTask$2.call(AsyncTask.java:345)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
<pre>

**Comment by NickToropov** [comment] 2018-11-26 10:57
@yz1311 Thanks for logs! Any repro steps/demo project?

**Comment by yz1311** [comment] 2018-11-26 11:19
@NickToropov  no, can not reproduct it .
This error just occurred in Huawei p20 & p20 Pro & mate10,according to the statistics service.

**Comment by NickToropov** [comment] 2018-11-27 15:19
@yz1311 do you have possibility to try to reproduce the issue on such devices?

**Comment by AndrewJack** [comment] 2018-12-17 12:46
Seen this issue in production too. 

Same stacktrace as @yz1311 
Only on Huawei devices. 
Android OS: 8.0 & 9.0
Models: [LYA-L29](https://www.gsmarena.com/huawei_mate_20_pro-9343.php), CLT-L29, LYA-L09. COL-L29, SNE-LX2, LYA-AL00

**Comment by yuri-kulikov** [comment] 2018-12-20 11:48
Hey @AndrewJack,
Thanks for this information!

Don't worry about NickToropov, he moved to another project, and his unassignment by you is just a bug 🙂 
Can you share some details about this issue? Does this happens every time on these devices or occasionally. We just don't have any of these devices to test it.

**Comment by yuri-kulikov** [comment] 2019-01-09 08:54
Unfortunately, we haven’t heard from you in a while, so I'll close the issue for now, but, please, feel free to reopen it if you have some additional details or questions.

**Closed by yuri-kulikov** 2019-01-09 08:54 UTC
Labels: android, waiting-for-clarification

**Comment by henrymoulton** [comment] 2019-08-27 11:23
@yuri-kulikov seeing the same as @AndrewJack and @yz1311
