### ISSUE TITLE
Error when install update :Invalid character '\u0003' 

### ISSUE THREAD

**Issue by vdgnart** [Microsoft/react-native-code-push#266] opened 2016-03-26 02:08 UTC
I use code-push 1.6.0 and react-native 0.17.0
export bundle : react-native bundle \
--platform android \
--entry-file index.android.js \
--bundle-output ./release/main.jsbundle \
--assets-dest ./release \
--dev false
then update : code-push release Checkin_android ./release 1.0.0 --deploymentName Staging
but error : Got JS Exception: SyntaxError: Invalid character '\u0003'
How can i fix it?
Thanks.

**Comment by lostintangent** [comment] 2016-03-26 02:50
The issue is that we didn't add support for releasing assets on Android until CodePush 1.7.0, so when you release via the CLI, it's uploading a ZIP to the server, but the version of the CodePush plugin you're using expects to get a JS bundle file.

You'll need to upgrade to 1.7.0+ of the CodePush plugin if you're app is using assets on Android. Unfortunately, that version of the CodePush plugin also requires at least React Native 0.19.0+, so you'd need to upgrade your RN dependency as well.

**Comment by lostintangent** [comment] 2016-03-26 19:04
@vdgnart I forgot to mention that one way you can verify this is the issue is to simply release a JS bundle file to CodePush, instead of a directory (which will be zipped). The problem with that scenario is that all of your images will disappear after doing a CodePush update, but you shouldn't see the error you're getting.

Unfortunately, React Native didn't add support for dynamically updating images until 0.19.0, which is why we take a hard dependency on that version and above at this point.

**Comment by lostintangent** [comment] 2016-03-29 01:14
@vdgnart Did this workaround help out? I'd love to make sure you're unblocked before closing this issue.

**Comment by lostintangent** [comment] 2016-03-31 18:05
I'm going to close this issue for now as isn't tracking a product bug that we can repro. @vdgnart If you could please try out the workaround I mentioned and let us know if you run into any issues, that would be awesome. Thanks again for reporting this!

**Closed by lostintangent** 2016-03-31 18:05 UTC
