### ISSUE TITLE
Headers not found while archiving build other than release

### ISSUE THREAD

**Issue by sagark1510** [Microsoft/react-native-code-push#1299] opened 2018-05-29 12:38 UTC
I can not archive my app for staging build configuration, but it is working on staging debug build config as well as archiving on release build config. 

I am getting `{any header file from AppDelegate.m}.h` not found.

### Steps to Reproduce
1. Create new build config staging with release configuration in xcode
2. create staging scheme, edit and select staging build config under build section
3. archive the app and you will get `React/RCTBundleURLProvider.h` not found. 

### Expected Behavior
What you expected to happen?
It should archive same as it works for release build.

### Actual Behavior
What actually happens?

![Image of Yaktocat](https://user-images.githubusercontent.com/2134076/40659042-bba01b3a-636a-11e8-94c0-480af9e4657d.png)

### Environment

* react-native-code-push version: 5.3.4
* react-native version: 0.55.4
* iOS/Android/Windows version: iOS
* Does this reproduce on a debug build or release build - release build

Note: I have archived my app for staging build before installing codepush plugin. And there are only two other plugins used react-native-vector-icons and react-native-config.

**Comment by NickToropov** [comment] 2018-05-30 14:00
Hi @sagark1510, thanks for posting the issue.
The most likely reason is that you didn't change `Per-configuration Build Products Path` for `Staging` configuration. Please see this [doc](https://github.com/Microsoft/react-native-code-push/blob/master/docs/multi-deployment-testing-ios.md) in step 7 and check if you have required changes. 
Please, let me know if it was helpful.

**Comment by sagark1510** [comment] 2018-06-01 03:15
@NickToropov  thanks for reply. I have done that step. Still it's giving this issue.

**Comment by NickToropov** [comment] 2018-06-01 07:54
@sagark1510 please could you provide me with demo app that reproduce the issue?

**Comment by sagark1510** [comment] 2018-06-01 08:45
Ok I'll share url very soon.

**Comment by sagark1510** [comment] 2018-06-01 10:01
@NickToropov I could produce it on react-native-config itself... so didn't integrated code-push. If you can check the project and let me know what can be the issue it would be very helpful.

below is the project which I am having issue with:
https://github.com/sagark1510/multi-env-issue

**Comment by NickToropov** [comment] 2018-06-04 09:08
Hi @sagark1510, Yes, the issue is not related to CodePush. It seems I was able to fix your project. Please could you grant me permissions that I could create branch in your repo and push changes?

**Comment by mvayngrib** [comment] 2018-06-04 20:18
@sagark1510 @NickToropov could you share the fix diff? I'm experiencing a similar issue

**Comment by sagark1510** [comment] 2018-06-05 04:18
@NickToropov I have added you as collaborator. Please check for the invitation.

**Comment by NickToropov** [comment] 2018-06-05 07:38
@sagark1510, I pushed my changes to new NT/fix-staging-build branch. Please look at it. 
```
- DF0C042220C141980054349E /* Staging Release */
+ AF0A605620C1900500818166 /* Staging Release */ 
``` 
I just recreated `Staging Release` configuration. Don't pay attention on such changes.

I think that the following changes could affect the success build:
 - shellScript
 - HEADER_SEARCH_PATHS
 - CONFIGURATION_BUILD_DIR
 - CONFIGURATION_TEMP_DIR

Please try it and let me know if it was helpful

**Comment by sagark1510** [comment] 2018-06-05 09:40
@NickToropov thanks mate. checking right now, will update asap.

**Comment by NickToropov** [comment] 2018-06-05 11:59
@NickToropov you're welcome! Glad to hear the issue was solved :)
I'll close this issue for now but please feel free to reopen it if you have any questions.

**Closed by NickToropov** 2018-06-05 11:59 UTC
Labels: external, iOS, waiting-for-clarification
