### ISSUE TITLE
Unable to create a Release with Hermes

### ISSUE THREAD

**Issue by mrousavy** [microsoft/react-native-code-push#1934] opened 2020-08-29 15:02 UTC
### Steps to Reproduce
1. Create React Native App
2. Enable Hermes in `android/app/build.gradle`:
    ```groovy
    project.ext.react = [
        enableHermes: true,  // clean and rebuild if changing
    ]
    ```
3. Run `appcenter codepush release-react`
4. See step `Converting JS bundle to byte code via Hermes, running command:` fail:

![Screenshot 2020-08-29 at 16 59 41](https://user-images.githubusercontent.com/15199031/91639744-09570000-ea19-11ea-8560-56fd87e78cef.png)

I've searched everywhere for any info about this (https://github.com/microsoft/appcenter-cli/pull/627, https://github.com/microsoft/appcenter-cli/issues/634, ..) but couldn't find any workarounds. I don't exactly remember if my previous builds were also created using Hermes, but if so, could that possibly be an issue? Otherwise I'm not doing anything unusual.

### Expected Behavior

I expect the CodePush release to succeed.

### Actual Behavior

It fails to convert the JS bundle to byte code via Hermes.

### Environment

* react-native-code-push version: 6.3.0
* react-native version: 0.63.2
* hermes-engine version: 0.5.2-rc1

**Comment by mrousavy** [comment] 2020-08-29 15:06
I've also tried using `hermes-engine` version **0.5.0** (the exact version `react-native` uses), but I'm still getting the same error.

**Comment by qwertypomy** [comment] 2020-08-31 15:42
Same issue after `react-native` upgrade to `0.63.2`.
Works ok on `0.62.2`

(both with hermes enabled)

**Comment by qwertypomy** [comment] 2020-08-31 15:50
@mrousavy try to upgrade `appcenter-cli`. Works for me with `appcenter-cli@2.6.7`

**Comment by andreidubov** [comment] 2020-09-07 13:50
Hi @mrousavy 

We have released a fix for this issue in the `appcenter-cli.` Please update the `appcenter-cli` to the latest version.

**Closed by andreidubov** 2020-09-07 13:50 UTC

**Comment by anuragdani16** [comment] 2021-02-14 04:50
Hello @andreidubov ! I have a similar issue. Using latest versions of the packages.

**Comment by anuragdani16** [comment] 2021-02-14 04:54
Hello @andreidubov ! Hope you are well. I am having a similar issue despite using latest versions of the packages.

appcenter-cli: 2.7.4
react-native-code-push: 7.0.0

Steps to reproduce - 
1. Create React Native App
2. Enable Hermes in android/app/build.gradle:
project.ext.react = [
    enableHermes: true,  // clean and rebuild if changing
]
3. Run appcenter codepush release-react

Error: 
![codepush_error](https://user-images.githubusercontent.com/49194726/107868918-80406200-6eae-11eb-8c3f-b6d20f8b9a17.png)

I have also opened an issue -
[https://github.com/microsoft/react-native-code-push/issues/2036](url)

Stuck on this for too long now. Please help.

Thanks in advance

**Comment by felipejh** [comment] 2022-09-07 03:12
I've the same error.

**Comment by engeslamadell** [comment] 2022-10-22 18:44
So for me, I'm using NX for our monorepo setup and I had this issue for days and I decided to look into the appcenter-cli code.

and at `appcenter-cli/dist/commands/codepush/lib/react-native-utils.js` i found this function 
```sh
function getHermesOSExe() {
  const react63orAbove =
    semver_1.compare(
      semver_1.coerce(getReactNativeVersion()).version,
      "0.63.0",
    ) !== -1;
  const hermesExecutableName = react63orAbove ? "hermesc" : "hermes";
  switch (process.platform) {
    case "win32":
      return hermesExecutableName + ".exe";
    default:
      return hermesExecutableName;
  }
}
```
which compares the react native version against `0.63.0` because of a change in the hermes command name

and in the monorepo setup, the appcenter-cli was looking for the react-native version inside the package.json for the project and it was like the following
```sh
"dependencies": {
    "react-native": "*",
    ....
}
```

and the reason of this is, in monorepos you have a global package.json file and all projects can share the packages in there
but with react native you need to have a sub package.json with the native libraries you use in your app so auto-linking can as expected.

and changing my package.json and include the react-native version, everything related to appcenter and codepush start to work as expected

```sh
"dependencies": {
    "react-native": "0.64.0",
    ....
}
```

**Comment by suguspnk** [comment] 2023-02-09 10:16
@engeslamadell thanks! it works!

**Comment by lucaspbordignon** [comment] 2024-07-22 16:44
Complementing the possible cases that @eeslamadelll mentioned, faced the same problem in my `package.json` configuration, which was set as

```typescript
"dependencies": {
    "react-native": "latest",
    ....
}
```

Changing `latest` to a fixed version did the trick ✅
