### ISSUE TITLE
Android: Codepush new version silently rolled back

### ISSUE THREAD

**Issue by emielvanliere** [Microsoft/react-native-code-push#835] opened 2017-05-10 16:26 UTC
### Description

We have a problem with Codepush on Android where a downloaded update seems to get silently rolled back even though the update went fine. When the update happens the user sees the new version; however when we restart the app the old version is loaded. If we look at the logs it appears that Codepush copied the older version over the newer version.

First launch:
```
05-10 18:12:47.632 18508-18508/com.mypackage D/ReactNative: [CodePush] Loading JS bundle from "assets://index.android.bundle"
```
After the update is applied (version `1.1.38`, see below):
```
05-10 18:12:52.570 18508-19194/com.mypackage D/ReactNative: [CodePush] Loading JS bundle from "/data/user/0/com.mypackage/files/CodePush/e6d18ba6dc9b3f999532812e5edb1b71d8efbb03c3b2bac6fd8af4f466bbfd69/CodePush/index.android.bundle"
```

When we restart the app we're back at `1.1.35`, even though the same location is used.
```
05-10 18:13:01.950 18508-18508/com.mypackage D/ReactNative: [CodePush] Loading JS bundle from "/data/user/0/com.mypackage/files/CodePush/e6d18ba6dc9b3f999532812e5edb1b71d8efbb03c3b2bac6fd8af4f466bbfd69/CodePush/index.android.bundle"
```

The javascript bundled in our app has version `1.1.35`, the update downloaded by Codepush has version `1.1.38`. These are the logs from our javascript bundle. We are sure to call `codePush.notifyAppReady();` in the `componentDidMount` of our root component.

 ```
05-10 18:12:49.037 18508-19194/com.mypackage D/RNSalesFlow: Bundle version: 1.1.35
05-10 18:12:49.088 18508-19194/com.mypackage D/RNSalesFlow: Codepush: syncstatus 5
05-10 18:12:49.088 18508-19194/com.mypackage D/RNSalesFlow: Codepush: checking for update
05-10 18:12:51.255 18508-19194/com.mypackage D/RNSalesFlow: Codepush: syncstatus 7
05-10 18:12:51.255 18508-19194/com.mypackage D/RNSalesFlow: Codepush: downloading package
05-10 18:12:52.531 18508-19194/com.mypackage D/RNSalesFlow: Codepush: syncstatus 8
05-10 18:12:52.531 18508-19194/com.mypackage D/RNSalesFlow: Codepush: installing update
05-10 18:12:52.561 18508-19194/com.mypackage D/RNSalesFlow: Codepush: syncstatus 1
05-10 18:12:52.562 18508-19194/com.mypackage D/RNSalesFlow: Codepush: update installed
05-10 18:12:53.742 18508-19273/com.mypackage D/RNSalesFlow: Bundle version: 1.1.38
05-10 18:12:53.789 18508-19273/com.mypackage D/RNSalesFlow: Codepush: syncstatus 5
05-10 18:12:53.789 18508-19273/com.mypackage D/RNSalesFlow: Codepush: checking for update
05-10 18:12:55.755 18508-19273/com.mypackage D/RNSalesFlow: Codepush: syncstatus 0
05-10 18:12:55.755 18508-19273/com.mypackage D/RNSalesFlow: Codepush: up-to-date
```
At this point the user will see the new version (`1.1.38`).

If we now restart the app we see this:
```
05-10 18:13:02.952 18508-19437/com.mypackage D/RNSalesFlow: Bundle version: 1.1.35
05-10 18:13:02.994 18508-19437/com.mypackage D/RNSalesFlow: Codepush: syncstatus 5
05-10 18:13:02.994 18508-19437/com.mypackage D/RNSalesFlow: Codepush: checking for update
05-10 18:13:03.056 18508-19437/com.mypackage D/RNSalesFlow: Codepush: syncstatus 0
05-10 18:13:03.058 18508-19437/com.mypackage D/RNSalesFlow: Codepush: up-to-date
```
Now we are back to `1.1.35`.

Note that the same code will update fine on iOS.

### Additional Information

* react-native-code-push version: `1.17.4-beta`
* react-native version: `0.42.3`
* Android version: all versions
* Does this reproduce on a debug build or release build? both
* Does this reproduce on a simulator, or only on a physical device? both

**Comment by sergey-akhalkov** [comment] 2017-05-11 08:43
Hi @emielvanliere, thanks for reaching us. I have not heard about such kind of issues before, so could you please be more specific regarding to repro steps or way how we could reproduce the issue (you can use our [sample app](https://github.com/Microsoft/react-native-code-push/tree/master/Examples) to reproduce it)? I also have several questions:  
1. could you please clarify what do you mean by `js bundle version 1.1.35/1.1.38`, is that your custom property?
2. Have you stopped the packager while testing CodePush updates? Please also note that CodePush updates should be tested in modes other that Debug.

**Comment by emielvanliere** [comment] 2017-05-11 11:45
Hi,

We have a custom setup (our react-native component is loaded as part of a fully native app) so reproducing this problem might not be trivial.

1. Yes, `1.1.35` and `1.1.38` are the (internal) versions of our js bundle.
2. Yes, we tested this on a device

**Comment by sergey-akhalkov** [comment] 2017-05-11 13:13
@emielvanliere, 
>We are sure to call codePush.notifyAppReady(); in the componentDidMount of our root component.

Have you wrapped the root component with CodePush (`MyRootComponent = codePush(MyRootComponent)`)? 
If so, I think that `codePush.notifyAppReady()` method is called twice (by CodePush and by your code) - so this may cause the issue, let's try to remove `codePush.notifyAppReady()` method call from your code and let me know if any updates.

If it does not help, please provide us with ideas how we could reproduce it. Without stable repro steps and source code samples (at least client side code where CodePush is used) it is really hard to determine the root cause of the issue.

**Comment by emielvanliere** [comment] 2017-05-11 13:24
No we don't wrap our root component. However, we did build codepush with the DEBUG switch on. We're going to investigate whether this was the problem and update this ticket. Thanks so far!

**Comment by sergey-akhalkov** [comment] 2017-05-17 08:47
Closing this for now, @emielvanliere, please feel free to reopen if any updates.

**Closed by sergey-akhalkov** 2017-05-17 08:47 UTC
Labels: Android, waiting-for-clarification

**Comment by emielvanliere** [comment] 2017-05-22 09:09
We've investigated the issue and it turns out that after we refactored our code (to Kotlin), we implemented the `getJSBundleFile()` override in the wrong place. Once we changed that as per the documentation CodePush works fine.
