### ISSUE TITLE
Cannot find module 'react-native-code-push'

### ISSUE THREAD

**Issue by calclavia** [Microsoft/react-native-code-push#389] opened 2016-06-22 01:56 UTC
Using Codepush 1.12.2-beta

When using the following line:
`import CodePush from 'react-native-code-push';`

I get the following error from the TS compiler. I also tried running it without TypeScript (just plain ES6), and it also results in inability to find module:
src/client/app.tsx(11,22): error TS2307: Cannot find module 'react-native-code-push'.

**Comment by lostintangent** [comment] 2016-06-22 02:04
If you change your import to "const CodePush = require('react-native-code-push')" does the error go away and everything work? 

We ship our d.ts with our NPM package, and our package.json references it, so I'd expect this to just work, but maybe the version of TS you're using doesn't support it? 

What version of TS are you using? I can try to repro this and see how can help resolve this error.

**Comment by calclavia** [comment] 2016-06-22 02:09
@lostintangent Using `const CodePush = require('react-native-code-push')` makes the error go away. But I can't use import statements.

TS version: 1.8.10

**Comment by lostintangent** [comment] 2016-06-22 02:19
OK, thanks for confirming that. I'll look into why TS isn't auto-detecting our module definition in order to allow import statements. Stay tuned!

**Comment by lostintangent** [comment] 2016-06-22 16:14
@calclavia Could you share your `tsconfig.json` file contents? Specifically, I'm curious if you have the `compilerOptions.noResolve` property set to `true`. I found that if I had that property set, then I ran into the same issue as you, but if I didn't, then everything would work great.

**Comment by calclavia** [comment] 2016-06-23 03:54
```
{
    "compilerOptions": {
        "target": "es6",
        "jsx": "react",
        "noImplicitAny": true,
        "experimentalDecorators": true,
        "preserveConstEnums": true,
        "outDir": "build",
        "sourceMap": true,
        "noEmitOnError": true,
        "allowJs": true
    },
    "filesGlob": [
        "typings/**/*.d.ts",
        "src/**/*.ts",
        "src/**/*.tsx"
    ],
    "exclude": [
        "node_modules",
        "test"
    ],
    "compileOnSave": false
}
```

**Comment by lostintangent** [comment] 2016-06-23 04:58
@calclavia It seems like the culprit is the fact that you're targetting ES6. If I use your exact config, I can repro the issue. However, if I change the target setting to ES5, everything works correctly. In your case, I'm sure you want to emit ES6, so another option that I noticed works is to change the moduleResolution property to "node". Could you try that out and see if it makes a difference for you?

**Comment by lostintangent** [comment] 2016-06-23 21:01
I confirmed with the TypeScript team that setting the `moduleResolution` property to `node` is the right solution here. The issue is that our NPM module ships with a d.ts file, but when you set the `target` compiler option to `es6`, that is apparently disabling the module resolution logic which will look for d.ts files within the `node_modules` folder. Explicitly setting `moduleResolution` to `node` "re-enables" the behavior that looks within the `node_modules` folder, and everything should work, using either `require` or ES6 imports. Let me know what you think.

**Comment by calclavia** [comment] 2016-06-25 05:28
@lostintangent Thanks! That works now.

**Comment by lostintangent** [comment] 2016-06-25 05:38
@calclavia I can definitely add this to our readme. Have you been able to load all other NPM modules using ES6 import statements? This issue seems like a general TypeScript thing, and I'd love to know if you had examples of other NPM modules that were working for you, so we could see if there's an issue with CodePush.

**Comment by lostintangent** [comment] 2016-06-27 06:44
I'm going to close this issue for now, but I'll make sure to update our docs tomorrow with TS info related to this issue in case others run into it. Thanks again for the feedback!

**Closed by lostintangent** 2016-06-27 06:44 UTC

**Comment by lostintangent** [comment] 2016-06-27 16:01
@calclavia FYI, I just added a section to our docs about this: https://github.com/Microsoft/react-native-code-push/blob/master/README.md#typescript-consumption

Let me know if you think we can improve this any further. Thanks again!
