### ISSUE TITLE
[Android]Gradle 3.4.2 can not generate codepush hash file

### ISSUE THREAD

**Issue by forrestzhang234** [microsoft/react-native-code-push#1744] opened 2019-12-13 09:19 UTC
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.gradle version ：com.android.tools.build:gradle:3.4.2
2. 
3.

### Expected Behavior
codepush.gradle can not generate CodePush hash file in apk

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version:
* react-native version:
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by alexandergoncharov** [comment] 2020-02-11 10:58
Hi @forrestzhang234 ,
Thanks for reporting!

Could you please fill all fields of the issue because the issue isn't clear for now?

I'm going to close this issue for now. Please feel free to reopen it when you fill issue fileds with the useful info.

**Closed by alexandergoncharov** 2020-02-11 10:58 UTC
