### ISSUE TITLE
Too many arguments to block call

### ISSUE THREAD

**Issue by rlog** [Microsoft/react-native-code-push#177] opened 2016-02-03 07:02 UTC
My Xcode Version 7.3 beta (7D129n)

<img width="936" alt="2016-02-03 2 57 26" src="https://cloud.githubusercontent.com/assets/73235/12775135/9572a9b6-ca86-11e5-9483-4e9a1bbbb050.png">

<img width="401" alt="2016-02-03 3 00 51" src="https://cloud.githubusercontent.com/assets/73235/12775190/fdfded24-ca86-11e5-9847-244a9729e376.png">

How could I fix this ?  

**Thanks!**

**Comment by lostintangent** [comment] 2016-02-03 15:36
Hey @rlog! That is due to a breaking change caused by React Native 0.19.0. If you upgrade to the latest version of the CodePush plugin (1.7.0), this will be resolved. Let me know how it goes!

**Comment by tristangodfrey** [comment] 2016-02-03 16:21
Just ran into this myself too, running `1.7.0-beta` :/

**Comment by lostintangent** [comment] 2016-02-03 16:27
Oh I see. Yeah apologies, as mentioned in the release docs, CodePush 1.7.0 requires React Native 0.19.0. RN included the breaking change you are hitting and added the platform support necessary for enabling updating images on Android. If you want to use the latest CodePush bits, you'll need to upgrade your RN installation. Otherwise, just install CodePush 1.6.0.

Sorry for the inconvenience here. We've been trying to maintain back compat with each of our plugin releases, but sometimes RN breaks us in a way that we have to take a new hard dependency on a specific platform version.

CodePush 1.7.0 primarily adds support for RN 0.19.0 (updating images on Android requires this version) so if you're not running that version, it wouldn't add any value to you anyways.

**Comment by tristangodfrey** [comment] 2016-02-03 16:36
Understood! Thanks for the swiftness @lostintangent appreciate it, enjoy your day buddy.

**Comment by geof90** [comment] 2016-02-09 01:14
I believe this issue was closed by https://github.com/Microsoft/react-native-code-push/pull/172 feel free to reopen otherwise.

**Closed by geof90** 2016-02-09 01:14 UTC
Labels: bug
