### ISSUE TITLE
[Android] error "undefined is not an object evaluating getUpdateMetadata

### ISSUE THREAD

**Issue by aknad** [microsoft/react-native-code-push#1637] opened 2019-07-23 15:10 UTC
Hi,
I recently updated RN to 0.59 and Code Push to 5.6.0
Now on my App Center diagnostics there are many issues like this:
> com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'p.default.getUpdateMetadata')

this problem affects only samsung s7 and s7 edge, which seems a bit strange:
![Screenshot 2019-07-23 at 17 06 03](https://user-images.githubusercontent.com/7056879/61723529-96d31580-ad6c-11e9-9662-65876ef13e70.png)

I use this function to set a Config variable:

`codePush.getUpdateMetadata().then(update => {
CONFIG.codePushRelease = update ? update.label : "";
});`

### Environment

* react-native-code-push version: 5.6.0
* react-native version: 0.59.8
* release build
* only on a physical device and probably only on Galaxy s7 and s7 edge

**Comment by alexandergoncharov** [comment] 2020-02-13 13:45
Hi @aknad ,
Thanks for reporting!

Unfortunately, I can't reproduce your issue. Could you pelase provide more detailed reprosteps or test project with reproducing issue.

I'm going to close this issue for now. Please feel free to reopen it if you hae any qeustions or provide more details.

**Closed by alexandergoncharov** 2020-02-13 13:45 UTC
