### ISSUE TITLE
Prevent duplicate releases?

### ISSUE THREAD

**Issue by LeBlaaanc** [Microsoft/react-native-code-push#352] opened 2016-05-25 17:48 UTC
I have a CI workflow that has the possibility to run `code-push release-react` at the same time. I did implement a check if the release exists in history but this doesn't help the edge case where two `release-react` might trigger at the same time. 

What can be done to prevent this or troubleshoot why this occurs if it shouldn't, all of the metadata and .jsbundle "should" be the same.

**Comment by lostintangent** [comment] 2016-05-25 17:59
@LeBlaaanc Hmm, the server should be rejecting duplicate releases, so if you're not seeing that behavior, that is a bug we need to investigate.

**Comment by LeBlaaanc** [comment] 2016-05-25 20:24
@lostintangent how can I help, I'm not seeing this behavior?

**Comment by lostintangent** [comment] 2016-05-25 20:59
@LeBlaaanc If you run `code-push release-react` locally, on the exact same codebase, without making any changes, do you see the subsequent releases get rejected by the server? Or does this only happen in your CI environment?

**Comment by geof90** [comment] 2016-05-25 21:32
@LeBlaaanc Could you also share more about your CI workflow? What's the motivation behind making two releases to the same app simultaneously? I'm not sure what the expected behaviour is on the server when two concurrent releases to the same app at the same time, i would expect its either one of two cases:
1. One gets rejected because of a duplicate release
2. One actually gets completely overwritten by the other
 
Do you actually see in your deployment history both of those updates with the exact same version?

**Comment by LeBlaaanc** [comment] 2016-05-25 21:34
@geof90 history lists both. We run code-push release as a side effect of compiling multiple apps that share the same jsbundle.

**Comment by lostintangent** [comment] 2016-05-29 17:51
I'm wondering if this is the same issue as #345, since the two individual CI environments would likely generate subtely different JS bundles, and therefore, result in duplicate releases.

**Comment by alexprice91** [comment] 2016-05-30 22:36
I am having a similar issue where I bundle up my code for a release. I do a code-push  for users who want to update, and I update my app in the app store. Once they download the app in the app store, it says that their is an update from codepush. 

I am thinking of passing in the version number in the metadata, and only showing there is an update if codepush's version is greater than the version they have. Thoughts?

**Comment by lostintangent** [comment] 2016-05-31 00:33
@alexprice91 That solution could work as a workaround, but ideally our plugin would be able to detect updates that are equivalent to the binary contents. We had this feature working for a while, but it was unfortunately regressed in React Native 0.26.0, so we're working with them to get it working again.

**Comment by LeBlaaanc** [comment] 2016-06-01 03:07
@alexprice91 I think you might be confusing the client side comparison (which I think is related/originated in #345) to the release comparison. My problem is my `release-react` command literally generates another "v" in the deployment list.

@lostintangent this still occurs and I don't see how it could even be prevented if I run say 5 release commands concurrently. What should be the expected behavior in this scenario with the current CodePush code? We keep mentioning some form of binary comparison but firstly, I'm using RN `0.25` and secondly I don't even know it would have anything yet to compare it to if it is run concurrently.

**Comment by lostintangent** [comment] 2016-06-01 03:40
@LeBlaaanc My assumption as of a week ago was that if multiple machines generated a JS bundle from the same code base, that the resulting bundles would be identical. It turns out that assumption was false, and unfortunately, if releases are made to CodePush multiple machines (e.g. be the same dev with different workstations, multiple devs on the team, or different CI build agents), then it becomes possible for the same release to actually be accepted multiple times, because from CodePush's point of view, they are different.

The reason I mentioned the binary hashing scenario is that I believe it is broken due to the same reason why the release command isn't rejecting an update that is "identical" to the latest one on the source deployment: because what we thought should be identical JS bundles turn out not to be. 

My hope is that once React Native / node-haste fixes the bundling process to be deterministic, then my aforementioned assumption becomes true and we gain various benefits as a result. There is still the possibility of two releases being allowed from CI due to some concurrency issues (I.e. the second release is made before the first is complete), but we can discuss that seperately, if it is in fact a common problem in practice.

**Comment by LeBlaaanc** [comment] 2016-06-01 04:01
Okay great. Thanks so much for the clarifications. Any timeline from the RN team or can you relay to us any thoughts or updates they have on the matter?

On May 31, 2016, at 10:40 PM, Jonathan Carter <notifications@github.com> wrote:

@LeBlaaanc My assumption as of a week ago was that if multiple machines generated a JS bundle from the same code base, that the resulting bundles would be identical. It turns out that assumption was false, and unfortunately, if releases are made to CodePush multiple machines (e.g. be the same dev with different workstations, multiple devs on the team, or different CI build agents), then it becomes possible for the same release to actually be accepted multiple times, because from CodePush's point of view, they are different.

The reason I mentioned the binary hashing scenario is that I believe it is broken due to the same reason why the release command isn't rejecting an update that is "identical" to the latest one on the source deployment: because what we thought should be identical JS bundles turn out not to be.

My hope is that once React Native / node-haste fixes the bundling process to be deterministic, then my aforementioned assumption becomes true and we gain various benefits as a result. There is still the possibility of two releases being allowed from CI due to some concurrency issues (I.e. the second release is made before the first is complete), but we can discuss that seperately, if it is in fact a common problem in practice.

**Comment by lostintangent** [comment] 2016-06-01 16:58
@LeBlaaanc Here is the discussion we started with the RN folks, where they indicated they will investigate solving the root cause of this issue: https://github.com/facebook/react-native/pull/7758.

**Comment by kennethlynne** [comment] 2016-06-09 15:14
The issue for me is that it rejects duplicates, but then my issue is that it crashes the build. Any parameters one can specify or something to work around it? Related: http://stackoverflow.com/questions/37725312/skip-deploying-to-codepush-when-the-package-content-has-not-changed

**Comment by lostintangent** [comment] 2016-06-09 16:13
@kennethlynne Is it crashing your build, or simply failing it? When the CLI rejects a duplicate release, it should just be returning with an error code, not actually crashing the process.

What would be your ideal behavior here? The duplicate rejection behavior is currently by design to prevent accidentally releasing the same thing multiple times. Do you want the CLI to allow duplicate releases?

**Comment by kennethlynne** [comment] 2016-06-09 16:59
@lostintangent it exits non-zero, so the build is failing, but not crashing. And the decision to not allow duplicate releases is a good one! I just need a simple way to allow us to merge to master and run the deployment without having to do complicated diffs etc. 

Whenever one changes documentation or parts of the native code, the build will fail if we do not guard the codepush step. 

The decired behaviour would probably be to pass a flag to the CLI so that it simply skips duplicates if there is no changes in the bundle, but does not exit non-zero, but it still exits non-zero on other issues.

**Comment by lostintangent** [comment] 2016-06-09 17:43
@kennethlynne We could do that, but in the meantime, most CI servers have a way to configure that certain build steps shouldn't fail the entire build if they fail. Which CI solution are you using? For example, Bitrise lets you specify the [`is_skippable: true`](http://devcenter.bitrise.io/docs/advanced-tips-tricks-for-bitrise-cli-workflows#section-don-t-mark-the-build-as-failed-if-a-given-step-would-fail-ignore-the-error-of-the-step-) setting on a specific step.

**Comment by kennethlynne** [comment] 2016-06-09 21:30
@lostintangent good point! Using bitrise, thanks!

**Comment by LeBlaaanc** [comment] 2016-06-10 00:09
I use bitrise as well fyi.

**Comment by lostintangent** [comment] 2016-06-10 00:21
@LeBlaaanc It's interesting that @kennethlynne would see his releases get rejected due to be equivalent to the latest release, however you aren't, despite the fact that you're both using Bitrise :)

**Comment by lostintangent** [comment] 2016-06-18 18:31
@LeBlaaanc I haven't had a chance to test it yet, but it appears that this issue has been resolved in the master branch of React Native. If so, that means it should hopefully be release in 0.29. I'll test it later to confirm, but I just wanted to give you the heads up in case you were also interested in trying the bleeding edge RN bits :)

**Comment by LeBlaaanc** [comment] 2016-06-18 18:32
@lostintangent ah interesting... I'll give it a go once 0.29 is released ;)

**Comment by lostintangent** [comment] 2016-06-24 22:14
@LeBlaaanc Just to confirm: this issue is in fact solved in RN 0.29, and I just checked in a fix on our end for iOS (yay!). We'll send out a PR to address the Android side of things, along with a few other fix we need to make to address some additional RN 0.29 breaking changes. Thanks for the patience here.

**Comment by lostintangent** [comment] 2016-06-27 17:28
The fix for this has now been shipped to NPM. As mentioned, it unfortunately requires RN 0.29, but once you install that, and the latest CodePush, this feature will work properly. Thanks for the patience and let us know if you run into any issues.

**Closed by lostintangent** 2016-06-27 17:28 UTC
Labels: bug, external
