### ISSUE TITLE
Rollback on app restart after changes being applied correctly.

### ISSUE THREAD

**Issue by joaovpmamede** [Microsoft/react-native-code-push#1483] opened 2018-12-20 21:08 UTC
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. run app on simulator
2. change code and run code-push
3. close app and open again to let code-push download new code

### Expected Behavior
New code to be kept without rollback.

### Actual Behavior
First time it downloads, restarts app and I see changes.
After I restart the app, changes are gone.

This is the logs from xcode:
```
2018-12-20 20:59:57.561 [info][tid:com.facebook.react.JavaScript] [CodePush] Checking for update.
2018-12-20 20:59:57.560948+0000 app qa[66550:2106224] [CodePush] Checking for update.
2018-12-20 20:59:58.437 [info][tid:com.facebook.react.JavaScript] [CodePush] Downloading package.
2018-12-20 20:59:58.437160+0000 app qa[66550:2106224] [CodePush] Downloading package.
2018-12-20 20:59:59.462 [warn][tid:com.facebook.react.CodePushQueue][RCTEventEmitter.m:53] Sending `CodePushDownloadProgress` with no listeners registered.
2018-12-20 20:59:59.462024+0000 app qa[66550:2107230] Sending `CodePushDownloadProgress` with no listeners registered.
2018-12-20 20:59:59.535266+0000 app qa[66550:2107263] 
[CodePush] Applying diff update.
2018-12-20 20:59:59.535522+0000 app qa[66550:2107263] 
[CodePush] Verifying hash for folder path: /Users/joaomamede/Library/Developer/CoreSimulator/Devices/5D45F8FB-2D9A-4643-B05F-9F5D3EE9BFA4/data/Containers/Data/Application/B4A07696-230B-485A-858A-B1FD43CC7AF6/Library/Application Support/CodePush/d64a4535c5a9f405f6dd170c9b1c800c256c1d8fcb049d04e8dddc8f92cf1176
2018-12-20 20:59:59.608353+0000 app qa[66550:2107263] 
[CodePush] Manifest string: (
    "CodePush/main.jsbundle:2a5e4a08d16a0356dfa5d5985fabe2373bf293f01f7886420e74845b5ea808b9",
    "CodePush/assets/node_modules/react-navigation-stack/dist/views/assets/back-icon@3x.png:3ddd0773ed27e23d25789f301731b3ac455ad8be5aa27a0a1b838f89c6d27225",
    "CodePush/assets/node_modules/react-navigation-stack/dist/views/assets/back-icon@2x.png:2b7443a9a58e92ca11a575bdc11598615a57dde305cd8ce70d602606b302cd98",
    "CodePush/assets/node_modules/react-navigation-stack/dist/views/assets/back-icon.png:2cdfeb8e5ccde7976f7012fb8cce73af2229029ee21d4f1509fed114871c6cd8",
    "CodePush/assets/node_modules/react-navigation-stack/dist/views/assets/back-icon-mask.png:a8f68eb210e72be88ff8caab2b65707e07aa24def3cf310867be62d408a305db",
    "CodePush/assets/node_modules/react-native-datepicker/date_icon.png:6a7b6423bb29810ad371a1fe11efad99dc32b61a4e65d4c84bf57723e6460652",
    "CodePush/assets/src/images/bg-auth.png:1add1db98f4ce358f93d1d1c7945d4387618c3c81dbb0c108b2a0a3a97296910",
    "CodePus
2018-12-20 20:59:59.609178+0000 app qa[66550:2107263] 
[CodePush] Expected hash: d64a4535c5a9f405f6dd170c9b1c800c256c1d8fcb049d04e8dddc8f92cf1176, actual hash: d64a4535c5a9f405f6dd170c9b1c800c256c1d8fcb049d04e8dddc8f92cf1176
2018-12-20 20:59:59.609353+0000 app qa[66550:2107263] 
[CodePush] The update contents succeeded the data integrity check.
2018-12-20 20:59:59.612 [info][tid:com.facebook.react.JavaScript] [CodePush] Installing update.
2018-12-20 20:59:59.611904+0000 app qa[66550:2106224] [CodePush] Installing update.
2018-12-20 20:59:59.628 [info][tid:com.facebook.react.JavaScript] [CodePush] Restarting app
2018-12-20 20:59:59.628536+0000 app qa[66550:2106224] [CodePush] Restarting app
2018-12-20 20:59:59.629305+0000 app qa[66550:2106152] 
[CodePush] Loading JS bundle from file:///Users/joaomamede/Library/Developer/CoreSimulator/Devices/5D45F8FB-2D9A-4643-B05F-9F5D3EE9BFA4/data/Containers/Data/Application/B4A07696-230B-485A-858A-B1FD43CC7AF6/Library/Application%20Support/CodePush/d64a4535c5a9f405f6dd170c9b1c800c256c1d8fcb049d04e8dddc8f92cf1176/CodePush/main.jsbundle
2018-12-20 20:59:59.630 [info][tid:main][RCTCxxBridge.mm:926] Invalidating <RCTCxxBridge: 0x600003c9c3c0> (parent: <RCTBridge: 0x600002886610>, executor: (null))
2018-12-20 20:59:59.629728+0000 app qa[66550:2106152] Invalidating <RCTCxxBridge: 0x600003c9c3c0> (parent: <RCTBridge: 0x600002886610>, executor: (null))
2018-12-20 20:59:59.630 [info][tid:main][RCTCxxBridge.mm:209] Initializing <RCTCxxBridge: 0x600003ca0960> (parent: <RCTBridge: 0x600002886610>, executor: (null))
2018-12-20 20:59:59.630008+0000 app qa[66550:2106152] Initializing <RCTCxxBridge: 0x600003ca0960> (parent: <RCTBridge: 0x600002886610>, executor: (null))
2018-12-20 20:59:59.634367+0000 app qa[66550:2107230] Task <B413280F-B4ED-4928-9714-B1E7F0F04132>.<3> load failed with error Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://codepush.azurewebsites.net/reportStatus/download, NSErrorFailingURLKey=https://codepush.azurewebsites.net/reportStatus/download, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <B413280F-B4ED-4928-9714-B1E7F0F04132>.<3>"
```

### Environment

* react-native-code-push version: 5.5.0
* react-native version: 0.56.0
* iOS/Android/Windows version: iOS
* Does this reproduce on a debug build or release build? both
* Does this reproduce on a simulator, or only on a physical device? both

**Comment by alexandergoncharov** [comment] 2018-12-21 08:57
Hi @joaovpmamede,
Thanks for reporting!

Could you please share your `appDelegate.m` file and do you have rollback metrics for this?

Thanks,
Alexander

**Comment by joaovpmamede** [comment] 2018-12-21 10:00
Sure.

`AppDelegate.m`:

```
/**
 * Copyright (c) 2015-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#import "AppDelegate.h"
#import <CodePush/CodePush.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <React/RCTLinkingManager.h>
#import <React/RCTPushNotificationManager.h>
#if __has_include(<React/RNSentry.h>)
#import <React/RNSentry.h> // This is used for versions of react >= 0.40
#else
#import "RNSentry.h" // This is used for versions of react < 0.40
#endif

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;

  #ifdef DEBUG
      jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
  #else
      jsCodeLocation = [CodePush bundleURL];
  #endif
  
  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"revup"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];

  [RNSentry installWithRootView:rootView];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];

  UIView* launchScreenView = [[[NSBundle mainBundle] loadNibNamed:@"LaunchScreen" owner:self options:nil] objectAtIndex:0];
  launchScreenView.frame = self.window.bounds;
  rootView.loadingView = launchScreenView;

  UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
  center.delegate = self;

  return YES;
}

- (BOOL)application:(UIApplication *)application
   openURL:(NSURL *)url
   options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  return [RCTLinkingManager application:application openURL:url options:options];
}

- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity
 restorationHandler:(void (^)(NSArray * _Nullable))restorationHandler
{
 return [RCTLinkingManager application:application
                  continueUserActivity:userActivity
                    restorationHandler:restorationHandler];
}

// Required to register for notifications
- (void)application:(UIApplication *)application didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings
{
  [RCTPushNotificationManager didRegisterUserNotificationSettings:notificationSettings];
}

// Required for the register event.
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
{
  [RCTPushNotificationManager didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
}

// Required for the notification event. You must call the completion handler after handling the remote notification.
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo
fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler
{
  NSMutableDictionary* userInfoCopy = [userInfo mutableCopy];
  userInfoCopy[@"userHasInteracted"] = @YES;

  [RCTPushNotificationManager didReceiveRemoteNotification:[NSDictionary dictionaryWithDictionary:userInfoCopy] fetchCompletionHandler:^(UIBackgroundFetchResult result) {
    if ([userInfoCopy[@"userHasInteracted"] boolValue] == YES) {
      return;
    }
    completionHandler(result);
  }];
}

// Required for the registrationError event.
- (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error
{
  [RCTPushNotificationManager didFailToRegisterForRemoteNotificationsWithError:error];
}

// Required for the localNotification event.
- (void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification
{
  [RCTPushNotificationManager didReceiveLocalNotification:notification];
}

@end
```

The curious thing is that if I check the `appcenter codepush deployment list` I don't see any rollback for that particular app/env and it says that in fact I have it installed although it rolled back.

**Comment by alexandergoncharov** [comment] 2018-12-21 10:07
It is interesting.  Your `appDelegate.m` looks like correct. 
Could you please provide some dummy project with reproducing issue and reprosteps? I would like to debug it.

**Comment by joaovpmamede** [comment] 2018-12-21 10:22
Yup, just give me some time so I can clone/recreate something, can't really share this one as it is.

**Comment by alexandergoncharov** [comment] 2018-12-21 10:43
Yeah, sure. Just provide it when it's ready, thanks :)

**Comment by joaovpmamede** [comment] 2018-12-21 14:42
Well, after some time I decided to run through the docs again, specifically the [Multi deployment testing](https://github.com/Microsoft/react-native-code-push/blob/master/docs/multi-deployment-testing-ios.md) and after duplicating the `release` scheme I finally was able to get codepush to work as expected.

Anyway what I had before was this:

![screenshot 2018-12-21 14 38 51](https://user-images.githubusercontent.com/1040722/50347649-335edc00-052e-11e9-9345-a005cecfa537.jpg)

and I think it should always be: `$(BUILD_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)` just like the docs say.

I'm not really sure if this was the only thing different but for now it's working and I'll fix the rest of my schemes/versions.

Thanks @alexandergoncharov for reaching out.

**Comment by yuri-kulikov** [comment] 2018-12-24 11:16
Hi @joaovpmamede,
That's great, thanks for keeping in touch!

Is there anything else we can help you with?

**Comment by yuri-kulikov** [comment] 2018-12-26 07:33
I'll close the issue for now, but feel free to reopen it if you have any questions! :)

**Closed by yuri-kulikov** 2018-12-26 07:33 UTC
Labels: bug, iOS, waiting-for-clarification

**Comment by AdamGold** [comment] 2019-06-11 14:39
Any news on this?

**Comment by khushbujilka22** [comment] 2023-10-16 13:12
I having same error:

`*** Assertion failure in -[RCTEventEmitter sendEventWithName:body:](), /Users/OnlyMac/development/universal-client-mobile-app_new/node_modules/react-native/React/Modules/RCTEventEmitter.m:53
2023-10-16 17:56:14.137967+0530 FabDeliveryClientAppToRename[5812:270999] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error when sending event: CodePushDownloadProgress with body: {
    receivedBytes = 1874408;
    totalBytes = 1874408;
}. RCTCallableJSModules is not set. This is probably because you've explicitly synthesized the RCTCallableJSModules in CodePush, even though it's inherited from RCTEventEmitter.'
*** First throw call stack:
(0x180a27c80 0x19824dee4 0x1821cdde0 0x1047a1508 0x1041d6c88 0x1041d8a3c 0x1041dbb68 0x1044c4ae4 0x1044bff6c 0x1044c4944 0x1813d3bb0 0x1820f739c 0x182108a70 0x1820e2a8c 0x1820f2fcc 0x1820f6498 0x182103ccc 0x10851d1a8 0x10850dfc8 0x108515150 0x108515ddc 0x10852163c 0x1dbd94e00 0x1dbd9492c)
libc++abi: terminating with uncaught exception of type NSException`

**Comment by mununki** [comment] 2023-12-27 05:57
@khushbujilka22 Did you fix this? I'm facing exactly same issue.
