### ISSUE TITLE
[Error]  No property named "ANDROID_BUILD_VERSION_NAME" exists in the "android/gradle.properties" file.

### ISSUE THREAD

**Issue by Chren** [Microsoft/react-native-code-push#660] opened 2017-01-05 03:54 UTC
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

* react-native-code-push version:1.16.1-beta
* react-native version:0.39.2
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?
* Repro steps and/or stack trace:

(The more info the faster we will be able to address it!)
When I run commend blow:
code-push release-react AIXY android -d AndroidDev --des "First Commit"
It throw an error:
Detecting android app version:

[Error]  No property named "ANDROID_BUILD_VERSION_NAME" exists in the "android/gradle.properties" file.

However there's ANDROID_BUILD_VERSION_NAME exists in gradle.properties file:

`org.gradle.daemon=true
org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.configureondemand=true

ANDROID_BUILD_SDK_VERSION=23
ANDROID_BUILD_VERSION_NAME=3.0.0
ANDROID_BUILD_VERSION=45
ANDROID_BUILD_TARGET_SDK_VERSION=22
ANDROID_BUILD_TOOLS_VERSION=23.0.1
ANDROID_BUILD_MIN_SDK_VERSION=16`

**Comment by sergey-akhalkov** [comment] 2017-01-09 13:15
@Chren - hi! 
Could you please confirm that there is no additional `gradle.properties` file exists in `android/app/` directory? In case we have both `android/app/gradle.properties` and `android/gradle.properties` used only first one.

**Comment by aiyidu** [comment] 2017-01-09 14:10
Yes, I'm sure there's only one gradle.properties at android/gradle.properties.

I finally avoid this error by running command with specify version explicitly (-t 3.0.0).

**Comment by sergey-akhalkov** [comment] 2017-01-09 14:38
@aiyidu - I've tried to reproduce the issue with no luck using following repro steps: 
1. > `react-native init myapp`  
    > `npm install --save react-native-code-push@1.16.1-beta`
    > `react-native link react-native-code-push`
2. Add `ANDROID_BUILD_VERSION_NAME=3.0.0` property to `android/gradle.properties` file
3. Change `versionName` property from `versionName "1.0"` to `versionName ANDROID_BUILD_VERSION_NAME` in `android/app/build.gradle` file
4. Then executed `code-push release-react myapp android -d AndroidDev --des "First Commit"` command 

So could you please correct my repro steps or provide me with code samples?

**Comment by aiyidu** [comment] 2017-01-10 02:26
I'm not using react-native init myapp to create project, but integrate react-native into exist project.
And here is the gradle.properties:

[gradle.zip](https://github.com/Microsoft/react-native-code-push/files/695116/gradle.zip)

**Comment by sergey-akhalkov** [comment] 2017-01-10 12:26
@aiyidu, I've integrated provided `gradle.properties` file into my project and it works well, so could you please help me to determine cause of the issue? Fists, we need to check version of your `code-push-cli` using `code-push -v` command and update it if it has version lower than `1.12.6-beta`.
In case update does not help we could try to debug `code-push-cli`. I suppose the issue probably occurs in `C:\Users\%username%\AppData\Roaming\npm\node_modules\code-push-cli\script\command-executor.js` file in the following lines: 
>try {
>    const parsedProperties: any = properties.parse(propertiesContent);
>    appVersion = parsedProperties[propertyName];
>} catch (e) {
>        throw new Error('Unable to parse "${propertiesFile}". Please ensure it is a well-formed properties file.');
>}
>if (!appVersion) {
>        throw new Error('No property named "${propertyName}" exists in the "${propertiesFile}" file.');
>}

So could you please add logs listed below after `appVersion = parsedProperties[propertyName];` line, then execute `code-push release-react AIXY android -d AndroidDev --des "First Commit"` command and send me console log?
> log('propertiesContent value: "${propertiesContent}"');
> log('parsedProperties value: "${parsedProperties}"');
> log('appVersion value: "${appVersion}"');

To get more info you could also debug node.js using following command:
`node --inspect --debug-brk "C:\Users\%username%\AppData\Roaming\npm\node_modules\code-push-cli\script\cli.js" release-react AIXY android -d AndroidDev --des "First Commit"`

**Comment by aiyidu** [comment] 2017-01-14 09:55
@sergey-akhalkov 
I am using mac. So the path actually is: "/usr/local/lib/node_modules/code-push-cli/script/command-executor.js "

The code-push version I am using is 1.12.6-beta

And I add log as below(which is a little different in mac):

exports.log("propertiesContent value: "+ propertiesContent);
exports.log("parsedProperties value: " + parsedProperties);
exports.log("appVersion value: " + appVersion);

Then I run command "code-push release-react AIXY android -d AndroidDev --des "First Commit""

I got this:

Detecting android app version:

# org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.e# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projeorg.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encKEYSTORE_ALIAS_PASSWORD=readyidu!@#jks
parsedProperties value: [object Object]
appVersion value: undefined
[Error]  No property named "ANDROID_BUILD_VERSION_NAME" exists in the "android/gradle.properties" file.

And could you tell me how to debug node.js in mac?
I run your command but get error:
node: bad option: --inspect

**Comment by sergey-akhalkov** [comment] 2017-01-16 11:55
@aiyidu, value of `propertiesContent` variable looks weird, it should be equal to `gradle.properties` file content. [fs.readFileSync()](https://nodejs.org/api/fs.html#fs_fs_readfilesync_file_options) default node.js function is used to get `gradle.properties` file content, but for now it returns wrong value. You could try to update `node.js` version, it might help.
> And could you tell me how to debug node.js in mac?
I run your command but get error:
node: bad option: --inspect

I suppose you are using old version of `node.js`, you could update it (I'm using 7.4.0) or [install node-inspector](http://stackoverflow.com/questions/40550885/debugging-local-nodejs-script-in-chrome-dev-tools). I've added `debugger;` code line before `var propertiesFile = knownLocations.find(fileExists);` then executed `sudo node --inspect --debug-brk /usr/local/lib/node_modules/code-push-cli/script/cli.js release-react rncp660 android -d AndroidDev --des "First Commit"` command to start debugging.
>parsedProperties value: [object Object]

To fix `[object Object]` you could wrap up `parsedProperties` variable with `JSON.stringify`:
`exports.log("parsedProperties value: " + JSON.stringify(parsedProperties));`

**Comment by panarasi** [comment] 2017-01-26 18:40
Closing this issue since the fix for this is already merged.

**Closed by panarasi** 2017-01-26 18:40 UTC
