### ISSUE TITLE
can't renew the project

### ISSUE THREAD

**Issue by hanleirx** [Microsoft/react-native-code-push#339] opened 2016-05-19 07:34 UTC
I don't know why that I carry out "code-push release-react MyApp ios",then I restart my app and it is no change，who can tell me why.and how to renew the app?

**Comment by dtivel** [comment] 2016-05-19 15:17
Did you add to your Info.plist file a `CodePushDeploymentKey` entry with the correct deployment key?  If you did not specify a deployment name in your `release-react` command, then the default deployment is Staging.  In this case the `CodePushDeploymentKey` value would be your Staging deployment key.

Does the app version of your update match your installed app version?  They must match for you to get the update.  You can find your update's app version by running:

    code-push deployment history MyApp Staging

In your app how are you calling [`sync()`](https://github.com/Microsoft/react-native-code-push#codepushsync) or [`checkForUpdate()`](https://github.com/Microsoft/react-native-code-push#codepushcheckforupdate)?

**Comment by lostintangent** [comment] 2016-05-24 14:16
Closing as a duplicate of #349.

**Closed by lostintangent** 2016-05-24 14:16 UTC
