### ISSUE TITLE
[Android] `codePushOnBinaryVersionMismatch/handleBinaryVersionMismatchCallback` This method cannot be triggered

### ISSUE THREAD

**Issue by TrustTheBoy** [Microsoft/react-native-code-push#1023] opened 2017-09-29 02:50 UTC
Hi! @max-mironov 
> The cell phone comes with version 1.0.1, and the latest is 1.0.2, but it doesn't perform the hook function

react native :0.48.4
RNCP: 5.1.1-beta

 [see doc source](https://microsoft.github.io/code-push/docs/react-native.html#codepushcheckforupdate)

```javascript
CodePushUpdata = () => {
        CodePush.sync({
            updateDialog: {
                appendReleaseDescription: true,
                descriptionPrefix:'update content：\n',
                title:'title',
                mandatoryUpdateMessage:'',
                mandatoryContinueButtonLabel:'update',
            },
            mandatoryInstallMode:CodePush.InstallMode.IMMEDIATE,
            //deploymentKey: CODE_PUSH_PRODUCTION_KEY,
            },
            (syncStatus)=> this.codePushStatusDidChange(syncStatus),
            (progress)=>{
                Toast.loading(`${progress.receivedBytes} of ${progress.totalBytes} bytes received`)
                //this.codePushDownloadDidProgress.bind(this)
            },
            (update)=> this.handleBinaryVersionMismatchCallback(update)
        );
    }
```

**Comment by sergey-akhalkov** [comment] 2017-09-29 06:59
Hi @TrustTheBoy, thanks for reaching us. Please take a look at this comment and let me know if it helps https://github.com/Microsoft/react-native-code-push/pull/888#issuecomment-309784920

Please also let me know if you see any issues.

**Comment by sergey-akhalkov** [comment] 2017-09-29 11:06
@TrustTheBoy, could you please share us your deployment history? - `code-push deployment history <appName> <deploymentName>` and also provide us the version of your app you are trying to update?

**Comment by TrustTheBoy** [comment] 2017-09-29 11:12
@akki-ng @max-mironov I try to build a new demo, or I cannot trigger the hook function
@sergey-akhalkov Build a private cloud on your foundation

**Comment by sergey-akhalkov** [comment] 2017-09-29 11:32
@TrustTheBoy, 
Could you please clarify what do you mean by `Build a private cloud on your foundation`?

Also, could you please provide me exact repro steps so I would be able to reproduce the issue?

**Comment by TrustTheBoy** [comment] 2017-09-29 11:32
@sergey-akhalkov  
```
┌───────┬──────────────┬─────────────┬───────────┬─────────────┬────────────────────────┐
│ Label │ Release Time │ App Version │ Mandatory │ Description │ Install Metrics        │
├───────┼──────────────┼─────────────┼───────────┼─────────────┼────────────────────────┤
│ v32   │ 9 hours ago  │ 1.0.2       │ Yes       │ 1.yellow    │ Active: 0% (0 of 40)   │
│       │              │             │           │             │ Total: 0               │
├───────┼──────────────┼─────────────┼───────────┼─────────────┼────────────────────────┤
│ v31   │ 9 hours ago  │ 1.0.2       │ Yes       │ 1.yellow    │ Active: 0% (0 of 40)   │
│       │              │             │           │             │ Total: 0               │
├───────┼──────────────┼─────────────┼───────────┼─────────────┼────────────────────────┤
│ v30   │ 9 hours ago  │ 1.0.1       │ Yes       │ 1.主题色       │ Active: 7.5% (3 of 40) │
│       │              │             │           │             │ Total: 3               │
├───────┼──────────────┼─────────────┼───────────┼─────────────┼────────────────────────┤
│ v29   │ 10 hours ago │ 1.0.1       │ Yes       │ 1.主题色       │ Active: 2.5% (1 of 40) │
│       │              │             │           │             │ Total: 2               │
│       │              │             │           │             │ Rollbacks: 1           │
├───────┼──────────────┼─────────────┼───────────┼─────────────┼────────────────────────┤
│ v28   │ 10 hours ago │ 1.0.1       │ Yes       │ 1.主题色       │ Active: 0% (0 of 40)   │
│       │              │             │           │             │ Total: 1               │
│       │              │             │           │             │ Rollbacks: 1           │
├───────┼──────────────┼─────────────┼───────────┼─────────────┼────────────────────────┤
│ v27   │ 10 hours ago │ 1.0.1       │ Yes       │ 1.主题色       │ Active: 0% (0 of 40)   │
│       │              │             │           │             │ Total: 1               │
│       │              │             │           │             │ Rollbacks: 1           │
├───────┼──────────────┼─────────────┼───────────┼─────────────┼────────────────────────┤
│ v26   │ 16 hours ago │ 1.0.1       │ No        │ 1.主题色       │ Active: 2.5% (1 of 40) │
│       │              │             │           │             │ Total: 1               │
├───────┼──────────────┼─────────────┼───────────┼─────────────┼────────────────────────┤
│ v25   │ 17 hours ago │ 1.0.2       │ Yes       │ 1.硬更新,Alert │ Active: 2.5% (1 of 40) │
│       │              │             │           │             │ Total: 1               │
├───────┼──────────────┼─────────────┼───────────┼─────────────┼────────────────────────┤
│ v24   │ 17 hours ago │ 1.0.2       │ Yes       │ 1.硬更新       │ Active: 0% (0 of 40)   │
│       │              │             │           │             │ Total: 0               │
├───────┼──────────────┼─────────────┼───────────┼─────────────┼────────────────────────┤
│ v23   │ 17 hours ago │ 1.0.1       │ Yes       │ 1.硬更新       │ Active: 5.0% (2 of 40) │
│       │              │             │           │             │ Total: 2               │
├───────┼──────────────┼─────────────┼───────────┼─────────────┼────────────────────────┤
│ v22   │ a day ago    │ 1.0.1       │ Yes       │ 1.toast     │ Active: 5.0% (2 of 40) │
│       │              │             │           │             │ Total: 2               │
├───────┼──────────────┼─────────────┼───────────┼─────────────┼────────────────────────┤
│ v21   │ a day ago    │ 1.0.1       │ Yes       │ 1.toast     │ Active: 2.5% (1 of 40) │
│       │              │             │           │             │ Total: 1               │
├───────┼──────────────┼─────────────┼───────────┼─────────────┼────────────────────────┤
│ v20   │ a day ago    │ 1.0.1       │ Yes       │ 1.toast     │ Active: 2.5% (1 of 40) │
│       │              │             │           │             │ Total: 1               │
├───────┼──────────────┼─────────────┼───────────┼─────────────┼────────────────────────┤
│ v19   │ a day ago    │ 1.0.1       │ Yes       │ 1.toast     │ Active: 2.5% (1 of 40) │
│       │              │             │           │             │ Total: 1               │
├───────┼──────────────┼─────────────┼───────────┼─────────────┼────────────────────────┤
│ v18   │ a day ago    │ 1.0.1       │ Yes       │ 1.toast     │ Active: 5.0% (2 of 40) │
│       │              │             │           │             │ Total: 2               │
└───────┴──────────────┴─────────────┴───────────┴─────────────┴────────────────────────┘
```

**Comment by TrustTheBoy** [comment] 2017-09-29 11:38
@sergey-akhalkov Sorry, I just made a mistake,

**Comment by TrustTheBoy** [comment] 2017-09-29 12:17
@sergey-akhalkov @max-mironov @akki-ng 
> New Demo ,You can test the test
history as follows
```
┌───────┬──────────────┬─────────────┬───────────┬─────────────┬──────────────────────┐
│ Label │ Release Time │ App Version │ Mandatory │ Description │ Install Metrics      │
├───────┼──────────────┼─────────────┼───────────┼─────────────┼──────────────────────┤
│ v8    │ 8 hours ago  │ 1.0.0       │ Yes       │ 1.version   │ Active: 20% (1 of 5) │
│       │              │             │           │             │ Total: 1             │
├───────┼──────────────┼─────────────┼───────────┼─────────────┼──────────────────────┤
│ v7    │ 8 hours ago  │ 1.0.2       │ Yes       │ 1.version   │ Active: 0% (0 of 5)  │
│       │              │             │           │             │ Total: 0             │
├───────┼──────────────┼─────────────┼───────────┼─────────────┼──────────────────────┤
│ v6    │ 8 hours ago  │ 1.0.0       │ Yes       │ 1.version   │ Active: 20% (1 of 5) │
│       │              │             │           │             │ Total: 1             │
├───────┼──────────────┼─────────────┼───────────┼─────────────┼──────────────────────┤
│ v5    │ 8 hours ago  │ 1.0.0       │ Yes       │ 1.version   │ Active: 20% (1 of 5) │
│       │              │             │           │             │ Total: 1             │
├───────┼──────────────┼─────────────┼───────────┼─────────────┼──────────────────────┤
│ v4    │ 8 hours ago  │ 1.0.0       │ Yes       │ 1.version   │ Active: 20% (1 of 5) │
│       │              │             │           │             │ Total: 1             │
├───────┼──────────────┼─────────────┼───────────┼─────────────┼──────────────────────┤
│ v3    │ 8 hours ago  │ 1.0.1       │ Yes       │ 1.version   │ Active: 0% (0 of 5)  │
│       │              │             │           │             │ Total: 0             │
├───────┼──────────────┼─────────────┼───────────┼─────────────┼──────────────────────┤
│ v2    │ 8 hours ago  │ 1.0.0       │ Yes       │ 1.yellow    │ Active: 20% (1 of 5) │
│       │              │             │           │             │ Total: 1             │
├───────┼──────────────┼─────────────┼───────────┼─────────────┼──────────────────────┤
│ v1    │ 8 hours ago  │ 1.0.0       │ Yes       │ 1.yellow    │ Active: 0% (0 of 5)  │
│       │              │             │           │             │ Total: 0             │
└───────┴──────────────┴─────────────┴───────────┴─────────────┴──────────────────────┘
```
```
mport React, { Component } from 'react';
import { AppRegistry,StatusBar,AppState, Alert,StyleSheet,View,Text } from 'react-native';
import CodePush from "react-native-code-push";


class CodePushVersion extends Component {
  constructor() {
        super();
        this.state = { restartAllowed: true };
    }
  componentDidMount() {
        AppState.addEventListener("change", (newState) => {
            newState === "active" && this.CodePushUpdata();
        });
    }
    CodePushUpdata = () => {
        CodePush.sync({
            updateDialog: {
                appendReleaseDescription: true,
                descriptionPrefix:'更新内容：\n',
                title:'更新标题',
                mandatoryUpdateMessage:'',
                mandatoryContinueButtonLabel:'更新',
            },
            mandatoryInstallMode:CodePush.InstallMode.IMMEDIATE,
            //deploymentKey: CODE_PUSH_PRODUCTION_KEY,
            },
            this.codePushStatusDidChange.bind(this),
            this.codePushDownloadDidProgress.bind(this),
            this.codePushOnBinaryVersionMismatch.bind(this)
        );
    }
    codePushStatusDidChange(syncStatus) {
    switch(syncStatus) {
      case CodePush.SyncStatus.CHECKING_FOR_UPDATE:
        this.setState({ syncMessage: "Checking for update." });
        break;
      case CodePush.SyncStatus.DOWNLOADING_PACKAGE:
        this.setState({ syncMessage: "Downloading package." });
        break;
      case CodePush.SyncStatus.AWAITING_USER_ACTION:
        this.setState({ syncMessage: "Awaiting user action." });
        break;
      case CodePush.SyncStatus.INSTALLING_UPDATE:
        this.setState({ syncMessage: "Installing update." });
        break;
      case CodePush.SyncStatus.UP_TO_DATE:
        this.setState({ syncMessage: "App up to date.", progress: false });
        break;
      case CodePush.SyncStatus.UPDATE_IGNORED:
        this.setState({ syncMessage: "Update cancelled by user.", progress: false });
        break;
      case CodePush.SyncStatus.UPDATE_INSTALLED:
        this.setState({ syncMessage: "Update installed and will be applied on restart.", progress: false });
        break;
      case CodePush.SyncStatus.UNKNOWN_ERROR:
        this.setState({ syncMessage: "An unknown error occurred.", progress: false });
        break;
    }
  }
  codePushOnBinaryVersionMismatch(binary){
    console.log("handleBinaryVersionMismatchCallback");
      //console.log(binary);
    Alert.alert(JSON.stringify(binary)+"二进制？");
  }
  codePushDownloadDidProgress(progress) {
    //alert(JSON.stringify(progress)+"下载进度")
      this.setState({progress});
    //Toast.loading(`${progress.receivedBytes} of ${progress.totalBytes} bytes received`)
  }
  render() {
     let progressView;
    if (this.state.progress) {
      progressView = (
        <Text style={styles.messages}>{this.state.progress.receivedBytes} of {this.state.progress.totalBytes} bytes received</Text>
      );
    }
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          one update
          update 1.0.2
          current 1.0.0
        </Text>
        <Text style={styles.instructions}>
          {progressView}
        </Text>
        <Text style={styles.instructions}>
          {this.state.syncMessage || ""}
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
let codePushOptions = { checkFrequency: CodePush.CheckFrequency.MANUAL };
const CodePushVersionView = CodePush(codePushOptions)(CodePushVersion);
AppRegistry.registerComponent('CodePushVersion', () => CodePushVersionView);
```

**Comment by akki-ng** [comment] 2017-09-29 12:35
@TrustTheBoy I'm not able to reproduce this issue. Can you make sure that installed binary version in the device is less than "1.0.2", and that installed binary must have codepush version "4.1.1 - beta or greater" and is using "codePushOnBinaryVersionMismatch" callback handler.

For example, the version of binary apk installed on your device is 1.0.0 and is using "codePushOnBinaryVersionMismatch" to alert the user if a binary is updated (greater than 1.0.0). Later if you make a new build and host it somewhere and then release a codepush update with a binary version 1.0.2, at that point installed binary will notify of updated version.

For clarity can you send us the logs of codepush when app is trying to check update, along with the **installed binary version** and **codepush release targetBinaryVersion**. It will make it easier for us to reproduce the issue.

**Comment by akki-ng** [comment] 2017-09-29 12:46
@TrustTheBoy If you check the code of codepush.js [block](https://github.com/Microsoft/react-native-code-push/blob/master/CodePush.js#L73-L89) . This piece of code triggeres "codePushOnBinaryVersionMismatch". I would suggest you to put some console in this block to check if its even being executed.
In your logs you must see if such binary updates are available
**"An update is available but it is not targeting the binary version of your app."**

Try printing "update" object just before the if block.

**Comment by TrustTheBoy** [comment] 2017-09-30 01:06
@akki-ng 
```
09-29 08:41:48.242 20295-20295/com.mobilegovernment W/Resources: Converting to string: TypedValue{t=0x10/d=0x3e8 a=-1}
09-29 08:41:48.295 20295-20355/com.mobilegovernment W/EGL_emulation: eglSurfaceAttrib not implemented
09-29 08:41:48.295 20295-20355/com.mobilegovernment W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xdf7927e0, error=EGL_SUCCESS
09-29 08:41:54.394 20295-20355/com.mobilegovernment W/EGL_emulation: eglSurfaceAttrib not implemented
09-29 08:41:54.394 20295-20355/com.mobilegovernment W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xda03b1a0, error=EGL_SUCCESS
09-29 08:41:54.438 20295-20449/com.mobilegovernment I/ReactNativeJS: ++++++++++++++++++apk?+++++++++++++++++++++
09-29 08:41:54.438 20295-20449/com.mobilegovernment I/ReactNativeJS: null
09-29 08:41:54.438 20295-20449/com.mobilegovernment I/ReactNativeJS: { install: [Function: install],
                                                                       isPending: false,
                                                                       bundlePath: '/CodePush/index.android.bundle',
                                                                       packageSize: 1036202,
                                                                       binaryModifiedTime: '1506679752937',
                                                                       packageHash: '4ee8dcdb60a806d16d3801f7c2e16c8ae5c2fc7d68e2ae307bf365a3f955555d',
                                                                       isMandatory: true,
                                                                       appVersion: '1.0.1',
                                                                       label: 'v30',
                                                                       downloadUrl: 'http://180.76.138.89:3000/download/fi/FihrYN2ZgTzWU7pj-0SQQDDuFqnj',
                                                                       description: '1.主题色',
                                                                       failedInstall: false,
                                                                       _isDebugOnly: true,
                                                                       deploymentKey: 'pxUUzmm3Ci7Wnmh9NOSYwd4m1zWE4ksvOXqog',
                                                                       isFirstRun: false }
09-29 08:41:54.476 20295-20355/com.mobilegovernment W/EGL_emulation: eglSurfaceAttrib not implemented
09-29 08:41:54.476 20295-20355/com.mobilegovernment W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xda03b180, error=EGL_SUCCESS
09-29 08:41:54.496 20295-21109/com.mobilegovernment W/unknown:InspectorPackagerConnection: Couldn't connect to packager, will silently retry
09-29 08:41:54.507 20295-20355/com.mobilegovernment W/EGL_emulation: eglSurfaceAttrib not implemented
09-29 08:41:54.507 20295-20355/com.mobilegovernment W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xeed44280, error=EGL_SUCCESS
09-29 08:41:54.636 20295-20355/com.mobilegovernment W/EGL_emulation: eglSurfaceAttrib not implemented
09-29 08:41:54.636 20295-20355/com.mobilegovernment W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xdf7927e0, error=EGL_SUCCESS

```

**Comment by sergey-akhalkov** [comment] 2017-10-04 09:50
Hi @TrustTheBoy, I've configured for you the demo app that will demonstrate you how binary version mismatch feature works: please see the source code of the app  [rncp1023 copy.zip](https://github.com/Microsoft/react-native-code-push/files/1355297/rncp1023.copy.zip)
Preconditions: 
1. App has version 1.0.0
2. Binary version mismatch has been configured in `demo.js` file
3. An CodePush update has been released that targets to 1.0.1 binary version

I'm closing the issue for now, please feel free to ask questions regarding the demo I have provided.

**Closed by sergey-akhalkov** 2017-10-04 09:50 UTC
Labels: documentation

**Comment by akki-ng** [comment] 2017-10-04 18:06
@sergey-akhalkov Thanks for taking time out to build demo. I appreciate your efforts. Thanks!

**Comment by sergey-akhalkov** [comment] 2017-10-05 06:48
@akki-ng, no problem!
