### ISSUE TITLE
Code push detecting updates at first app install even there's no release

### ISSUE THREAD

**Issue by mamoussa405** [microsoft/react-native-code-push#2728] opened 2024-07-12 19:09 UTC
Hello, I have encountered an issue after adding CodePush to my React Native app. CodePush detects updates after the first app installation, even though I haven't made any new releases. I compared the bundle in CodePush with the one in my APK and found no differences. What could be causing this problem?

### Steps to Reproduce
1. Push a release to CodePush for a specific environment.
2. Build an APK for the same environment.
3. Run the app

### Expected Behavior
CodePush should not detect any updates.

### Actual Behavior
CodePush detects new updates.

### Environment

* react-native-code-push version: 8.3.0
* react-native version: 0.72.3
* Does this reproduce on a debug build or release build? Both
* Does this reproduce on a simulator, or only on a physical device? Both

**Comment by DordeDimitrijev** [comment] 2024-07-16 14:24
Hello @mamoussa405 thank you for reaching out. Bascially the scenario you mentioned is not an issue but rather the design of the codepush sdk. When you run your app after the fresh install  the application itself just has knowledge that the update it fetched was never applied and thus it applies it even tough the changes might be the same. Please let me know if this helps out or if you have any addtional questions.

**Comment by mamoussa405** [comment] 2024-07-19 13:17
Thank you so much for responding Sir, is there any fix for that, i dont't want the users to get that there's updates at first install, thanks in advance.

**Comment by DordeDimitrijev** [comment] 2024-07-22 10:54
I think this approach might do the trick for you. In app/build.gradle try to bump versionName. If you had versionName from codepush set to 1.0 try using in your local build 1.1. or 2.0 for versionName.

**Comment by mamoussa405** [comment] 2024-07-30 22:50
Do you mean that the app version should not match the exact version in codepush, it just needs to be in the target range?

**Comment by DordeDimitrijev** [comment] 2024-07-31 09:11
build.gradle version must match binary tag version your provide  otherwise it won't recognize the update. If you for example have update for binaryVersion 1.0 and you locally increment your build.gradle version to 1.1 it won't pickup those updates. If you wish to get updates also for that version you need to specify it when creating release. This is the only way since by design codepush will pickup any update that wasn't applied for specific version even if it has the same contents as in your scenario.

**Comment by mamoussa405** [comment] 2024-07-31 15:11
okay noted, thank you so much Sir.

**Comment by DordeDimitrijev** [comment] 2024-08-12 08:56
Closing, as  code-push is working according to design

**Closed by DordeDimitrijev** 2024-08-12 08:56 UTC

**Comment by Kawaljeet-AUI** [comment] 2024-10-11 05:50
@DordeDimitrijev - In my case, I have a release `1.4.0` released to the iOS App store. I started doing mandatory code pushes to this build with the target `-t 1.4.0`. Here is my command:
```
appcenter codepush release-react -a <my-appcenter> -d Production --plist-file 'ios/Info.plist' --xcode-project-file 'ios/Mobile.xcodeproj/project.pbxproj' -t 1.4.0
```

(Specified the path to .plist file and .pbxproj file as it is a mono repo)

I have made a code push to this version. The build hosted is `1.4.0` and the updates are being sent to the same version. Works well for existing users.

Now, when a new user downloads the app, they see the mandatory dialog to update the build immediately. Ideally, the build should somehow download the latest code push updates as well. Here are my code push config options:

```
const codePushOptions = {
  checkFrequency: codePush.CheckFrequency.ON_APP_RESUME,
  updateDialog: true,
  installMode: codePush.InstallMode.IMMEDIATE,
};
```
Am I missing something here? What should be done for the user to NOT SEE the code push mandatory update and that the code gets installed with the latest version automatically?

**Comment by DordeDimitrijev** [comment] 2024-10-11 11:57
Hello @Kawaljeet-AUI thank you for reaching out! Since you'd like to remove the default dialog for mandatory updates you need remove updateDialog prop so the default dialog is not shown. If you still need dialog for some cases you can use checkForUpdate function and from it extract information about the update and based on that call sync function with or without displaying the dialog. It would look something like this.

```
const update = await codePush.checkForUpdate()
await codePush.sync({ updateDialog: update.isMandatory, installMode: codePush.InstallMode.IMMEDIATE });
```
Feel free to check out the docs for the [api reference](https://learn.microsoft.com/en-us/appcenter/distribution/codepush/rn-api-ref#javascript-api-reference)
