### ISSUE TITLE
reload the app don't load local main.jsbundle

### ISSUE THREAD

**Issue by lhuazai** [Microsoft/react-native-code-push#1379] opened 2018-08-14 09:24 UTC
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):
![image](https://user-images.githubusercontent.com/10182945/44083311-3442f988-9fe6-11e8-8f48-6be864d15914.png)
 I can upload this bundle and the app can show the updateDialog ,but app don't load the new bundle,please give me some tips! thanks.
### Steps to Reproduce
1. bundle-ios in ./ios/main.jsbundle
2. code-push release  myapp ./ios/main.jsbundle 2.1.0  --mandatory true
3.reload this app ,but app don't load the new bundle

### Expected Behavior
What you expected to happen?

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version:
* react-native version:
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by NickToropov** [comment] 2018-08-14 10:06
Hi @lhuazai. If I understand you correctly your app shows update dialog, you tap "Install" button, downloading process is reported, app restarts but after that your new updates are not applied and you see the previous version of app?
If yes, then the most likely cause of the problem is an error that occurs  when new bundle is loaded.
Please share logs from XCode or any other tracking system(if you use them). Also it would be great if you could provide us with a demo app that reproduces your issue.

**Comment by lhuazai** [comment] 2018-08-14 11:47
Hi @NickToropov  I use xcode to bundle ios select follow scheme
![image](https://user-images.githubusercontent.com/10182945/44086109-1f9eaf4c-9fee-11e8-84c0-86ab83b0f030.png)
and I this is my load jsCodeLocation function
![image](https://user-images.githubusercontent.com/10182945/44086226-783c0280-9fee-11e8-8d9b-9676fee11948.png)

**Comment by NickToropov** [comment] 2018-08-14 12:37
Do you observe any errors in XCode logs window?

**Comment by NickToropov** [comment] 2018-08-14 12:42
also I think you should use something similar to
```
#ifdef DEBUG
     jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
     jsCodeLocation = [CodePush bundleURL];
#endif
```
Please read [this section](https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-ios.md#plugin-configuration-ios).

Please let me know if it was helpful.

**Comment by NickToropov** [comment] 2018-08-20 13:12
Hi @lhuazai!
We haven’t heard from you in a while, so I am going to go ahead and close this issue. If you still have any questions, you can reopen this issue; or if you prefer you can create a new one.

**Closed by NickToropov** 2018-08-20 13:12 UTC
Labels: iOS, waiting-for-clarification

**Comment by tusharpandey** [comment] 2020-02-23 10:37
I am facing this issue , any solution team?
