### ISSUE TITLE
Update not working / Unable to get the hash of the binary's bundled resources

### ISSUE THREAD

**Issue by thomasngataly** [microsoft/react-native-code-push#1754] opened 2020-01-07 20:48 UTC
Hello,
I tried to update my app with codepush several times but no updates are found when i restart the app.

### Steps to Reproduce
1. Install the library for RN > 0.60
2. Push an update with codepush release-react Production
3. Restart the app

### Expected Behavior
The app should be updated

### Actual Behavior
Nothing happens, when i fetch the log with adb i see that No update is found and the app is up to date (even though i have several pending updates).
```
[09:47:10] Checking for update.
[09:47:11] App is up to date.
```
When i fetch the log of the play store released app i have the following notice : 
```[CodePush] Unable to get the hash of the binary's bundled resources - "codepush.gradle" may have not been added to the build definition.```

### Environment

* react-native-code-push version: 6.0.0
* react-native version: 0.60.4
* iOS/Android/Windows version: Android 10
* Does this reproduce on a debug build or release build? Release build
* Does this reproduce on a simulator, or only on a physical device? Physical device

Any help ? Thanks

**Comment by lironsher** [comment] 2020-01-15 11:37
any news? 
I have similar issue, some of the devices are geting the update and some not.

**Comment by franzwarning** [comment] 2020-02-06 18:32
Getting this as well -- .61.5

**Comment by alexandergoncharov** [comment] 2020-02-11 10:01
Hi @thomasngataly, @lironsher, @franzwarning,

Unofrtunately, I can't reproduce this issue. Could you pelase provide more detailed reprosteps or test project?
Also, please ensure that you have done all setup steps: https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-android.md#plugin-installation-and-configuration-for-react-native-060-version-and-above-android

Please let me know if it was helpful or you have any questions.

**Comment by alexandergoncharov** [comment] 2020-02-13 09:49
I'm going to close this issue for now. Please feel free to reopen it if you have any questions or provide more details.

**Closed by alexandergoncharov** 2020-02-13 09:49 UTC
Labels: android, bug, waiting-for-clarification

**Comment by alemkhodadadi** [comment] 2020-03-09 20:35
I spend whole day but not found what's the problem. any resolve??

**Comment by SeveHo** [comment] 2020-11-13 21:08
@thomasgataly how did you resolve this issue?

**Comment by yaronlevi** [comment] 2020-12-07 12:42
Also seeing this... anyone got a direction for the root cause?

**Comment by thiagobucca** [comment] 2020-12-08 01:29
i have this problem as well, couldn't find the root cause but got the same message with logcat on my app. All my Android builds generated by appcenter are now crashing on launch.

**Comment by hungtrn75** [comment] 2021-03-22 03:13
[pull request](https://github.com/microsoft/react-native-code-push/pull/2023/commits/d0a06bfbee9405e5628c52b11251e2bb2f2f6c02)
I followed this and it worked
