### ISSUE TITLE
Build not installed on Android even though downloaded

### ISSUE THREAD

**Issue by bonnmh** [microsoft/react-native-code-push#2576] opened 2023-08-29 08:23 UTC
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
Below is the output I got from Logcat
D  [CodePush] Loading JS bundle from "assets://index.android.bundle"
D  [CodePush] Unable to get the hash of the binary's bundled resources - "codepush.gradle" may have not been added to the build definition.
I  [CodePush] Reporting binary update (2.1.33)
D  [CodePush] Re-allowing restarts
D  [CodePush] Applying full update.

### Expected Behavior
What you expected to happen?
I noticed an increase in downloads but the new code wasn't applied and the installs didn't change on the console, even though I restarted my app several times

### Actual Behavior
What actually happens?
<img width="414" alt="image" src="https://github.com/microsoft/react-native-code-push/assets/48821705/50707f59-a91e-45ad-825c-4914382e0eba">

App.jsx
```
let codePushOptions = {
  checkFrequency: CodePush.CheckFrequency.MANUAL,
  installMode: CodePush.InstallMode.ON_NEXT_RESTART,
  mandatoryInstallMode: CodePush.InstallMode.ON_NEXT_RESTART
};

export const App = __DEV__ ? _App : CodePush(codePushOptions)(_App);
```

And use
```
 const codePushDownloadDidProgress = async (progressNum: DownloadProgress, dataUpdate: RemotePackage | null) => {
        let currProgress = Math.round((progressNum.receivedBytes / progressNum.totalBytes) * 100) / 100;
        if (currProgress >= 1) {
            CodePush.allowRestart();
            await CodePush.notifyAppReady();
        }
    };

    const _handleUpdateApp = async () => {
        if (__DEV__) {
            return;
        }
        try {
            const update = await CodePush.checkForUpdate();
            if (update) {
                showSuccessToast({description: t('common:updating')});
                CodePush.sync(
                    {
                        deploymentKey: CODE_PUSH_DEV_KEY_FINAL,
                        updateDialog: undefined,
                        installMode: CodePush.InstallMode.ON_NEXT_RESTART,
                        mandatoryInstallMode: CodePush.InstallMode.ON_NEXT_RESTART,
                        rollbackRetryOptions: {
                            delayInHours: 1,
                            maxRetryAttempts: 3
                        }
                    },
                    status => codePushStatusDidChange(status),
                    (_value) => codePushDownloadDidProgress(_value, update)
                );
            }
        } catch (error) { }
    };
```

### Environment

* react-native-code-push version: ^8.1.0
* react-native version: 0.72.3
* Android version: any
* Does this reproduce on a debug build or release build? Yes
* Does this reproduce on a simulator, or only on a physical device? Yes

(The more info the faster we will be able to address it!)

**Comment by chenweigh** [comment] 2023-09-04 11:03
hi, did you encounter this error, on android

```
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class net.jcip.annotations.GuardedBy found in modules jetified-jcip-annotations-1.0 (net.jcip:jcip-annotations:1.0) and jetified-jcip-annotations-1.0-1 (com.github.stephenc.jcip:jcip-annotations:1.0-1)
     Duplicate class net.jcip.annotations.Immutable found in modules jetified-jcip-annotations-1.0 (net.jcip:jcip-annotations:1.0) and jetified-jcip-annotations-1.0-1 (com.github.stephenc.jcip:jcip-annotations:1.0-1)
     Duplicate class net.jcip.annotations.NotThreadSafe found in modules jetified-jcip-annotations-1.0 (net.jcip:jcip-annotations:1.0) and jetified-jcip-annotations-1.0-1 (com.github.stephenc.jcip:jcip-annotations:1.0-1)
     Duplicate class net.jcip.annotations.ThreadSafe found in modules jetified-jcip-annotations-1.0 (net.jcip:jcip-annotations:1.0) and jetified-jcip-annotations-1.0-1 (com.github.stephenc.jcip:jcip-annotations:1.0-1)

* Try:
```

**Comment by mohitarora777** [comment] 2023-09-15 09:53
same issue

**Comment by DmitriyKirakosyan** [comment] 2023-09-26 06:38
I will mark this as a duplicate of https://github.com/microsoft/react-native-code-push/issues/838.
Please take a moment to review the conversation in the original issue. If none of the proposed solutions address your concern, kindly leave a comment in #838. We can continue the discussion there and potentially reopen the issue if necessary.

**Closed by DmitriyKirakosyan** 2023-09-26 06:38 UTC
