### ISSUE TITLE
not work on react-native 0.72.4 for Android

### ISSUE THREAD

**Issue by fantasyado** [microsoft/react-native-code-push#2590] opened 2023-09-25 08:38 UTC
### Steps to Reproduce
1. build Android app
2. publish an update with codepush
3. open the android app and wait a minute then reopen App.

### Expected Behavior
Android app can update via OTA

### Actual Behavior
What actually happens?

  Android app can NOT update via OTA, but works well on iOS side 
```

  [CodePush] Loading JS bundle from "assets://index.android.bundle"
  [CodePush] Unable to get the hash of the binary's bundled resources - "codepush.gradle" may have not been added to the build definition  
```

### Reproducible Demo

no

### Environment

* react-native-code-push version: 8.1.0
* react-native version: 0.72.4
* iOS/Android/Windows version: Android 12.0
* Does this reproduce on a debug build or release build? Release
* Does this reproduce on a simulator, or only on a physical device? Both

(The more info the faster we will be able to address it!)

pid-3638                             D  [CodePush] Loading JS bundle from "assets://index.android.bundle"
2023-09-25 16:29:55.523  3638-3672  ReactNative             pid-3638                             D  [CodePush] Unable to get the hash of the binary's bundled resources - "codepush.gradle" may have not been added to the build definition.

**Comment by DmitriyKirakosyan** [comment] 2023-09-26 06:37
@fantasyado , thank you for reaching out! I will mark this as a duplicate of https://github.com/microsoft/react-native-code-push/issues/838.
Please take a moment to review the conversation in the original issue. If none of the proposed solutions address your concern, kindly leave a comment in #838. We can continue the discussion there and potentially reopen the issue if necessary.

**Closed by DmitriyKirakosyan** 2023-09-26 06:37 UTC
