### ISSUE TITLE
Android: no update available for releaseStaging build

### ISSUE THREAD

**Issue by Colmea** [Microsoft/react-native-code-push#758] opened 2017-03-15 11:09 UTC
### Description

Hello,

I try to use code-push for my app, but despite all my updates in the Staging, the app won't update (debug says the app is up to date). I tried everything.

### Reproduction

What I did:
- Checked my deployment key and android version:

build.gradle: 
```
defaultConfig {
        applicationId "com.XXXXX"
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 4
        versionName "1.0.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }

releaseStaging {
            signingConfig signingConfigs.release

            buildConfigField "String", "CODEPUSH_KEY", '"XXX_O3R38JXXXXXXXX-SwNXXXXqMz"'
        }
```

- Release a staging/production (and mandatory) update for all binary versions.

Command used: `code-push release-react Hewy-Android android --m --targetBinaryVersion "*"`
![image](https://cloud.githubusercontent.com/assets/974918/23945184/d7cfe736-0975-11e7-8a71-18321ceb7976.png)

- Add the sync command in my App component:
```
componentDidMount() {
        codePush.sync({
            updateDialog: true,
            installMode: codePush.InstallMode.IMMEDIATE
        });
    }
```

- Build the releaseStaging version and run it on my phone: 
`react-native run-android --configuration=releaseStaging`

- Result: my app is always up to date. What's wrong with my config ?

### Additional Information

* react-native-code-push version: 1.17.2-beta
* react-native version: 0.40.0
* iOS/Android/Windows version: 6.0
* Does this reproduce on a debug build or release build? releaseStaging build
* Does this reproduce on a simulator, or only on a physical device? Tested on a physical device.

**Comment by max-mironov** [comment] 2017-03-16 14:47
Hello @Colmea - that looks very interesting!
I've tried to reproduce the issue on my own and add `releaseStaging` to my build gradle and build it with `react-native run-android --variant=releaseStaging` and it works. 
How do you see message 

> app is up to date?

Can you provide us with output for both `code-push debug android` and `adb logcat` commands?
E.g. mine said: 

>  Loading JS bundle from "assets://index.android.bundle"
[07:32:52] Checking for update.
[07:32:52] Reporting binary update (1.0)
[07:32:54] Downloading package.
[07:32:55] Installing update.
[07:32:55] Update is installed and will be run when the app next resumes.

Also on your screenshot seems that you are showing history for Production deployment whereas releaseStaging should be for Staging one?

**Comment by Colmea** [comment] 2017-03-17 08:40
Hi @max-mironov ,

Thanks for your quick reply.

Regarding the screenshot with deployment history. My bad, the screenshot is cropped, but the first table is actually the Staging deployments.

> app is up to date
Comes from the code-push debug android:
```
[09:18:02] Checking for update.
[09:18:02] Reporting binary update (0.3.0)
[09:18:02] App is up to date.
[09:18:02] Checking for update.
[09:18:02] App is up to date.

```

Questions:
- I saw you use `--variant=releaseStaging`. I got an error when running this instead of "--configuration=releaseStaging": `Task 'installReleaseStagingDebug' not found in root project XXX`.
Should I really use --variant option ? Or --configuration works too ?

- Should I see a download when first running my staging app ? Or only when I update it and it's already installed with a previous version.

**Comment by max-mironov** [comment] 2017-03-17 11:47
@Colmea 

As for your question regarding usage of `configuration` instead of `variant` - I believe it depends upon react-native version you are running for, please see similar SO question [here](http://stackoverflow.com/a/42288238).

You will have 

>[07:32:54] Downloading package.

message only when you actually download package or you mean that you will see download progress bar when downloading?

Btw your logs said that you are actually running version 0.3.0, have you tried to run new binary version and see if it helps?

Anyway if you don't mind can we add some logging to see what deployment key you are actually running against your app. Could you please go to node_modules -> react-natve-code-push -> CodePush.js file and add `log(config.deploymentKey);` at line 31 right after this one:
 `const config = deploymentKey ? { ...nativeConfig, ...{ deploymentKey } } : nativeConfig;` .
So then remove the app from device, rebuild it deploy again and run `code-push debug android`.
Please let us know hte results and if you see the same deployment key as specified with build.gradle here.

**Comment by Colmea** [comment] 2017-03-17 13:47
Hoow, ok. Found it !

The deployment key is, indeed, not the good one. Actually, I've har corder the deployment key:

MainApplication.java:
```
protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new CodePush(getResources().getString(R.string.reactNativeCodePush_androidDeploymentKey), getApplicationContext(), BuildConfig.DEBUG), 
```

And in my strings:xml:
`    <string moduleConfig="true" name="reactNativeCodePush_androidDeploymentKey"> XXXXXJz1LSztANsCsNXXXX1xeXXX </string>`


The question is: how can I dynamically give the Staging or Production deployment key in MainApplication.java following the build type ?

So, instead of:
` new CodePush('deployment-key-here', getApplicationContext(), BuildConfig.DEBUG), `

We could have something like:
` new CodePush(buildTypes.CODEPUSH_KEY), getApplicationContext(), BuildConfig.DEBUG), `

Is this possible ? If no, what's the solution to have a dynamic deployment key in MainApplication.java ?

**Comment by max-mironov** [comment] 2017-03-17 14:18
@Colmea - thanks for quick turn around!

Yeah, that should be possible, at least looks like I was able to do this initially when trying to reproduce the issue. May be you can share the minimum example of your app so I can try it on my environment to see if it works?

**Comment by max-mironov** [comment] 2017-03-23 05:32
@Colmea - hi, could you please look at this and let us know if we can help you here.

**Comment by Colmea** [comment] 2017-03-23 09:41
HI @max-mironov 
I guess you can close this issue since I resolved my "bug".

I still don't know how to dynamically add my codepush key in MainApplication.java and why we need this if we have the keys in build.gradle, but it's not related to this issue.

Thank you very much for your help !

**Comment by sergey-akhalkov** [comment] 2017-03-23 10:03
@Colmea, got it, closing this for now.

>I still don't know how to dynamically add my codepush key in MainApplication.java and why we need this if we have the keys in build.gradle, but it's not related to this issue.

Please look at https://github.com/Microsoft/react-native-code-push#android
Using this approach you just need to specify build type you what to use, so `BuildConfig.CODEPUSH_KEY` property will contain appropriate deployment key value.

**Closed by sergey-akhalkov** 2017-03-23 10:03 UTC
Labels: waiting-for-clarification
