### ISSUE TITLE
New deployment is not applied.

### ISSUE THREAD

**Issue by ohjeyong** [Microsoft/react-native-code-push#1566] opened 2019-04-22 10:54 UTC
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Deploy new bundle
2. Call codePush.checkUpdate()
3.Check downloadUrl

### Expected Behavior
What you expected to happen?
Update successful or downloadUrl works fine.

### Actual Behavior
What actually happens?
Update is not applied even though chcekUpdate returns new bundle label and download url. Also, that downloadUrl is not working too.

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version: 5.6.0
* react-native version: 0.59.5
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build? release build
* Does this reproduce on a simulator, or only on a physical device? physical device

(The more info the faster we will be able to address it!)

I have used this package in last 6 month. It works perfectly fine. However, today, while I'm working on minor javascript update to my app, I found that the new deployment bundle is not applied. I tried to deploy it as mandatory, but still update is not applied. I confirmed that new bundle is uploaded successfully in appcenter.
I call codePush.checkUpdate() then it returns new bundle label. However, new bundle downloadUrl is not working. If I copy and paste downloadUrl in browser, 404 returns like below image.
![Screenshot from 2019-04-22 19-51-28](https://user-images.githubusercontent.com/11625617/56497351-1ec03e00-6538-11e9-8185-9d9621f2ebd1.png)
I think azure cdn is broken. Can you check?

**Comment by ohjeyong** [comment] 2019-04-22 11:07
After 30minutes, downloadUrl works fine but app update is still not applied.

**Comment by ohjeyong** [comment] 2019-04-22 11:08
Now, downloadUrl is not working again. I think azure cdn is not stable now.

**Comment by DeerDevelop** [comment] 2019-04-22 11:11
same issue.

**Comment by yuri-kulikov** [comment] 2019-04-22 12:24
Hey @ohjeyong, @DeerDevelop 
Thanks for reporting!

Could you please clarify what kind of URL you can't access?

**Comment by leedan77** [comment] 2019-04-22 12:48
Same issue.
Hi @yuri-kulikov,
```https://codepushupdates.azureedge.net/storagev2/[blob_url]``` can't be accessed.
The other one is fine.

**Comment by ohjeyong** [comment] 2019-04-22 13:01
Hi, @yuri-kulikov
Same as @leedan77.

I can download bundle file via appcenter website download bundle button(this button is linked with https://codepush.blob.core...

But not working on https://codepushupdates.azureedge... which is the downloadUrl from codePush.checkUpdate().

**Comment by yuri-kulikov** [comment] 2019-04-22 16:21
We're still investigating. Please keep us informed if the problem is solved.

**Comment by ohjeyong** [comment] 2019-04-23 01:41
This morning I have retried and it has been solved without doing anything. I think it is temporary network issue or azure cdn issue.

**Comment by yuri-kulikov** [comment] 2019-04-29 14:54
Since the problem is solved I think we can close the issue for now. But we will continue to monitor this. Please feel free to reopen the issue or create another one if needed.

**Closed by yuri-kulikov** 2019-04-29 14:54 UTC
