### ISSUE TITLE
codepush.gradle breaks incremental build

### ISSUE THREAD

**Issue by iain-merrick-fanduel** [Microsoft/react-native-code-push#1384] opened 2018-08-20 14:56 UTC
### Steps to Reproduce
1. Build Android project with Gradle
2. Without changing any code, build project again

### Expected Behavior
As no files have changed, I expect the build to be a no-op (no tasks should be executed)

### Actual Behavior
Several build tasks are executed.

Starting with the generated example program, and filtering out the up-to-date tasks, I get:

```
$ ./gradlew :app:assembleDebug | grep -v UP-TO-DATE
:app:preBuild
:react-native-code-push:preBuild
:app:preDebugBuild
:react-native-code-push:preReleaseBuild
:app:checkDebugManifest
:react-native-code-push:checkReleaseManifest
:app:generateDebugBuildConfig
:react-native-code-push:prepareComAndroidSupportAppcompatV72301Library
:app:generateDebugResValues
:app:compileDebugShaders
:react-native-code-push:prepareComAndroidSupportSupportV42301Library
:app:processDebugJavaRes
:react-native-code-push:prepareComFacebookFbuiTextlayoutbuilderTextlayoutbuilder100Library
:app:validateSigningDebug
:react-native-code-push:prepareReleaseDependencies
:app:prepareDebugDependencies
:app:generateDebugResources
:app:mergeDebugResources
:app:processDebugResources
:app:generateDebugSources
:app:packageDebug
:app:assembleDebug

BUILD SUCCESSFUL

Total time: 1.837 secs
```

It looks like CODE_PUSH_APK_BUILD_TIME is being calculated from the current system clock and embedded in a resource. Because that resource value is different every time, Gradle regenerates the resource files and rebuilds the APK every time.

Tracing through the source control history, CODE_PUSH_APK_BUILD_TIME looks to have been added to work around an intentional Android plugin change, which avoided embedding timestamps in order to make incremental builds work properly: https://issuetracker.google.com/issues/37116029

Why is the timestamp needed? Would it be possible to use a hash of the input files instead?

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app.

Reproduces as described above on generated example app.

### Environment

* react-native-code-push version: 5.4.1
* react-native version: 0.56.0
* iOS/Android/Windows version: Gradle 3.5.1
* Does this reproduce on a debug build or release build? Both
* Does this reproduce on a simulator, or only on a physical device? N/A

**Comment by alexandergoncharov** [comment] 2018-08-22 16:39
Hi @iain-merrick-fanduel ,
Thanks for reporting!

We will investigate this issue a bit later. It is in queue.  Sorry for this delay.

Thanks,
Alexander

**Comment by yuri-kulikov** [comment] 2018-09-05 13:36
Hello, @iain-merrick-fanduel,
I've done some investigation about this **```CODE_PUSH_APK_BUILD_TIME```**.
I've found that it is used to decide whether the application should use a **code-push bundle** or the **"binary bundle"** from the fresh build. 
Every bundle downloaded by code-push receives a property to associate this bundle with the current application build, so if you rebuild the application it wouldn't use the old **code-push bundle** and takes the fresher **bundle from the build**. [[Code]](https://github.com/Microsoft/react-native-code-push/blob/82b3336adb0a0bc2168b81d91499b13df7ad585c/android/app/src/main/java/com/microsoft/codepush/react/CodePush.java#L226)
So that's why this timestamp needed.
But if we only use the bundles hash then we can't determine which bundle to use: the one from CodePush server or the bundle embedded in apk.

**Comment by iain-merrick-fanduel** [comment] 2018-09-05 14:20
Would it be possible to use the timestamp of the most recent commit, maybe? That way it won't change arbitrarily across rebuilds, but it would still do the right thing in e.g. Jenkins builds.

**Comment by NickToropov** [comment] 2018-09-05 14:40
Hi @iain-merrick-fanduel yes, it's possible but it's also possible that some users don't use any VCS, so they'll have to support some kind of "recent commit" or "timestamp" manually. That's why plugin logic shouldn't be depend on VCS.

**Comment by NickToropov** [comment] 2018-09-06 09:12
@iain-merrick-fanduel, do you have any other questions?

**Comment by iain-merrick-fanduel** [comment] 2018-09-06 09:15
Well, no, but it would still be good to find a solution that works correctly with incremental builds. This is important for reproducible (hermetic) builds too.

**Comment by NickToropov** [comment] 2018-09-06 12:26
Yes, thanks for suggestion! But currently we have no appropriate solution for the issue. May be later changes will allow to improve this behavior. We'll keep that in mind!

Will close this issue as it seems to be answered, feel free to reach us if you need any help with code-push.
Thanks for using CodePush!

**Closed by NickToropov** 2018-09-06 12:26 UTC
Labels: question

**Comment by iain-merrick-fanduel** [comment] 2018-09-07 15:19
Hi Nick, here's another suggestion:
- have a build task that calculates a hash of the files
- store the hash in a file
- use the timestamp of that file

This solves the incremental build case because nothing changes (including the timestamp) if there are no code changes. But if the code does change, the timestamp will always increase.

**Comment by abdullahizzuddiin** [comment] 2020-01-02 06:58
Hello, 
Has this problem resolved?

I faced the same problem, incremental build broke caused by `CODE_PUSH_APK_BUILD_TIME` changed every build.

![image](https://user-images.githubusercontent.com/6801853/71655020-766da500-2d67-11ea-8f99-7e22ad769816.png)

![image](https://user-images.githubusercontent.com/6801853/71655106-f267ed00-2d67-11ea-9ee3-2e11947e0d96.png)
