### ISSUE TITLE
New Architecture (Bridgeless) support?

### ISSUE THREAD

**Issue by FightFarewellFearless** [microsoft/react-native-code-push#2742] opened 2024-08-27 12:46 UTC
Any plan to support New Architecture?

**Comment by DmitriyKirakosyan** [comment] 2024-08-28 11:30
Duplicate of https://github.com/microsoft/react-native-code-push/issues/2696 - we are not going to support new architecture.

**Closed by DmitriyKirakosyan** 2024-08-28 11:30 UTC

**Comment by DordeDimitrijev** [comment] 2024-12-03 11:41
RNCP won't support NA please check https://github.com/microsoft/react-native-code-push/issues/2774#issuecomment-2507636494 for reference.

**Comment by DordeDimitrijev** [comment] 2024-12-11 22:53
@esbenvb  You can try the approach mentioned in this comment to use the new architecture https://github.com/microsoft/react-native-code-push/issues/2781#issuecomment-2519480160
