### ISSUE TITLE
Android dependencies resolve quite slow

### ISSUE THREAD

**Issue by seanadkinson** [Microsoft/react-native-code-push#1080] opened 2017-11-14 16:11 UTC
Anything that tries to resolve dependencies from `react-native-code-push` is going really slowly.  See screenshot below of a simple `clean`

### Expected Behavior
What you expected to happen?
Resolution should be as fast as other modules

### Actual Behavior
What actually happens?
![2017-11-14_0756](https://user-images.githubusercontent.com/1429507/32790321-fb481884-c912-11e7-8c5b-bd732e9ad2d7.png)

### Environment

* react-native-code-push version: 5.1.3-beta
* react-native version: 0.49.5
* iOS/Android/Windows version: High Sierra, Android Studio 3, gradle 3.3

**Comment by max-mironov** [comment] 2017-11-20 13:49
Hey @seanadkinson, do you still experience the issue on your side? 
Is it the 1st time you are using react native code push or it was working well previously?

I've tried on my newly created app (High Sierra, Android Studio 3) and got the following output on clean:
```
20Nov17
16:45	Executing tasks: [clean, :app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies]

16:45	Gradle build finished in 7s 271ms

```

**Comment by seanadkinson** [comment] 2017-11-21 20:29
@max-mironov It didn't use to perform this slowly (at least I never noticed it).  We've been using code-push for months, and it hasn't been an issue.  Possibly related to upgrading to High Sierra, since I did that about the time this issue appeared..  What's odd, of course, is that all the other libraries resolve quickly.  I'll try doing some more testing on my end, and ket you know if I find anything.  Thanks

**Comment by max-mironov** [comment] 2017-11-22 07:56
@seanadkinson - please let us know what you'll find out finally.

Also probably you can take a look at similar issue on SO - https://stackoverflow.com/questions/40227064/gradle-builds-are-very-slow-after-upgrading-to-mac-os-sierra, not sure if related but you can check it out anyway.

**Comment by max-mironov** [comment] 2017-11-24 09:02
@seanadkinson I'd rather close the issue in the meantime as it does't seems to be something that affects all users and more likely specific to your environment. 
But we are good to help you investigate and collaborate more if needed and if the issue still persists - just let us know when you get a chance to revisit it and if you need any help!

**Closed by max-mironov** 2017-11-24 09:02 UTC
Labels: android, waiting-for-clarification

**Comment by seanadkinson** [comment] 2017-11-25 00:00
Thanks @max-mironov, looks like that SO answer you provided did the trick!  Weird that it only affected `react-native-code-push`.  I appreciate your help.

**Comment by max-mironov** [comment] 2017-11-26 17:43
Thanks for response @seanadkinson, good to know that the issue is fixed!
