### ISSUE TITLE
Development/debug build crashes on android after downloading update

### ISSUE THREAD

**Issue by ujwal-setlur** [Microsoft/react-native-code-push#1272] opened 2018-05-03 23:15 UTC
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Build android development version of react-native app with code-push enabled.
2. Load on android emulator or phone
3. App loads and says there is an update.
4. After update is downloaded, app crashes.

### Expected Behavior
New bundle should run

### Actual Behavior
New bundle crashes, and code-push reverts to existing bundle.
```
05-03 23:06:08.639  4208  4251 I ReactNativeJS: Downloading package.
05-03 23:06:09.285  4208  4251 I ReactNativeJS: 65100 of 4928365 received.
05-03 23:06:09.325  4208  4251 I ReactNativeJS: 171596 of 4928365 received.
05-03 23:06:09.374  4208  4251 I ReactNativeJS: 343628 of 4928365 received.
05-03 23:06:09.416  4208  4251 I ReactNativeJS: 417356 of 4928365 received.
05-03 23:06:09.460  4208  4251 I ReactNativeJS: 548428 of 4928365 received.
05-03 23:06:09.505  4208  4251 I ReactNativeJS: 663116 of 4928365 received.
05-03 23:06:09.550  4208  4251 I ReactNativeJS: 785996 of 4928365 received.
05-03 23:06:09.596  4208  4251 I ReactNativeJS: 917068 of 4928365 received.
05-03 23:06:09.638  4208  4251 I ReactNativeJS: 1015372 of 4928365 received.
05-03 23:06:09.683  4208  4251 I ReactNativeJS: 1171020 of 4928365 received.
05-03 23:06:09.726  4208  4251 I ReactNativeJS: 1310284 of 4928365 received.
05-03 23:06:09.770  4208  4251 I ReactNativeJS: 1482316 of 4928365 received.
05-03 23:06:09.816  4208  4251 I ReactNativeJS: 1629772 of 4928365 received.
05-03 23:06:09.860  4208  4251 I ReactNativeJS: 1777228 of 4928365 received.
05-03 23:06:09.904  4208  4251 I ReactNativeJS: 1932876 of 4928365 received.
05-03 23:06:09.949  4208  4251 I ReactNativeJS: 2063948 of 4928365 received.
05-03 23:06:09.993  4208  4251 I ReactNativeJS: 2260556 of 4928365 received.
05-03 23:06:10.037  4208  4251 I ReactNativeJS: 2375244 of 4928365 received.
05-03 23:06:10.082  4208  4251 I ReactNativeJS: 2506316 of 4928365 received.
05-03 23:06:10.327  4208  4251 I ReactNativeJS: 2719308 of 4928365 received.
05-03 23:06:10.416  4208  4251 I ReactNativeJS: 3227212 of 4928365 received.
05-03 23:06:10.527  4208  4251 I ReactNativeJS: 3604044 of 4928365 received.
05-03 23:06:10.571  4208  4251 I ReactNativeJS: 3694156 of 4928365 received.
05-03 23:06:10.615  4208  4251 I ReactNativeJS: 3817036 of 4928365 received.
05-03 23:06:10.660  4208  4251 I ReactNativeJS: 3857996 of 4928365 received.
05-03 23:06:10.708  4208  4251 I ReactNativeJS: 3964492 of 4928365 received.
05-03 23:06:10.750  4208  4251 I ReactNativeJS: 4087372 of 4928365 received.
05-03 23:06:10.793  4208  4251 I ReactNativeJS: 4259404 of 4928365 received.
05-03 23:06:10.838  4208  4251 I ReactNativeJS: 4406860 of 4928365 received.
05-03 23:06:10.884  4208  4251 I ReactNativeJS: 4546560 of 4928365 received.
05-03 23:06:10.926  4208  4251 I ReactNativeJS: 4661248 of 4928365 received.
05-03 23:06:10.971  4208  4251 I ReactNativeJS: 4792320 of 4928365 received.
05-03 23:06:11.015  4208  4251 I ReactNativeJS: 4915200 of 4928365 received.
05-03 23:06:11.021  4208  4251 I ReactNativeJS: 4928365 of 4928365 received.
05-03 23:06:11.314  4208  4223 D ReactNative: [CodePush] Applying full update.
05-03 23:06:11.316  4208  4251 I ReactNativeJS: Installing update.
05-03 23:06:11.330  4208  4251 I ReactNativeJS: Update installed.
05-03 23:06:11.337  4208  4252 D ReactNative: [CodePush] Loading JS bundle from "/data/user/0/io.grubmobile.app/files/CodePush/c12478e93c7c3fcc04bac253cfeb34e3066d2b69b04b65557fbdcee7475bb417/CodePush/index.android.bundle"
05-03 23:06:11.339  4208  4251 I ReactNativeJS: [CodePush] Restarting app
05-03 23:06:11.349  4208  4208 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()
05-03 23:06:11.408  4208  4208 D ReactNative: ReactInstanceManager.onJSBundleLoadedFromServer()
05-03 23:06:11.409  4208  4208 D ReactNative: ReactInstanceManager.recreateReactContextInBackground()
05-03 23:06:11.409  4208  4208 D ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
05-03 23:06:11.409  4208  4208 D ReactNative: ReactInstanceManager.tearDownReactContext()
05-03 23:06:11.410  4208  4208 D ReactNative: CatalystInstanceImpl.destroy() start
05-03 23:06:11.411  4208  4372 D ReactNative: ReactInstanceManager.createReactContext()
05-03 23:06:11.450  4208  4372 D ReactNative: Initializing React Xplat Bridge.
05-03 23:06:11.456  4208  4372 D ReactNative: Initializing React Xplat Bridge before initializeBridge
05-03 23:06:11.459  4208  4372 D ReactNative: Initializing React Xplat Bridge after initializeBridge
05-03 23:06:11.459  4208  4372 D ReactNative: CatalystInstanceImpl.runJSBundle()
05-03 23:06:11.510  4208  4226 D ReactNative: CatalystInstanceImpl.destroy() end
```
![screen shot 2018-05-03 at 4 06 47 pm](https://user-images.githubusercontent.com/5835869/39606855-6d041a18-4eec-11e8-83fa-81d181a9da1c.png)

### Error

facebook::react::Recoverable: Could not open file ReactNativeDevBundle.js: No such file or directory

### Environment

* react-native-code-push version: 5.3.2
* react-native version: 0.55.3
* iOS/Android/Windows version: Android 7 and 8
* Does this reproduce on a debug build or release build? Android debug only
* Does this reproduce on a simulator, or only on a physical device? Both

Why do debug builds even use code-push? I thought debug builds bypass code-push? Only release builds should use code-push, right?

**Comment by alexandergoncharov** [comment] 2018-05-07 13:31
Hi @ujwal-setlur,

Thanks for reporting!
I reproduced your issue. I'll investigate it a little bit later.

Thanks,
Alexander

**Comment by alexandergoncharov** [comment] 2018-05-07 13:34
About debug builds with code-push: I'm afraid it is No, debug builds use code-push functionality. But if you will try to update app throw codePush with enabling liveReload server You would just get app version which you use on liveReload server.  It may seem that update isn't working. 

From documentation(Here: https://github.com/Microsoft/react-native-code-push#releasing-updates):

> NOTE: CodePush updates should be tested in modes other than Debug mode. In Debug mode, React Native app always downloads JS bundle generated by packager, so JS bundle downloaded by CodePush does not apply.

Thanks,
Alexander

**Comment by ppatel890** [comment] 2018-05-31 20:33
Any Update with this? Dealing with the same issue

**Comment by gdancel** [comment] 2018-06-01 07:45
+1

**Comment by alexandergoncharov** [comment] 2018-06-06 10:51
Hi all,
Sorry for long delay.

Found that the issue is reproducing only in `Live Reload` mode.
As hot workaround you can just comment your CodePush calling during developing your app. But don't forget to uncomment it when you will release your updates.
If you would like to test CodePush logic(that your updates successful will be installed to your user devices) you should use only Release build. 
Investigation of the reason of issue in progress.

Thanks,
Alexander

**Comment by monkibraum** [comment] 2018-07-04 02:54
I've got this error without Live Reload mode on. In physical device, the app crash immediately after update starts.

**Comment by alexandergoncharov** [comment] 2018-07-04 15:48
Hi all,
Sorry for long delay.

I opened PR for this issue: https://github.com/Microsoft/react-native-code-push/pull/1332. 
Could please someone test it?

Thanks,
Alexander

**Comment by ujwal-setlur** [comment] 2018-07-04 15:54
I will test it today. Thanks!

**Comment by alexandergoncharov** [comment] 2018-07-05 08:37
@ujwal-setlur, Thanks for help!

Please let me know about your results.

**Comment by alexandergoncharov** [comment] 2018-07-09 13:30
Hi all,

I'm going to close this issue as fix already in master. This changes will be available in the next publish.
Feel free to reopen this if you have any questions or issue reproduce again.

Thanks,
Alexander

**Closed by alexandergoncharov** 2018-07-09 13:30 UTC
Labels: bug, fix-in-pull-requests

**Comment by g33ktony** [comment] 2018-08-08 21:56
React Native 0.56
react-native-code-push 5.4.1
![screenshot_1533765369](https://user-images.githubusercontent.com/3960100/43866608-f5981f2e-9b2b-11e8-83b5-5f97cb792e93.png)

**Comment by alexandergoncharov** [comment] 2018-08-13 07:15
Hi @g33ktony ,
Thanks for reporting!

Could you please provide reprosteps as I can't reproduce it after fix? All works correct for me.

**Comment by nitrosalat** [comment] 2018-08-23 10:36
Hi, i have the same issue

React Native 0.55.4
react-native-code-push 5.4.1

**Comment by alexandergoncharov** [comment] 2018-08-23 11:10
Hi @nitrosalat ,
Thanks for reporting!

Could you please provide reprosteps as I can't reproduce it after fix? All works correct for me.

**Comment by Devlin556** [comment] 2018-09-17 10:13
Hi @alexandergoncharov . I have the same issue in an Android app. It happens after handle installation code-push bundle and only on Dev version of the app.

**Comment by alexandergoncharov** [comment] 2018-09-17 10:39
Hi @Devlin556,
Thanks for reporting!

Could you please provide reprosteps as I can't reproduce it after fix?
Also, please ensure that you use fresh `react-native-code-push` version.

**Comment by wenkangzhou** [comment] 2018-09-29 08:50
I have the same issue in Android.

React Native 0.56.0
react-native-code-push 5.4.1

**Comment by g33ktony** [comment] 2018-11-12 22:48
I have the same issue now on react-native-code-push v5.4.2 and react-native 0.57.3

I think is related to the change of the app id that was com.innboard and now is cl.innboard
Don't know if there is something we can do to reset this config in codepush cli when releasing an update to a deployment

**Comment by g33ktony** [comment] 2018-11-12 22:59
@ujwal-setlur have you changed the app id before configuring code-push? I see the one you have is different from default

**Comment by ujwal-setlur** [comment] 2018-11-12 23:04
@g33ktony, nope I didn't. Thing to note is that this happens only on debug build for Android. App id is the same between release and debug builds

**Comment by alexandergoncharov** [comment] 2018-11-13 07:37
Hi @wenkangzhou, @g33ktony , @ujwal-setlur ,

I see that you all have the issue like that. Could you please provide logs, versions, reprosteps or dummy project with reproducing issue?

Thanks,
Alexander

**Comment by g33ktony** [comment] 2018-11-14 20:48
> Hi @wenkangzhou, @g33ktony , @ujwal-setlur ,
> 
> I see that you all have the issue like that. Could you please provide logs, versions, reprosteps or dummy project with reproducing issue?
> 
> Thanks,
> Alexander

react-native: 0.57.3
react-native-code-push: ^5.4.2

![captura de pantalla 2018-11-14 a la s 14 47 39](https://user-images.githubusercontent.com/3960100/48511429-4f2ede00-e81c-11e8-95dc-be07654be15a.png)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3960100/48511340-0d059c80-e81c-11e8-8b38-dde43d51fc3a.gif)

**Comment by yashojha19** [comment] 2018-11-15 12:12
react-native 0.56.0
react-native-code-push 5.3.5 
and also tested it with 
react-native-code-push 5.4.2
code-push was working fine some days before, but recently I did one npm install and it messed up everything. Red screen shows and on 
`react-native log-android` shows this


```
11-15 17:40:46.009  4486  4506 D ReactNative: [CodePush] Applying full update.
11-15 17:40:46.025  4486  4562 I ReactNativeJS: [CodePush] Installing update.
11-15 17:40:46.052  4486  4563 D ReactNative: [CodePush] Loading JS bundle from "/data/user/0/com<app_package_nam>e/files/CodePush/ed3cd25941b72c1fc8efc1ccc5b07f4535474e528fcf3250200510506981680c/index.android.bundle"
11-15 17:40:46.052  4486  4486 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()
11-15 17:40:46.054  4486  4562 I ReactNativeJS: [CodePush] Restarting app
11-15 17:40:46.089  4486  4486 D ReactNative: ReactInstanceManager.onJSBundleLoadedFromServer()
11-15 17:40:46.090  4486  4486 D ReactNative: ReactInstanceManager.recreateReactContextInBackground()
11-15 17:40:46.090  4486  4486 D ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
11-15 17:40:46.090  4486  4486 D ReactNative: ReactInstanceManager.tearDownReactContext()
11-15 17:40:46.096  4486  4486 D ReactNative: CatalystInstanceImpl.destroy() start
11-15 17:40:46.102  4486  4759 D ReactNative: ReactInstanceManager.createReactContext()
11-15 17:40:46.277  4486  4759 D ReactNative: Initializing React Xplat Bridge.
11-15 17:40:46.287  4486  4759 D ReactNative: Initializing React Xplat Bridge before initializeBridge
11-15 17:40:46.297  4486  4506 D ReactNative: CatalystInstanceImpl.destroy() end
11-15 17:40:46.300  4486  4759 D ReactNative: Initializing React Xplat Bridge after initializeBridge
11-15 17:40:46.300  4486  4759 D ReactNative: CatalystInstanceImpl.runJSBundle()
```

**Comment by baicuhaha** [comment] 2018-12-20 07:13
Sorry I have this problem too  RN:0.57.7   , "react-native-code-push": "^5.5.0",

**Comment by g33ktony** [comment] 2019-01-10 20:53
I have updated to react-native-code-push: 5.5.0 and I still having the same issue

**Comment by darkfiredarkhalo** [comment] 2019-01-14 02:16
react: 16.6.0-alpha.8af6728
react-native: 0.57.4
react-native-code-push:  5.5.1

I have the same issue in Android

**Comment by seckinbrke** [comment] 2019-02-08 10:19
Same İssue please Help us..

**Comment by vladpalkanov** [comment] 2019-02-12 15:42
"react": "16.6.3"
"react-native": "0.58.4"
"haul": "^1.0.0-rc.12"
"react-native-code-push": "^5.5.2"

The same issue using Android 9 emulator

**Comment by dachinat** [comment] 2019-03-24 05:14
Same here using `debug`

**Comment by viralS-tuanlv** [comment] 2019-03-25 07:14
i am using "react-native-code-push": "^5.6.0" and got this issue, please telll me why? thanks

**Comment by KitYeungDev** [comment] 2019-04-05 04:52
If use ```Debug``` mode: ```react-native run-android```, happen this issue;
If use ```Release``` mode: ```react-native run-android --variant=release```, update version success.

@alexandergoncharov 
Anyway, have any better way to test code push in debug mode?

**Comment by gamsim** [comment] 2019-05-16 04:44
I'm getting the same with latest RN.

"react-native": "0.59.8"
"react-native-code-push": "5.6.0"

**Comment by rendomnet** [comment] 2019-05-29 12:58
same issue
    "react-native-code-push": "^5.6.0",
    "react-native": "^0.59.8",
