### ISSUE TITLE
IOS update problem

### ISSUE THREAD

**Issue by alexeyMohnatkin** [Microsoft/react-native-code-push#840] opened 2017-05-16 13:11 UTC
I'm trying to update ios app (ad-hoc build), but I don't see any changes. code-push cli says that updates have been installed. No problems with android.

`code-push release-react appname-ios ios -d Production -t 1.0.8`

![image](https://cloud.githubusercontent.com/assets/7474676/26107381/c70ada84-3a51-11e7-9fc8-85485f7ba59d.png)

code-push 1.17.4-beta
rn 0.42.0
IOS 10.3.1 

Should it work on ad-hoc?

**Comment by sergey-akhalkov** [comment] 2017-05-17 09:22
Hi @alexeyMohnatkin, thanks for reaching us. I believe that ad-hoc apps should work with CodePush as well as other app. As of now, it is hard to say what goes wrong without any logs or code samples. Please let me know if you have any questions.

**Comment by pvsong** [comment] 2017-05-17 10:31
Same problem.

**Comment by pvsong** [comment] 2017-05-17 10:50
codePush work when install app from x-code to iphone. or run on simulator.
When upload app to testflight or release, codePush not work.

**Comment by sergey-akhalkov** [comment] 2017-05-17 12:44
Hi @pvsong, I've a CodePushified react-native app that has been built in release mode and installed it on the iPhone. It works well for me without any exception. Also [here is the customer](https://github.com/Microsoft/react-native-code-push/issues/699#issue-207108563)  that has CodePushified app and successfully distributes it via TestFlight - then the app successfully downloads and applies CodePush update. 
To determine the root cause the issue you probably need to set up an exception reporter library and share collected logs with me, so I would able to analyze it and try to determine the cause of the issue.
As of now it is really hard to say what goes wrong without any logs or code samples.

**Comment by jbcullis** [comment] 2017-05-17 18:58
I have it working on Android and iOS without exception, however there seems to be an issue that has only presented on iOS where the app thinks it has successfully updated even if the update process was int interrupted. Once that issue occurs, the only way to get those devices to get up to date is to roll a new version.

**Comment by pvsong** [comment] 2017-05-18 18:27
![screen shot 2017-05-19 at 1 25 47 am](https://cloud.githubusercontent.com/assets/9800579/26217581/1de6a25c-3c32-11e7-86d6-ac75ae1386ee.png)

**Comment by alexeyMohnatkin** [comment] 2017-05-18 19:38
@sergey-akhalkov, what logs do you need?
Here's my entry file
```
...
import codePush from 'react-native-code-push';
...
class App extends Component {
	render() {
		return (
			<Provider store={store}>
				<RootContainer />
			</Provider>
		);
	}
}

export default codePush(App);
```

There's another strange thing: when I run Staging build it installs updates from Production deployment. 
![image](https://cloud.githubusercontent.com/assets/7474676/26220207/65e91d4a-3c1a-11e7-83d3-dc504d012fac.png)

![image](https://cloud.githubusercontent.com/assets/7474676/26220109/02200ca6-3c1a-11e7-9089-c8151eff90cc.png)

And I have right app keys in right places, I checked many times.

**Comment by sergey-akhalkov** [comment] 2017-05-19 07:53
@alexeyMohnatkin, I've just tried to configure and install test app on device that uses Release and Staging schemes and it works well for me. I've just completed [this steps](https://github.com/Microsoft/react-native-code-push#ios), then I've changes Archive's Build Configuration value from default "Release" to "Staging":
![image](https://cloud.githubusercontent.com/assets/4928157/26238349/568097c2-3c81-11e7-937e-d240470264f1.png)

So could you please confirm if you've changed Archive's default Build Configuration value?

**Comment by sergey-akhalkov** [comment] 2017-05-19 08:02
Hi @jbcullis, could you please create new issue and provide us more info, so we would able to investigate and fix it?

**Comment by sergey-akhalkov** [comment] 2017-05-26 06:52
@alexeyMohnatkin, @jbcullis, closing this for now, please feel free to reopen or create new issue so we would able to help you.

**Closed by sergey-akhalkov** 2017-05-26 06:52 UTC
Labels: iOS

**Comment by dwilt** [comment] 2017-06-06 05:15
We're running into this issue as well. I've made some changes which I can confirm were correctly uploaded:

![image](https://cloud.githubusercontent.com/assets/1065539/26814608/0994f7a2-4a44-11e7-92b2-674d36241310.png)

And in the console it says it updated:

![image](https://cloud.githubusercontent.com/assets/1065539/26814615/2143b0be-4a44-11e7-93a2-3e65e92f4256.png)

but I'm not seeing my changes show up in the app. You can see the matching version number(14). Here's my code:

```js
export function restartApp() {
    codePush.restartApp();
}

export default async function () {
    if (codePushEnabled) {
        const successCode = await codePush.sync({
            deploymentKey: CODEPUSH_KEY,
            installMode: codePush.InstallMode.ON_NEXT_RESTART
        });

        if (successCode === codePush.SyncStatus.UPDATE_INSTALLED) {
            store.dispatch(showUpdateModal());
        }
    }
}
```
When the app starts, we are calling `sync`, then on complete, showing a modal to let the user know we want them to restart the app:

![image](https://cloud.githubusercontent.com/assets/1065539/26814667/8c1ee3ea-4a44-11e7-95df-90eeccd9cd67.png)

When they click "Ok, restart!" it does restart the app and after a restart I can see in the console is shows "Reporting CodePush update success (v14)" but my changes aren't there. Any ideas?

This used to be working flawlessly but it wasn't until lately things aren't working properly.

Versions:
```
"react-native": "0.41.2",
"react-native-code-push": "^1.17.3-beta",
```

**Comment by sergey-akhalkov** [comment] 2017-06-06 12:53
Hi @dwilt, I've tried to reproduce the issue but with now luck, so could you please create [new issue](https://github.com/Microsoft/react-native-code-push/issues/new) and provide us as much info as possible?

**Comment by dwilt** [comment] 2017-06-06 15:29
@sergey-akhalkov I figured it out.  We had a conditional inside of our `AppDelegate.m` file pointing to the packager bundle and not CodePush:
```
#ifdef DEBUG
    jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
#else
    jsCodeLocation = [CodePush bundleURL];
#endif
```
which I double checked because of [this](https://github.com/Microsoft/react-native-code-push/issues/323#issuecomment-215745965) comment

**Comment by sergey-akhalkov** [comment] 2017-06-06 16:44
@dwilt, got it, we also have an [iOS Plugin Configuration guide](https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-ios.md#plugin-configuration-ios), so you could also verify if everything is set upped correct. 
Thank you for your response and let me know if you have any questions or see any issues.

**Comment by jinxac** [comment] 2017-06-21 06:59
@sergey-akhalkov changing `Release` to `Staging` under archives messes up with the `Pod Dependencies`. Pods are installed in `Staging` folder instead of `Release` folder but the linking occurs to `Release` folder which throws error ld: framework not found for pod files.

**Comment by sergey-akhalkov** [comment] 2017-06-21 07:33
Hi @jinxac, got it, let's continue investigation in the issue you have created https://github.com/Microsoft/react-native-code-push/issues/893
