### ISSUE TITLE
Images not rendering properly on ios after code-push with resizeMode center

### ISSUE THREAD

**Issue by Ashwin-Mothilal** [Microsoft/react-native-code-push#1222] opened 2018-03-01 15:16 UTC
### Steps to Reproduce
1. React Native Image Component local image which matches resizeMode center 
2. Install the app from Xcode Production version
3. Change the tintColor of the image or change text if you have
4. Release using "code-push release-react <AppName> ios "

### Expected Behavior
Images should render properly as it is in dev version debug mode

### Actual Behavior
   Images with resizeMode "center" gets resizeMode "cover". I am mentioning "cover" because it matches with it in dev mode.

 ### SCREENSHOTS
[After CodePush to Production App - 1 Improper images](https://drive.google.com/file/d/1Q4KG0iBL2-2GSYHlaiTcNvib98R6jE_2/view?usp=sharing)

[After CodePush to Production App - 1 Some proper images](https://drive.google.com/open?id=1snOXtjRzeBsi_T1792rtyrgMti441pwa) - Images representing Views, Comments, Attachments are looking good.

[Expected / Debug Build](https://drive.google.com/open?id=1NiZha3qVYLK-OFC1Uwnv-7D5jDBjs_98)

### Environment

* react-native-code-push version: 5.2.1
* react-native version: 0.52.0
* iOS/Android/Windows version: iOS version 11.2.6
* Does this reproduce on a debug build or release build? Release

###Notes
The App uses this [tabbar](https://github.com/timomeh/react-native-material-bottom-navigation) component in React Navigation
For the topbar it uses StackNavigator.

**Comment by adbl** [comment] 2018-03-12 09:57
I notice this for `resizeMode: "stretch"` too. We are using `stretch` together with `capInsets` for some shadow assets (on semi transparent views) and it makes the shadow look completely wrong.

**Comment by adbl** [comment] 2018-03-12 10:07
Aha, actually I see now that `resizeMode: "stretch"` is respected but it seems like the `capInsets` are just gone (which makes the shadow look wrong). Maybe a separate issue.

**Comment by syq7970** [comment] 2018-03-15 09:04
+1

**Comment by Zakeelm** [comment] 2018-03-26 21:02
Hey there! 

We haven't forgotten about this issue. We have been doing some internal changes on the way we're executing github support. Are you still having this problem?

**Comment by adbl** [comment] 2018-03-27 05:27
Hello, the case I mentioned above: yes!

**Comment by iTOYS** [comment] 2018-03-28 15:38
Hi guys,
Unfortunately I can't reproduce you issue.
There is my `App.js`:
```
import React, { Component } from 'react';
import { StyleSheet, Text, View, TouchableOpacity, Image } from 'react-native';
import codePush from "react-native-code-push";

class App extends React.Component {
  render() {
    return (
      <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
        <Image
          style={{width: 100, height: 100, margin: 20}}
          source={require('./1.png')}
          resizeMode='cover'
          tintColor='#ff00ff'
        />
        <Image
          style={{width: 100, height: 100, margin: 20}}
          source={require('./1.png')}
          resizeMode='center'
          tintColor='#ff00ff'
        />
        <Image
          style={{width: 100, height: 100, margin: 20}}
          source={require('./1.png')}
          resizeMode='stretch'
          tintColor='#ff00ff'
          capInsets={{left: 15, right: 15, bottom: 15, top: 15}}
        />
        <TouchableOpacity
          style = {{height: 70, width: 200, backgroundColor: 'green'}}
          onPress={() => {
             codePush.sync({
                  updateDialog: true,
                  installMode: codePush.InstallMode.IMMEDIATE
              });
          }}>
        <Text>Current version: 15</Text> 
      </TouchableOpacity>
      </View>
    )
  }
}

let codePushOptions = { checkFrequency: codePush.CheckFrequency.MANUAL };
export default App = codePush(codePushOptions)(App);
```

After codepush release was installed all looks the same as in a binary version:
<img src="https://user-images.githubusercontent.com/4017593/38039381-cf274920-32b5-11e8-8534-404e877bbd67.png" data-canonical-src="https://user-images.githubusercontent.com/4017593/38039381-cf274920-32b5-11e8-8534-404e877bbd67.png" width="400" />

Would be great if you can create little project which I can use to reproduce

Thanks!

**Comment by adbl** [comment] 2018-03-28 18:56
@iTOYS Thanks for the reply. In the case I described above (using a drop shadow image), we use `absolute` position and unset the width/height like this:
```
  shadow: {
    position: "absolute",
    top: -18,
    left: -20,
    bottom: -22,
    right: -20,
    width: undefined,
    height: undefined,
  },
```

with `capInsets`:
```
{
  top: 22,
  left: 24,
  bottom: 26,
  right: 24,
}
```

This is probably relevant to the issue, especially unsetting width/height, I should have mentioned it before.

**Comment by iTOYS** [comment] 2018-03-29 12:24
Sorry guys, I doesn't see difference between binary version and codepush.
Example project would be helpful!

**Comment by Ashwin-Mothilal** [comment] 2018-04-02 08:34
Sorry, was busy in other projects. I am still facing this issue. @iTOYS It's not possible for me to create a example project for some days. The only difference I see in Code push code is, I am not doing it manually, its done by Default option which is OnAppResume I think. I have updated the screenshots and text also, feel free to ask questions!

**Comment by iTOYS** [comment] 2018-04-02 08:44
Hi @Ashwin-Mothilal 
I don't have access to new images.
CodePush options that i use don't have any affects to styles.
I'm waiting project from you :)

Thanks!

**Comment by Ashwin-Mothilal** [comment] 2018-04-02 09:11
I have changed the permissions for the images, you can check it now. Just have a look at it. I will try to give project after this week, working on other production issues.

**Comment by tomauty** [comment] 2018-04-05 02:48
Noticing this as well. Changing to resizeMode={'contain'} seems to fix it. Most of these were absolutely positioned images. Maybe some data stripped from assets in the bundling/distribution process?

**Comment by iTOYS** [comment] 2018-04-05 13:33
CodePush and plugins doesn't change your code and assets.
Could you please download your bundle and compare props values?

https://codepush.azurewebsites.net/updateCheck?deploymentKey=[your-key]&appVersion=[app-version]

**Comment by iTOYS** [comment] 2018-04-25 10:52
Closing this issue for now! I recommend you to wrap all your props values with `{}`

Thanks!

**Comment by Ashwin-Mothilal** [comment] 2018-04-26 11:33
Hi, I am attaching the sample project for you [here](https://github.com/Ashwin-Mothilal/codepushSample) 

Please find the image after **code push Update** 
![img_0054](https://user-images.githubusercontent.com/11491430/39303448-b9e9af92-4973-11e8-8b49-d2a864d50b76.jpg)

**Comment by stueynet** [comment] 2018-05-03 17:52
What if we are not using it as props but using it within the Image style object? Same problem? Also would it not make sense to have the code-push build mimic the behaviour of a normal production build? Production builds work and look just fine with no errors whatsoever.

**Comment by ex3ndr** [comment] 2018-08-19 07:14
Same here. I have two separate issueses. 

First is a background image for a chat. It had transparency (by mistake) and for some reason it was resized incorrectly. It was zoomed and very low res. iOS had this bug, but android works well.

Second case is a simple png images with capInsets. It looks like it just ignores cap insets at all.

**Comment by ex3ndr** [comment] 2018-08-19 10:25
Ok, i figured out the root cause of the issue. When loading images from CodePush bundle it doesn't respect scale factor of the resource. It works well for built-in resources since UIImage can load with right scale factor automatically. 

Unfortunately, the only (and dirty) solution is to patch react-native implementation.

In react-native/React/Base/RTCUtils.m patch `RCTImageFromLocalAssetURL`:
```
image = [UIImage imageWithData:fileData];
```

with 
```
CGFloat scale = 1.0;
if ([[imageURL absoluteString] hasSuffix: @"@3x.png"]) {
  scale = 3.0;
} else if ([[imageURL absoluteString] hasSuffix: @"@2x.png"]) {
  scale = 2.0;
}
image = [UIImage imageWithData:fileData scale: scale];
```

This will work only for png files.

**Comment by ex3ndr** [comment] 2018-08-19 17:10
For sure it should be opened back. Also after digging around image loading it turns out that there are no image caching at all for built-in images on iOS. For example, if app will show series of messages with bubble decorations then build with codepush will load each image again and again. That's really creepy for performance.

**Comment by makirby** [comment] 2018-09-06 16:32
@ex3ndr you're a damn hero

**Comment by stueynet** [comment] 2018-09-06 17:34
@iTOYS  or anyone from Microsoft can you open this back up please or let us know how we can deal with it? Editing React Native core files is not an option.

**Comment by alexandergoncharov** [comment] 2018-09-07 10:13
Hi all,

Sure, I'll reopen it. Thanks for reporting!
It requires more time for investigate. Sorry for this delay.

**Comment by makirby** [comment] 2018-09-07 11:32
@stueynet for now i am patching the RN package using the code from @ex3ndr, for me this is a good solution until there is a better solution. https://gist.github.com/makirby/6f7a0b6ef2e8865751206b2b69e1abdc

**Comment by bthuan** [comment] 2018-09-11 20:47
@ex3ndr's solution works for me, thank you digging into it. But I think it's pretty hacky

**Comment by NickToropov** [comment] 2018-09-26 13:29
@wynch yes, it's RN issue. CodePush does nothing with your js/assets. It just calls RN cli under the hood and pushes generated bundle to CodePush server from where your customers can download it. The main difference between downloaded bundle and binary bundle is location. We saw several places in RN code where there are conditions checking whether bundle/asset is located in app or in file system. We don't know if there is a RP with fixes in RN repository.

**Comment by Fsarmento** [comment] 2018-10-03 11:31
Hi,

I just bumped into this same problem today.
I have a  background image with "resizeMode: 'repeat'". After updating the sentence in the middle of the screen using codepush, the image resizeMode or size changes (iPhone 6):

<img width="977" alt="screen shot 2018-10-03 at 12 16 03" src="https://user-images.githubusercontent.com/18128610/46407710-bc246380-c707-11e8-9c3d-1ae2bd0a192d.png">

This project is available here: https://github.com/Fsarmento/codepushImageRepeate

**Comment by NickToropov** [comment] 2018-10-04 14:38
Hi @Fsarmento! thanks for demo app! I've reproduced the issue. Please try to apply workaround suggested by @ex3ndr [above](https://github.com/Microsoft/react-native-code-push/issues/1222#issuecomment-414118064). It works for me.

**Comment by emilioicai** [comment] 2018-11-09 10:29
Modifying React Native's code is not a solution for any project using continuous integration so this issue prevents Code Push from being integrated in any medium to large size app.

**Comment by yuri-kulikov** [comment] 2018-11-22 16:53
Hi @ascherkus!

You did a really great job finding this particular commit! 👍
I wish we'd figured it out sooner and I hope it will be fixed soon.

**Comment by HighSoftWare96** [comment] 2019-01-09 15:56
Same problem here... I solved forcing the image to be with resizeMode stretch 😞

**Comment by ScreamZ** [comment] 2019-01-31 17:13
Hello @geof90 @lostintangent @max-mironov 

I'm facing the same issue, removing `resizeMode: "center"` fixed the problem, can you have a look at this please ?

It's really important I guess for many company that relies heavily on Codepush…

Best regards guys

**Comment by MichielDeMey** [comment] 2019-02-15 10:55
Hey guys, a fix has been merged into master in the React Native project.
(cfr. https://github.com/facebook/react-native/issues/22383 & https://github.com/facebook/react-native/pull/23446)

You can create a patch file from the following diff: https://patch-diff.githubusercontent.com/raw/facebook/react-native/pull/23446.diff

**Comment by ScreamZ** [comment] 2019-02-15 11:34
Marvelous ! I made a workaround, i'll wait react native to update :) THanks

**Comment by alexandergoncharov** [comment] 2019-02-21 11:24
Hi all,
I see that This issue have been fixed in react-native. https://github.com/facebook/react-native/issues/22383
So, I'm going to close this issue for now. Please feel free to reopen it if you have any questions.

Thanks,
Alexander

**Closed by alexandergoncharov** 2019-02-21 11:24 UTC
Labels: bug, iOS, investigating

**Comment by holgersindbaek** [comment] 2019-03-02 09:58
@ScreamZ What workaround did you do?

**Comment by ScreamZ** [comment] 2019-03-03 12:39
Not using `center` mode, i was not specially requiring it for my use case.

**Comment by andyboythekid** [comment] 2019-03-22 19:39
updating to RN 0.59.1 worked for me

**Comment by khokanuzzman** [comment] 2022-04-25 05:41
use "contain". worked for me...
resizeMethod={'resize'}
resizeMode={'contain'}
