### ISSUE TITLE
Error: Failed to release a CodePush update. - Android

### ISSUE THREAD

**Issue by jamiesonbates** [microsoft/react-native-code-push#1676] opened 2019-09-05 01:35 UTC
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. appcenter codepush release-react --app {app_name}  -d {deployment_name}

### Expected Behavior
What you expected to happen?
Expect to generate a new js bundle and push it to the correct app / environment.

### Actual Behavior
What actually happens?

![Screen Shot 2019-09-04 at 6 30 56 PM](https://user-images.githubusercontent.com/9344645/64304819-3118a280-cf42-11e9-9d31-3f583473efd4.png)

### Reproducible Demo
I cannot create a reproducible demo.

We are new to code push, but have configured it and have used it to push new js bundles on both iOS and Android. 

A few hours prior to writing this, I successfully pushed a new bundle to iOS with no problems, however, pushing to android simply does not work for some reason. Unfortunately, I have exhausted all my resources for debugging this (at least that I know of).

### Environment

* react-native-code-push version: 5.6.0
* react-native version: 0.59.5
* iOS/Android/Windows version: N/A
* Does this reproduce on a debug build or release build? release
* Does this reproduce on a simulator, or only on a physical device? N/A

(The more info the faster we will be able to address it!)

**Comment by JonasWho** [comment] 2019-09-18 12:22
I'm experiencing the same. My release for iOS works well, but Android fails every time with no useful error message. It's the same for Staging and Production.
- react-native-code-push version: 5.7.0
- react-native version: 0.59.9

Here is a screenshot of the log with `--debug`
![Screenshot 2019-09-18 at 14 16 53](https://user-images.githubusercontent.com/925342/65148072-c2e2de00-da1f-11e9-80bf-e05cc5c1f70a.png)

**Comment by nishanbajracharya** [comment] 2019-09-25 05:09
Have the same issue. iOS release goes fine but android release fails. It's the same error messages. Has there been any update on this?

**Comment by ukasiu** [comment] 2019-10-16 08:34
I'm also experiencing this. Any workarounds?

**Comment by nishanbajracharya** [comment] 2019-10-17 06:47
The `appcenter-cli`version I had issue with was `2.x`. After reverting to `1.2.2` the android build seemed to work.

**Comment by ukasiu** [comment] 2019-10-17 07:06
@nishanbajracharya thanks!

**Comment by andreidubov** [comment] 2020-02-13 07:10
Hi @jamiesonbates ,
Thank you for reporting!


Please update your appcenter-cli, now the current version is 2.3.3.
If you have questions related to appcente-cli, you can refer to their repository: https://github.com/microsoft/appcenter-cli.

I'm going to close this issue for now. Please feel free to reopen it if you still have any questions or issues.

**Comment by apostolou** [comment] 2020-04-02 19:26
hello @andreidubov , 
I'm facing the same isssue with appcenter 2.4.0 and RN 0.59.5
iOS sync works perfectly but I'm having the exact same error for android as mensioned above.
Any ideas on how I can understand what is going wrong ? 
Thanks

**Comment by rdewolff** [comment] 2020-07-13 19:28
Facing same issue on `appcenter version 2.6.2`

**Comment by andreidubov** [comment] 2020-07-14 06:55
@apostolou @rdewolff 

I reopen this issue, we will investigate it again.

Thank you very much.

**Comment by jdewells** [comment] 2020-08-25 11:05
'allo berks.

We ran into this problem recently and found a cause by running the command with `DEBUG=*` at the start, like this:

`DEBUG=* appcenter codepush release-react ...`

This output in the debug logs that we had an "invalid version" of React-Native, which was `^0.62.2`. The previous version didn't have the caret (the `^` character).

When we pinned the version to `0.62.2`, we could run the command properly. Hope this helps figure out the issue.

**Comment by mrousavy** [comment] 2020-09-03 18:09
@jdewells Your fix worked for me, but this shouldn't be a problem. CodePush should parse the version number either way and ignore the `^`  character, so this definitely is a **bug** and isn't **resolved**!

**Comment by dayze** [comment] 2020-09-04 13:31
Exactly the same error, we removed the caret and it works. 
Thank you @jdewells

**Comment by snowpardx** [comment] 2020-10-05 09:57
Hi there, I'm appologize for the issue being open for such a long time. By the way at the moment being I'm unable to repro the issue.
![image](https://user-images.githubusercontent.com/3825438/95064424-6032b200-0708-11eb-8489-3dd077ef6d47.png)

Do you still have issues releasing your react-native changes with most recent CLI used (2.7.1) and react-native(0.63.3) if so could you please share the sample, so that we could repro?

Cc @mrousavy @dayze explicitly summoning you as people who experienced issues relatively recently.

**Comment by andreidubov** [comment] 2020-10-13 11:04
I'm going to close this issue for now as I haven't heard from you in a while, unfortunately.
Please feel free to reopen it if you have any questions.

**Comment by rdewolff** [comment] 2020-10-13 12:19
Last time I tried this it didn't work. I think closing the issue because you "haven't heard from you in a while" is not a good way to handle the problem.

**Comment by snowpardx** [comment] 2020-10-13 17:07
@rdewolff I agree with you that it feels as not a good way to handle the problem, unfortunately we have to follow this practice of closing issues without replies to keep their overall amount manageable and focus on most requested ones sorry for the inconvenience it causes. 

For this particular issue there are some reports about issue happening in the past. Unfortunately at the current moment we unable to reproduce the issue and asking community for help to at least find the project(preferably simplified) where it happens, so that could investigate and fix. When there are no further replies for some timeframe we assume, that nobody is experiencing the issues anymore, so we can just close it.

You mentioned that you have issue last time you tried, do you have it now with latest appcenter cli installed? If so could you please share some project to repro with us?

**Comment by mrousavy** [comment] 2020-10-13 17:11
Sorry for not replying! Actually last week I had this exact issue, will try again this week, maybe I didn't have the latest CLI? In the meantime I removed the `^` from the RN version string

**Comment by andreidubov** [comment] 2020-10-14 10:02
Thank you for your activity, we reopened the card and will Investigate this issue again. We will be very grateful if you provide us with repro steps or a project, this will help us in our investigation.

**Comment by n-kurdiukov-akvelon** [comment] 2020-10-15 16:20
I've created the [PR:1104](https://github.com/microsoft/appcenter-cli/pull/1104) with fix for appcenter-cli. Let's wait for the review and release.

**Comment by n-kurdiukov-akvelon** [comment] 2020-10-30 07:56
It's fixed in https://github.com/microsoft/appcenter-cli/releases/tag/v2.7.3

**Closed by n-kurdiukov-akvelon** 2020-10-30 07:56 UTC
Labels: android

**Comment by rajscet** [comment] 2022-12-10 07:06
Disable hermes then it will work
