### ISSUE TITLE
[Android] Codepush crash || Received 2998272 bytes, expected 3012378 || CodePushUpdateManager.java line 198 in com.microsoft.codepush.react.CodePushUpdateManager.downloadPackage

### ISSUE THREAD

**Issue by thecachedbyte** [Microsoft/react-native-code-push#1335] opened 2018-07-05 12:45 UTC
* react-native-code-push version: 5.3.2
* react-native version: ^0.49.3
* iOS/Android/Windows version: No specific version
* Does this reproduce on a debug build or release build? - release
* Does this reproduce on a simulator, or only on a physical device? - nope

**CodePushUpdateManager.java line 198 in com.microsoft.codepush.react.CodePushUpdateManager.downloadPackage**

We are getting this crash on production? Can someone tell me whats wrong?

**Comment by alexandergoncharov** [comment] 2018-07-06 23:15
Hi @thecachedbyte 
Thanks for reporting!

Could you please clarify is it stable issue and you have only 2998272  bytes for all time or it was once?

Thanks,
Alexander

**Comment by thecachedbyte** [comment] 2018-07-07 05:22
Hi @alexandergoncharov 

Sharing crash message instance against one deployment name where we did only one OTA till now.

Received 3006028 bytes, expected 3012378 - 284 instance
Received 2997836 bytes, expected 3012378 - 272 instance
Received 2999686 bytes, expected 3012378 - 20 instance
Received 3008306 bytes, expected 3012378 - 19 instance
Received 2999884 bytes, expected 3012378 - 16 instance
Received 2998272 bytes, expected 3012378 - 15 instance
Received 3004234 bytes, expected 3012378 - 13 instance
Received 3010674 bytes, expected 3012378 - 11 instance
Received 2996938 bytes, expected 3012378 - 9 instance
Received 3010354 bytes, expected 3012378 - 7 instance

Let me know if you need more information.

**Comment by alexandergoncharov** [comment] 2018-07-09 14:05
Hi @thecachedbyte 
It is strange issue. 
Is it possible to reproduce issue on your device? If yes, could you please share logs from AndroidStudio/adb logcat? Possible there can be more info about this issue.
Also, could you please provide your configuration for CodePush?  (It is like so: https://github.com/Microsoft/react-native-code-push/blob/master/Examples/CodePushDemoApp/App.js#L81)

And could you please clarify have you tried to release one more update?

Thanks,
Alexander

**Comment by thecachedbyte** [comment] 2018-07-09 15:13
@alexandergoncharov We are using default config.[ Option 1](https://github.com/Microsoft/react-native-code-push#plugin-usage)

Unable to reproduce locally. Its not happening for all your user base. Its happening for a very small set of user and there is no pattern.

**Comment by alexandergoncharov** [comment] 2018-07-11 12:10
Hi @thecachedbyte ,
Sorry for long delay.

This is strange issue. Possible there can be some user-locally issue but I'm not sure for now.
What is situation at now? Is there more number the same instances of issues?

Thanks,
Alexander

**Comment by thecachedbyte** [comment] 2018-07-11 12:16
@alexandergoncharov Yes we are still getting similar issue reported at crashlytics and newrelic. I will try to get some more logs if possible.

Ideally even if there is a mismatch in data received vs expected it should not crash, rather it should re initiate fresh download. Please correct me if i am missing something.

**Comment by alexandergoncharov** [comment] 2018-07-11 13:49
@thecachedbyte , unfortunately it isn't so. In mismatch case there will be just error with logging this error massage. https://github.com/Microsoft/react-native-code-push/blob/master/android/app/src/main/java/com/microsoft/codepush/react/CodePushUpdateManager.java#L198

But yeah, I think that it will be better if plugin will try to download update one more time in mismatch case. Please let me investigate it more closer.

**Comment by thecachedbyte** [comment] 2018-07-13 14:50
@alexandergoncharov Error trace from sentry

```
com.microsoft.codepush.react.g: Received 3005194 bytes, expected 3012378
    at com.microsoft.codepush.react.h.a(SourceFile:198)
    at com.microsoft.codepush.react.CodePushNativeModule$3.a(SourceFile:210)
    at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(SourceFile:204)
    at android.os.AsyncTask$2.call(AsyncTask.java:333)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at java.lang.Thread.run(Thread.java:764)
java.lang.RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$3.done(AsyncTask.java:353)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
    at java.util.concurrent.FutureTask.run(FutureTask.java:271)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at java.lang.Thread.run(Thread.java:764)
```

**Comment by NickToropov** [comment] 2018-07-16 14:43
Hi @thecachedbyte, do you have information about how many different devices/users report this issue? (whether it's a single/small group of devices with connection issues or may be a group of devices from a region with internet issues)

**Comment by thecachedbyte** [comment] 2018-07-18 03:41
@NickToropov Its only happening with Samsung devices. No other common pattern.

**Comment by alexandergoncharov** [comment] 2018-07-21 10:20
Hi @thecachedbyte ,

Thanks for this additional info. We'll investigate approach for adding several attempts to get update in mismatch size case.

We'll keep you in touch.

Thanks,
Alexander

**Comment by jkk** [comment] 2018-07-31 12:49
Chiming in to say that we are experiencing a similar issue in production. Relatively rare, Samsung devices only, but causing difficulties deploying to an Enterprise user base where everyone is required to use the app. The only workaround is to delete and reinstall the app, forcing CodePush to try again (and hopefully succeed).

**Comment by jkk** [comment] 2018-08-07 22:04
We are attempting to deploy a stopgap measure which tries to detect code-push errors and timeouts, then allows the user to restart the app. If anyone else has had success with workarounds, please share! I will report our findings after deploying and gathering data.

**Comment by alexandergoncharov** [comment] 2018-08-13 08:14
Hi @thecachedbyte and @jkk ,

Possible do you have some more specified pattern of issue? Possible this is specific device or specific Android version/Samsung android shell version? Or something else that can help me reproduce issue?

**Comment by alexandergoncharov** [comment] 2018-08-15 07:07
@jkk , Thanks!

Could you please clarify all issue devices have this issue or not? For example all `Samsung S9, Android 8.0` have this issue? or some this devices can get update successfully?

**Comment by alexandergoncharov** [comment] 2018-08-20 10:52
@jkk, @thecachedbyte friendly reminder about my last questions =)

**Comment by thecachedbyte** [comment] 2018-08-20 11:27
@alexandergoncharov only a few of these devices are getting impacted. But it is happening every time for them. One of our user is facing this issue in every session. As soon as he opens our app after sometimes it is getting crashed.

**Comment by alexandergoncharov** [comment] 2018-08-22 19:08
@thecachedbyte , Got it. Thanks. I think that calling one more downloading will not fix  issue with this behavior.  I should investigate it more.

**Comment by jkk** [comment] 2018-08-28 16:00
We haven't been able to reliably reproduce this issue on our end on specific physical devices or emulators. It doesn't seem to happen every time, and our instrumentation is not the best, so it's hard to pin down. If/when we are able to gather more useful data, I'll be sure to share. Thanks for looking into it!

**Comment by alexandergoncharov** [comment] 2018-09-03 10:51
@jkk , Sure! It will be useful if you find more information. Please keep us in touch.

**Comment by thecachedbyte** [comment] 2018-09-07 05:34
@alexandergoncharov One thing I noticed.

**Comment by thecachedbyte** [comment] 2018-09-27 04:07
@alexandergoncharov Do we have any update on this? more than 25% of our app crashes are because of this issue. :( Are we anywhere close to the root cause?

Just wondering if we are the only one facing this issue? is there something wrong in our integration (it is a hybrid app, not a react native only app)?

Attaching stack trace, if it helps.
[GoibiboAndroid-crashreport-09-26-2018_1517+0530.txt](https://github.com/Microsoft/react-native-code-push/files/2422442/GoibiboAndroid-crashreport-09-26-2018_1517%2B0530.txt)

**Comment by thecachedbyte** [comment] 2018-09-27 04:13
We create a new deployment name whenever there is a contract change between react native and native team. One thing I noticed app team uses [codepush cli](https://github.com/Microsoft/code-push/tree/master/cli) to create new deployment name and react native team uses [appcenter cli](https://github.com/Microsoft/appcenter-cli) to do a codepush release.

Its highly unlikely but can that cause any issue?

**Comment by alexandergoncharov** [comment] 2018-10-01 15:51
Hi @thecachedbyte ,

Sorry for delay. No, it shouldn't affect updating app. Appcenter cli is just new cli with codepush and other managing appcenter. Code-push cli is just for CodePush and will be deprecated soon. This CLIs have same functionality.

I thought that issue possible might be in byte counting on device  but after investigating counting logic I didn't found any issues.
Also I noticed by your [message](https://github.com/Microsoft/react-native-code-push/issues/1335#issuecomment-403189890) that all issue updates have less bytes then expected. Possible there is some network or device app stack(like os or some launchers) issue. Also possible there is some pattern about location, Do you have this information?

Yeah, you and @jkk just 2 who reported about this issue.
Also, Could you please provide more info about your hybrid app?

**Comment by alexandergoncharov** [comment] 2018-10-15 08:09
Hi @thecachedbyte,

CodePush should catch any errors from CodePush logic and just print this error to console without any crashing app as CodePush should NOT break app for any reason. Or do you have info about exactly crashing app?

Or do you mean just ignore this error? If so, I think it isn't good idea as I see that we have less bytes than we expected by your statistics: https://github.com/Microsoft/react-native-code-push/issues/1335#issuecomment-403189890. Possible it is mean that we loss something during getting update and behaviour for this case can be unexpected. But if you agree with that and would like to test it with your users I can remove this checking.

**Comment by alexandergoncharov** [comment] 2018-11-09 14:14
Hi @thecachedbyte and @jkk ,

Just a friendly ping about my last question :) 
And is behaviour the same?

**Comment by alexandergoncharov** [comment] 2018-11-16 13:00
Hi @thecachedbyte and @jkk ,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it.

Thanks,
Alexander

**Comment by vivek-walecha-657** [comment] 2018-11-19 05:58
Hi,
@alexandergoncharov  how can this be possible, what thats the problem in our codepush, how there can be size mismatch?
`URL downloadUrl = new URL(downloadUrlString);
            connection = (HttpURLConnection) (downloadUrl.openConnection());
            bin = new BufferedInputStream(connection.getInputStream());

            long totalBytes = connection.getContentLength();
            long receivedBytes = 0;

            File downloadFolder = new File(getCodePushPath());
            downloadFolder.mkdirs();
            downloadFile = new File(downloadFolder, CodePushConstants.DOWNLOAD_FILE_NAME);
            fos = new FileOutputStream(downloadFile);
            bout = new BufferedOutputStream(fos, CodePushConstants.DOWNLOAD_BUFFER_SIZE);
            byte[] data = new byte[CodePushConstants.DOWNLOAD_BUFFER_SIZE];
            byte[] header = new byte[4];

            int numBytesRead = 0;
            while ((numBytesRead = bin.read(data, 0, CodePushConstants.DOWNLOAD_BUFFER_SIZE)) >= 0) {
                if (receivedBytes < 4) {
                    for (int i = 0; i < numBytesRead; i++) {
                        int headerOffset = (int) (receivedBytes) + i;
                        if (headerOffset >= 4) {
                            break;
                        }

                        header[headerOffset] = data[i];
                    }
                }

                receivedBytes += numBytesRead;
                bout.write(data, 0, numBytesRead);
                progressCallback.call(new DownloadProgress(totalBytes, receivedBytes));
            }

            if (totalBytes != receivedBytes) {
                throw new CodePushUnknownException("Received " + receivedBytes + " bytes, expected " + totalBytes);
            }`

This is the code to calculate total bytes in connection and receivedBytes.

Please reopen the issue if possible, we need to discuss.

**Comment by vivek-walecha-657** [comment] 2018-11-19 08:40
@alexandergoncharov Thank You for reopening the issue. Please can you help how there can be a mismatch?

**Comment by vivek-walecha-657** [comment] 2018-11-19 08:49
One thing I have done is while integrating is added this line:
CodePush.setReactInstanceHolder(mReactNativeHost); after super.onCreate(); in Application class, but documentation says:
<img width="856" alt="screen shot 2018-11-19 at 2 18 42 pm" src="https://user-images.githubusercontent.com/13266610/48695779-115bfc00-ec06-11e8-9f2b-4e11e2d881e4.png">
needs to be called before super.onCreate(). Is that the issues?

**Comment by alexandergoncharov** [comment] 2018-11-19 08:53
Hi @vivek-walecha-657 ,

I'm not sure about the reason. There may be many options: some network issue, local router issue, some Samsung launcher issue(as all issue devices is Samsung https://github.com/Microsoft/react-native-code-push/issues/1335#issuecomment-412535309).  
Unfortunately we still haven't found the real reason of this issue as we can't stably reproduce it.

@vivek-walecha-657 Could you please clarify have you faced this issue too? If yes could you please provide info as much as possible.  For we should stable reproduce it for investigating and fixing it.

Thanks,
Alexander

**Comment by alexandergoncharov** [comment] 2018-11-19 08:54
@vivek-walecha-657,
 I'm not sure that it can be the reason of issue. Have you found some changes of behaviour after  adding `CodePush.setReactInstanceHolder(mReactNativeHost); `?

**Comment by vivek-walecha-657** [comment] 2018-11-19 09:02
@alexandergoncharov, Thanx for writing back.

Not exactly, Can you throw some light on the size mismatch?
Because it can be possible the bundle we are uploading to app centre and the size coming by update API of code push are not equal.

Tell what other input you need from me? @thecachedbyte and me are working together on this issue.

Regards,
Vivek

**Comment by vivek-walecha-657** [comment] 2018-11-21 13:13
@alexandergoncharov 
We need to update code push react native SDK to the latest version. the code snippet I have attached above is of the older SDK code. If you should have told us this it would be solved earlier.
Anyways it's my bad ill update the react native SDK.

**Comment by goshashwat** [comment] 2018-11-21 13:30
This is fixed in the below release.
https://github.com/Microsoft/react-native-code-push/releases/tag/v5.3.4

**Comment by alexandergoncharov** [comment] 2018-11-23 13:08
Hi @vivek-walecha-657,

>Can you throw some light on the size mismatch?

I don't have any big info about that but what kind of info would you like to get?

It would be really great if you find some pattern or something else that can help us reproduce this issue on us device for debugging this issue. Unfortunately without this info it is really hard to find real reason of issue.

You can just update `code push react native SDK` as npm package. `npm update react-native-code-push`. Please let me know if you waiting from me some other information.

**Comment by alexandergoncharov** [comment] 2018-12-05 07:19
Hi @vivek-walecha-657,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander

**Closed by alexandergoncharov** 2018-12-05 07:19 UTC
Labels: android, bug, waiting-for-clarification

**Comment by neeshurajput** [comment] 2021-02-05 10:45
I am facing the same issue. Its coming only in the samsung devices.
Galaxy S10+
Galaxy C9 Pro
Galaxy J2 Pro
Galaxy S9+
Galaxy S7
Galaxy A9 (2018)
Galaxy A7 (2018)

Library versions :
React Native : 0.62.2
react-native-code-push : 6.3.0


Crash Log : 
Caused by java.lang.IllegalStateException: closed
       at com.android.okhttp.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:175)
       at com.android.okhttp.internal.http.HttpEngine$2.read(HttpEngine.java:1025)
       at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:397)
       at com.google.firebase.perf.network.InstrHttpInputStream.read(InstrHttpInputStream.java:121)
       at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
       at java.io.BufferedInputStream.read(BufferedInputStream.java:347)
       at com.microsoft.codepush.react.CodePushUpdateManager.downloadPackage(CodePushUpdateManager.java:181)
       at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:290)
       at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:284)
       at android.os.AsyncTask$3.call(AsyncTask.java:378)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
