### ISSUE TITLE
CodePushMalformedDataException App Crashing on code-push

### ISSUE THREAD

**Issue by bgoyal2222** [Microsoft/react-native-code-push#913] opened 2017-07-05 14:06 UTC
This is the crash log which i get after sending updates to my app via code-push

java.lang.RuntimeException: 
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4982)
  at android.app.ActivityThread.-wrap1(ActivityThread.java:0)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533)
  at android.os.Handler.dispatchMessage(Handler.java:111)
  at android.os.Looper.loop(Looper.java:207)
  at android.app.ActivityThread.main(ActivityThread.java:5754)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)
Caused by: com.microsoft.codepush.react.CodePushMalformedDataException: 
  at com.microsoft.codepush.react.CodePushUtils.getJsonObjectFromFile(CodePushUtils.java:198)
  at com.microsoft.codepush.react.CodePushUpdateManager.getCurrentPackageInfo(CodePushUpdateManager.java:55)
  at com.microsoft.codepush.react.CodePushUpdateManager.getCurrentPackageFolderPath(CodePushUpdateManager.java:72)
  at com.microsoft.codepush.react.CodePushUpdateManager.getCurrentPackageBundlePath(CodePushUpdateManager.java:82)
  at com.microsoft.codepush.react.CodePush.getJSBundleFileInternal(CodePush.java:149)
  at com.microsoft.codepush.react.CodePush.getJSBundleFile(CodePush.java:140)
  at com.microsoft.codepush.react.CodePush.getJSBundleFile(CodePush.java:132)
  at com.plexusmd.MainApplication$1.getJSBundleFile(MainApplication.java:76)
  at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:78)
  at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41)
  at com.fabricio.vergal.RNWorkers.RNWorkersManager.init(RNWorkersManager.java:59)
  at com.plexusmd.MainApplication.onCreate(MainApplication.java:139)
  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1018)
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4979)

To reproduce:
Build a new react native project RN version 0.43.4
and install react-native-code-push v2.1.0 beta
and try releasing any small javascript change like change color of text and try

code-push release-react <App name> android 

react-native-code-push version:2.1.0 beta
react-native version: 0.43.4

**Comment by bgoyal2222** [comment] 2017-07-05 14:10
Is there any way to code-push changes on this version because this version is in market place and is crashing on sending update via code-push

**Comment by max-mironov** [comment] 2017-07-06 11:08
Hey @bgoyal2222, I just have tried to reproduce your issue with `react-native 0.43.4` and `react-native-code-push 2.1.0-beta` following your steps but with no luck. (android 7 real device)
Did you happen to reproduce this issue constantly with the steps you have provided? 
Have you tried to release another version to see if it works?
At what time did you see the crash, what CodePush InstallMode do you use?

Also just a guess but probably your issue could be somehow related to #910, so maybe it make sense to update to `2.1.1-beta` to see if it helps.

**Comment by bgoyal2222** [comment] 2017-07-07 14:33
Ya it seems like its solved in 2.1.1-beta but is there any way that we can make this change in the existing app which is on the playstore with code-push version 2.1.0-beta.. other than releasing new build..
Thanks @max-mironov for help

**Comment by max-mironov** [comment] 2017-07-07 15:24
@bgoyal2222 unfortunately I believe that you should update code push dependency to 2.1.1-beta to fix this issue because the problem is with code-push itself, so seems that the only way is to release new version of your app. Sorry for inconvenience.

**Comment by max-mironov** [comment] 2017-07-10 06:01
I'm closing the issue for now, please let us know if you have more questions.

**Closed by max-mironov** 2017-07-10 06:01 UTC
Labels: android, no-repro, waiting-for-clarification
