### ISSUE TITLE
[Android] a unzipped folder exist in device, if downloaded bundle has missing js bundle file name 

### ISSUE THREAD

**Issue by krunalsshah** [Microsoft/react-native-code-push#1366] opened 2018-08-03 06:56 UTC
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Set Up instruction in Android 
https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-android.md
It expects to set 
```
@Override
        protected String getJSBundleFile() {
            return CodePush.getJSBundleFile();
        }
```
Reference 
https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/ReactNativeHost.java#L131
- In my case `null` resulted in exception highlighted below 
https://github.com/Microsoft/react-native-code-push/blob/master/android/app/src/main/java/com/microsoft/codepush/react/CodePushUpdateManager.java#L241
2. I noticed the directory with `packageHash` still exists in `data/data/<package_id>/files/CodePush/<packagehash>/CodePush/

### Expected Behavior
What you expected to happen?
Exception thrown and no need to create a copy first till preconditions are met

### Actual Behavior
What actually happens?
a unzipped folder exist in device, if downloaded bundle has missing js bundle file name 

### Solution
Throw exception prior to creating a copy of unzipped folder

**Comment by NickToropov** [comment] 2018-08-03 07:45
Hi @krunalsshah, is this issue reproduced stably? If yes, please provide us with demo app or detailed repro steps that we could find the cause of the problem faster. Also please specify the following information:
* react-native-code-push version:
* react-native version:
* package.json file
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

**Comment by krunalsshah** [comment] 2018-08-03 07:55
@NickToropov thanks for writing back. 
react-native-code-push version: 5.3.5
react-native version: 0.55.4
Does this reproduce on a debug build or release build? both
Does this reproduce on a simulator, or only on a physical device? simulator

Submitting the PR https://github.com/Microsoft/react-native-code-push/pull/1367
The idea is to check if the bundle file name exists in the unzippedFolderPath folder before copying content over to `newUpdateFolderPath`

**Comment by NickToropov** [comment] 2018-08-03 08:48
Am I right that you suggest just not to create and keep new folder with invalid update?

**Comment by krunalsshah** [comment] 2018-08-03 15:44
@NickToropov yes you are correct, I pushed the update. before throwing exception we can delete the folder silently. I believe it should be okay to delete `newUpdateFolderPath` if it exists due to execution of line, https://github.com/Microsoft/react-native-code-push/blob/master/android/app/src/main/java/com/microsoft/codepush/react/CodePushUpdateManager.java#L228

**Comment by NickToropov** [comment] 2018-08-03 15:56
@krunalsshah  thanks for answering! We'll review it more detailed a bit later. Will be in touch!

**Comment by krunalsshah** [comment] 2018-08-03 18:37
@NickToropov pushed the changes and tested it. Looks safe to me. thanks

**Comment by NickToropov** [comment] 2018-08-14 10:10
Hi @krunalsshah, please could you check my [answer](https://github.com/Microsoft/react-native-code-push/pull/1367#issuecomment-412077822) in your PR and let me know if you can do required changes or provide any other feedback.

**Comment by NickToropov** [comment] 2018-09-05 14:27
Hi! I'll close this issue for now as there is no activity here and in PR. Please reopen them if you have time to continue work on your PR.

**Closed by NickToropov** 2018-09-05 14:27 UTC
Labels: android, fix-in-pull-requests
