### ISSUE TITLE
Android app doesn't recognize version code in semver expressions

### ISSUE THREAD

**Issue by gavinyeah** [Microsoft/react-native-code-push#759] opened 2017-03-17 03:46 UTC
### Description

Android app doesn't recognize version code in semver expressions, while it works for iOS app.

### Reproduction

When I use following command to release for android, it works fine and all clients can get the update:
`code-push release-react MyApp android`

When I use command with semver expression for targetBinaryVersion like below, all clients can't get the update:
`code-push release-react MyApp android -t ">=2.7.0"`

My app versionName defined in build.gradle is 2.7.0
Here is the deployment history:

┌───────┬─────────────┬───────────────────────┐
│ Label 　　│ App Version 　　　　│ Install Metrics 　　　　　　　　　　│
├───────┼─────────────┼───────────────────────┤
│ v5　　　　│ 2.7.0　　　　　　　│ Active: 30% (3 of 10)　　　　　　　│
│　　　　　│　　　　　　　　　　│ Total: 6 (3 pending)　　　　　　　│
├───────┼─────────────┼───────────────────────┤
│ v6　　　　│ >=2.7.0　　　　　　│ No installs recorded　　　　　　　│
├───────┼─────────────┼───────────────────────┤
│ v7　　　　│ >=2.7.0 　　　　　│ No installs recorded　　　　　　　　│
├───────┼─────────────┼───────────────────────┤
│ v8　　　　│ 2.7.0　　　　　　　│ Active: 20% (2 of 10) 　　　　　　　│
│　　　　　│　　　　　　　　　│ Total: 2 (1 pending)　　　　　　　　│
│　　　　　 │　　　　　　　　　│ Rollbacks: 1　　　　　　　　　　　│
├───────┼─────────────┼───────────────────────┤
│ v9　　　　│ >=2.7.0　　　　　　│ No installs recorded　　　　　　　│
├───────┼─────────────┼───────────────────────┤
│ v10　　　│ ~2.7.0　　　　　　　│ No installs recorded　　　　　　　│
└───────┴─────────────┴───────────────────────┘

### Additional Information

* react-native-code-push version: 1.17.1-beta
* react-native version: 0.39.2
* Android version: 6.0.1/7.0
* Does this reproduce on a debug build or release build? Both.
* Does this reproduce on a simulator, or only on a physical device? Physical devices.

**Comment by max-mironov** [comment] 2017-03-20 08:45
Hello @gavinyeah, thank you for your question,

I've tried to reproduce this on sample app, so I've:
1) Defined app version in build.gradle as of 2.7.0
2) Deployed the app with react-native run-android
3) Released new version with `-t ">=2.7.0"` flag
4) Was able to apply new release
![image](https://cloud.githubusercontent.com/assets/24542698/24092870/475d46f2-0d0e-11e7-9a97-ef5b88421f14.png)

Do you have any special aspects about your app? Is your case reproducible with our sample app?
Also can you try to run `code-push debug android` command and share with as what is the output when you run your app and try to update it?

**Comment by gavinyeah** [comment] 2017-03-23 09:32
Hi @max-mironov , thanks a lot for looking into this.

I'm afraid the issue is caused by the bundle naming, not the version expressions.

In our local environment, we're using index.android.bundle for Android deployment while using index.ios.bundle for iOS deployment. It works fine.

In our build system on Visual Studio Online, we're using main.jsbundle for both Android and iOS deployment. They're deployed separately but both use main.jsbundle as the name of bundle. It works fine for iOS but no installs for Android at all.

Now I've changed the bundle name back to index.android.bundle for Android and it works. Semver expressions also work fine.

**Comment by max-mironov** [comment] 2017-03-23 09:56
@gavinyeah - thank you so much for detailed explanation of the root cause of the issue. If you don't mind I'm closing this one now, please feel free to reach as if you see any issues with code-push.

**Closed by max-mironov** 2017-03-23 09:56 UTC
Labels: waiting-for-clarification
