### ISSUE TITLE
iOS 11.0.3 flash back

### ISSUE THREAD

**Issue by iOSQiao** [Microsoft/react-native-code-push#1045] opened 2017-10-13 09:18 UTC
iPhone: 11.0.3
react-native: 0.42.0
react-native-code-push: 1.17.2-beta

When iOS 11.0.3 hot update the jsbundle, the iPhone was flash back.
How should I solve this problem?

**Comment by ruslan-bikkinin** [comment] 2017-10-13 09:37
Hi @iOSQiao and thanks for submitting the issue. Please clarify does your issue duplicating #1041?

**Comment by iOSQiao** [comment] 2017-10-13 09:41
No it isn't a duplicate.

**Comment by ruslan-bikkinin** [comment] 2017-10-13 09:48
@iOSQiao could you please clarify, what do you mean when you are saying "flash back"?

**Comment by iOSQiao** [comment] 2017-10-13 09:52
App automatically exits, and the hot update is not successful.

**Comment by ruslan-bikkinin** [comment] 2017-10-13 09:56
@iOSQiao okay, i got it. So could you please provide us any logs from your application?

**Comment by iOSQiao** [comment] 2017-10-13 10:11
here, 
![2017-10-13 18 08 54](https://user-images.githubusercontent.com/13956756/31541618-e20b2bce-afd4-11e7-9e0d-988e9ef961c7.png)

**Comment by ruslan-bikkinin** [comment] 2017-10-13 10:27
Well, @iOSQiao, hard to say what is the cause of your problem using information you provided. Please, could you fill the entire [issue template](https://github.com/Microsoft/react-native-code-push/blob/master/.github/ISSUE_TEMPLATE.md) so we will be aware about details that can be important in investigation.

**Comment by iOSQiao** [comment] 2017-10-16 02:51
This is the wrong message.
![Uploading 屏幕快照 2017-10-16 10.48.28.png…]()

**Comment by iOSQiao** [comment] 2017-10-16 03:32
I found out why, it turns out that's because of this. [https://github.com/CRAlpha/react-native-wkwebview/issues/83](https://github.com/CRAlpha/react-native-wkwebview/issues/83).

**Comment by ruslan-bikkinin** [comment] 2017-10-16 08:22
Thanks for the update, I’m closing this, please feel free to reopen if needed.

**Closed by ruslan-bikkinin** 2017-10-16 08:22 UTC
Labels: incomplete, iOS, waiting-for-clarification
