### ISSUE TITLE
Where can I find the rollback reason?

### ISSUE THREAD

**Issue by UtillYou** [microsoft/react-native-code-push#1951] opened 2020-09-18 07:30 UTC
My code push keeps rolling back on iOS while works fine on Android. If I use mandatory mode, it also works fine on iOS, but that is not what I want. Because it will update every time I restart my iOS app. So I want to find the rollback reason. Is there any logs or something

### Environment

* react-native-code-push version:6.3.0
* react-native version:0.63.0
* iOS/Android/Windows version:iOS 13.5
* Does this reproduce on a debug build or release build?  Both debug and release
* Does this reproduce on a simulator, or only on a physical device? Both

(The more info the faster we will be able to address it!)

**Comment by ruslan-bikkinin** [comment] 2020-10-01 15:53
Hi @UtillYou and thanks for contacting us.

As [documentation says](https://github.com/microsoft/react-native-code-push#debugging--troubleshooting) 
```
If you're not calling sync on app start (like within componentDidMount of your root component), then you need to explicitly call notifyApplicationReady on app start, otherwise, the plugin will think your update failed and roll it back.
```
the possible reason for newly released updates to be rolled back is that something changed in the app code that prevents `notifyApplicationReady` to be called at app start. 

As for now CodePush doesn't support any additional information why the update is rolled back and it's not clear how to achieve that given that rollback feature relies only on the fact that `notifyApplicationReady` wasn't called at app start. There could the dozen of reasons why it happened depending on how particular app is designed and integrated with CodePush.

We could help you to identify the cause if you could provide simplified versions of your app like the stable version where update isn't rolled back and the next version on which update has started to roll back. You can strip all essential parts of your app which touches commercial secrets etc leaving just the main minimal skeleton on which the problem is still reproducable.

**Comment by danut-t** [comment] 2020-10-02 11:48
I think that the main problem is that we don't receive any feedback for rollbacks, not even if on retries they have been installed. They just happen and it's a complete mystery as to why. I have a similar issue, recently encountering a lot of rollbacks on the android side, but no crashes logged and we cannot reproduce it no matter what we try. Maybe something could be implemented to have rollback reasons somewhere in the Appcenter dashboard

**Comment by ruslan-bikkinin** [comment] 2020-10-02 12:56
Thanks for the explanation. As for now we already have a feature request for it here: #1099 but currently we don't have an ETA when it will be implemented as our team has another priorities in the list. As soon as we are ready to pick it up we will make an announcement in the original issue to notify users that this highly requested feature is triaged and taken to work. 
As for now I'm going to close this one, feel free to leave a comment/vote for it in the original issue.

**Closed by ruslan-bikkinin** 2020-10-02 12:56 UTC
Labels: waiting-for-clarification
