### ISSUE TITLE
Can not build Android project

### ISSUE THREAD

**Issue by hardikvirani6** [microsoft/react-native-code-push#1845] opened 2020-04-22 07:17 UTC
ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :react-native-code-push.
Show Details
Affected Modules: app

    "appcenter": "3.0.2",
    "appcenter-analytics": "3.0.2",
    "appcenter-crashes": "3.0.2",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-code-push": "^6.2.0",

**Comment by KGDeveloper** [comment] 2020-05-25 02:41
Hello, have you solved this problem? I have encountered this problem too. It has been bothering me for a long time and I cannot find a solution

**Comment by alexandergoncharov** [comment] 2020-06-02 14:42
Hi @KGDeveloper , @KGDeveloper ,
Thanks for reporting!

Could you please provide some test project with reproducing issue and repro steps?

**Comment by KGDeveloper** [comment] 2020-06-04 09:10
I have solved this problem, and the steps are as follows
I'm going to introduce this in `settings.gradle`,
`include ':react-native-code-push'
project(':react-native-code-push').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-code-push/android/app')`

**Comment by andreidubov** [comment] 2020-06-10 08:01
Since there is no answer and we cannot reproduce it I'm going to close this issue for now. Please feel free to reopen it if you have any questions or issues.

**Closed by andreidubov** 2020-06-10 08:01 UTC
Labels: bug, waiting-for-clarification

**Comment by nabilfreeman** [comment] 2020-10-28 09:31
I also have this issue upon upgrading from RN 61 to RN 63. CodePush 6.3.0.
