### ISSUE TITLE
Force checking update in native code

### ISSUE THREAD

**Issue by oney** [Microsoft/react-native-code-push#65] opened 2015-11-24 06:01 UTC
Last week, I did a stupid thing. I deployed new js release using CodePush. Some users downloaded new js bundle and applied it, then the app crashed. After restarting the app, it crashed immediately. So, there is no chance to check new update from CodePush. Users were angry and went to App Store to give 1 star rating. There are about 5000 affected users.

Therefore, what I am thinking is forcing check update in native code when the app had crashed.
In Javascript, after checkForUpdate, set `check_update_last_time` to be `true`
```javascript
var UserDefaults = require('react-native-userdefaults-ios');
codePush.checkForUpdate().then((update) => {
  UserDefaults.setBoolForKey(true, 'check_update_last_time') ;
});
```
In `AppDelegate.m`, If `check_update_last_time` is `NO`, it means the app didn't check update last time. So it should be check update in native before load js code. If there is new js release, download and apply it.
If `check_update_last_time` is `YES`, set `check_update_last_time` to be `NO` and load js directly.
```objective-c

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  if (![[[NSUserDefaults standardUserDefaults] objectForKey:@"check_update_last_time"] boolValue]) {
    // Check new release and download it from CodePush
  } else {
    [[NSUserDefaults standardUserDefaults] setObject:@(NO) forKey:@"check_update_last_time"];
    NSURL *jsCodeLocation = [CodePush getBundleUrl];
    RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                        moduleName:@"MyApp"
                                                 initialProperties:nil
                                                     launchOptions:launchOptions];
    ...
  }
```
Any opinion? It's not necessary that it's included in CodePush.

**Comment by lostintangent** [comment] 2015-11-24 06:47
Yikes, I'm sorry to hear about that! I'd love to discuss how we could help prevent that kind of situation. Out of curiosity, what was the cause of the crash? Was the JS code busted due to relying on a different version of the native side? Was it a native crash?

Are you currently specifying a rollbackTimeout when you call sync/apply? When you do, the native code will expect you to call CodePush.notifyApplicationReady after an update, and if you don't, it assumes the update failed and immediately rolls you back to the previous version. It will then "blacklist" any updates that previously failed so that it doesn't try to install them again. It would be great to know if that capability would have been able to help you in this particular scenario. Otherwise, we should investigate other options.

**Comment by geof90** [comment] 2015-11-24 06:54
Hi @oney, I'm sorry to hear about that experience. We definitely need some better support for helping developers recover their apps from a failed update. Your suggestion makes sense and is definitely something our team can consider to implement in future releases amongst other methods that we have talked about.

Right now, apart from the rollbackTimeout install option that @lostintangent mentioned, another method I would suggest to avoid running into such issues is to make full use of the Staging and Promote actions built into our CodePush CLI. This means that during development, you could be testing the entire end to end update experience against the Staging deployment, and only after you have verified that the Staging deployment is can be installed and run without any crashes, use the `code-push promote` command to transfer that bundle from Staging to Production.

**Comment by oney** [comment] 2015-11-24 09:31
Thanks.
I only use `CodePush.sync();` to update. My `react-native-code-push` version is `1.1.2-beta`.
Does `CodePush.sync();`automatically rollback when the code runs incorrectly?

**Comment by geof90** [comment] 2015-11-24 09:59
Not by default. You have to specify it as part of the options, eg:
```
// After the update is installed, the timer waits for 5 seconds, 
// if it does not receive a notifyApplicationReady() call, it will rollback.
var seconds = 5;
CodePush.sync({rollbackTimeout: seconds});
```
https://github.com/Microsoft/react-native-code-push#codepushsync

**Comment by geof90** [comment] 2015-11-24 21:36
Please note that I edited my previous comment, the rollbackTimeout takes milliseconds as opposed to seconds which is mentioned in the README. We're fixing the docs

**Comment by oney** [comment] 2015-11-26 06:21
Thanks for reply.
I am a little confused. So, if I set rollbackTimeout to 5000 when calling sync method, my problem will be solved. Is it right?

**Comment by lostintangent** [comment] 2015-11-26 15:52
When you specify a rollbackTimeout to sync, you are basically telling the CodePush runtime to assume the update failed if your app doesn't call notifyApplicationReady within the specified amount of time. When this occurs, it will automatically roll users back to the previous version of the app, so that they aren't stuck on a busted version.

So specifying a rollbackTimeout of 5000, gives your app 5 seconds to call notifyApplicationReady before being rolled back.

This would have helped your scenario if your crash was caused by buggy JavaScript. If you had a native crash however, then this wouldn't likely have helped you.

We're looking into making the rollback support automatic, so that you don't have to specify the timeout and/or call notifyApplicationReady, but you still get the protection of the runtime catching a bad update and rolling your users back automatically.

In your case, would this have helped your users? We believe this behavior is valuable, but I want to make sure we consider other solutions that can help prevent this in the future.

**Comment by lostintangent** [comment] 2015-12-02 22:29
I'm going to close this for now since I'm not sure if we have any actionable next steps. In addition to the rollback timeout feature I mentioned above on the client, we are also working on a server-driven rollback feature that would let you rollback a deployment to remove a broken release and ensure that users get upgraded back to the working version. I'm hoping these two features together will help respond to incidents like this in the future.

Please do let us know if there are any additional requirements/feedback here though!

**Closed by lostintangent** 2015-12-02 22:29 UTC

**Comment by oney** [comment] 2015-12-04 17:42
Still thinking this issue. How about using confirming new release success callback that is combined with rollback callback?
It means that the app downloads new version and applies it, but it doesn't make this new version valid in next launch. If new version works correctly, we call a function to marks new version as successful. If new version crashes, in next launch, the app will find last version fails, then apply previous version and blacklist this version.
