### ISSUE TITLE
"auto roll-back" version after reopen app

### ISSUE THREAD

**Issue by vedovato** [Microsoft/react-native-code-push#696] opened 2017-02-08 18:38 UTC
After modifying some features and stuff in our app we just released both new versions over the air and all goes ok. The app discover the update accordingly, then installs it and so restart the app. 

Everything was ok until i realize that when i restart the app it kind of roll-back to the default store version (w/o our new updates). Any suggestion would be appreciated.

Obs: When it auto-roll-back, the app just don't alert again about the update just released.

* react-native-code-push version: ^1.16.1-beta
* react-native version: 0.37.0
* iOS/Android/Windows version: ios: 10.2.x / android: x.x.x
* Does this reproduce on a debug build or release build? Released build
* Does this reproduce on a simulator, or only on a physical device? only on physical device
* Repro steps and/or stack trace: integrate code-push, send an update OTA, install the update, close the new app version on device and open it again

(The more info the faster we will be able to address it!)

**Comment by silhouettes** [comment] 2017-02-08 19:06
Hey @vedovato, is your root component wrapped? Like this: https://github.com/Microsoft/react-native-code-push#plugin-usage

**Comment by vedovato** [comment] 2017-02-13 18:59
Hey @silhouettes thanks for your reply. No, it isn't wrapper but it's "working".

Couple of questions:
- Why does it work without being wrapped? 
- How do i wrap it in a wix-react-native-navigation project since it doesn't use regular class structure?

**Comment by silhouettes** [comment] 2017-02-13 22:12
Hi @vedovato:

The wrapper just calls .sync(), but the difference is that it also calls [`notifyAppReady()`](https://github.com/Microsoft/react-native-code-push/blob/master/docs/api-js.md#codepushnotifyappready) in the root componentDidMount. If this function is not called in the first run of a CodePush update to 'rubber stamp' it as having launched successfully, the update will be rolled back the next time the app is started.

So, to solve your problem, I suggest you just add a call to that function as soon as the update is loaded. Does that solve your issue?

**Comment by vedovato** [comment] 2017-02-15 12:53
Well, i think it didn't @silhouettes. Could you take a look at my code? I think everything is ok and no errors/warnings are shown: Btw, it is working fine in Android and just iOS roll-back as mentioned.

'use strict'

import React, { Component } from 'react'
import { Text, View, ListView, StyleSheet, RefreshControl } from 'react-native'
import Meteor from 'react-native-meteor'
import MergeObj from 'object-merge'
import SETTINGS from '../utils/settings'
import NewsItem from '../components/NewsItem'
import Loading from '../components/Loading'
import Separator from '../components/Separator'
import codePush from 'react-native-code-push'


@codePush
export default class News extends Component {

  constructor(props) {
    super(props)
    this.state = {
      isLoading: true,
      refreshing: false,
      dataSource: new ListView.DataSource({
        rowHasChanged: (row1, row2) => row1 !== row2
      })
    }
  }


  componentDidMount() {
    this.filterData()
    // this.codePushCheck()
    this.setState({
      isLoading: false
    })
  }


  componentWillReceiveProps(data) {
    this.filterData(data)
  }


  codePushCheck() {
    codePush.sync({
      updateDialog: true,
      installMode: codePush.InstallMode.IMMEDIATE,
      checkFrequency: codePush.CheckFrequency.ON_APP_RESUME
    });
  }


  filterData(updatedData) {
    let data = this.props.meteorData.filter(Boolean)
      , result = '' // filter result
      , type = this.props.dataType // economia, politica etc


    // if type IS empty, return all news types
    if(!type) {
      result = data
    } else {
      result = data.filter((value) => value.cat === type)
    }

    this.setState({
      dataSource: this.state.dataSource.cloneWithRows(result),
    })
  }


  render() {
    return this.state.isLoading ? <Loading /> : (
      <View style={styles.wrapper}>
        <ListView
          dataSource={this.state.dataSource}
          enableEmptySections={true}
          renderSeparator={ (data, i)=> <Separator key={i} /> }
          renderRow={ (data)=> <NewsItem navigator={this.props.navigator} data={data} /> }
        />
      </View>
    )
  }

}

const styles = StyleSheet.create({
  wrapper: {
    backgroundColor: SETTINGS.LIGHT_COLOR,
    height: SETTINGS.WINDOW_HEIGHT,
  }
})

**Comment by sergey-akhalkov** [comment] 2017-02-27 09:53
@vedovato, do you still experiencing the issue? Please let me know if you see any issues.

**Comment by vedovato** [comment] 2017-03-06 12:05
Yeah, i do @sergey-akhalkov but i think it's something with **wix-react-native-navigation** not codepush itself. I'm not being able to wrap my root component..

**Comment by sergey-akhalkov** [comment] 2017-03-06 12:11
@vedovato, could you please provide me minimal version of the app (https://codepaste.net/ehp1a1 link does not work for me) where the issue reproduces? So I will investigate it and try to help you.

**Comment by vedovato** [comment] 2017-03-06 12:16
Hey, ok i'd appreciate that @sergey-akhalkov. [Here goes the code snapshot](https://gist.github.com/vedovato/d4405ff36db140125e607fdec6d66621).

Thank you!

**Comment by sergey-akhalkov** [comment] 2017-03-06 12:52
@vedovato, I have a quick look on your code snapshot and I could advice you the following:
1. Remove lines: https://gist.github.com/vedovato/d4405ff36db140125e607fdec6d66621#file-index-js-L4,  https://gist.github.com/vedovato/d4405ff36db140125e607fdec6d66621#file-index-js-L60 and https://gist.github.com/vedovato/d4405ff36db140125e607fdec6d66621#file-news-js-app-news-screen-L31
2. Add `News = codePush({ installMode: codePush.InstallMode.ON_NEXT_RESUME })(News);` line here: https://gist.github.com/vedovato/d4405ff36db140125e607fdec6d66621#file-news-js-app-news-screen-L112

Please let me know if it helps or if you see any issues.

**Comment by max-mironov** [comment] 2017-03-14 06:57
@vedovato - hi, do you have a chance to look at this?

**Comment by vedovato** [comment] 2017-03-14 13:06
I'll have a look into it soon, @max-mironov @sergey-akhalkov. Sorry for delaying.

**Comment by max-mironov** [comment] 2017-03-23 05:34
@vedovato - any updates about this? Just a friendly ping :)

**Comment by vedovato** [comment] 2017-03-23 14:56
Last week i was in trouble with apple certificates so i couldn't test it properly in my phone and this is very important to us so i'll try my best to feedback you very soon. Thank you for pinging me again, @max-mironov

**Comment by vedovato** [comment] 2017-03-23 16:17
Reiterating, i'll be able to only see this tomorrow in the afternoon :/

**Comment by max-mironov** [comment] 2017-03-23 17:38
@vedovato 
No problem, it's not something super urgent. Please verify it at any convenient time for you :) We just wanted to be sure that the issue is fixed for you.

**Comment by sergey-akhalkov** [comment] 2017-03-31 07:46
@vedovato, closing this for now, please feel free to reopen if the issue still reproduces or if you have any questions.

**Closed by sergey-akhalkov** 2017-03-31 07:46 UTC
Labels: investigating, waiting-for-clarification

**Comment by grigored** [comment] 2017-06-07 12:17
Had the same problem, this is what worked for me https://github.com/Microsoft/react-native-code-push/issues/875

**Comment by kwnccc** [comment] 2017-08-06 19:30
I'm currently facing this issue no matter what configuration I have tried.
React Native: 0.45.1
RN Code Push: 3.0.1-beta

After releasing a new version in Staging, there is no way I can update the application version since it's always rolling back with the debug message: 
```
[CodePush] Checking for update.
[CodePush] An update is available, but it is being ignored due to having been previously rolled back.
[CodePush] App is up to date.
```

I've also tried the solution @grigored has proposed, but neither this approach has helped update the application. 

Do you have any idea how can I resolve this issue?

**Comment by grigored** [comment] 2017-08-06 22:50
In my case messing around with codePush.sync() brought only problems. What if you remove the part in componentDidMount() part?

**Comment by kwnccc** [comment] 2017-08-07 05:46
@grigored also tried commenting out the `componentDidMount()` but the same problem occured to me. 😞

**Comment by kwnccc** [comment] 2017-08-07 06:54
@sergey-akhalkov @grigored I've also tried a pure react-native project with just react-native and react-native-code-push as dependencies, but the exact same error occurs. I'm running both apps with `rect-native run-ios` using packager.

**Comment by sergey-akhalkov** [comment] 2017-08-07 07:52
Hi @kwnccc, thanks for reaching us. Could you please share pure project source code with me? So I'll be able to investigate it and find out the root cause of the issue.

**Comment by kwnccc** [comment] 2017-08-07 08:57
@sergey-akhalkov yeah sure, what i did is to actually create a new RN application. 

- `react-native init TestingCodePush && cd TestingCodePush`
- initialised the app with CodePush `code-push app add TestingCodePush-iOS ios react-native` (being already authorised)
- `npm install --save react-native-code-push`
- then I've modified `index.ios.js` to the following:

```
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';

import codePush from "react-native-code-push";

export default class TestingCodePush extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.ios.js
        </Text>
        <Text style={styles.instructions}>
          Press Cmd+R to reload,{'\n'}
          Cmd+D or shake for dev menu
        </Text>
      </View>
    );
  }
}

TestingCodePush = codePush(TestingCodePush)

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('TestingCodePush', () => TestingCodePush);
```

- run the application `react-native run-ios` -> opened the app in the emulator -> enable js remote debugging
- released to the Staging env with `code-push release-react TestingCodePush-iOS ios`
- refresh app with CMD + R -> watched logs for checking updates and downloading updates in the chrome debugger
- shut down the application, then reopen in and the rollback error occurs instead of the update.
```
[CodePush] Checking for update.
[CodePush] An update is available, but it is being ignored due to having been previously rolled back.
[CodePush] App is up to date.
```

**Comment by sergey-akhalkov** [comment] 2017-08-07 09:19
@kwnccc, thanks for sharing the source code and repro steps. I can see that the source code is fine, but I can see an issue in your repro steps - you shouldn't test CodePush updates in Debug mode while react-native packager is working, please take a look at this NOTE from official docs:
>NOTE: CodePush updates should be tested in modes other than Debug mode. In Debug mode, React Native app always downloads JS bundle generated by packager, so JS bundle downloaded by CodePush does not apply.

If you want to test CodePush updates in development/debug mode for iOS you should do the following:

1. Modify the AppDelegate.m to force the JSCode location to be "remote". (This is already done for you if you are using the example app)
```objective-c
jsCodeLocation = [CodePush bundleURL];

//#ifdef DEBUG
////  jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios&dev=true"];
//  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios"fallbackResource:nil];
//#else
//  jsCodeLocation = [CodePush bundleURL];
//#endif
//
```

2. Comment around lines 17-20 in node_modules/react-native/packager/react-native-code.sh the lines:
```sh
    # if [[ "$PLATFORM_NAME" = "iphonesimulator" ]]; then
      # echo "Skipping bundling for Simulator platform"
      # exit 0;
    # fi
```

Please let me know if it help or if the issue is still reproduced for you.

**Comment by kwnccc** [comment] 2017-08-07 10:08
@sergey-akhalkov I cannot run the application that way, it seems like it doesn't load anything. I've also tried without packager and it runs properly but because I cannot debug it in browser I'm not sure if the update has been completed properly. After running `code-push deployment history TestingCodePush-iOS Staging`, the last version deployed it logs `No installs recorded`. 
Is there any other way I can try the Staging deployed application?

**Comment by sergey-akhalkov** [comment] 2017-08-07 10:58
@kwnccc, do I get it right if you are searching the way to verify if an update has been installed or not? To achieve it you could use `codePush.SyncStatus.UPDATE_INSTALLED` [event](https://github.com/Microsoft/react-native-code-push/blob/master/docs/api-js.md#syncstatus), also you could call and print result of execution of `getUpdateMetadata` [method](https://github.com/Microsoft/react-native-code-push/blob/master/docs/api-js.md#updatestate)

Please let me know if you have any questions.

**Comment by SutharRohit** [comment] 2023-02-01 17:47
Hi,

I am getting the same issue in iOS only, but for the android it is working fine.

i am using:
```
"react-native": "0.66.4",
"react-native-code-push": "^7.1.0",
```

anyone found solution for this issue ?

**Comment by ducgiangtrankma** [comment] 2023-02-26 10:21
> Hi,
> 
> I am getting the same issue in iOS only, but for the android it is working fine.
> 
> i am using:
> 
> ```
> "react-native": "0.66.4",
> "react-native-code-push": "^7.1.0",
> ```
> 
> anyone found solution for this issue ?

Same issue.
