### ISSUE TITLE
there is null pointer

### ISSUE THREAD

**Issue by xhacker5000** [Microsoft/react-native-code-push#249] opened 2016-03-16 16:28 UTC
``
 "dependencies": {
    "react-native": "^0.21.0",
    "react-native-code-push": "^1.8.0-beta"
  }
``
Up is my version info
and when I build project there is 
``
RCTJSCProfiler.m:102:7: Called function pointer is null (null dereference)
``
Is that OK?

**Comment by lostintangent** [comment] 2016-03-16 17:02
Is this error related to CodePush? RCTJSCProfiler.m is a React Native file, so I don't think that would be caused by us.

**Comment by lostintangent** [comment] 2016-03-19 18:30
@xhacker5000 I haven't been able to repro this issue, so I'm thinking it's unrelated to CodePush. I'm going to close the issue for now, but please reopen it if you continue to experience this problem. Thanks!

**Closed by lostintangent** 2016-03-19 18:30 UTC
