### ISSUE TITLE
use sim card flow  is fine,but wifi  can not receive update info，and debug info is [CodePush] Network request failed

### ISSUE THREAD

**Issue by ytt123** [microsoft/react-native-code-push#1628] opened 2019-07-16 02:38 UTC
use sim card flow is fine,but wifi can not receive update info，and debug info is [CodePush] Network request failed

**Comment by alexandergoncharov** [comment] 2020-02-12 12:06
Hi @ytt123 ,
Thanks for reporting! 

Unfortunatelly, I can't reproduce this issue. Could you please provide more detailed reprosteps or test project with reproducing issue?

I'm going to close this issue for now. Please feel free to reopen it when you provide more info or if you have any questions.

**Closed by alexandergoncharov** 2020-02-12 12:06 UTC
