### ISSUE TITLE
App is not updated second time.

### ISSUE THREAD

**Issue by Invictus-Munish** [microsoft/react-native-code-push#2725] opened 2024-07-11 07:56 UTC
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.
2. 
3.

### Expected Behavior
What you expected to happen?
The updates should be properly installed.

### Actual Behavior
What actually happens?
For the first time the app updates perfectly but than the next update is errored.
```
  STACK TRACE AND/OR SCREENSHOTS
```
![Screenshot 2024-07-11 at 1 24 42 PM](https://github.com/microsoft/react-native-code-push/assets/86218548/b0760bf6-e64a-4e9c-afec-4ef732ce8fb5)

### Reproducible Demo

* Download https://github.com/microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version: 8.0.0
* react-native version: 0.72.10
* iOS/Android/Windows version: 13
* Does this reproduce on a debug build or release build? release build
* Does this reproduce on a simulator, or only on a physical device? physical

(The more info the faster we will be able to address it!)

**Comment by DordeDimitrijev** [comment] 2024-07-11 14:48
Hi @Invictus-Munish thank you for reaching out. I can't reproduce the issue you are encountering. Based on the logs i can see that you made some modifications which caused the hash value of the codepush folder to be changed and this shouldn't happen and that's why it cancels the update. Could you please share a demo app or steps to reproduce this issue?

**Comment by sontruongna** [comment] 2024-07-23 06:57
Same issue in Android

**Comment by yaoz0816** [comment] 2024-07-23 09:22
same issue in android

**Comment by yaoz0816** [comment] 2024-07-23 09:23
> Same issue in Android

hi, Have you solved it?

**Comment by DordeDimitrijev** [comment] 2024-07-23 09:39
Hi @sontruongna  @yaoz0816  could you please provide which version of react-native and react-native-code-push you are using?

**Comment by sontruongna** [comment] 2024-07-23 09:43
> Hi @sontruongna @yaoz0816 could you please provide which version of react-native and react-native-code-push you are using?

```
"react-native": "^0.74.2",
"react-native-code-push": "8.3.0",
```

Update: When i downgrade react-native-code-push version to 8.2.2 it worked

**Comment by DmitriyKirakosyan** [comment] 2024-07-26 01:27
The fix has been released. Closing.

**Closed by DmitriyKirakosyan** 2024-07-26 01:27 UTC
