### ISSUE TITLE
[android]Jsbundle has been updated, but all the pictures have disappeared.

### ISSUE THREAD

**Issue by chengkaigithub** [Microsoft/react-native-code-push#1354] opened 2018-07-18 08:39 UTC
### Actual Behavior
What actually happens?
```
For existing native adnroid application.
code-push release-react TestMPOSRN-android android --des "some info" -t 1.0.0 -d staging

Jsbundle has been updated, but all the pictures have disappeared.

I've been looking for it for a long time, but I haven't solved this problem. Please help me!
```

### Reproducible Demo

project: sorry! The project contains some private information, so it can not be provided for the time being.
but code-push-server is a private server, not to be open.

### Environment

* react-native-code-push version:5.4.0
* react-native version:0.56.0
* Android version:4.4.4
* Does this reproduce on a debug build or release build? debug and release
* Does this reproduce on a simulator, or only on a physical device? device

(The more info the faster we will be able to address it!)

```
07-18 16:18:32.039 8635-8635/com.suixingpay.reactNativeModule D/ReactNative: [CodePush] Loading JS bundle from "assets://index.android.bundle"
07-18 16:18:33.350 8635-8705/com.suixingpay.reactNativeModule I/ReactNativeJS: [CodePush] Sync already in progress.
07-18 16:18:33.359 8635-8705/com.suixingpay.reactNativeModule I/ReactNativeJS: [CodePush] Sync already in progress.
07-18 16:18:33.367 8635-8705/com.suixingpay.reactNativeModule I/ReactNativeJS: codePush.SyncStatus.CHECKING_FOR_UPDATE
07-18 16:18:33.371 8635-8705/com.suixingpay.reactNativeModule I/ReactNativeJS: [CodePush] Reporting binary update (1.0.0)
07-18 16:18:33.549 8635-8705/com.suixingpay.reactNativeModule I/ReactNativeJS: codePush.SyncStatus.DOWNLOADING_PACKAGE
07-18 16:18:36.359 8635-8704/com.suixingpay.reactNativeModule D/ReactNative: [CodePush] Applying full update.
07-18 16:18:36.367 8635-8705/com.suixingpay.reactNativeModule I/ReactNativeJS: codePush.SyncStatus.INSTALLING_UPDATE
07-18 16:18:36.394 8635-8705/com.suixingpay.reactNativeModule I/ReactNativeJS: codePush.SyncStatus.UPDATE_INSTALLED
07-18 16:18:42.950 8635-8635/com.suixingpay.reactNativeModule D/ReactNative: [CodePush] Loading JS bundle from "/data/data/com.suixingpay.reactNativeModule/files/CodePush/da694eed48aed0bd1501aba2d10044a02711c01aad332253052789ff6777ec6b/CodePush/index.android.bundle"
07-18 16:18:43.768 8635-8807/com.suixingpay.reactNativeModule I/ReactNativeJS: [CodePush] Sync already in progress.
07-18 16:18:43.782 8635-8807/com.suixingpay.reactNativeModule I/ReactNativeJS: [CodePush] Sync already in progress.
07-18 16:18:44.261 8635-8807/com.suixingpay.reactNativeModule I/ReactNativeJS: codePush.SyncStatus.CHECKING_FOR_UPDATE
07-18 16:18:44.265 8635-8807/com.suixingpay.reactNativeModule I/ReactNativeJS: [CodePush] Reporting CodePush update success (v4)
07-18 16:18:44.376 8635-8807/com.suixingpay.reactNativeModule I/ReactNativeJS: codePush.SyncStatus.UP_TO_DATE
```

**Comment by chengkaigithub** [comment] 2018-07-19 02:32
in assetPathUtils:
```
const drawableFileTypes = new Set([
  'gif',
  'jpeg',
  'jpg',
  'png',
  'svg',
  'webp',
  'xml',
]);

function getAndroidResourceFolderName(asset: PackagerAsset, scale: number) {
  // NOTE: When uploading updates, It is not empty.
  // FIXME: When running on a mobile phone, There is a {} printed here.
  console.log('code-push-res', drawableFileTypes);
  if (!drawableFileTypes.has(asset.type)) {
    return 'raw';
  }
  ......
}
```

So I wrote a method of traversing array and redefined a drawableFileTypesFix.
Modify the logic in the getAndroidResourceFolderName method.
```
const drawableFileTypesFix = [
    'gif',
    'jpeg',
    'jpg',
    'png',
    'svg',
    'webp',
    'xml',
];

const isInArray = (arr, value) => {
    for (var i = 0; i < arr.length; i++) {
        if (value === arr[i]) {
            return true;
        }
    }
    return false;
}

function getAndroidResourceFolderName(asset: PackagerAsset, scale: number) {
    ......
    if (!drawableFileTypes.has(asset.type) && !isInArray(drawableFileTypesFix, asset.type)) {
        return 'raw';
      }
    ......
}
```

I am not sure whether such a change is correct, but it works correctly.

**Comment by alexandergoncharov** [comment] 2018-07-19 09:01
Hi @chengkaigithub ,
Thanks for reporting!

It is interesting.
Could you please clarify what type of asset did you use?

Thanks,
Alexander

**Comment by chengkaigithub** [comment] 2018-07-19 09:30
Hello @alexandergoncharov ,
Thank you for your answer!

I used the PNG picture.
I output the asset.type，It's png.

Thanks,
ChengKai

**Comment by alexandergoncharov** [comment] 2018-07-19 14:38
@chengkaigithub Got it. And after this changes you successfully got your image in app?

**Comment by chengkaigithub** [comment] 2018-07-20 03:32
@alexandergoncharov Yes, the Android device can be updated normally. I'm going to try IOS today.

**Comment by chengkaigithub** [comment] 2018-07-20 05:55
@alexandergoncharov  I just tested IOS, and there's no problem for updating.

**Comment by alexandergoncharov** [comment] 2018-07-20 08:10
@chengkaigithub Thanks for this checking. Let me investigate this. 

Also, Is it possible to provide some test project with reproducing issue? You can just create clear project with your picture?  For app.js file code you can use example form this repo: https://github.com/Microsoft/react-native-code-push/blob/master/Examples/CodePushDemoApp/App.js

**Comment by chengkaigithub** [comment] 2018-07-20 23:50
@alexandergoncharov You can look at this project. I just deleted some sensitive information.

[https://github.com/chengkaigithub/TestPrimordialFuseRN.git](url)

**Comment by alexandergoncharov** [comment] 2018-07-23 19:04
Sure, Thanks for test project.
I'll let you know about this results.

**Comment by NickToropov** [comment] 2018-07-25 15:35
Hi @chengkaigithub, could you explain in more details how should we build your demo (may be step by step explanation)? If I open it in Android Studio and run it (press green triangle) then app turns out without js bundle at all. I also tried to generate signed release apk but result was the same. Did I miss any steps?

**Comment by chengkaigithub** [comment] 2018-07-26 02:17
Hello @NickToropov 
You need to execute the package script first before running the project.
Command is as follows(MAC):
./offlinePackageRN.sh android

**Comment by NickToropov** [comment] 2018-07-27 07:02
Thanks @chengkaigithub, I'll try it a bit later. I (or @alexandergoncharov) will back as soon as there are any news.

**Comment by alexandergoncharov** [comment] 2018-07-27 09:37
Hi @chengkaigithub ,

Unfortunately I also can't run your app. At first I run `./offlinePackageRN.sh android` and`npm i`.
Then I tried to run `react-native link` but got next Error:
> rnpm-install ERR! Something went wrong while linking. Error: ENOENT: no such file or directory, open '/Users/alexander.goncharov/Documents/TestPrimordialFuseRN/android/app/src/main/java/com/suixingpay/testmposrn/MainApplication.java' 
Please file an issue here: https://github.com/facebook/react-native/issues 
ENOENT: no such file or directory, open '/Users/alexander.goncharov/Documents/TestPrimordialFuseRN/android/app/src/main/java/com/suixingpay/testmposrn/MainApplication.java'

Also tried to run `react-native run-android` but got next error: 
>Scanning folders for symlinks in /Users/alexander.goncharov/Documents/TestPrimordialFuseRN/node_modules (16ms)
Android project not found. Maybe run react-native android first?

Could you please clarify if I miss something or could you please provide detailed steps for run your app?

Thanks,
Alexander

**Comment by chengkaigithub** [comment] 2018-07-28 10:07
@alexandergoncharov 
The first step:  npm install
Second steps:  react-native link
Third steps:  ./offlinePackageRN.sh android
Fourth parts:  Open android projects with studio
Fifth steps:  "./gradlew clean" run in AndroidStudio Terminal
Sixth steps: Run app in AndroidStudio

Recently, I was busy with a new project and I might not be able to respond promptly.

**Comment by NickToropov** [comment] 2018-07-30 08:02
Hi @chengkaigithub! It seems that something is missed in demo repository.
I got the following errors when tried to execute specified commands:
➜  TestPrimordialFuseRN git:(master) ✗ react-native link
Scanning folders for symlinks in ~/Projects/TestPrimordialFuseRN/node_modules (23ms)
? What is your CodePush deployment key for Android (hit <ENTER> to ignore) <here my key>
rnpm-install info Platform 'ios' module react-native-code-push is already linked
rnpm-install info Linking react-native-code-push android dependency
rnpm-install ERR! Something went wrong while linking. Error: ENOENT: no such file or directory, open `~/Projects/TestPrimordialFuseRN/android/app/src/main/java/com/suixingpay/testmposrn/MainApplication.java'
Please file an issue here: https://github.com/facebook/react-native/issues

ENOENT: no such file or directory, open '~/Projects/TestPrimordialFuseRN/android/app/src/main/java/com/suixingpay/testmposrn/MainApplication.java'
➜  TestPrimordialFuseRN git:(master) ✗ ./offlinePackageRN.sh android
--------------------------------- android 准备工作 ---------------------------------
创建目录: ./bundle/android
开始打包 android
Scanning folders for symlinks in ~/Projects/TestPrimordialFuseRN/node_modules (29ms)
Scanning folders for symlinks in ~/Projects/TestPrimordialFuseRN/node_modules (19ms)
Loading dependency graph, done.

SyntaxError: ~/Projects/TestPrimordialFuseRN/node_modules/react-native-scrollable-tab-view/SceneComponent.js: A trailing comma is not permitted after the rest element (9:32)

   7 |
   8 | const SceneComponent = (Props) => {
  9 |   const {shouldUpdated, ...props, } = Props;
     |                                 ^
  10 |   return <View {...props}>
  11 |       <StaticContainer shouldUpdate={shouldUpdated}>
  12 |         {props.children}

--------------------------------- 打包 android 结束 ---------------------------------
--------------------------------- android 移动文件开始 ---------------------------------
移动android文件到指定位置
cp: ./bundle/android/index.android.bundle: No such file or directory
cp: ./bundle/android/index.android.bundle.meta: No such file or directory
cp: ./bundle/android/drawable-hdpi/*: No such file or directory
cp: ./bundle/android/drawable-mdpi/*: No such file or directory
cp: ./bundle/android/drawable-xhdpi/*: No such file or directory
cp: ./bundle/android/drawable-xxhdpi/*: No such file or directory
cp: ./bundle/android/drawable-xxxhdpi/*: No such file or directory
--------------------------------- android 移动文件结束 ---------------------------------

and then in Android Studio terminal:
➜  android git:(master) ✗ ./gradlew clean
zsh: no such file or directory: ./gradlew

Could you please check one more time if everything is ok in repository and reprosteps?

**Comment by chengkaigithub** [comment] 2018-08-05 12:53
Hello @NickToropov !
I personally tried it today, and there really is a little problem.
Please try again under my process.
In the TestPrimordialFuseRN directory.

The first step:
 npm install

Second steps:
 create Folder: TestPrimordialFuseRN/android/react-native-module/src/main/assets

Third steps: 
/node_modules/react-native-scrollable-tab-view/SceneComponent.js 
Modify this line of code for this file: const {shouldUpdated, ...props, } = Props;
after modification: const {shouldUpdated, ...props } = Props;

Fourth steps: 
./offlinePackageRN.sh android

Fifth parts: 
Open android projects with studio.
Run app in AndroidStudio

CodePush deployment in the project requires you to create one yourself, and we do not allow it to be publicly available.

CodePush deployment can be modified in this file: TestPrimordialFuseRN/android/react-native-module/src/main/java/com/suixingpay/reactNativeModule/RNEntryActivity.java

After the app is launched, clicking on the HelloWorld text on the screen will load the RN interface.

Recently in the development of web projects, I encountered a problem similar to the Set does not exist.
Reference: [https://reactjs.org/docs/javascript-environment-requirements.html](https://reactjs.org/docs/javascript-environment-requirements.html)

But I don't have time to explore the feasibility of the reactjs link.

Recently busy, recovery is late, sorry.

**Comment by NickToropov** [comment] 2018-08-13 08:41
Hi @chengkaigithub! Thanks for detailed steps. I was able to reproduce the issue. It's definitely a weird behavior. Will continue to look for the cause of the problem. If you have any news or any investigation results please share them here. Will be in touch.

**Comment by NickToropov** [comment] 2018-09-18 13:11
Hey @chengkaigithub! Please take a look at [this thread](https://github.com/facebook/react-native/issues/19827). The main idea is that some classes are used before being declared by babel. In your app such code is: 
```
const drawableFileTypes = new Set([
  'gif',
   ...
]);
``` 
As a workaround try to modify your `index.js` to:
```
import {name as appName} from './app.json';
import {AppRegistry} from 'react-native';

AppRegistry.registerComponent(appName, () => require('./app/Root').default);
```
I've tested this approach and CodePush updates were installed and run properly(images are shown).

Also you can try to update RN to 0.57.0 and check if it helps as many dependencies related to babel were upgraded.

Please, let me know if it was helpful.

**Comment by chengkaigithub** [comment] 2018-09-20 08:58
Hello @NickToropov !
`AppRegistry.registerComponent(appName, () => require('./app/Root').default);`

I tried it and could fix it.
Thank you very much.

**Comment by NickToropov** [comment] 2018-09-20 09:50
Awesome! Do you have any other questions?

**Comment by chengkaigithub** [comment] 2018-09-21 01:30
Hi @NickToropov 
No other questions! Thanks!

**Comment by NickToropov** [comment] 2018-09-21 07:10
Thanks for using CodePush!

**Closed by NickToropov** 2018-09-21 07:10 UTC
Labels: bug, external, waiting-for-clarification
