### ISSUE TITLE
CodePushDownloader Issue on IOS

### ISSUE THREAD

**Issue by Malikkhoja** [microsoft/react-native-code-push#1834] opened 2020-04-07 07:34 UTC
Hi,

We installed the latest version of CodePush v6.2.0. After updating it the ios fails to build with the below error:
react-native-code-push/ios/CodePush/CodePushDownloadHandler.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

Can anyone help?

Thanks in advance

**Comment by YosefOberlander** [comment] 2020-04-14 22:38
same. any updates?

**Comment by spiandorello** [comment] 2020-04-15 02:43
same. any updates?

**Comment by YosefOberlander** [comment] 2020-04-17 19:45
Nope still broken.

**Comment by melihberberolu** [comment] 2020-04-27 12:03
Any updates ?

**Comment by Nirodha26** [comment] 2020-05-29 13:47
Facing the same issue.

**Comment by alexandergoncharov** [comment] 2020-06-05 10:46
Hi all,
Thanks for reporting!

Could please someone provide some demo app with reproducing issue and reprosteps? I would like to reproduce issue and investigate it.

**Comment by alexandergoncharov** [comment] 2020-06-16 11:49
Hi @melihberberolu, @YosefOberlander , @spiandorello, @melihberberolu, @Nirodha26,

Could please someone provide some demo app with reproducing issue and reprosteps? I would like to reproduce issue and investigate it.

**Comment by YosefOberlander** [comment] 2020-06-16 12:28
I'll do it when I come home tonight

**Comment by alexandergoncharov** [comment] 2020-06-23 08:43
Hi @YosefOberlander ,

Just a friendly ping :)

**Comment by YosefOberlander** [comment] 2020-06-23 23:56
@alexandergoncharov sorry for the delay. I'll try todo it tonight

**Comment by YosefOberlander** [comment] 2020-07-05 15:58
@alexandergoncharov Sorry for the late response. i finally tried to reproduce the error and it no longer happens. i used react-native 0.59.10

**Comment by alexandergoncharov** [comment] 2020-07-06 14:09
Oh, I see. Looks like that issue is gone with new versions.

So, I'm going to close this issue for now.
Please feel free to reopen it if you have any questions or face this issue again.

**Closed by alexandergoncharov** 2020-07-06 14:09 UTC
Labels: bug, no-repro, waiting-for-clarification
