### ISSUE TITLE
Decorating memoized component

### ISSUE THREAD

**Issue by Kerizer** [microsoft/react-native-code-push#2037] opened 2021-02-17 20:41 UTC
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Wrap functional component into `memo` function (imported from `react` or other library)
2. Decorate this component with codepush

### Expected Behavior
Codepush is working

### Actual Behavior
When checking if `render` method exists there is no check if `RootComponent.prototype` exists - and it does not exists if `RootComponent` is wrapped into `memo` - https://github.com/microsoft/react-native-code-push/blob/master/CodePush.js#L581
![image](https://user-images.githubusercontent.com/21887713/108264425-3090bd80-7170-11eb-9181-ecb999c81c81.png)

Simplest solution  would be to change `if (RootComponent.prototype.render) {` with `if (RootComponent.prototype && RootComponent.prototype.render) {` (let's say somebody really needs to use `memo` on the codepushuble component for whatever reason)

### Environment

* react-native-code-push version: 7.0.0
* react-native version: Any
* iOS/Android/Windows version: Any
* Does this reproduce on a debug build or release build? - Both
* Does this reproduce on a simulator, or only on a physical device? -Both

(The more info the faster we will be able to address it!)

**Comment by Kerizer** [comment] 2021-02-18 06:43
I can also send a PR in case if this is ok solution. If for some reason you don't want people to decorate memoized components it's also possible to throw some more descriptive error

**Comment by muxbert** [comment] 2021-08-10 14:21
@Kerizer I have the same issue when using mobX observer wrapper on the root component, did fix this issue?

**Comment by Kerizer** [comment] 2021-12-14 18:04
> This issue has been automatically marked as stale because it has not had any activity for 60 days. It will be closed if no further activity occurs within 15 days of this comment.

Not resolved yet

**Comment by pxpeterxu** [comment] 2022-01-06 04:09
Two workarounds:

### 1. Don't use `React.memo`

`React.memo` also has minimal benefits for the top-level component since by definition, it'll only get rendered once in your app, and its props are never going to change. You probably can get by without React.memo

### 2. Use React.memo, but fake it.

A quick workaround (since the only thing that [`App.prototype` is used for is to check if it has a `render()` function](https://github.com/microsoft/react-native-code-push/blob/v7.0.4/CodePush.js#L581), which functional components do not): just fake a prototype!

```tsx
let RootComponent = () => (
  return <View><Text>Hello world</Text></View>;
);

const RootComponentPrototype = RootComponent.prototype;
RootComponent = React.memo(RootComponent);
RootComponent.prototype = RootComponentPrototype;
```

In terms of an actual patch for this, we probably could add a `RootComponent.prototype && RootComponent.prototype.render` in the if statement on https://github.com/microsoft/react-native-code-push/blob/v7.0.4/CodePush.js#L581

**Comment by DmitriyKirakosyan** [comment] 2024-07-04 06:46
Closing as duplicate of https://github.com/microsoft/react-native-code-push/issues/2701.
The [PR](https://github.com/microsoft/react-native-code-push/pull/2705) is merged and the fix will be available in the next release.

**Closed by DmitriyKirakosyan** 2024-07-04 06:46 UTC
Labels: investigating, do not close
