### ISSUE TITLE
[Error]  unable to get local issuer certificate

### ISSUE THREAD

**Issue by alen252** [Microsoft/react-native-code-push#1104] opened 2017-12-12 10:49 UTC
### Steps to Reproduce
1.code-push login
2. input the token which is copyed from web

### Expected Behavior
login success

### Actual Behavior
What actually happens?

**[Error]  unable to get local issuer certificate**

### Environment

* react-native-code-push version:2.1.4
* react-native version:0.51.0
* iOS/Android/Windows version:Android
My computer is MAC OS

**Comment by sergey-akhalkov** [comment] 2017-12-12 11:09
Hi @alen252, thanks for reaching us. The issue looks very weird, just have tried to login using Mac - have no issues. Have you seen this solution https://github.com/nodejs/node/issues/3742#issuecomment-155545828 for the same issue in the nodejs repo?

**Comment by alen252** [comment] 2017-12-12 11:27
@sergey-akhalkov I execute "npm config set strict-ssl false". But this don't solve my problem.

**Comment by sergey-akhalkov** [comment] 2017-12-12 11:39
@alen252 , got it, could you please make sure you are not behind the proxy?

**Comment by alen252** [comment] 2017-12-12 11:49
@sergey-akhalkov Yes,I'm sure i don't set proxy.

**Comment by sergey-akhalkov** [comment] 2017-12-12 11:56
>Yes,I'm sure i don't set proxy.

What version of `code-push-cli` are you using? Could you please try to login via https://github.com/Microsoft/appcenter-cli ?

**Comment by alen252** [comment] 2017-12-12 12:06
@scottbommarito code-push version is 2.1.4 I don't have code-push-cli command. I try login via https://github.com/Microsoft/appcenter-cli. I login success.But code-push login still failed.

**Comment by sergey-akhalkov** [comment] 2017-12-12 12:37
>I try login via https://github.com/Microsoft/appcenter-cli. I login success.

Great, due to CodePush is a part of the AppCenter - you can use AppCenter CLI now.

>But code-push login still failed.

Hmm, haven't seen such kind of issues before, it's really hard to say what goes wrong here because I believe the issue is probably environment specific, but let's try the following:
1. `code-push logout`
2. `npm uni -g code-push-cli`
3. `npm i -g code-push-cli`
4. logout from the https://appcenter.ms/apps and the login
5. `code-push login`

Let me know if you have any changes.

**Comment by alen252** [comment] 2017-12-12 12:43
@sergey-akhalkov 
After 1-5, there is no change. The error still happen.

**Comment by sergey-akhalkov** [comment] 2017-12-12 12:56
@alen252 , do you have any issues with start using the new `appcenter-cli` instead of old `code-push-cli` (please take a look at for more info http://microsoft.github.io/code-push/)? The issue looks very specific and it does not reproduce nor for me nor for the rest of the CodePush team, also haven't seen such kind of issues before from the other customers.
I'm going to investigate it once again and let you know if I have any updates, but for now I believe you can start using new cli without any issues. 

Please let me know if you have any concerns or have any issues w/ the new cli.

**Comment by sergey-akhalkov** [comment] 2017-12-13 07:50
Closing this, please feel free to reopen and provide more info / exact repro steps that will help us to reproduce this issue.

**Closed by sergey-akhalkov** 2017-12-13 07:50 UTC
Labels: no-repro, question

**Comment by alen252** [comment] 2017-12-15 03:06
@sergey-akhalkov  I begin to user AppCenter CLI.But when i run "appcenter codepush release-react" command.I got a error:
Error: <HEAD><TITLE>Authentication Required</TITLE></HEAD>
<BODY BGCOLOR="white" FGCOLOR="black"><H1>Authentication Required</H1><HR>
<FONT FACE="Helvetica,Arial"><B>
</B></FONT>
<HR>

</BODY>

I feel it is hard to user code push in China.

**Comment by sergey-akhalkov** [comment] 2017-12-15 12:36
Hi @alen252, ahh I see, going to try to investigate why `codepush-management.azurewebsites.net` is probably blocked or so, btw we are going to use in the appcenter-cli another codepush service soon that should not have such kind of problem. Will let you know if I have any updates.
