### ISSUE TITLE
CodePush.checkForUpdate returns 503

### ISSUE THREAD

**Issue by eliorsp** [microsoft/react-native-code-push#1959] opened 2020-10-15 16:18 UTC
### Steps to Reproduce
1. call CodePush.checkForUpdate with key parameter
2. get 503 in network (console in catch)

### Expected Behavior
What you expected to happen?

### Actual Behavior
What actually happens?
This app work with code push long time,
today i get 503 from check for update function

  STACK TRACE AND/OR SCREENSHOTS
```
![image](https://user-images.githubusercontent.com/34032250/96157339-db6f4180-0f1a-11eb-92af-58a364f0527c.png)



### Environment

* react-native-code-push version:
5.6.1
* react-native version:
60
* iOS/Android/Windows version:
same
* Does this reproduce on a debug build or release build?
same
* Does this reproduce on a simulator, or only on a physical device?
same

**Comment by digital-tcbs** [comment] 2020-10-15 18:42
Same here!

**Comment by Krasavinigor** [comment] 2020-10-16 07:29
Hi @eliorsp @digital-tcbs! 
Thank you for reporting! 

We know about this issue. You are using RNCP lower than [v.5.7.0](https://github.com/microsoft/react-native-code-push/releases/tag/v5.7.0) and this problem may be using our legacy service, which is currently experiencing low availability. We are currently in the process of restoring it (see [#1952](https://github.com/microsoft/react-native-code-push/issues/1952) ).

The current service is stable, so I can suggest update react-native-push to the latest version.

**Comment by Krasavinigor** [comment] 2020-10-16 08:28
I'm going to close this issue as duplicate of #1952.

**Closed by Krasavinigor** 2020-10-16 08:28 UTC
