### ISSUE TITLE
android.view.WindowManager$BadTokenException

### ISSUE THREAD

**Issue by SudoPlz** [Microsoft/react-native-code-push#1258] opened 2018-04-16 15:49 UTC
Hey there,

we recently received the following crash from one of our devices in production:

```
android.view.WindowManager$BadTokenException Unable to add window -- token android.os.BinderProxy@1cd563c is not valid; is your activity running? 
    ViewRootImpl.java:903 android.view.ViewRootImpl.setView
    WindowManagerGlobal.java:372 android.view.WindowManagerGlobal.addView
    WindowManagerImpl.java:97 android.view.WindowManagerImpl.addView
    Dialog.java:408 android.app.Dialog.show
    CodePushDialog.java:91 com.microsoft.codepush.react.CodePushDialog.showDialogInternal
    CodePushDialog.java:47 com.microsoft.codepush.react.CodePushDialog.showDialog
    Method.java:-2 java.lang.reflect.Method.invoke
    JavaMethodWrapper.java:374 com.facebook.react.bridge.JavaMethodWrapper.invoke
    JavaModuleWrapper.java:162 com.facebook.react.bridge.JavaModuleWrapper.invoke
    NativeRunnable.java:-2 com.facebook.react.bridge.queue.NativeRunnable.run
    Handler.java:751 android.os.Handler.handleCallback
    Handler.java:95 android.os.Handler.dispatchMessage
    MessageQueueThreadHandler.java:31 com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage
    Looper.java:154 android.os.Looper.loop
    MessageQueueThreadImpl.java:194 com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run
    Thread.java:762 java.lang.Thread.run
```

could it be related to codepush trying to show a dialog while in the [Background Thread](https://stackoverflow.com/questions/18662239/android-view-windowmanagerbadtokenexception-unable-to-add-window-on-buider-s)?

"react-native-code-push": "5.2.2",
"react-native": "0.53.3",
Device: Physical, Android 7.0 API 24 Samsung SM-G955U

**Comment by buptkang** [comment] 2018-04-26 05:33
Hey, based on your given information, we cannot check what this exception root cause can be. We would suggest you to make another codepush release, which only disable the codepush dialog setting (updateDialog: false) without changing anything else. After that, you can monitor if such error is thrown again? Let us know if you have further concern.

**Comment by NickToropov** [comment] 2018-05-22 14:50
Hi @SudoPlz,
please take a look at my PR that should fix your issue

**Comment by NickToropov** [comment] 2018-05-24 15:16
Hi @SudoPlz,

we released new plugin version - 5.3.4 with fix for this issue.
Please, update your app with new plugin.

**Comment by NickToropov** [comment] 2018-05-25 07:06
@SudoPlz, I'll close this issue as it was resolved by hot fix but please feel free to reopen it if you have any questions or the issue turns out.

**Closed by NickToropov** 2018-05-25 07:06 UTC
Labels: android, bug

**Comment by SudoPlz** [comment] 2018-05-25 17:37
Will do, thanks @NickToropov I really appreciate it.
