### ISSUE TITLE
About incremental updates

### ISSUE THREAD

**Issue by dongbingbin77** [Microsoft/react-native-code-push#892] opened 2017-06-20 09:37 UTC
### Description

I saw the following fragment in the source code of codepush, it seems to be incrementally updated, but how can I use incremental updates? In the document and did not find the relevant command

### Reproduction

```
 String diffManifestFilePath = CodePushUtils.appendPathComponent(unzippedFolderPath,
                    CodePushConstants.DIFF_MANIFEST_FILE_NAME);
            boolean isDiffUpdate = FileUtils.fileAtPathExists(diffManifestFilePath);
            if (isDiffUpdate) {
                String currentPackageFolderPath = getCurrentPackageFolderPath();
                CodePushUpdateUtils.copyNecessaryFilesFromCurrentPackage(diffManifestFilePath, currentPackageFolderPath, newUpdateFolderPath);
                File diffManifestFile = new File(diffManifestFilePath);
                diffManifestFile.delete();
            }
```
### Additional Information

* react-native-code-push version:2.1.0-beta
* react-native version:0.44.3
* iOS/Android/Windows version:android

**Comment by sergey-akhalkov** [comment] 2017-06-20 14:36
Hi @dongbingbin77, thanks for reaching us, could you please clarify what do you mean by `incremental updates`?

**Comment by dongbingbin77** [comment] 2017-06-21 03:00
"incremental updates"，It should be: differential updates. From the codepush website to see this content: "The CodePush client supports differential updates, so even though you are releasing your JS bundle and assets on every update, your end users will actually download the files they Need the call handles this automatically so that you can focus on creating awesome apps and we can worry about optimization end user downloads.
And I would like to know how to use this function.

**Comment by sergey-akhalkov** [comment] 2017-06-21 09:18
@dongbingbin77, got it, thanks for the clarification. This feature works by default on code push server and there is no need to perform some additional actions from your side. But currently we have an issue with this feature https://github.com/Microsoft/cordova-plugin-code-push/issues/255 and we're working on it.

Please let me know if you have any questions or see any issues.

**Comment by dongbingbin77** [comment] 2017-06-21 10:21
Meaning that this function is the default, but now there are bugs, need to repair it? If so, I would like to know when to fix this problem?

**Comment by sergey-akhalkov** [comment] 2017-06-21 10:30
@dongbingbin77,

>Meaning that this function is the default, but now there are bugs, need to repair it?

Correct.

>If so, I would like to know when to fix this problem?

We are working on it and I'm hoping this will happen soon. Sorry for the inconvenience - I'll let you know if any updates,

**Comment by dongbingbin77** [comment] 2017-06-21 10:43
ok, thank you very much

**Comment by sergey-akhalkov** [comment] 2017-06-26 08:22
Hi @dongbingbin77, we've investigated it and found out the root cause of the issue. So the fix has been implemented and we are going to test it and verify if everything is ok.
I hope that we'll deploy the fix to Prod soon (I suppose it will happen on this week). Ones again - sorry for the inconvenience and for the delay.

**Comment by sergey-akhalkov** [comment] 2017-06-26 13:09
Hi @dongbingbin77, the fix has been deployed, please release new update and verify if it works.

**Closed by sergey-akhalkov** 2017-06-26 13:09 UTC
Labels: bug, fix-in-master

**Comment by dongbingbin77** [comment] 2017-07-01 23:42
thank you very much
