### ISSUE TITLE
Can't access https://codepushupdates.azureedge.net/storagev2

### ISSUE THREAD

**Issue by karlFrascari2** [Microsoft/react-native-code-push#1513] opened 2019-01-28 19:31 UTC
### Steps to Reproduce
1. Try to access https://codepushupdates.azureedge.net/storagev2/some-valid-key using WIFI
2. Note that the page don't load
3. If I turn off my WiFi, using my phone internet, it works!

### Expected Behavior
Download the package and install code push on both (Ios and Android)

### Actual Behavior
The page doesn't load and the package is not downloaded

![image](https://user-images.githubusercontent.com/9298260/51861001-42515f00-2322-11e9-82d4-b75abf2959b4.png)

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version: 5.4.2
* react-native version: 0.57.5
* iOS/Android/Windows version: 9/9
* Does this reproduce on a debug build or release build? Both
* Does this reproduce on a simulator, or only on a physical device? Both

Hey guys! thanks for helping! Is there any issue with code push servers? I am able to download the bundle only via mobile network! On Wifi it does not work! And I am pretty sure that there is internet connection on it. :/

**Comment by yuri-kulikov** [comment] 2019-01-30 07:21
Hi @karlFrascari2 
Thanks for reporting and sorry for the delay!

Could you confirm if the problem is still relevant to you?
I tried to download a blob from `https://codepushupdates.azureedge.net/storagev2/{some-valid-key}` and it worked fine for me.

**Comment by karlFrascari2** [comment] 2019-01-30 15:52
Hi Yuri thanks for the answers! 

So the problem is that  https://codepushupdates.azureedge.net/storagev2/ is intermittent, some times works sometimes I receive a 401. 

This is happening for a lot of users. Do I need to whitelist these URLs in react-native code somewhere?

**Comment by yuri-kulikov** [comment] 2019-01-31 07:17
@karlFrascari2, can you try to download it from here:
```
https://codepush.blob.core.windows.net/storagev2/{key}
```
And where did you find the route previously?

**Comment by yuri-kulikov** [comment] 2019-03-04 14:15
Hey, @karlFrascari2
Sorry for this unforgivably long delay!

Are you still experiencing this problem?
I tried to find information regarding this issue but unfortunately didn't find anything new...

**Comment by yuri-kulikov** [comment] 2019-03-18 12:20
Unfortunately, we haven’t heard from you in a while, so I'll close the issue for now, but please feel free to reopen it if you have some additional details or questions.

**Closed by yuri-kulikov** 2019-03-18 12:20 UTC
Labels: waiting-for-clarification
