### ISSUE TITLE
Why codepush does not download the latest version

### ISSUE THREAD

**Issue by davenlin19** [microsoft/react-native-code-push#1921] opened 2020-08-06 07:46 UTC
I installed CodePush on my react-native app (ios) and it seems to work but in a strange way.

The current version of my app is 1.5.7. This is how I implement codepush in my index.js code:

```
    import App from './App';
    import {AppRegistry} from 'react-native';
    import {Provider} from 'react-redux';
    import codePush from 'react-native-code-push';

    function HeadlessCheck({ isHeadless }) {
        if (isHeadless) {
            return null;
        }

        return <Provider store={store}><App /></Provider>;
    }

    AppRegistry.registerComponent(appName, () => codePush(HeadlessCheck));
```

Then I create an app version 1.5.7 on Apple Store, a 1.5.7 version on AppCenter.
1 day later when Apple validated my app, I create a new version 1.5.8 on AppCenter with some changes on my code.

But my app only updates to the 1.5.7 (I saw the number of download and install of this version on AppCenter increase). But the number of download of the 1.5.8 version stays 0.

Why my app can not reach the latest version? Please help me!
Thank you!

**Comment by andreidubov** [comment] 2020-08-07 07:52
Hi @davenlin19 
Thanks for the reporting.

Unfortunately, I was not able to reproduce this problem myself. Could you provide more context so that I can investigate and reproduce the issue? 

It would be nice to have some of the following information:
* What versions of react-native-code-push and react-native are you using.
* How did you set up react-native-code-puhs in your project?
* Steps to reproduce the issue, or what steps do you take to run the application.
* Logs of your device (it will be marked as [CodePush]).
* Have you tested the release of the update before publishing the application to the AppStore, if so, then it worked ok?

If possible could you please provide a test project with the issue.

**Comment by davenlin19** [comment] 2020-08-07 15:21
Hi @andreidubov Thanks for replying me!

This is the required information:
- react-native-code-push: 6.3.0
- react-native: 0.62.2

**How did I setup react native code push?**
I followed the first 5 steps for IOS: https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-ios.md
I used Staging deployment key.

**Steps to reproduce the issue**
- I use XCode to run the project (I already configured the run configuration to Release) in a simulator.
- I saw CodePush tried to refresh my app, but still version 1.5.7. I don't really understand why, because my local version is 1.5.7 and codepush refresh my app on start, to get the 1.5.7 version from appcenter, again? (I saw the number of download and install on appcenter for the 1.5.7 increase).
- Then I tried to add some code, then push a new version 1.5.8 to appcenter. Close the app and re-open it, nothing happens.

**Log**
Could you please help me how to show log in release mode?
Does CodePush work in debug mode? So I can have a log to share with you

Thank you @andreidubov!

**Comment by ruslan-bikkinin** [comment] 2020-09-30 15:20
Hi @davenlin19 and sorry for the late response. Are you still experiencing the issue?

**Comment by ruslan-bikkinin** [comment] 2020-10-08 09:28
Closing this due to inactivity. Feel free to reopen if needed.

**Closed by ruslan-bikkinin** 2020-10-08 09:28 UTC
Labels: investigating, waiting-for-clarification
