### ISSUE TITLE
ios build failed

### ISSUE THREAD

**Issue by wuyunqiang** [Microsoft/react-native-code-push#891] opened 2017-06-20 03:54 UTC
* react-native-code-push version: "^2.1.0-beta"
* react-native version:"0.44.3"
* react: "16.0.0-alpha.6"
* iOS/Android/Windows version: "ios"
* Does this reproduce on a debug build or release build?  "debug"
* Does this reproduce on a simulator, or only on a physical device? "simulator"

npm install --save react-native-code-push@latest
react-native link react-native-code-push
then react-native run-ios 

 error: implicit declaration of function 'RCTSharedApplication' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
UIViewController *vc = [[[RCTSharedApplication() delegate] window] rootViewController];

error: bad receiver type 'int'
  UIViewController *vc = [[[RCTSharedApplication() delegate] window] rootViewController];
                            ^~~~~~~~~~~~~~~~~~~~~~
2 errors generated.

**Comment by sergey-akhalkov** [comment] 2017-06-20 07:37
Hi @wuyunqiang, thanks for reaching us. I'm not able to reproduce the issue with the steps you has provided (before your steps I've performed `react-native init` command to create clean RN project) - please provide us more info regarding your project (source code, app sample, etc.)

**Comment by wuyunqiang** [comment] 2017-06-20 08:41
@sergey-akhalkov  I try to perform 'rnpm unlink react-native-code-push' 
and react-native link react-native-code-push
but still here.

 error: implicit declaration of function 'RCTSharedApplication' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  UIViewController *vc = [[[RCTSharedApplication() delegate] window] rootViewController];
                            ^
 error: bad receiver type 'int'
  UIViewController *vc = [[[RCTSharedApplication() delegate] window] rootViewController];
                            ^~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
** BUILD FAILED **

Android is ok.
I don't konw ios.

**Comment by sergey-akhalkov** [comment] 2017-06-20 09:14
@wuyunqiang, please take a look at [Plugin Installation (iOS - Manual)](https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-ios.md#plugin-installation-ios---manual) and check if your app has been configured in the same way or not. Please let me know if any updates.

**Comment by sergey-akhalkov** [comment] 2017-06-23 15:08
Closing this for now, please feel free to reopen if needed.

**Closed by sergey-akhalkov** 2017-06-23 15:08 UTC
Labels: iOS, no-repro
