### ISSUE TITLE
Unable to parse env variable when using code-push release command

### ISSUE THREAD

**Issue by 2ducanhpham** [Microsoft/react-native-code-push#859] opened 2017-05-25 04:38 UTC
my file .env
VERSION=1.0.0

when code push android & ios error : version name

_ex: Detecting android app version:
[Error]  No property named "env.get(VERSION)" exists in the "android/gradle.properties" file._

* react-native-code-push version: 1.7.4
* react-native version: 0.42.3
*react-native-config v0.4.2

**Comment by max-mironov** [comment] 2017-05-25 10:54
Hi @2ducanhpham, thank  you for your question.
Could you please give me a little guidance how I can reproduce your problem from the scratch?
Have you followed configuration steps described here https://github.com/luggit/react-native-config#android?
Also is it possible for you to verify if the issue reproduces without code-push plugin installed?

**Comment by 2ducanhpham** [comment] 2017-05-25 11:01
Everything work fine if I hard code VERSION in Xcode & versionName in android/app/build.gradle

But not good with environment variable

**Comment by max-mironov** [comment] 2017-05-26 12:33
@2ducanhpham thank you for your reply. Could you please double check that the issue is relative to code-push? (i.e. remove code-push, add logic that grabs env variable somewhere and check to see if you have issue like this one:
```ex: Detecting android app version:
[Error] No property named "env.get(VERSION)" exists in the "android/gradle.properties" file.
```
Please let us know the results.

**Comment by 2ducanhpham** [comment] 2017-05-27 04:23
Android:

    defaultConfig {
        applicationId project.env.get("BUNDLE_ID")
        minSdkVersion 16
        targetSdkVersion 22
        versionCode project.env.get("BUILD_NUMBER").toInteger()
        versionName project.env.get("VERSION")
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        manifestPlaceholders = [ FABRIC_KEY:project.env.get("FABRIC_KEY") ]
    }

IOS:
<key>CFBundleShortVersionString</key>
	<string>__RN_CONFIG_VERSION</string>

**Comment by max-mironov** [comment] 2017-05-31 09:24
Hi again @2ducanhpham, sorry for delay in response, I believe I've got your point. 

So the issue you have faced arrises because our CLI does not have logic to parse env variables in gradle/plist files (basically all the parsing "magic" is done [here](https://github.com/Microsoft/code-push/blob/master/cli/script/command-executor.ts#L887)). 

Probably we could think about support for parsing env variables but anyway there can be issues because different modules can vary in API (e.g. [dotenv](https://www.npmjs.com/package/dotenv) uses **process.env.VARNAME** whereas  other library can use other semantics like this one **project.env.get("VARNAME")** etc.

For your particular case I think that [general](https://github.com/Microsoft/code-push/tree/master/cli#releasing-updates-general) release form will be suitable.
So you just define your version nave as a parameter here and it should work.

Please let us know the results.

**Comment by 2ducanhpham** [comment] 2017-06-02 04:10
Thanks you so much. I hope microsoft can create a better integrated library of environment variables.
This is necessary for all applications when deploy

**Comment by max-mironov** [comment] 2017-06-02 04:26
@2ducanhpham - got it and thank you for your feedback. We are constantly working on improving the product, so I believe this can be addressed somewhere in future. 
If you don't mind I'm closing the issue currently, feel free to reach us if any questions.

**Closed by max-mironov** 2017-06-02 04:26 UTC
Labels: waiting-for-clarification

**Comment by SameeraMadushan** [comment] 2021-03-04 13:37
Is this feature available now? 
Still, I'm getting `"No property named "env.get(APP_VERSION)"` when passing env variables with appcenter command.
