### ISSUE TITLE
Integrated into an existing iOS app. RCTFatalException, invoking sendRequest on target Networking with params.

### ISSUE THREAD

**Issue by eshwartm** [Microsoft/react-native-code-push#1313] opened 2018-06-08 06:12 UTC
### Steps to Reproduce
1. Followed all the steps to integrate react native code push in an existing iOS app with Cocoapods. 
2. Followed all the steps to integrate multi deployment i.e., creating a `Staging` configuration.

### Expected Behavior
What you expected to happen?

Run properly.

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS

Terminating app due to uncaught exception 'RCTFatalException: Exception '*** -[__NSArrayM objectAtIndex:]: index 2 beyond bounds [0 .. 1]' was thrown while invoking sendRequest on target Networking with params (
    GET,
    "https://codepush.azurewebsites.net/updateCheck?deploymentKey=&appVersion=&packageHash=&isCompanion=&label=&clientUniqueId=",
    1,
        (
                (
            accept,
            "application/json"
        ),
                (
            "content-type",
            "application/json"
        ),
                (
            "x-codepush-plugin-name",
            "react-native-code-push"
        ),
                (
            "x-codepush-plugin-version",
            "5.3.4"
        ),
                (
            "x-codepush-sdk-version",
            "2.0.5"
        )
    ),
        {
        trackingName = unknown;
    },
    blob,
    0,
    0,
    1
)
callstack: (
	0   CoreFoundation                      0x0000000112072d4b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000111ad421e objc_exception_throw + 48
	2   CoreFoundation                      0x0000000111fa42eb -[__NSArrayM objectAtIndex:] + 203
	3   React                               0x000000010f1e4f8e -[RCTModuleMethod invokeWithBridge:module:arguments:] + 367
	4   React                               0x000000010f1e7f12 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 266
	5   React                               0x000000010f1e7c8c ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 78
	6   libdispatch.dylib                   0x0000000113559978 _dispatch_call_block_and_release + 12
	7   libdispatch.dylib                   0x00000001135830cd _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x0000000113560e17 _dispatch_queue_serial_drain + 236
	9   libdispatch.dylib                   0x0000000113561b4b _dispatch_queue_invoke + 1073
	10  libdispatch.dylib                   0x000000011356202b _dispatch_queue_override_invoke + 683
	11  libdispatch.dylib                   0x0000000113564385 _dispatch_root_queue_drain + 720
	12  libdispatch.dylib                   0x0000000113564059 _dispatch_worker_thread3 + 123
	13  libsystem_pthread.dylib             0x00000001139361ca _pthread_wqthread + 1387
	14  libsystem_pthread.dylib             0x0000000113935c4d start_wqthread + 13
)', reason: 'Exception '*** -[__NSArrayM objectAtIndex:]: index 2 beyond bounds [0 .. 1]...'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000112072d4b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000111ad421e objc_exception_throw + 48
	2   React                               0x000000010f1a2a46 RCTGetFatalHandler + 0
	3   React                               0x000000010f1e8126 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 798
	4   React                               0x000000010f1e7c8c ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 78
	5   libdispatch.dylib                   0x0000000113559978 _dispatch_call_block_and_release + 12
	6   libdispatch.dylib                   0x00000001135830cd _dispatch_client_callout + 8
	7   libdispatch.dylib                   0x0000000113560e17 _dispatch_queue_serial_drain + 236
	8   libdispatch.dylib                   0x0000000113561b4b _dispatch_queue_invoke + 1073
	9   libdispatch.dylib                   0x000000011356202b _dispatch_queue_override_invoke + 683
	10  libdispatch.dylib                   0x0000000113564385 _dispatch_root_queue_drain + 720
	11  libdispatch.dylib                   0x0000000113564059 _dispatch_worker_thread3 + 123
	12  libsystem_pthread.dylib             0x00000001139361ca _pthread_wqthread + 1387
	13  libsystem_pthread.dylib             0x0000000113935c4d start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

### Environment
```
"dependencies": {
    "appcenter": "^1.4.0",
    "react": "16.2.0",
    "react-native": "^0.54.2",
    "react-native-code-push": "^5.3.4",
    "watchman": "^1.0.0"
  }
```
* iOS/Android/Windows version: iOS version 10.2 iPhone 6 simulator
* Does this reproduce on a debug build or release build? `Staging` (that is a duplicate Release build)
* Does this reproduce on a simulator, or only on a physical device? Simulator. Not tried on physical device.

Additional info:

https://react-native.canny.io/feature-requests/p/xmlhttprequest-exception-thrown-while-invoking-sendrequest-on-target-rctnetworking-with-params

**Comment by eshwartm** [comment] 2018-06-08 06:14
`deploymentKey` in the URL removed for obvious reasons.

**Comment by NickToropov** [comment] 2018-06-08 20:19
Hi @eshwartm, thanks for posting the issue.
Please could you provide us with more detailed steps or/and demo apps that reproduce your issue?

**Comment by eshwartm** [comment] 2018-06-09 01:49
[rct_native.zip](https://github.com/Microsoft/react-native-code-push/files/2086537/rct_native.zip)

I have attached a sample project. You need to run `npm install` on the root folder, and maybe `gem install` and `pod install` in the iOS project folder inside the root folder.

**Comment by eshwartm** [comment] 2018-06-09 02:01
When I comment out the line that says `codePush(SimpleView)` which is what links the component to Code Push, I don't get any errors.

**Comment by NickToropov** [comment] 2018-06-11 12:30
Hi @eshwartm, I've done the specified steps but can't build the project. I get `No such module 'React'` in AppDelegate.swift file. Any suggestions how to fix it?

**Comment by eshwartm** [comment] 2018-06-11 12:57
will get back to you after checking. Need 10 minutes

**Comment by eshwartm** [comment] 2018-06-11 13:13
- I run `npm install` on the root folder i.e., `rct-native`. 
- Then I `cd` into `rct-native-test`, run `bundle install`, and `pod install`.
- If `pod install` fails, comment out the `plugin cocoapods-fix-react-native` line in the Podfile, and run `pod install` again.
- And then uncomment the same line (`plugin cocoapods-fix-react-native`) and run `pod install` again.
- At this point, I run `npm start` on the root folder (`rct-native`).
- I clean the xcode project and build it anyway (inspite of the error message `'No such module React'`)

**Comment by eshwartm** [comment] 2018-06-11 13:14
I suggest you try cleaning and running the project first.

**Comment by NickToropov** [comment] 2018-06-11 15:56
I've already tried it many times

**Comment by NickToropov** [comment] 2018-06-13 09:57
Hi @eshwartm, I think I was able to reproduce your issue. Please try to rename your file  `index.android.js` to `index.ios.js` and let me know if it was helpful.

**Comment by NickToropov** [comment] 2018-06-20 06:52
Hi @eshwartm, I'll close this issue for now but please feel free to reopen it if you have any questions.

**Closed by NickToropov** 2018-06-20 06:52 UTC
Labels: iOS, waiting-for-clarification

**Comment by ksairi** [comment] 2018-11-22 22:36
Hi all!
I have a situation with codepush v5.4.2, react-native v0.57.3 in iOS v11.4.1, Xcode v9.4.2
I followed the manual instructions and I have the same structure as @nodesman mentions.
Here is how it is set up:

``class DirectDrinks extends React.Component {``
``render () {``
``return (``
        ``<Provider store={store}>``
          ``<App />``
        ``</Provider>``
     ``)``
    ``}``
  ``}``
 ``const DirectDrinksContainer = __DEV__ ?  DirectDrinks : codePush(DirectDrinks)
  AppRegistry.registerComponent('DirectDrinks', () => DirectDrinksContainer)
}``

This is the error:

``DirectDrinks Rep Staging[1019:756474] *** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: undefined is not an object (evaluating 'h.init')', reason: 'Unhandled JS Exception: undefined is not an object (evaluating 'h.init'), stack:
init@725:583
<unknown>@658:787
n@2:553
<unknown>@654:808
n@2:553
<unknown>@653:148
n@2:553
<unknown>@651:381
n@2:553
<unknown>@647:658
n@2:553
<unknown>@641:349
n@2:553
<unknown>@640:79
n@2:553
<unknown>@337:380
n@2:553
<unknown>@336:79
n@2:553
<unknown>@335:79
n@2:553
<unknown>@334:79
n@2:553
<unknown>@328:206
n@2:553
<unknown>@327:79
n@2:553
<unknown>@13:913
n@2:553
<unknown>@12:30
n@2:553
i@2:266
global code@1069:9
'
*** First throw call stack:
(0x1822d2d8c 0x18148c5ec 0x100b58478 0x100b54960 0x1822da580 0x1821b9748 0x1821be56c 0x100b6c384 0x100bb3054 0x100bb2db0 0x181bc4aa0 0x181bc4a60 0x181bce9b4 0x181bcf2fc 0x181bcfcc8 0x181bd8098 0x181ef7e70 0x181ef7b08)
libc++abi.dylib: terminating with uncaught exception of type NSException``

In `__DEV__` no crashes, but when ``codepush()`` function executes, it crashes
