### ISSUE TITLE
Task :app:generateBundledResourcesHashRelease FAILED  no such file or directory, scandir   /react-native-code-push/scripts/getFilesInFolder.js jenkins

### ISSUE THREAD

**Issue by Ancy1** [microsoft/react-native-code-push#1771] opened 2020-01-24 15:59 UTC
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.
2. 
3.

### Expected Behavior
What you expected to happen?

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version:
* react-native version:
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by Ancy1** [comment] 2020-01-28 09:19
Any Suggestions

**Comment by alexandergoncharov** [comment] 2020-02-14 12:35
Hi @Ancy1 ,
Thanks for reporting!

Could you pelase provide more repro steps or test projecti with reproducing issue? Because it isn't clear how we can rperoduce it.
I'm going to close this issue for now. Please feel free to reopen it if you have any questions.

**Closed by alexandergoncharov** 2020-02-14 12:35 UTC
