### ISSUE TITLE
REACT_NATIVE  not updating

### ISSUE THREAD

**Issue by ronitpattjoshi** [Microsoft/react-native-code-push#877] opened 2017-06-07 12:19 UTC
i have successfully updated using (codePushOptions) in terminal but i didn't get an update after restarting an Application also in android.

**Comment by ronitpattjoshi** [comment] 2017-06-08 06:12
Can you help me to get through my issue please?

**Comment by max-mironov** [comment] 2017-06-08 06:52
Hey @ronitpattjoshi. sorry for delay in response. So could you please describe your issue in more details i.e. 
a) Explain what you did, what you expected to happen, and what actually happens. Also exact reproduction steps and stack trace will be much appreciated.
b) If possible try to reproduce your bug on our basic sample: https://github.com/Microsoft/react-native-code-push/tree/master/Examples/CodePushDemoApp. If you can't reproduce the bug on it, provide us as much info as possible about your project, how you initiate code-push, may be you can share with us basic sample.

Also additional information like:
* react-native-code-push version
* react-native version
* Android version
* Does this reproduce on a debug build or release build

would be also very useful for us.

**Comment by ronitpattjoshi** [comment] 2017-06-08 08:48
Hi, 
Thanks for replying.
i have followed your documentation and written each and every code in AndroidStudio and my .js file in React-Native and successfully uploading but when i am trying to update my Application its saying your app is up to date.
Its a debug build.    
when i am running the code (code-push deployment ls sampleBlur -k) then its sayings no install recorded

**Comment by max-mironov** [comment] 2017-06-08 08:59
@rahuljiresal  - thanks for reply. 
So in general CodePush updates should be tested in modes other than Debug mode. In Debug mode, React Native app always downloads JS bundle generated by packager, so JS bundle downloaded by CodePush does not apply. 

Also what is the output for `code-push deployment history <AppName> <DeploymentName>` command? Can you confirm that your target binary version match the bundle binary version your are running? Can you please double check that deployment key points to correct Deployment?
And do I get it right that CodePush in your application is initialized the same way as we do in our example?

**Comment by ronitpattjoshi** [comment] 2017-06-08 13:47
Heh thanks for the reply.
After running  code-push deployment history <AppName> <DeploymentName>
I got only two version updated but other are saying NO install recorder.
where do I got the target binary version and bundle binary version?
The deployment key will be same for every push right?
Code push has initialize the same as of yours

**Comment by max-mironov** [comment] 2017-06-08 14:18
@ronitpattjoshi 
So you see that you have not empty Install Metrics for two versions, correct? Could you paste the output here to make it clear?
Please have a look at [docs ](https://github.com/Microsoft/code-push/tree/master/cli#target-binary-version-parameter)how to specify Target Binary Version. Bundle version could be specified in `build gradle` file.
The deployment key specified in your application should match the deployment key associated with the deployment for which you are producing the updates via code-push CLI.

**Comment by max-mironov** [comment] 2017-06-13 07:04
@ronitpattjoshi - do you have a chance to look at this? Please let us know if any further questions.

**Comment by max-mironov** [comment] 2017-06-15 06:57
Closing this for now, please feel free to reopen if you still face the issue or have any further questions.

**Closed by max-mironov** 2017-06-15 06:57 UTC
Labels: question

**Comment by ronitpattjoshi** [comment] 2017-07-21 09:44
I have download your project from Github but still i am getting error saying "An unknown error occurred"
