### ISSUE TITLE
CodePush update rollback

### ISSUE THREAD

**Issue by mxc7609** [Microsoft/react-native-code-push#1357] opened 2018-07-20 11:10 UTC
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.Adding RN pages in Android Native Project. 
2. Set ReactInstanceManager
`
ReactInstanceManagerBuilder builder = ReactInstanceManager.builder()
                    .setApplication(application)
                    .setJSMainModulePath("index")
                    .setUseDeveloperSupport(false)
                    .addPackage(new MyReactPackage())
                    .addPackage(new MainReactPackage())
                    .addPackage(new RNCameraPackage())
                    .addPackage(new CodePush(BuildConfig.CODEPUSH_KEY,context.getApplicationContext(),BuildConfig.DEBUG))
                    .setUseDeveloperSupport(BuildConfig.DEBUG);
            builder.setJSBundleFile(CodePush.getJSBundleFile());
            builder.setInitialLifecycleState(LifecycleState.BEFORE_CREATE);
            mReactInstanceManager = builder.build();
            mReactInstanceManager.createReactContextInBackground();
`
3.SetContentView
`
mReactRootView = MyReactInstanceManager.getInstance().getRootView(this, bundle);
        setContentView(mReactRootView);
`
4. My react code
`
MyApp=codePush(MyApp);

AppRegistry.registerComponent('dakaApp', () => MyApp);
`
5. Run application and CodePush updated.
07-20 18:58:33.076 10240-10299/? I/ReactNativeJS: Installing update.
07-20 18:58:33.123 10240-10299/? I/ReactNativeJS: Update installed.
6. Restart Application updated rollback.
07-20 19:03:16.453 10909-10991/? I/ReactNativeJS: [CodePush] An update is available, but it is being ignored due to having been previously rolled back.

### Expected Behavior
What you expected to happen?
Restart application with update installed.

### Actual Behavior
What actually happens?
One of my phone rollback with error:
Could not open file/data/data/com.zl.daka/files/CodePush/b6c42430143519b4dc93cbd4237bcd887db71bd97f0fac54029dc1721760a628/CodePush/index.android.bundle: No such file or directory

The other one download update every time i restart my application. All images are not visible before download finished.

### Environment

* react-native-code-push version:5.4.0
* react-native version:0.55.4
* iOS/Android/Windows version: 26.0.1
* Does this reproduce on a debug build or release build? release build
* Does this reproduce on a simulator, or only on a physical device? both

**Comment by buyuxing** [comment] 2018-07-23 08:02
i add the follow code:

let codePushOptions = {checkFrequency: CodePush.CheckFrequency.MANUAL};
App = CodePush(codePushOptions)(App)
export default App

it wouldn't rollback anymore

**Comment by mxc7609** [comment] 2018-07-23 08:08
Released my update using 'code-push release-react MyApp-Android android'.

In my project, jsBundle pre-loaded in onCreate Method of MyApplication.

`
@Override
    public void onCreate() {
        super.onCreate();
        MyReactInstanceManager.getInstance().init(this);
`

Code for MyReactInstanceManager:

`
public static MyReactInstanceManager getInstance() {
        if (mInstance == null) {
            synchronized (MyReactInstanceManager.class) {
                if (mInstance == null) {
                    mInstance = new MyReactInstanceManager();
                }
            }
        }
        return mInstance;
    }

    /**
     * @param context
     */
    public void init(Context context) {
        getReactInstanceManager(context);
    }

    /**
     * @param context
     * @return
     */
    public ReactInstanceManager getReactInstanceManager(Context context) {
        Application application = (Application) context.getApplicationContext();
        if (mReactInstanceManager == null) {
            ReactInstanceManagerBuilder builder = ReactInstanceManager.builder()
                    .setApplication(application)
                    .setJSMainModulePath("index")
                    .addPackage(new MyReactPackage())
                    .addPackage(new MainReactPackage())
                    .addPackage(new RNCameraPackage())
                    .addPackage(new CodePush(BuildConfig.CODEPUSH_KEY,context.getApplicationContext(),BuildConfig.DEBUG))
                    .setUseDeveloperSupport(BuildConfig.DEBUG);
            builder.setJSBundleFile(CodePush.getJSBundleFile());
            builder.setInitialLifecycleState(LifecycleState.BEFORE_CREATE);
            mReactInstanceManager = builder.build();
//            CodePush.setReactInstanceHolder(new ReactInstanceHolder() {
//                @Override
//                public ReactInstanceManager getReactInstanceManager() {
//                    return mReactInstanceManager;
//                }
//            });
            mReactInstanceManager.createReactContextInBackground();
        }
        return mReactInstanceManager;
    }
`

I tried build reactInstanceManager inside Activity, it works. But it leads to a blank screen for the first time react pages open. With pre-load, CodePush always rolled back.

Thanks for the help~

**Comment by NickToropov** [comment] 2018-07-25 15:55
Hi guys!
 
@buyuxing, the cause of your problem is that you didn't call `CodePush.notifyAppReady()`. Please see this [doc](https://github.com/Microsoft/react-native-code-push/blob/master/docs/api-js.md#codepushnotifyappready)

@mxc7609, could you please share the output of command `code-push deployment history MyApp-Android <your-deployment[Staging|Production|AnyOther]> --format=json` and it would be very helpful if you could create a demo project that reproduces the issue as it's hard to say what is wrong in your project now.

**Comment by buyuxing** [comment] 2018-07-26 01:46
@NickToropov Thanks for help

after review the code of CodePush i realized that

function codePushify(options = {}) {
    ...
    var decorator = (RootComponent) => {
    const extended = class CodePushComponent extends React.Component {
      componentDidMount() {
        if (options.checkFrequency === CodePush.CheckFrequency.MANUAL) {
          CodePush.notifyAppReady();
        } else {  
        ...
        }
so add  CodePush(codePushOptions)(App) works
but i 'm comfusing why iOS don't need CodePush.notifyAppReady() to be called.

**Comment by NickToropov** [comment] 2018-07-30 10:18
Hi @buyuxing, it's very strange. I've just checked it. Both Android and iOS rolled back. Could you please provide us with simple demo project that reproduces different behavior?

**Comment by NickToropov** [comment] 2018-08-06 07:47
Hey guys! 
We haven’t heard from you in a while, so I am going to go ahead and close this issue. If you still have any questions, you can reopen this one or if you prefer you can create a new issue.

**Closed by NickToropov** 2018-08-06 07:47 UTC
Labels: android, bug, waiting-for-clarification

**Comment by gwl002** [comment] 2019-04-17 08:51
> i add the follow code:
> 
> let codePushOptions = {checkFrequency: CodePush.CheckFrequency.MANUAL};
> App = CodePush(codePushOptions)(App)
> export default App
> 
> it wouldn't rollback anymore

I do as you say,But It do not work!

**Comment by srinivastalnikar** [comment] 2022-10-17 07:03
For me immediate restart is working, but it's rolling back on NEXT_RESTART, any pointers regarding this?
