### ISSUE TITLE
Release update app issue

### ISSUE THREAD

**Issue by jose920405** [Microsoft/react-native-code-push#1097] opened 2017-12-04 15:33 UTC
Hi,

Thanks for this module, it has been very useful.

I had a problem with the releases I'm doing, because I always update again and again, even if I increase the version of the app.

Steps:

1) Upload my build to TestFlight (TF) `1.0`.
2) Send a code-push release fixing to error.

![captura de pantalla 2017-12-04 a la s 10 23 24 a m](https://user-images.githubusercontent.com/12536184/33560243-370b0c62-d8dd-11e7-9818-3f89a1d2a887.png)

3) Upload a new build to TF with versión `1.0.2`.

![unnamed](https://user-images.githubusercontent.com/12536184/33560731-8b25881c-d8de-11e7-80a0-db5b4943c7db.png)

4) Install the new versión and the update is running again. 😞 
_____

I always thought that when uploading a version to TF and increasing the number of the version, the update was ignored.

Clearly this is not happening and I want to ask what I can do:

**So that updates from previous versions do not apply to new ones.**

### Environment
* code-push-cli version: `2.1.2-beta`
* react-native-code-push version: `1.16.1-beta`
* react-native version: `0.39.0`
* iOS version: `> 10`
* Does this reproduce on a debug build or release build? yes, both
* Does this reproduce on a simulator, or only on a physical device? both

**Comment by ruslan-bikkinin** [comment] 2017-12-05 09:34
Hi @jose920405 and thanks for submitting the issue. To fix your issue please use patch version for `targetBinaryVersion` key when you are releasing new update like `1.0.1`, `1.0.2`, etc because `1.0` will be interpreting by codepush as range `>= 1.0.0 < 1.1.0`. Please refer to relevant documentation [section](https://github.com/Microsoft/code-push/tree/master/cli#target-binary-version-parameter) for more details.

Please let us know if it helps or any updates.

**Comment by ruslan-bikkinin** [comment] 2017-12-05 09:38
Closing it as duplicate of https://github.com/Microsoft/code-push/issues/541

**Closed by ruslan-bikkinin** 2017-12-05 09:38 UTC
Labels: duplicate
