### ISSUE TITLE
[Android] Update is installed without restart app manually with all default configuration.

### ISSUE THREAD

**Issue by JuanbingTeam** [Microsoft/react-native-code-push#617] opened 2016-11-23 10:27 UTC
RN   0.36.1
CodePush  1.16.0

I just Codepush-fy my app with all default config:
`export default codePush(App)`

Release react with follow command:
`code-push release-react UserAuth android -g ./app/build.gradle -t ~1.0`

Update is installed (app restart automatically) when i start app for the first time. According to Documents, mandatory is set to false by default, So, i guess it's a bug... android native side bug....

`
I/ReactNativeJS: [CodePush] Checking for update. 

I/ReactNativeJS: [CodePush] Reporting binary update (1.0)

I/ReactNativeJS: [CodePush] Downloading package.

I/ReactNativeJS: [CodePush] Installing update.

D/ReactNative: [CodePush] Loading JS bundle from "/data/data/com.ap

I/ReactNativeJS: [CodePush] Restarting app

I/ReactNativeJS: [CodePush] Checking for update.

I/ReactNativeJS: [CodePush] Reporting CodePush update success (v33)

I/ReactNativeJS: [CodePush] App is up to date.
`

@silhouettes

**Comment by yellowChao** [comment] 2016-11-23 10:31
+1 please help me，give me a hand

**Comment by vonovak** [comment] 2016-11-23 13:49
+1 I have explicitly set installMode.ON_NEXT_RESTART but the js bundle is updated without waiting for the restart. running 0.37

**Comment by silhouettes** [comment] 2016-11-23 19:44
Tagging @SimchaShats as their issue is a duplicate of this one.

**Comment by silhouettes** [comment] 2016-11-23 20:00
Are you all running `react-native-code-push@1.16.0-beta`, or do some of you have earlier versions?

**Comment by SimchaShats** [comment] 2016-11-24 07:33
Hi @silhouettes 
CodePush: "version": "1.16.0-beta"
RN: 0.37

**Comment by vonovak** [comment] 2016-11-24 08:31
running the same setup as @SimchaShats

**Comment by JuanbingTeam** [comment] 2016-11-24 09:48
Does anybody test on iOS devices? ....

**Comment by SimchaShats** [comment] 2016-11-24 09:48
@silhouettes @vonovak may be it can be also important, I'm using [wix-navigation](https://github.com/wix/react-native-navigation), it has a little bit different point of entrance in application...

**Comment by vonovak** [comment] 2016-11-24 09:55
I'm using ex-navigation so that shouldn't be the issue

**Comment by JuanbingTeam** [comment] 2016-11-28 03:03
Same issue found on iOS.

But, creating new code push app using cmd line solved the problem. 

Now, everything works well both on android and iOS.

Cheeeeeers!!

**Comment by silhouettes** [comment] 2016-11-29 03:15
Hi all, I've tested this with our sample app with RN 0.37 and CodePush 1.16 and have been unable to reproduce it. I can try this with a different app, but in the meantime, is it possible that you have a prior mandatory release (between the version originally running on the device, and the latest version) that is causing your latest release to be converted to mandatory?

More documentation on that behavior here: https://github.com/Microsoft/code-push/tree/master/cli#mandatory-parameter

**Comment by JuanbingTeam** [comment] 2016-11-29 10:27
@silhouettes , 

Yes, once released a mandatory release by mistake.....
Everything works well after deleting the old app, and creating a new one.....

**Comment by vonovak** [comment] 2016-11-30 13:03
mandatory was the problem, sorry. I guess this can be closed

**Comment by silhouettes** [comment] 2016-12-01 18:03
@yellowChao, @SimchaShats, can I confirm whether this explains your issues also? Is it possible that you have a prior mandatory release (between the version originally running on the device, and the latest version) that is causing your latest release to be converted to mandatory?

More documentation on that behavior here: https://github.com/Microsoft/code-push/tree/master/cli#mandatory-parameter

**Comment by silhouettes** [comment] 2017-01-19 00:56
Great :) - so seems like the problem for most people was an intermediary mandatory release. Closing for now!

**Closed by silhouettes** 2017-01-19 00:56 UTC
