### ISSUE TITLE
Task :app:generateBundledResourcesHashRelease FAILED

### ISSUE THREAD

**Issue by Ancy1** [microsoft/react-native-code-push#1776] opened 2020-01-30 11:06 UTC
> Task :app:generateBundledResourcesHashRelease FAILED
internal/fs/utils.js:220
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '/Users/rr/rr-BetaApp/android/app/build/generated/res/react/release'
    at Object.readdirSync (fs.js:854:3)
    at getFilesInFolder (/Users/rr/rr-BetaApp/node_modules/react-native-code-push/scripts/getFilesInFolder.js:7:26)
    at Object.<anonymous> (/Users/rr/rr-BetaApp/node_modules/react-native-code-push/scripts/generateBundledResourcesHash.js:38:1)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11 {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/rr/rr-BetaApp/android/app/build/generated/res/react/release'
}

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateBundledResourcesHashRelease'.
> Process 'command 'node'' finished with non-zero exit value 1

react-native-code-push version: 6.0.0
react-native version: 0.60.5
gradle version: 5.4.1
Does this reproduce on a debug build or release build? Release build. Debug build works fine.Its in Releasse after Androidx Migration. Jenkins build fails with this issue

**Comment by alexandergoncharov** [comment] 2020-02-11 08:57
Hi @Ancy1,
Thanks for reporting!

Unfortunately I can't reproduce this issue. Could you please provide detailed reprosteps or test project?

Thanks,
Alexander

**Comment by alexandergoncharov** [comment] 2020-02-13 09:48
I'm going to close this issue for now. Please feel free to reopen it if you have any qeustions or provide more details.

**Closed by alexandergoncharov** 2020-02-13 09:48 UTC
Labels: android, waiting-for-clarification
