### ISSUE TITLE
Possible to fix automatic rollbacks that occur?

### ISSUE THREAD

**Issue by huangkaiw3n** [Microsoft/react-native-code-push#880] opened 2017-06-09 17:00 UTC
### Description

A small number of users get automatic rollback sometimes. When that happens, they lose that update. I've experienced it before and a reinstall of the app allowed the code push to update the app successfully. Is there anything on the dev side to trigger something like this or some way to code the codePush syncing to attempt to sync again even after a rollback? So that an update is not lost to a user until a reinstall.

### Additional Information

* react-native-code-push version: 2.0.3-beta
* react-native version: 0.44.0
* iOS/Android/Windows version: On iOS and Android (not sure what are the user's versions)
* Does this reproduce on a debug build or release build: Release (As I've never ran codepush on debug mode)
* Does this reproduce on a simulator, or only on a physical device: Doesn't reproduce consistently and never tried codepushing when running on simulator (debug mode)

Eg. when I check the deployment stats:
<img width="191" alt="screen shot 2017-06-10 at 12 49 00 am" src="https://user-images.githubusercontent.com/6903360/26985825-ca537c80-4d77-11e7-8a92-7b2bcccfcf95.png">

### My CodePush code in App.js (imported by index.ios.js and index.android.js)
```
let codePushOptions = {
  checkFrequency: codePush.CheckFrequency.ON_APP_RESUME,
  installMode: codePush.InstallMode.IMMEDIATE
};

export default codePush(codePushOptions)(App)
```

**Comment by iageoghe** [comment] 2017-06-12 04:06
Hi @huangkaiw3n - Thanks for submitting this issue. I have a couple of questions:
1. Do you mean that such users can not update until the next release you distribute through CodePush?
2. Do you want a behavior where the app tries X number of times to install a CodePush release?

**Comment by huangkaiw3n** [comment] 2017-06-12 07:34
@iageoghe Thanks for looking at this issue.

Regarding your questions:
1. I'm not 100% sure if this is even the case. Eg. When a user gets an automatic rollback presumably due to a crash on the first update attempt, whether he will be able to receive the next CodePush release. (So far, I've only encountered an automatic rollback perhaps once or twice on my staging CodePush releases. And when they happen, closing and reopening the app did not trigger another attempt to update. Reinstalling the app did trigger the CodePush update though)
2. Yeah, this could be a way to combat the issue where the update is clean but the app crashed at the update attempt due to some arbitrary problem that could happen at the time of update. I was also wondering if my CodePush syncing code was generally the correct way to call sync or if there is any existing way to address this.

Do you know if this is a first or were there any others experiencing lost updates due to an auto rollback at CodePush update attempt?

**Comment by Minishlink** [comment] 2017-06-29 12:23
FYI, we seem to have this issue on an app using 2.1.0-beta, but not on another app that uses 2.0.3-beta, though this might be a coincidence.

**Comment by jbcullis** [comment] 2017-07-23 19:38
I've been experiencing this too. It seems like the app thinks it has already updated. It's very sporadic and I cannot reproduce this at will but when users contact me to say the app isn't updating a reinstall or rolling a new version will typically resolve the issue.

**Comment by huangkaiw3n** [comment] 2017-07-26 21:38
@jbcullis Hey I think we're facing the same issue. Could you share your react native version and react native code push version? Also how you are calling the sync in your react native code? This could help us find some clues.

**Comment by jbcullis** [comment] 2017-07-26 21:44
@huangkaiw3n  our versions are:   

    "react": "~15.4.0-rc.4",
    "react-native": "0.38.0",
    "react-native-code-push": "^1.17.0-beta",

Calling sync when the app starts:
CodePush.sync({ updateDialog: false, installMode: CodePush.InstallMode.IMMEDIATE }).then(...)

The then statements hides the loading box if an update is not found.

**Comment by jbcullis** [comment] 2017-07-26 21:46
It's the strangest issue, most of my users are rural and I suspect the issue occurs when an update fails and the app seems to think it's the current version until you either reinstall or roll a new version. Issue does not necessarily repeat for specific users and I've had this reported on both iPhone and multiple android devices so it seems to be circumstantial.

**Comment by jbcullis** [comment] 2017-07-26 21:52
I had never thought to look for rollbacks, I have been watching this since our most recent update 8 days ago and now have 1 rollback on iOS.

**Comment by JasonHenson** [comment] 2017-09-24 21:06
+1

**Comment by jeremyong** [comment] 2017-11-03 17:59
We just want an option to disable it at this point. We have observed in vitro that the rollback is happening on its own accord *without* a crash happening. To be frank, this functionality is strictly undesirable and I don't know of any use case why you'd want to rollback to the bundled code ever. The most I would expect is a simple checksum to ensure that what was deployed is in fact what was shipped.

Note that objections to this proposal would probably take the form of "but what if the user is stuck and can't ever update." This is true regardless of if the rollback takes place or not as the developer is always potentially able to introduce a bug that prevents an update/sync from happening.

**Comment by jbcullis** [comment] 2017-11-04 11:59
Yep, I second this @jeremyong - Put something in the API that allows us to FORCE an update to the latest bundle. We put in a long press button so we can ask users to do a manual check but it doesnt help at all because code-push thinks it has the latest version. The issue has always been that once an update faile, code-push still thinks it was a successful update therefore refuses to update.

**Comment by ghuh** [comment] 2017-11-04 16:42
We've seen this issue when the user manually kills the app on Android, there was no crash involved.

RN: 0.47.2
Codepush: 5.0.0-beta
Android: 7.0 (Galaxy S7)

**Comment by yaronlevi** [comment] 2017-11-05 23:35
<img width="819" alt="screen shot 2017-11-06 at 1 34 30" src="https://user-images.githubusercontent.com/5398977/32420421-b04819c8-c292-11e7-8469-e1a36b532303.png">

We always get 10% rollbacks

react-native-code-push@5.1.3-beta
react-native@0.49.0

**Comment by huangkaiw3n** [comment] 2017-11-06 03:28
To be fair, the rollback is useful if it is **really** rolling back for a case where the JS bundle has a problematic line that causes the app to crash.

**BUT** that isn't working good and instead, good bundles are getting rolled back and these users lose that push for good until they reinstall. So yeah, @jeremyong's suggestion sounds good. A flag to disable rollbacks for a push would fix this issue.

**Comment by yaronlevi** [comment] 2017-11-06 08:59
@huangkaiw3n +1

It could be great if had a way to diagnose the reason for a specific rollback, or as suggested disable this feature altogether. We get rollbacks on JS bundles that are 100% good.
My guess is that the process of installing the new bundle gets interrupted in some way: flaky internet connection, some wired user interaction regarding resume/open.
But we can only guess, as there is no way of knowing what happened in the client's end.

**Comment by ruslan-bikkinin** [comment] 2017-11-07 12:09
@jeremyong @jbcullis @ghuh @yaronlevi @huangkaiw3n
Hi all of you guys and let me clarify how rollback is working. CodePush does not trace any errors or something like that, the condition to determine whether the update was succeeded or not is if `codePush.notifyAppReady` (or `codePush.notifyApplicationReady`) was called. This method mark update as `installed successfully` on native side so if on next app start there will be pending update with status differs than `installed successfully` then it will be rolled back. If you are using sync command, this will be done automatically as part of update mechanism:

https://github.com/Microsoft/react-native-code-push/blob/8c5bf4ba72a63de6a58e87e1276345656a1d3147/CodePush.js#L343

This part of code couldn't be called when there was error before reaching this code which in general could be caused by incorrect bundle execution which, in turn, caused by bug in bundle initialization. As you can see this is very straight-forward and harmless approach, so if you want to rollback application update in other conditions you should install update manually, no need to provide additional option for this.

Please let us know if this information was helpful for you or you need additional help from our side.

**Comment by yaronlevi** [comment] 2017-11-07 13:10
@ruslan-bikkinin 

> could be caused by incorrect bundle execution which

Regarding "incorrect bundle execution",
do you mean some error in our javascript code?
Like in app.js near AppRegistry.registerComponent()?

And if not, where is this "bug in bundle initialization" could be found. The only code we control (write) is JS and some native modules.

**Comment by ruslan-bikkinin** [comment] 2017-11-07 15:05
@yaronlevi 

If `CodePush.notifyApplicationReady();` will not be called until next app restart app will be rolled back. This method call could be unreached due to several errors including developer code bugs.

Please refer to this documentation [section](https://github.com/Microsoft/react-native-code-push/blob/master/docs/api-js.md#codepushnotifyappready) for more info.

**Comment by jbcullis** [comment] 2017-11-07 15:45
@ruslan-bikkinin we have all the same issues as @huangkaiw3n - I don't know 100% if it's the false rollback since we have not yet been able to reproduce it locally. There is no consistency for reproduction as far as I can tell.
What I can tell you with 100% certainty is, the app THINKS it's the latest version and refuses to update. Maybe give us an option to submit our own version number and leave the version control to us?

**Comment by jbcullis** [comment] 2017-11-07 15:46
@ruslan-bikkinin - hypothetically, if the app experienced a hard exit in the same session where we updated the bundle, would it be possible for the app to still think it's up to date but roll back to the previous bundle?

**Comment by huangkaiw3n** [comment] 2017-11-07 16:17
@ruslan-bikkinin Yeah, there's no way to reproduce consistently as they're 'false roll-backs', presumably an arbitrary condition between update and `notifyApplicationReady`.

Even perfectly good apps do crash very occasionally. When it does crash between the update and `notifyApplicationReady`, the code push is lost to the user till an install.

I only encountered it when the users started to really go up, and it was from user feedback. Was able to further confirm my suspicions when I actually encountered it once or twice when testing on Staging.

Low percentage, but strictly undesirable:
<img width="611" alt="screen shot 2017-11-08 at 12 12 35 am" src="https://user-images.githubusercontent.com/6903360/32504125-1074b404-c41a-11e7-87b7-990dd6fcc0f3.png">

**Comment by jeremyong** [comment] 2017-11-07 18:23
@ruslan-bikkinin exactly as @huangkaiw3n has said.

Also I've read the code and understand the general flow (and have commented out relevant sections locally). I still think that no rollback whatsoever is the best policy. Our code leverages sync as suggested and we are certain that `notifyApplicationReady` is called but the rollback occurs anyways sporadically and we have observed this first hand as well. I don't trust the usage of user preferences to store metadata about whether a bundle succeeded or failed.

**Comment by JasonHenson** [comment] 2017-11-07 22:17
Not really sure what the debate is. I would never want to have "ghost" rollbacks that happen without my knowledge and leave users stuck on an old version. If I don't initiate the rollback then I personally don't want it to happen. If an update fails, it should try it again the next time code push checks for an update. If for some reason the app starts to crash because of the latest version code pushed, users could put in a support ticket and we would look into the issue and just code push a fix or release a new binary as a last resort.

**Comment by ruslan-bikkinin** [comment] 2017-11-08 12:04
@ghuh 

> We've seen this issue when the user manually kills the app on Android, there was no crash involved.

Please submit new issue for it with detailed information about your application so we could help you in this particular case.

@ghuh  @jbcullis 

> hypothetically, if the app experienced a hard exit in the same session where we updated the bundle, would it be possible for the app to still think it's up to date but roll back to the previous bundle?

> If for some reason the app starts to crash because of the latest version code pushed, users could put in a support ticket and we would look into the issue and just code push a fix or release a new binary as a last resort.

If you release broken update (that causes app to crash) and disable automatic client rollbacks, your application couldn't be updated via codepush anymore that will lead to bad user experience. This is not what we expect for our customers in general. As a solution for possible rare false-positive rollbacks we could implement retry installation mechanism in future: if for some reason update couldn't be installed we rollback it but doesn't send report to the server. Instead we will try to install it again later and if will not succeeded then we will rollback it and send report to the server. I believe that would be a reasonable compromise in this case.

**Comment by JasonHenson** [comment] 2017-11-08 12:25
I think rolling back and retrying to update again would be best.

I was thinking last night whether it is possible to check for rollbacks and then log therollback with sentry.io, so at least I would get an email when this happens.

**Comment by huangkaiw3n** [comment] 2017-11-08 12:56
@ruslan-bikkinin Building in retries sound good and I believe should be built as a default behaviour. The whole issue of these false-positives though rare is that the user loses the update entirely. A retry mechanism perhaps like `!latestVersion && minimumTimeSinceRollback` should eliminate these entirely since they are rare.

So far this is the only nagging issue I have with using code-push for close to a year and rest of it has been smooth so thumbs up and a big thanks to the code-push team.

**Comment by yaronlevi** [comment] 2017-11-08 14:52
+1 for a retry mechanism

**Comment by ruslan-bikkinin** [comment] 2017-11-09 10:17
Go it, guys!

> Also, getting some kind of log info about the device that experienced the rollback could be very helpful.

How do you think, @yaronlevi, what kind of information will be useful?

**Comment by yaronlevi** [comment] 2017-11-09 14:49
@ruslan-bikkinin 

We use **react-native-device-info** (which is quite popular).

I would try to follow the implementation of:

```
import DeviceInfo from 'react-native-device-info';
const uniqueid = DeviceInfo.getUniqueID();
```
 
And make this unique id, which is a unique device id, available in a log when a crash happens.

Looking at the source code of DeviceInfo.getUniqueID() could be a good place to look at, as this library is pretty mature and well tested, and generates this unique id for both iOS and Android.

**Comment by jbcullis** [comment] 2017-11-09 17:46
@ruslan-bikkinin I'm interested in a retry, or even a result on the sync that tells me it's a rollback user and an option for us to tell it to retry would be ideal....that way we could log it and possibly identify cause for rollback. Our users are primarily rural so my feeling is it's a dropped connection but don't know for sure.
I was trying to hard reset the phone during a code-push the other day but couldn't replicate it. I know it's not a back push because the same user will re-install and get the latest package no problem.

**Comment by jeremyong** [comment] 2017-11-09 18:19
@jbcullis I don't think this is a good idea. Based on statistics and logs I've collected. The rollbacks may be occurring _to the same people_ even after a follow-on release is happening. Again, I'm not sure exactly what might be causing it, but with your approach, an affected user may continuously download and apply the update, only to roll it back on the next application start. I think it should be disabled until the root cause is determined.

**Comment by jbcullis** [comment] 2017-11-09 18:30
@jeremyong in our experience, it's luck of the draw with any given push. We have users who have been successfully accepting pushes for the last 18 months and out of the blue, one of the releases will present this issue. Push a new release or ask the user to re-install the app and the problem is solved. This means, the very same push is working just fine with the same user on the same device which is why I believe it's more likely an environmental issue. The randomness is also what is making it so hard to debug because we are yet to be able to re-produce it in house.

My preference would be on sync, a response indicating the user has rolled back but failing that, the next best solution for us is a perpetual retry...meaning each time sync is called the app tries to update. At bare minimum, I'd like to see an option to catch a rollback and add it to our bug tracker.

**Comment by yaronlevi** [comment] 2017-11-25 13:51
Does one of the suggested solution mentioned above is scheduled on the roadmap or is considered?

This is especially important since Code Push is now a part of App Center which is a paid service. This could come as a real deal breaker for some.

**Comment by monotkate** [comment] 2017-11-26 21:40
@ruslan-bikkinin We've been trying to implement retries in our flow that uses the API commands instead of sync due to state issues, where we want to try a bad install again with a cleared user state but have been running into issues, particularly on ios.

Can code-push handle rollback more than once from the same failed upload?  On ios I'm seeing issues where the pushed build never calls `notifyAppReady`, and yet still manages to get stuck on the failed build after the first rollback.

**Comment by ruslan-bikkinin** [comment] 2017-11-28 07:15
@monotkate 
I believe there is no way to implement retry logic using API because this feature requires SDK changes. 

@yaronlevi 
Yes, we are considering to implement this as highly requested feature. I'll keep you posted.

**Comment by monotkate** [comment] 2017-12-01 22:06
@ruslan-bikkinin Yeah, we came to that conclusion ourselves.  It would be awesome if, when you guys implement retry, we've got the ability to run code based on how many times it's retried.  That way we can try to do something like wipe state between retries in case it's causing failures.

**Comment by ryanvanderpol** [comment] 2017-12-04 15:58
When rollbacks like this happen is there anyway to see a log somewhere?  We're using Sentry in our app but not seeing anything relevant in there and we're seeing really high rollback rates for our last five or six OTA updates.  I have no idea why they're rolling back and I can't seem to find logs anywhere.

![image](https://user-images.githubusercontent.com/1936460/33561946-03d7cd8a-d8e2-11e7-9507-a9a29a3b1311.png)

**Comment by ruslan-bikkinin** [comment] 2017-12-05 09:15
@ryanvanderpol Unfortunately, codepush doesn't provide any logs for rollbacks for now. You can create separate issue to continue discussion about your specific case.

**Comment by yaronlevi** [comment] 2017-12-06 23:58
Crash reporting on Code Push errors should be a top priority in the roadmap. Especially now that App Center is a paid service.

**Comment by pniko** [comment] 2017-12-07 11:14
Hi @yaronlevi, please see my response in #1099 for more information. You'll be happy to know we have our eyes already on the problem.

**Comment by jbcullis** [comment] 2017-12-30 16:00
We really need resolution on this, I've had 2 nasty emails and lost both customers over this issue this month.

**Comment by ajwhite** [comment] 2018-01-09 22:57
I've observed that installations that fail at the download level appear to result in a failure to install and get marked as a rollback. Our logs seem to indicate intermittent interruptions on the code push server side, which one should expect of any remote resource.

However, I'd imagine we can be more resilient about download failures. I may be wrong that's what my small number of rollbacks represents, but I just encountered a higher volume and the logs I have on file show:
- An SSL error has occurred and a secure connection to the server cannot be made
- Could not connect to the server
- The request timed out

The number of log entries seems to match the number of rollbacks reported.

---

What can be done to gracefully handle transport related issues, where the installation can become reattempted w/o `ignoreFailedUpdates` being used, as that can have unintended consequences of actual rollbacks being reattempted.

**Comment by jbcullis** [comment] 2018-01-09 23:01
Good work @ajwhite  - most of our customers are rural so consistent connectivity is not guaranteed.....this would explain a lot for us because it seems luck of the draw who experiences a rollback on any given release.

**Comment by ajwhite** [comment] 2018-01-10 00:00
Indeed [a failure can be marked](https://github.com/Microsoft/react-native-code-push/blob/9f4eef363d7d422096b9d6baf2f1a9f735c848da/ios/CodePush/CodePush.m#L670-L672) if part of the download & unpacking process failed.

However, it's not a catch-all scenario. This is only if it's a "code push error". A code push error can happen when:
- [The download is missing a bundle file](https://github.com/Microsoft/react-native-code-push/blob/9f4eef363d7d422096b9d6baf2f1a9f735c848da/ios/CodePush/CodePushPackage.m#L218-L222) 
- [Fails the hash check when signature verification is enabled](https://github.com/Microsoft/react-native-code-push/blob/9f4eef363d7d422096b9d6baf2f1a9f735c848da/ios/CodePush/CodePushPackage.m#L244-L252)
- [Fails the signature check when signature verification is enabled](https://github.com/Microsoft/react-native-code-push/blob/9f4eef363d7d422096b9d6baf2f1a9f735c848da/ios/CodePush/CodePushPackage.m#L257-L267)
- [Missing JWT when signature verification is enabled](https://github.com/Microsoft/react-native-code-push/blob/9f4eef363d7d422096b9d6baf2f1a9f735c848da/ios/CodePush/CodePushPackage.m#L272-L278)
- [Fails the hash check when signature verification is not enabled](https://github.com/Microsoft/react-native-code-push/blob/9f4eef363d7d422096b9d6baf2f1a9f735c848da/ios/CodePush/CodePushPackage.m#L292-L300)


All of these are valid reasons to reject the build. I'm not otherwise seeing download failures leading to rollbacks, so this might be a red herring. I can't pin down why only a subset of devices are rolling back..

**Comment by jbcullis** [comment] 2018-01-10 02:01
@ajwhite My assumption was some sort of interruption but maybe it's more likely the initial connection to code push as you suggested previously.
What I can tell you is, same person, same device....will be fine for all previous updates and then randomly runs into this issue....then a new release will get that same user back on course.

**Comment by yaronlevi** [comment] 2018-01-10 06:27
@ajwhite You said "in our logs"... What logs to do you mean, JS or Native? Something like Sentry.io?

**Comment by ajwhite** [comment] 2018-01-11 00:14
@yaronlevi these would be JS logs on a separate service like Sentry

**Comment by jariwalabhavesh** [comment] 2018-02-08 07:06
I was also face this issue. Now i am able to identify why it is happening in my case.
1. I had codepush V2 already publish for android app
2. Then i had release V3 and facing rollback in this version

I found that i had commented below code block, which is causing rollback in V3
```
// codePush.sync({
//   updateDialog: true,
//   installMode: codePush.InstallMode.IMMEDIATE
// });
```

**Comment by hobzcalvin** [comment] 2018-04-09 22:09
I was pointed to this issue via App Center support staff. Lots of React mentions but this is definitely an issue for us too in Cordova.

The worst part in our experience is new users who download our app for the first time: Let's say we've released a dozen CodePush releases since the app was released to the app store. All those releases worked fine (except maybe the latest) and target the given app-store version. The user downloads the app from the app store and it attempts to get the latest CodePush release, but (clearly very mysterious thing!) happens and the app rolls back. But instead of attempting to install the previous / perfectly-fine CodePush release, the CodePush plugin reverts to the version of the code that was packaged with the app, which is now very out of date.

So I would propose falling back to installing previous CodePush updates, in addition to retrying install of the latest one, instead of simply giving up.

As a quasi-workaround, we can manually roll back the latest release, which creates a new one, which the app will hopefully successfully install. Then we can try re-releasing the problematic update, etc. But this results in lots of release churn that interrupts users while they're in the app. Really not a solution.

**Comment by hobzcalvin** [comment] 2018-04-09 22:14
Out of curiosity, has anyone tried using the `notifyFailed` handler in [notifyApplicationReady](https://github.com/Microsoft/cordova-plugin-code-push#codepushnotifyapplicationready) to document when notifying the plugin fails? Obviously if there's such an error handler, there must be some theoretical way for `notifyApplicationReady` to fail, which almost guarantees a rollback.

**Comment by yuri-kulikov** [comment] 2018-12-06 16:09
Hello everybody!

I'm glad to inform you that we've implemented the **"Re-try mechanism for CodePush Rollbacks"** feature. 

CodePush rollbacks can occur for several reasons including closing an app during install, faulty cellular reception, etc. When this occurred the app never re-tried to download this update which results in a customer being stuck on an old version of an app until the developer decides to push a new release or the user re-installs or clears the app (This is a bad experience). Users was essentially stuck running old versions.

This feature will allow users who have had some random rollback to eventually receive the last working update. We understand that this will not save people from rollbacks, as well as not fix the metrics (you’ll still see random rollbacks as well as additional download + install(/rollback) for every re-try), but users will finally be able to install an update that were rolled-back accidentally.

For example, you could set options like this:
```
syncOptions: { 
  ...
  rollbackRetryOptions: {
    delayInHours: 12,
    maxRetryAttempts: 1
  }
  ...
}
```
then use this options `App = CodePush(syncOptions)(App)` or `CodePush.sync(syncOptions)`,
and in this case, if a rollback occurs, then the application will ignore this update for **12 hours** after the rollback, and then it can try to install this update again (but only **once**, as we have set in `maxRetryAttempts`). You can read more about how to use this options [here](https://github.com/Microsoft/react-native-code-push/blob/master/docs/api-js.md#codepushoptions).

We appreciate your feedback about this.

**Comment by hobzcalvin** [comment] 2018-12-06 16:50
Thanks for this update. Can `delayInHours` be set to `0` for immediate retry? Seems to me that waiting some number of hours doesn't help much, but retrying the same update several times should eliminate one-off update errors.

My company (where I no longer work) had to scrap CodePush after significant effort implementing it because of this bug. (If we couldn't rely on CodePush to release important new app features it was useless to us.) Sadly, this fix probably comes far too late to consider adopting it again. We had no idea why rollbacks could even happen; AFAICT reasons like "closing an app during install, faulty cellular reception" were never previously mentioned. It's helpful to know this now, at least.

**Comment by yaronlevi** [comment] 2018-12-07 11:09
Setting delayInHours=0 would cause an immediate retry?

**Comment by yuri-kulikov** [comment] 2018-12-07 12:57
Hi @hobzcalvin, @yaronlevi
Thanks for you feedback!

> Can delayInHours be set to 0 for immediate retry?

Yes, you can set it to `0` (or, for example, `1 / 60` if you want to wait 1 minute), but if you set delay to `0` and unintentionally release a broken update, then each user might get some additional crashes and that's also a bad experience. Developers will need some time to disable a broken update or release a fixed update.

> AFAICT reasons like "closing an app during install, faulty cellular reception" were never previously mentioned.

In fact, the reasons of this exceptional rollbacks can be quite unclear and we don't know each of them, it may be caused by some hardware issues, some unusual user actions or developer js-code issues, etc. Each case is quite individual and this feature can help users to mitigate these circumstances.

> Setting delayInHours=0 would cause an immediate retry?

Not exactly, it will mean that during the **next sync request with this options**, the application will not ignore this package (until `maxRetryAttempts` is reached). For example if you use it with `CodePush.CheckFrequency.ON_APP_START(/ON_APP_RESUME)` and user got a rollback, then as soon as he launches the application, it will re-download the update right after the start and install it as usual.

**Comment by yaronlevi** [comment] 2018-12-07 19:40
@yuri-kulikov Great feature (-: It's nice seeing React Native and CodePush going forward and improving all time.

**Comment by yuri-kulikov** [comment] 2018-12-14 11:55
We close the issue, but if you find something or if you have some questions, please let us know!

**Closed by yuri-kulikov** 2018-12-14 11:55 UTC
Labels: enhancement

**Comment by mohamedsharaf** [comment] 2020-01-27 20:06
use .sync() without any param fix it

**Comment by muzzammil-geniteam** [comment] 2021-01-21 13:59
Hello Guys , I am also facing the same issue . Unfortunately nothing has worked 

This is my App.js

/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow strict-local
 */
import {useEffect, useState} from 'react';
import React from 'react';
import Container from './App/Navigation/Container/Container';
import codePush from 'react-native-code-push';
import {View, Text} from 'react-native';

// let codePushOptions = {checkFrequency: codePush.CheckFrequency.ON_APP_RESUME};

const codePushOptions = {
  updateDialog: false,
  installMode: codePush.InstallMode.IMMEDIATE,
  checkFrequency: codePush.CheckFrequency.ON_APP_RESUME,
};

import {initializeLanguage} from './App/locales/index';

const App = () => {
  // Bootstrap();
  [isLoaded, setIsLoaded] = useState(false);
  useEffect(() => {
    initializeLanguage().then((response) => {
      setIsLoaded(response);
    });
  }, []);

  codePush.sync({
    updateDialog: false,
    installMode: codePush.InstallMode.IMMEDIATE,
  });

  if (isLoaded) {
    return <Container />;
  } else {
    return (
      <View>
        <Text>Loading...!</Text>
      </View>
    );
  }
};

export default codePush(codePushOptions)(App);

**Comment by YaoHuiJi** [comment] 2021-10-05 23:33
hi  @yuri-kulikov , is rollbackRetryOptions removed in new version?  I can see it in new [API document ](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/rn-api-ref#codepushoptions)

I met this problem too, a few users stuck in old version, even I release a new version but it seems those users just ignore any new updates and stay at old version forever

**Comment by vemahendran** [comment] 2023-04-11 08:05
App crashes is very normal now-a-days. There should be a way to disable the automatic rollback in AppCenter.

**Comment by lklepner** [comment] 2023-04-11 11:28
Expo Update might be a better approach these days.
