### ISSUE TITLE
copush process exited when push file to oss 

### ISSUE THREAD

**Issue by Raylively** [microsoft/react-native-code-push#1751] opened 2020-01-01 13:40 UTC
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.
2. 
3.

### Expected Behavior
push file to codepush with oss, alway 

### Actual Behavior
push file to codepush,storage_type is oss, alway occerd a error and the codepush process exited

```
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/tmp/codepush_AwZ4CCWCKeTy9t1eb3fJuZMiMAcX5ply/955ee56672757b5405e47c5181516c2d640cb928d54066e552ffa8f5512451f5/dataCenter/CodePush/index.android.bundle'
    at Error (native)

### Environment

* react-native-code-push version:
* react-native version:
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by alexandergoncharov** [comment] 2020-02-11 10:18
Hi @Raylively,

Could you please fill reposteps for reproducing your issue because it isn't clear for now?

I'm going to close this issue for now. Please feel free to reopen it after filling reprosteps or if you have any questions.

**Closed** 2020-02-11 10:18 UTC
Labels: bug, waiting-for-clarification
