### ISSUE TITLE
What is the right way to load a react project in react-native project and use code push to update?

### ISSUE THREAD

**Issue by dyfvicture** [Microsoft/react-native-code-push#1460] opened 2018-11-27 10:10 UTC
I'm using react-native to load another react project(some static resources, index.html and some images) with Webview, and using code push to do hot update, but found that hot update has no effect, it seems like index.html was updated but not reloaded, was this the problem I'am using "uir" to load source in Webview? What is the right way to load a react project in react-native project with android and use code push to update?

### Steps to Reproduce
1. Build a react project
![image](https://user-images.githubusercontent.com/6755466/49073043-8796d900-f26c-11e8-9eff-9ecfb7912ce2.png)
2. Copy the resources into android's static source folder(android/app/src/main/assets) 
3. Load the resources by using Webview container in a react-native project(use uri)
![image](https://user-images.githubusercontent.com/6755466/49073906-777ff900-f26e-11e8-9d03-be515ee488ea.png)
3. Modify react project , and do steps 1, 2, and run code push:
```
1. react-native bundle --platform android --dev false --entry-file index.js --bundle-output ./android/app/src/main/assets/index.android.bundle --assets-dest ./android/app/src/main/assets 
2. code-push release updex-android android/app/src/main/assets 1.0.0
```

### Environment

* react-native-code-push version:2.1.9
* react-native version:2.0.1
* iOS/Android/Windows version:iOS10.14.1 
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by dyfvicture** [comment] 2018-11-28 11:40
Hello @yuri-kulikov 
Thanks for your reply.
I have submited a demo : [github](https://github.com/dyfvicture/CodePush.git) you could download and try to run on android.
I have a built project in the pages folder(index.html and a image), want use react-native to be a container(to generate android and iOS app) and support hot update(the index.html and all assets it reference), These are the command i create bundle and push update
```
1. rm -rf ./android/app/src/main/assets/* && react-native bundle --platform android --dev false --entry-file index.js --bundle-output ./android/app/src/main/assets/index.android.bundle --assets-dest ./android/app/src/main/assets && cp -rf pages/* android/app/src/main/assets
2. code-push release updex-android android/app/src/main/assets 1.0.0
```
You could try like this:

 - Install on a android device : react-native run-android
 - Modify the deployment key in MainApplication.java to yours, and the index.html in pages folder(may be `Hello, xxx` ),run `npm run release-and`
 -  Open your app and update to see whether it updated

My questions:
 - whether the bundle contains all assets in pages folder
 - Is the `uri` way support hot update ? `source={uri: 'file:///android_asset/index.html' }` 

Thanks for your help!

**Comment by yuri-kulikov** [comment] 2018-11-29 07:04
Hi @dyfvicture,
Sorry for the delay.

I was finally able to reproduce it! I will try to find a solution when I have enough time and hope it happens soon. I'll let you know as soon as I find something.

Thank you for your patience!

**Comment by dyfvicture** [comment] 2018-11-29 07:12
Thank you @yuri-kulikov, I really appreciate for your time and effort !

**Comment by yuri-kulikov** [comment] 2018-12-11 12:48
Hi @dyfvicture,  
Sorry again for this huge delay!

Finally I was able to make enough time for this question, the issue was quite complicated.

As you already know, `<WebView>` element cannot work with `source = { require('./...html') }`, and the only way to set source is to use `{ uri: "file:///..."}`.
I expected that I could set path to our CodePush file directly like this:
```js
// Some example from my app
{ uri: "file:///data/user/0/com.updex_rn/files/CodePush/3b4d1ba9141098114d19ad0263b99a19c9c2cfa4a0dd1c241b574e0ac6d12b3a/assets/index.html" }
```
But, unfortunately, the result was the same... I got this error:
```javascript
W/ReactNativeJS: 'Encountered an error loading page'
{
    canGoForward: false,
    code: -1,
    canGoBack: false,
    description: 'net::ERR_ACCESS_DENIED',
    loading: false,
    title: 'Webpage not available',
    url: 'file:///data/user/0/com.updex_rn/files/CodePush/3b4d1ba9141098114d19ad0263b99a19c9c2cfa4a0dd1c241b574e0ac6d12b3a/assets/index.html',
    target: 7 
}
```
As with `require('./pages/index.html')`.

This means we simply don't have access to the files directly, and as I understand, that's the reason why `require(...)` doesn't work on Android. WebView only has access to `file:///android_asset/...`. I also tried to grant my app a permission to `Storage`, but it also didn't help.

Unfortunately, I don't see any other way to make it work.

**Comment by dyfvicture** [comment] 2018-12-14 04:06
@yuri-kulikov OK, thanks for your help !

**Comment by yuri-kulikov** [comment] 2018-12-14 12:03
@dyfvicture, it was the least I could do! I'll close the issue for now, but let me know if you have any questions.

**Closed by yuri-kulikov** 2018-12-14 12:03 UTC
Labels: android, investigating, question

**Comment by rafaelcorreiapoli** [comment] 2019-03-15 22:51
This is our current use case as well. Any updates on this ?
