### ISSUE TITLE
Diff-Update package size over 500kb every times in my hybrid project

### ISSUE THREAD

**Issue by zjkhiyori** [microsoft/react-native-code-push#1681] opened 2019-09-12 03:38 UTC
### Steps to Reproduce
1. release update package
2. download diff package
3. applying diff update

### Expected Behavior
download diff package which i changed, It's usually about 10kb

### Actual Behavior
diff package over 500kb every time i tested
```
totalBytes: ', 514235, 'receiveBytes: ', 514235
```

### Environment

* react-native-code-push version:5.6.0
* react-native version:0.59.10
* iOS/Android/Windows version: Android9.0
* Does this reproduce on a simulator, or only on a physical device? physical device

In my thought, the diff logic is in your backend server side 

so could you help me to find what wrong is ?

**Comment by zjkhiyori** [comment] 2019-09-12 03:46
![image](https://user-images.githubusercontent.com/13451748/64752615-cc1d0800-d552-11e9-8cfd-743f077d2f5b.png)
my binary resource files size

**Comment by 17554265585** [comment] 2019-11-20 03:22
I have the same problem. Have you solved it？

**Comment by andreidubov** [comment] 2020-02-13 11:25
Hi @zjkhiyori,
Thank you for reporting!

Unfortunately I can't reproduce this issue. Could you please provide detailed reprosteps or test project? Everything works correctly for me on the latest version of react-native-push code.

I'm going to close this issue for now. Please feel free to reopen it if you have any questions or issues.

**Closed by andreidubov** 2020-02-13 11:25 UTC
Labels: waiting-for-clarification
