### ISSUE TITLE
An explanation of the error "User interaction is not allowed"

### ISSUE THREAD

**Issue by abaddonGIT** [Microsoft/react-native-code-push#1453] opened 2018-11-18 01:45 UTC
In sentry many error "User interaction is not allowed" when i code push. Never found because of what this error appears. All installed according to documentation.

### Steps to Reproduce
"codepush-release:debug:ios": "code-push release-react Path/app-ios ios --deploymentName debug -p ./ios/App/Info.plist"

### Actual Behavior

![error](https://user-images.githubusercontent.com/3716060/48667660-6b689e80-eaec-11e8-8d0c-bc2911ea4987.jpg)

### Environment

* react-native-code-push version: 5.3.3
* react-native version: 0.55.3
* iOS/Android/Windows version: 11.4
* release build
* physical device

**Comment by NickToropov** [comment] 2018-11-20 10:05
Hi @abaddonGIT! Do you have any logs (besides sentry) or investigation results specifying that the issue is related to CodePush? Are you able to reproduce the issue on demo RN project created from scratch with integrated CodePush plugin? Did you try to bump up versions of RN and CodePush plugin?
We require as more info as possible about your project to try to help you. Also it would be very helpful if you could create demo project that reproduce the issue.

**Comment by NickToropov** [comment] 2018-11-27 09:53
Hey! 
We haven’t heard from you in a while, so I am going to go ahead and close this issue. Should you still have any questions, you can reopen the issue or if you prefer you can create a new one.

**Closed by NickToropov** 2018-11-27 09:53 UTC
Labels: iOS, waiting-for-clarification
