### ISSUE TITLE
codePush undefined

### ISSUE THREAD

**Issue by freddy24** [Microsoft/react-native-code-push#701] opened 2017-02-14 09:47 UTC
I add codePush into my project, do as the document says.
 index.android.js.
`import codePush from "react-native-code-push";`
```
componentDidMount(){
	codePush.sync();
}
```
When I run my project, Error come cross, `codePush` undefined,
I used React-Native 0.40.0
code push 1.12.6-beta

**Comment by sergey-akhalkov** [comment] 2017-02-14 12:33
@freddy24, could you please try to use `var codePush = require("react-native-code-push")` instead of `import...`? In case the issue is still reproduces please share me with full content of `MainApplication.java` and `index.android.js.` files - It feels like your app using some additional libraries such as `NavigationModule` or another.

**Comment by freddy24** [comment] 2017-02-14 13:46
here is my full content of index.android.js and MainApplication.java
```
import React, { Component } from 'react';
import { Provider } from 'react-redux'
import {
    AppRegistry,
    Text,
    View,
    Alert
} from 'react-native';
import Home from './src/modules/home';
import Base from './src/modules/base';
import configureStore from './src/configureStore'
import codePush from "react-native-code-push"

class nativeappIndex extends Component {
    constructor(props) {
        super(props);
        this.state = {
        };
    }
    componentDidMount(){
         codePush.sync();
    }
    render() {
        const store = configureStore();
        const {initData,queryInfo} = this.props;
        return (
            <View style={{flex:1}}>
                    <Provider store={store}>
                        <Base initData={initData} queryInfo={queryInfo}/>
                    </Provider>
            </View>
        );
    }
}
```
MainApplication.java
```
private static final MyReactPackage packages = new MyReactPackage();

    public static MyReactPackage getPackages() {
        return packages;
    }

    private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {

        @Override
        protected boolean getUseDeveloperSupport() {
            return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
            return Arrays.asList(
                    new MainReactPackage(), packages,new CodePush("my deploymentkey",MainApplication.this,BuildConfig.DEBUG);
            );
        }
    };

    @Override
    public ReactNativeHost getReactNativeHost() {
      
```  return mReactNativeHost;
    }

**Comment by sergey-akhalkov** [comment] 2017-02-14 14:52
@freddy24, I could see two `getPackages()` methods in your `MainApplication.java`, so it seems like native part of CodePush was not installed properly.
Please try inject new instance of CodePush in the first `getPackages()` method and let me know if any changes:
```java
public static MyReactPackage getPackages() {
    return packages; // inject CodePush here
}
```

**Comment by freddy24** [comment] 2017-02-15 00:28
@sergey-akhalkov thank you for your reply.
I change the code as below:
```
private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {

        @Override
        protected boolean getUseDeveloperSupport() {
            return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
            return Arrays.asList(
                    new MainReactPackage(), packages,new CodePush("my deploymentkey",MainApplication.this,BuildConfig.DEBUG);//remove packages
            );
        }
    };
```
still have this problem.

**Comment by freddy24** [comment] 2017-02-15 01:04
I got this message:[CodePush] The CodePush module doesn't appear to be properly installed. Please double-check that everything is setup correctly.

I install code push in my project with Android - Manual:
my module named "passenger",not "app"
```
1.include ':passenger', ':react-native-code-push'
project(':react-native-code-push').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-code-push/android/app')
```
```
2.dependencies {
    ...
    compile project(':react-native-code-push')
}
```
```
3....
apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"
...
```
Is there any problem with my install steps?

**Comment by sergey-akhalkov** [comment] 2017-02-15 14:58
>I got this message:[CodePush] The CodePush module doesn't appear to be properly installed. Please double-check that everything is setup correctly.

It happens due to native-side of CodePush was not installed properly. For now I could not see anything wrong with CodePush installation, so could you please provide me with minimal version of the app where the issue reproduces? You also could compare your `MainApplication.java` file with [the same file](https://github.com/Microsoft/react-native-code-push/blob/master/Examples/CodePushDemoApp/android/app/src/main/java/com/codepushdemoapp/MainApplication.java) in CodePushDemoApp.

**Comment by moaxaca** [comment] 2017-02-15 21:02
Had the same issue in IOS. After doing `react-native link react-native-code-push ` had to clean then rebuild. It appears to be an install issue.

**Comment by freddy24** [comment] 2017-02-16 06:12
@sergey-akhalkov @moaxaca thank you very much!
I find my problem. my activity is not extends ReactActivity, 
```
@Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        ReactRootView mReactRootView = new ReactRootView(this);
        mReactInstanceManager = ReactInstanceManager.builder()
                .setApplication(MainApplication.getInstance())
                .setBundleAssetName("index.android.bundle")
                .setJSMainModuleName("index.android")
                .addPackage(new MainReactPackage())
                .addPackage(MainApplication.getPackages())
                .addPackage(new CodePush("my key", getApplication(), BuildConfig.DEBUG))//I didnot add this code before.
                .setJSBundleFile(CodePush.getJSBundleFile())
                .setUseDeveloperSupport(BuildConfig.DEBUG)
                .setInitialLifecycleState(LifecycleState.RESUMED)
               .build();
        mReactRootView.startReactApplication(mReactInstanceManager, "loanapplyReact", bundle);
        setContentView(mReactRootView);
    }
```
`.addPackage(new CodePush("my key", getApplication(), BuildConfig.DEBUG))//I didnot add this code before. `
problem fixed! thank you again.

**Comment by sergey-akhalkov** [comment] 2017-02-16 07:16
@freddy24, got it, thanks for the response.
@moaxaca, please let me know if you still experiencing the issue or if you have any questions.

**Comment by sergey-akhalkov** [comment] 2017-02-17 08:03
Closing this for now, please feel free to reopen if needed.

**Closed by sergey-akhalkov** 2017-02-17 08:03 UTC
Labels: investigating
