### ISSUE TITLE
Rollback after restart on android

### ISSUE THREAD

**Issue by niros001** [Microsoft/react-native-code-push#1129] opened 2018-01-03 16:12 UTC
Hi, i'am using:
RN v0.46.1
code-push v5.2.1

My app updated successfully every code push, After app restart it's rollback to one version before last update. for example:
My app installed on version 0.8.0, i update to version 0.8.1 successfully and after that to 0.8.2 successfully. After app restarted it's rollback to 0.8.1 instead stay in 0.8.2

**Comment by sergey-akhalkov** [comment] 2018-01-05 11:14
Hi @niros001, thanks for reaching us!

Could you please fill out our [issue template](https://github.com/Microsoft/react-native-code-push/issues/new) to provide us more info?

The main concern here is that we cannot currently understand what you have done (what steps have you performed) to reproduce the issue. Providing a minimal working version of your app where the issue reproduces also would be great.

**Comment by sergey-akhalkov** [comment] 2018-01-08 11:15
@niros001, just a friendly ping.

**Comment by sergey-akhalkov** [comment] 2018-01-10 11:17
Closing this, please feel free to reopen and provide us more info regarding your issue.

**Comment by niros001** [comment] 2018-01-26 09:17
Sorry for the big delay,
For example i have in my code config file with app version parameter with value of '1.0'.

Steps to Reproduce:
1. Change the value of app version to '1.1'.
2. Update the app with code push.
3. Change the value of app version to '1.2'.
4. Update the app with code push.

Expected Behaviour:
App version should change to '1.2'.

Expected Behaviour:
App version is changed to '1.2', yet, after restarting the app it rolls back to '1.1'.

**Comment by max-mironov** [comment] 2018-01-26 12:32
Hi there @niros001 , thanks for staying in touch. 
In order to fix your issue faster and to get out what is going wrong here we need some additional information from your side, more specifically:
1) exact way you are integrating CodePush (with code samples)
2) ios/android?
3) release/debug mode?
4) simulator/real device?
5) what was in your update, anything suspicious?
6) probably sharing deployment history would be useful (especially if you add --format json argument to it)

So 1st point is the most important. Also would be great if you could share with us minimum sample where we can reproduce the issue.

Finally reopening it and looking forward for more details from your side!

**Comment by niros001** [comment] 2018-01-28 17:53
1. ‘updateApp(){
    ToastAndroid.show('Checking for update.', ToastAndroid.SHORT);
    codePush.sync({installMode: codePush.InstallMode.IMMEDIATE}).then((isUpdateAvailable)=> {
        const msg = isUpdateAvailable ? "updating..." : "App is up to date!";
        ToastAndroid.show(msg.toString(), ToastAndroid.SHORT);
    });
}’
2. Android
3. Release
4. Real device
5. Any changes, for this case only string of app version (In app folder - not native)

**Comment by sujitpk-perennial** [comment] 2018-03-14 05:32
I am also facing same issue? @niros001 have you find any solution?

**Comment by iTOYS** [comment] 2018-03-22 11:27
Hi guys, sorry for delay.
Unfortunately I can't reproduce this issue.
There is my `App.js`:
```
import React, { Component } from 'react';
import { StyleSheet, Text, View, TouchableOpacity } from 'react-native';
import codePush from "react-native-code-push";

class App extends React.Component {
  render() {
    return (
      <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
        <TouchableOpacity
          style = {{height: 70, width: 200, backgroundColor: 'red'}}
          onPress={() => {
             codePush.sync({
                  updateDialog: true,
                  installMode: codePush.InstallMode.IMMEDIATE
              });
          }}>
        <Text>Current version: 10</Text> 
      </TouchableOpacity>
      </View>
    )
  }
}

let codePushOptions = { checkFrequency: codePush.CheckFrequency.MANUAL };
export default App = codePush(codePushOptions)(App);
```

react-native-cli: 2.0.1
react-native: 0.54.2
react-native-code-push: 5.3.2

If you still faced this issue feel free to reopen it and please attach you example project that I can use to reproduce.

Thanks!

**Closed by iTOYS** 2018-03-22 11:27 UTC
Labels: android, incomplete
