### ISSUE TITLE
Update is invalid when built on CI server

### ISSUE THREAD

**Issue by ggordan** [Microsoft/react-native-code-push#711] opened 2017-02-20 17:52 UTC
Hi all, 

I'm running into a strange issue. doing a code-push deploy from my computer works fine (on a clean repo) and the release is successfully installed on the device, however when attempting to do the exact same steps on our CI server, everything appears to work fine, however attempting to install the release on the device results in the following:

```
[05:26:10] Loading JS bundle from "assets://index.android.bundle"
[05:26:10] Checking for update.
[05:26:10] Downloading package.
[05:26:10] An unknown error occurred.
[05:26:10] Update is invalid - A JS bundle file named "index.android.bundle" could not be found within the downloaded contents. Please check that you are releasing your CodePush updates using the exact same JS bundle file name that was shipped with your app's binary.
[05:26:10] Loading JS bundle from "assets://index.android.bundle"
```

Are there any additional dependencies that are required that I just might be missing. I am running

```bash
    - npm install
    - npm install -g code-push-cli
    - code-push release-react -d Production my-app android
```

Output 

```
code-push release-react --mandatory -d Production my-app android
Detecting android app version:

Using the target binary version value "1.0.4" from "android/app/build.gradle".

Running "react-native bundle" command:

node node_modules/react-native/local-cli/cli.js bundle --assets-dest /var/folders/jm/fw86rxds0xn69sk40d18y69m0000gp/T/CodePush --bundle-output /var/folders/jm/fw86rxds0xn69sk40d18y69m0000gp/T/CodePush/index.android.bundle --dev false --entry-file index.android.js --platform android
Loading dependency graph, done.
bundle: start
bundle: finish
bundle: Writing bundle output to: /var/folders/jm/fw86rxds0xn69sk40d18y69m0000gp/T/CodePush/index.android.bundle
bundle: Copying 79 asset files
bundle: Done writing bundle output
bundle: Done copying assets

Releasing update contents to CodePush:
Upload progress:[==================================================] 100%
Successfully released an update containing the "/var/folders/jm/fw86rxds0xn69sk40d18y69m0000gp/T/CodePush" directory to the "Production" deployment of the "my-app" app.
```

Any advice would be greatly appreciated, thanks.

**code-push version**: 1.12.6-beta
**react-native version**: 0.40

**Comment by sergey-akhalkov** [comment] 2017-02-28 14:57
@ggordan, sorry for slow response. 
Do you still experiencing the issue? If so, could you please put `console.log(downloadUrl)` line before [this line](https://github.com/Microsoft/react-native-code-push/blob/master/package-mixins.js#L12) or just debug it? Use this url for downloading via browser and unzipping update package contents , so we would able to determine if the problem is in preparing CodePush update (`code-push-cli`) or in React Native Module for CodePush (`react-native-code-push`).

**Comment by sergey-akhalkov** [comment] 2017-03-07 11:14
@ggordan, just a friendly ping.

**Comment by max-mironov** [comment] 2017-03-14 07:05
Closing the issue for now, please reopen/create a new one if the issue still persist or you have any questions.

**Closed by max-mironov** 2017-03-14 07:05 UTC
Labels: investigating, waiting-for-clarification
