### ISSUE TITLE
Can't download new bundle

### ISSUE THREAD

**Issue by dannyyaou** [Microsoft/react-native-code-push#716] opened 2017-02-23 10:38 UTC
* react-native-code-push version: 1.17.0-beta
* react-native version: 0.40
* iOS/Android/Windows version: iOS

Today When I release an update using codepush, My IOS end user will get a syncStatus 7, and try to start downloading new bundle, but there's nothing received, and my app has a view to tell user that the app is updating, and the size of the view is as big as the whole screen, so that make my user stuck on that view...

yesterday, I just update my react-native-code-push to 1.17.0-beta, I don't know if the problem is related to it.

And here's my code to update app:

`	 
 codePush.sync({
	    updateDialog: updateDialog,
	    installMode: codePush.InstallMode.IMMEDIATE,
	    deploymentKey: <MY deploymentKey>
},function(syncStatus){
	  	if (syncStatus == 7) {
				this.showUserUpdatingPage()
	  	}
}.bind(this),({ receivedBytes, totalBytes, }) => {
	  	var pregress = receivedBytes/totalBytes*100
	  	this.setState({updatingProgress:Math.ceil(pregress)})
});
`

Thanks a lot!

**Comment by silhouettes** [comment] 2017-02-23 10:48
Hi @dannyyaou, do you have any code to hide the page? Here are all of the possible SyncStatuses: https://github.com/Microsoft/react-native-code-push/blob/bb04535fbef4cb580da4c29ae628452cc0774fc8/CodePush.js#L496/

**Comment by silhouettes** [comment] 2017-02-23 10:50
Also, which version of `react-native-code-push` did you upgrade from originally?

**Comment by dannyyaou** [comment] 2017-02-23 11:01
it seems to be ^1.14.6-beta

**Comment by dannyyaou** [comment] 2017-02-23 17:11
Its seems like the version that can't get the next version is the first version with react-native-code-push@1.17.0-beta...
Hmm This line seems confused... Can you understand me lol

**Comment by dannyyaou** [comment] 2017-02-23 17:18
Maybe it's related to this commit?<br/>
[Resolve CodePush.h for new iOS apps created with RN 0.40 (#665)](https://github.com/Microsoft/react-native-code-push/commit/90f0bb81d14bad6e868db90c285eb11087dec78c)
<br/>
change of scripts/postlink/ios/postlink.js<br/>
`var codePushHeaderImportStatement = `#import "CodePush.h"`;`
became
`var codePushHeaderImportStatement = `#import <CodePush/CodePush.h>`;
`

**Comment by dannyyaou** [comment] 2017-02-23 17:53
But in the simulator. It still works like a charm

**Comment by silhouettes** [comment] 2017-02-23 19:48
@dannyyaou, a few more questions:

1. As mentioned before, are you handling the other `SyncStatuses` and hiding the view when you get a bad one? https://github.com/Microsoft/react-native-code-push/blob/bb04535fbef4cb580da4c29ae628452cc0774fc8/CodePush.js#L496/
2. To confirm, this is happening on real devices, but not the simulator? Can you tell me the iOS version that is running on the real device?
3. To confirm, the issue is both that no download progress being reported, and also the download never completes?

**Comment by dannyyaou** [comment] 2017-02-24 00:21
@silhouettes
1. Nope, Just handling the situation that SyncStatus is 7 with opening that page I mentioned above, and there's no button to hide that page.
2. its happening on many ios device including mine, and the version of my device is 10.2.1.
3. Since debugging with released version app is impossible ( is that true? ), the only thing I know is that no download progress was being reported, and I'd waited for a long time, and the download never completes?

**Comment by dannyyaou** [comment] 2017-02-24 00:47
I tried to recreate the problem today with simulator and Staging development key
and I got this error log

console.warn @ YellowBox.js:69
(anonymous) @ debuggerWorker.js:25
(anonymous) @ debuggerWorker.js:53
logging.js:3 [CodePush] this._nativeModule.addListener is not a function

**Comment by dannyyaou** [comment] 2017-02-24 01:06
Maybe its related to change on package-mixins.js
which this line of code: 
downloadProgressSubscription = DeviceEventEmitter.addListener(...
had changed to be
downloadProgressSubscription = codePushEventEmitter.addListener(...

**Comment by silhouettes** [comment] 2017-02-24 01:11
@dannyyaou I will follow up on your other comments later, but are you saying you're not hiding the screen if the app is up-to-date or if there was an error? Surely you need to handle the `UP_TO_DATE`, `UPDATE_IGNORED`, and `UNKNOWN_ERROR` statuses if you don't want the screen to show forever?

**Comment by dannyyaou** [comment] 2017-02-24 01:13
Yap, That's a mistake that I didn't handling those state.

**Comment by silhouettes** [comment] 2017-02-25 02:42
@sergey-akhalkov @max-mironov - Could one of you look at this when you come back on Monday?

**Comment by max-mironov** [comment] 2017-02-27 11:50
Hi @dannyyaou, is it correct that before updating code-push plugin to the latest version everything works as expected?
Also this is not absolutely clear for me: 
>When I mentioned the version which is the first version with react-native-code-push@1.17.0-beta, that means the bundle version that uploaded to codepush server, but native code on the device is still 1.14.6-beta, I guess that's cause of the problem..

Have you tried to remove code-push plugin completely from the app and then reinstall the latest version again?

**Comment by max-mironov** [comment] 2017-03-06 07:20
@dannyyaou - hi, do you have a chance to look at this?

**Comment by dannyyaou** [comment] 2017-03-08 06:01
Hello, Sorry for replying so late!
yes ! reinstall last version do work!

**Comment by sergey-akhalkov** [comment] 2017-03-08 08:27
@dannyyaou, thank you for the response, closing this for now, please feel free to reopen if needed.

**Closed by sergey-akhalkov** 2017-03-08 08:27 UTC
Labels: investigating, waiting-for-clarification
