### ISSUE TITLE
Dashboard statistics number seem not correct

### ISSUE THREAD

**Issue by luatnd** [microsoft/react-native-code-push#1730] opened 2019-11-26 11:12 UTC
### Problem
`Install` is far smaller than `Downloads` for all versions.
The latest version was released 3 weeks ago.
Is there any mistake in statistics?

### Steps to Reproduce
Just go to your dashboard and see this screen:

![image](https://user-images.githubusercontent.com/1859127/69624741-d772d080-1077-11ea-9c60-6ccd96a36f5c.png)

Can anyone tell me:

* What is `ACTIVE` mean? What is `3256 of 9449` ?
* Why `Install` is far smaller than `Downloads`, will all my clients be stayed up to date if they open app?

I use `InstallMode.ON_NEXT_RESUME` and `CodePush.sync()` automatic-flow, no other manually handlings

Thanks

**Comment by luatnd** [comment] 2020-02-19 09:28
I think it's a reporting issue, happy to see any update on this issue.

**Comment by alexandergoncharov** [comment] 2020-06-17 13:19
Hi @luatnd ,
Thanks for reporting!

Yeah, it is a known issue that our metrics can be incorrect. But it is hard to investigate since it is hard to reproduce but it is on our roadmap. Here is an issue for that: https://github.com/microsoft/code-push/issues/410

**Comment by alexandergoncharov** [comment] 2020-06-25 08:27
Hi @luatnd ,

I'm going to close this issue as a duplicate.  I'll ping you in that original issue if we will need some info from you. Also, we will keep you posted.

Please feel free to reopen this issue if you have any questions.

**Closed by alexandergoncharov** 2020-06-25 08:27 UTC
Labels: bug, waiting-for-clarification
