### ISSUE TITLE
[Error] App "XXX" does not exist.

### ISSUE THREAD

**Issue by wangcheng714** [Microsoft/react-native-code-push#1083] opened 2017-11-20 08:31 UTC
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.  code-push release-react com-rrd-finance-android android --bundleName "index.android.bundle" --deploymentName "devRelease" --description "RRD App  5.4.0版本发布" --development false --entryFile "./src/entry/index.android.js" --targetBinarsion ">=5.4.1 <5.5.0"
2.  But if i execute this command use app owner not collaborator ， it publish ok 
3.  

### Expected Behavior
What you expected to happen?

publish ok

### Actual Behavior
What actually happens?
```
   App "com-rrd-finance-android" does not exist.
```

**Comment by felix-zg** [comment] 2017-11-20 09:51
Same here 👍

**Comment by max-mironov** [comment] 2017-11-20 11:59
Hey @wangcheng714, @felix-zg
So just to clarify -> you are able to release the update being an owner of the app but collaborators are unable to release the app due to `app does not exist` error?

If you get a chance - could you please try the following:
1) Share the output of `code-push app ls` when logged in as a collaborator
2) Try to release the update using the new [AppCenter CLI](https://github.com/Microsoft/appcenter-cli) to get out if it is not working also? (`appcenter codepush release-react`)
3) Login to [AppCenter](https://appcenter.ms) site to verify if you are added as a collaborator's there?

**Comment by felix-zg** [comment] 2017-11-20 13:54
Hey @max-mironov,
Thank you for the fast response, I found the following change with `code-push app ls`.
The app name changed from "AppName" to "Username/AppName".
Change of the app name solved the issue for me.

**Comment by aubreywahl** [comment] 2017-11-20 18:06
I'm having the same problem as OP.

@felix-zg this totally fixed the problem! Thank you :)

**Comment by wangcheng714** [comment] 2017-11-21 03:09
@max-mironov   i change the name form AppName to Username/AppName ,  @felix-zg   work for me! Thank you !

**Comment by max-mironov** [comment] 2017-11-21 07:08
Thanks guys, good to know that the issue is resolved for you.

**Comment by thecachedbyte** [comment] 2017-11-25 14:52
Changing AppName to Username/AppName is not working for me.

Note: I am a collaborator not an owner.

**Comment by max-mironov** [comment] 2017-11-26 17:57
Hey @thecachedbyte, thanks for reporting!  Several questions:
What is the exact error you see? Is it still "App doesn't exist?"
Are you trying it with OLD CLI? If yes what is the CLI version you are on?
Can you share the output of `code-push app ls` command?
Can you try it with [new CLI](https://github.com/Microsoft/appcenter-cli) and let us know if it is not working either?

**Comment by thecachedbyte** [comment] 2017-11-27 04:49
Its happening for new CLI also.. appcenter version 1.0.3.. erroe is same "app doesn't exist" https://github.com/Microsoft/appcenter-cli/issues/324

**Comment by max-mironov** [comment] 2017-11-27 08:33
Hey @thecachedbyte, just have tried (I am a collaborator for this app) and it works for me.
![image](https://user-images.githubusercontent.com/24542698/33257080-af15f304-d309-11e7-9460-c296cebc77a1.png)

```
D:\Projects\Issues\rnIssue1090>code-push release-react sergey.akhalkov/rncp976-android android
Detecting android app version:

Using the target binary version value "1.0" from "android\app\build.gradle".
...
Releasing update contents to CodePush:

Upload progress:[==================================================] 100% 0.0s
Successfully released an update containing the "C:\Users\max\AppData\Local\Temp\CodePush" directory to the "Staging" deployment of the "sergey.akhalkov/rncp976-android" app.

D:\Projects\Issues\rnIssue1090>
```
Can you share the exact command you are executing? Does your app belongs to organization in app center or not?

**Comment by thecachedbyte** [comment] 2017-11-27 10:04
![image](https://user-images.githubusercontent.com/9081933/33261247-3707f8ce-d388-11e7-8150-2a91592c010f.png)

**Comment by max-mironov** [comment] 2017-11-27 10:07
@thecachedbyte thanks for quick turnaround!

As for new CLI - it seems that this [PR](https://github.com/Microsoft/appcenter-cli/pull/321) is needed to fix your issue (if you get a chance to test it with it that would be great).
Otherwise could you try with old CLI? Could you share the output and command you are using with us?

**Comment by southerneer** [comment] 2017-11-27 18:43
@max-mironov I'm having this same problem, and I'm trying to understand how [the PR](https://github.com/Microsoft/appcenter-cli/pull/321) you referenced would fix it. Does that PR only apply if you've used `set-current` for the default app? I've tried both ways (implicit app name with `set-current` and explicit app name with -a flag) with a non-owner account on both old and new CLIs (`code-push release-react` and `appcenter codepush release-react`) and I'm still having the problems described by OP.

**Comment by max-mironov** [comment] 2017-11-28 07:19
@southerneer please take a look at the following comment: https://github.com/Microsoft/appcenter-cli/issues/324#issuecomment-347434975

**Comment by max-mironov** [comment] 2017-11-29 06:55
Closing this as the issue is resolved in latest version of appcenter.

**Closed by max-mironov** 2017-11-29 06:55 UTC

**Comment by abdemirza** [comment] 2023-03-02 10:35
I was facing the same issue then I logged into the appcenter again using `appcenter login` and then logged into my account and now new apps are showing up, verified it using `appcenter apps list`
