### ISSUE TITLE
Icons disappearing

### ISSUE THREAD

**Issue by maxdjohnson** [Microsoft/react-native-code-push#180] opened 2016-02-04 02:27 UTC
Hi there, just deployed CodePush in our app but we're starting to notice missing icons on some devices. 

Comparing two phones running the same app store version and the same bundle downloaded from codepush, one shows all the icons while the other is missing a few (the icons on a TabBarIOS component).

The working phone is running ios 9.2, the other is running 9.3 beta 2.
The app is using code-push-react-native 1.6.0-beta and react-native 0.18.1

**Comment by lostintangent** [comment] 2016-02-04 02:42
Hmm interesting. Apologies for that! So the only devices that exhibit this issue are pre-release versions of iOS? On those devices, are you seeing all assets that you require via the RN assets system disappear after the CodePush update or just the tab bar icons?

We haven't done any testing with iOS 9.3 yet, so it's possible there is a breaking change in either RN or the CodePush plugin we need to respond to. We can take a look at this ASAP tomorrow if you could confirm that the issue appears to be limited to that iOS version.

Thanks so much for reporting this!

**Comment by maxdjohnson** [comment] 2016-02-04 03:01
No worries thanks for the quick reply!

It seems like it's only happening for the 9.3 prerelease and the TabBarIOS images. The odd thing is that the images were working on the prerelease phone before the bundle was updated via codepush. I'll do some more investigation tomorrow and try to reproduce it.

**Comment by lostintangent** [comment] 2016-02-04 03:11
That is really bizarre! I would expect the images to either work or not, so it's really intriguing to me that only the tab bar icons disappear after the CodePush update. Are you using custom icons or system icons? I just ask because I'll try to reproduce the issue on my end and I want to make sure I know the exact setup.

**Comment by maxdjohnson** [comment] 2016-02-04 03:15
We're using custom icons. Thanks for digging in!

**Comment by lostintangent** [comment] 2016-02-04 17:36
Hey @maxdjohnson, so I haven't been able to repro this issue unfortunately :( I upgraded my iPhone to 9.3 beta 2, and added a `TabBarIOS` component to a demo app, and I'm not seeing the icons disappear after doing a CodePush update. I tried doing an update that did and didn't modify the actual icon to see whether there was an issue with the diffing logic on the server, but it worked in both cases. Can you confirm a couple of things for me, just to make sure I'm testing the right condtions:

1. Are you referencing your `TabBarIOS.Item` icons via a `require` statement or are you relying on referencing them within an xcassets file/etc.? I'm currently testing the `require` strategy and it seems to be working fine.

    ```javascript 
    <TabBarIOS.Item title="Please work!" icon={require("./sample.png")}>
    ...
    </TabBarIOS.Item>
    ```

2. Could you paste in an example of the `react-native bundle` and `code-push release` commands you ran to perform the update? I just want to make sure we're doing the same thing. I'm 99.9999% confident that you are doing the right thing, since it's working on some devices. Otherwise, the icons shouldn't be working at all if you were only releasing the JS bundle for example.

3. Have you continued to confirm that this only repros on iOS 9.3 beta 2? 

Thanks so much and apologies again for the issue here!

**Comment by maxdjohnson** [comment] 2016-02-04 18:41
1. Yes I'm using require for the tab bar images
2. I'm running the bundler and code push from a python3 script. Relevant parts:
```
def make_release():
    try:
        os.mkdir('./release')
    except FileExistsError:
        pass
    print("Building release javascript bundle")
    subprocess.run(['react-native', 'bundle',
        '--entry-file', 'index.ios.js',
        '--platform', 'ios',
        '--dev', 'false',
        '--bundle-output', BUNDLE,
        '--sourcemap-output', BUNDLE_MAP,
        '--assets-dest', './release'],
        check=True)
    shutil.copy2(BUNDLE, './release/main.jsbundle')
```
(slightly different from the example - creates the jsbundle ouside the release dir and then copies it in)
```
    subprocess.run(['code-push', 'release', 'Nudge', './release', push_config.version], check=True)
```
3. Tested on another 9.3 beta device and no issue - looks like it's not the ios version causing the issue

I investigated some more by downloading the app container from both phones. Looks like there is a folder of assets missing from the release directory of the problematic app. Note these are both running the same OS, the same app version, and the same code push bundle, but one code push bundle is missing some assets. Could it be a problem with the unpacking of the code push archive?

If it would help in debugging I can send you both bundles to investigate

**Comment by lostintangent** [comment] 2016-02-04 20:14
Hmm, very interesting. Yeah if you could send me both bundles that would be very helpful. You can e-mail me at joncart@microsoft.com.

BTW, is your app `Nudge Health Tracking`? (I'm inferring that from your command snippets). If so, I just downloaded it and everything seemed to work great on an iOS 9.3 beta 2 device. Assuming this is your app, it also seemed like you do a silent install that applies on resume? :) Really awesome looking app!

**Comment by maxdjohnson** [comment] 2016-02-05 00:24
Sent!

**Comment by AndreyNikiforov** [comment] 2016-02-05 01:26
Seeing the same behavior. RN 0.19, Code-push 0.7.0-beta, iOS 9.2.1

**Comment by lostintangent** [comment] 2016-02-05 01:26
Thanks so much! This is really useful.

One other question: for all the devices that didn't have this issue, do you know whether they had already installed a previous CodePush update? In the samples you sent me, the one that worked looked like an app that only installed the latest release from CodePush, whereas the one with missing images, it had installed a previous CodePush update.

This scenario of transitioning between CodePush releases should work fine, but I'm just curious if you could validate whether any other successful device had also previously installed another update. That would help rule out that scenario, now that we know the issue isn't related to the iOS version.

**Comment by lostintangent** [comment] 2016-02-05 01:30
@AndreyNikiforov In your case, are only some of the images missing after the update as well? Or all images? Additionally, can you confirm whether this issue inhibited itself after an initial CodePush update or a subsequent one (I.e. an app installed a CodePush update with no problem and then later installed another update only to have some images missing).

**Comment by maxdjohnson** [comment] 2016-02-05 01:37
There was a device that had installed a previous code push update that did not exhibit the issue. Don't have a copy of the app container for you unfortunately, since I reinstalled the app to test on 9.3

**Comment by AndreyNikiforov** [comment] 2016-02-05 01:44
@lostintangent Images were in the app after install though Crashlytics and disappeared after subsequent code-push update (in my case it happens even on new installs due to the fact that code-push does not have version metadata).

I am wondering it this bug may be related to the breaking change in RN 0.19: Load assets from same folder as JSbundle – e730a9f...

**Comment by lostintangent** [comment] 2016-02-05 01:48
@AndreyNikiforov Are all of the images disappearing for you after installing the CodePush update? Are you releasing your assets to CodePush along with the JS bundle?

**Comment by AndreyNikiforov** [comment] 2016-02-05 04:08
@lostintangent I was using RN 0.14 and releasing main.jsbundle only. After upgrading to RN 0.19 (and code-push 0.7) without changing code-push release params, I started loosing images (all as far as I can differentiate). 

I followed guides and added assets catalog to the bundle I am releasing and still loosing images. I don't know how to check code-push release content through code-push cli, so I can only assume that code-push distributed bundle and assets together.

**Comment by lostintangent** [comment] 2016-02-05 04:20
@AndreyNikiforov RN 0.15.0 is when iOS changed the way it loaded images to require them to be located relative to the JS bundle (RN 0.19.0 is when the same behavior launched for Android), so now that you're on 0.19.0, you have to upload your assets along with the JS bundle every time you release an update to CodePush. Can you share an example of the "react-native bundle" and "code-push release" commands you're running?

**Comment by AndreyNikiforov** [comment] 2016-02-05 04:51
@lostintangent I debugged processes before code-pus release execute and found that assets was not prepared in my CI for code-push. After I fixed it, images appeared!

Thanks for your prompt responses!

**Comment by lostintangent** [comment] 2016-02-05 05:04
@AndreyNikiforov Awesome! I'm soo glad that worked for you :)

**Comment by lostintangent** [comment] 2016-02-12 20:01
Hey @maxdjohnson, have you seen this issue occur again or was is just that one instance? We haven't been able to track down why this might happen, but we made some general improvements to our diff update logic that could potentially prevent a partial update from happening.

**Comment by maxdjohnson** [comment] 2016-02-17 17:16
Haven't used it since so not sure. I would have confidence to use it if the client verified the checksum of the bundle contents (after unpacking, before loading the new code) and rolled back if there was a mismatch (client side rollback is really inspired, my favorite feature. Seems like a perfect solution for this)
Is this part of the update improvements you mentioned / is it on the roadmap?

**Comment by lostintangent** [comment] 2016-02-17 18:50
We actually do this already :) We believe the bug you're hitting is related to the diff update process, which merges the contents of the current update with the contents of the newly downloaded update. In that case, the downloaded zip would be valid, but it would only include the changed files, so we're relying on the diff merge to fill in the gaps. For some reason, that process seemed to have missed copying some of the images :/

**Comment by maxdjohnson** [comment] 2016-02-17 19:39
Awesome to hear! I might be misunderstanding, but it sounds like the checksum is verified before the diff is applied. What do you think about doing a final checksum after the diff (and any other transformations) are applied? This seems like a sure-fire way to ensure that the state of the bundle on the device exactly matches the bundle uploaded to CodePush.

**Comment by lostintangent** [comment] 2016-02-17 19:58
Ah right, I see what you are saying. Yeah that would in fact be the right way to do it. The existing checksum validates the integrity of non-diffs, and the proposal you're making would validate the integrity of updates post diff-merging. We can absolutely do that and can probably get it out early next week with our next planned release!

**Comment by maxdjohnson** [comment] 2016-02-17 20:34
Great thanks! Impressed with your velocity :)

**Comment by geof90** [comment] 2016-02-19 19:23
@maxdjohnson We have merged a PR https://github.com/Microsoft/react-native-code-push/issues/205 that verifies the integrity of merged diff updates. With that I will close this issue for now. Please feel free to reopen it if you see the same issue pop up. Thanks!

**Closed by geof90** 2016-02-19 19:23 UTC
Labels: bug
