### ISSUE TITLE
How to get the reason for the Rollbacks?

### ISSUE THREAD

**Issue by s349856186** [Microsoft/react-native-code-push#1488] opened 2018-12-24 09:05 UTC
1. IOS
     Active: 3.1% (12 of 381) │
     Total: 12 (26 pending)   │
     Rollbacks: 3      

2. Android
     Active: 4.3% (14 of 329) │
     Total: 14 (5 pending)    │
     Rollbacks: 2       

How to get the reason for the rollback? Thanks

### Environment
* react-native-code-push version: "^5.3.5",
* react-native version:"0.51.0",
* iOS/Android/Windows version: ios&&Android
* Does this reproduce on a debug build or release build?  release
* Does this reproduce on a simulator, or only on a physical device?physical device

componentWillMount(){       
          CodePush.disallowRestart();
          CodePush.sync( 
                 {
                    deploymentKey: CODE_PUSH_KEY,
                    updateDialog: false,
                    installMode: CodePush.InstallMode.ON_NEXT_SUSPEND,
                 },
                this.codePushStatusDidChange.bind(this),
                this.codePushDownloadDidProgress.bind(this)
          );
}

    componentDidMount(){

        CodePush.allowRestart();
        
        CodePush.notifyAppReady();
    }

**Comment by yuri-kulikov** [comment] 2018-12-24 17:52
Hi @s349856186,
Thanks for this question!

Unfortunately, there is no simple answer to this question. There's a good explanation for [how rollback works](https://github.com/Microsoft/react-native-code-push/issues/880#issuecomment-342463583). There are some reasons why a rollback can occur, for example in some cases it can be caused by closing the app during the installation, but CodePush can't get that kind of information.

We've implemented a [feature](https://github.com/Microsoft/react-native-code-push/issues/880#issuecomment-444926393) that allows users to reinstall a rolled-back package after some delay, it can't stop updates from rollback, but can help users to get the updates eventually.

**Comment by yuri-kulikov** [comment] 2018-12-25 15:19
Hi @s349856186,
> I am currently using 5.3.5, If I upgraded locally to 5.5.0 and then released the update containing "rollbackRetryOptions", those Rollback devices can be updated normally (because they are 5.3.5)?

Users with "5.3.5 binary version" will ignore 'rollbackRetryOptions' since this feature is implemented in a native code, so you need to release a new binary version of your app for this feature to work.

**Comment by s349856186** [comment] 2018-12-26 00:47
@yuri-kulikov Thank you for your reply

**Comment by s349856186** [comment] 2018-12-27 05:13
@yuri-kulikov 
IOS:
 Active: 36% (183 of 507) │
 Total: 183 (105 pending) │
 Rollbacks: 51  

Android:
  Active: 41% (161 of 391) │
  Total: 161 (38 pending)  │
  Rollbacks: 57  

I don't know why so much rollbacks, and what will cause the pending, and the pending will not be updated again?

**Comment by yuri-kulikov** [comment] 2018-12-27 09:40
@s349856186 could please you describe the steps you have taken?

**Comment by s349856186** [comment] 2018-12-27 10:20
@yuri-kulikov 
`componentWillMount(){
CodePush.disallowRestart();
CodePush.sync(
{
deploymentKey: CODE_PUSH_KEY,
updateDialog: false,
installMode: CodePush.InstallMode.ON_NEXT_SUSPEND,
},
this.codePushStatusDidChange.bind(this),`
this.codePushDownloadDidProgress.bind(this)
);
}`

componentDidMount(){

    CodePush.allowRestart();
    
    CodePush.notifyAppReady();
}

**Comment by yuri-kulikov** [comment] 2018-12-27 14:36
@s349856186, can you please specify some detailed information:
* `react-native-code-push` version: `5.3.5`?
* `react-native` version: ?
* is it your first code-push release?
* can you reproduce a rollback on your device?

**Comment by s349856186** [comment] 2018-12-28 00:56
@yuri-kulikov sorry
react-native-code-push version: "^5.3.5",
react-native version:"0.51.0",
iOS/Android/Windows version: ios&&Android
Does this reproduce on a debug build or release build? release
Does this reproduce on a simulator, or only on a physical device?physical device

is it your first code-push release? yes，it's first code-push 
My cmd is : 
code-push release-react myappAndroid android --d Production
code-push release-react myappIOS ios --d Production

can you reproduce a rollback on your device?
I try many times yesterday, not reproduce

**Comment by yuri-kulikov** [comment] 2019-01-09 09:09
Hey @s349856186,
Sorry for the delay!

I tried to reproduce the issue with the code you provided, but everything works fine. Maybe you could provide us with some simple demo project so we can check your code directly and maybe detect some problems?

**Comment by yuri-kulikov** [comment] 2019-01-21 10:31
Unfortunately, we haven’t heard from you in a while, so I'll close the issue for now, but please feel free to reopen it if you have some additional details or questions.

**Closed by yuri-kulikov** 2019-01-21 10:31 UTC
Labels: bug, waiting-for-clarification
