### ISSUE TITLE
DOWNLOADING_PACKAGE forever...

### ISSUE THREAD

**Issue by cnjsstong** [Microsoft/react-native-code-push#362] opened 2016-06-01 13:58 UTC
We've been consistently having issues with deploying new bundles. Existing users who have ever had downloaded a new push will see DOWNLOADING_PACKAGE forever. First-time users are fine. We are using 1.10.4-beta, both native and js parts.

**Comment by lostintangent** [comment] 2016-06-01 14:55
That is really bizarre! Are you seeing this on both Android and iOS?

**Comment by lostintangent** [comment] 2016-06-06 02:10
@cnjsstong Are you still hitting this issue? I'd love to make sure you're unblocked, and would love to get a little more details so we can try to repro the problem. Thanks!

**Comment by lostintangent** [comment] 2016-06-08 15:57
@cnjsstong We sent out a PR to prevent the call to `sync` from hanging like this, however, it doesn't address the root cause of why you're hitting this issue in the first place.

After the fix in #368 is merged, you would see the `DOWNLOADING_PACKAGE` status, and then the `Promise` returned by `sync` would resolve with `UNKNOWN_ERROR`, because the call was hanging due to an exception being thrown when the update is downloading. That said, you want the `sync` call to actually succeed, so we need to understand what's going on.

If you could let us know if you're experiencing this problem on iOS or Android, what version of React Native you're using, and what other RN plugins your app has installed, that would be hugely helpful to try to get a repro. Thanks!

**Comment by lostintangent** [comment] 2016-06-11 18:47
I'm going to close this for now since we can't unfortunately repro it, and we resolved the hang. If you experienced any instances where calling sync results in an exception, please let us know, and we can investigate the issue further. Thanks!

**Closed by lostintangent** 2016-06-11 18:47 UTC
