### ISSUE TITLE
Warning: Stateless function components cannot be given refs

### ISSUE THREAD

**Issue by diegocouto** [Microsoft/react-native-code-push#750] opened 2017-03-10 10:58 UTC
Hi, guys!

First of all, thanks for your amazing work with code-push, it's awesome! 😉

### Description

After finishing codePush setup process, I've started to see a warning like:

```
Warning: Stateless function components cannot be given refs 
(See ref "rootComponent" in App created by CodePushComponent). 
Attempts to access this ref will fail.
```

### Reproduction

Currently, I have a setup file which is responsible for defining the main component, which is just like:

**setup.js**
```javascript
// ...
let App = () => (
  <Provider store={store}>
    <StyleProvider style={theme}>
      <RouterWithRedux scenes={scenes} />
    </StyleProvider>
  </Provider>
);

module.exports = codePush(App);
```

**index.ios.js / index.android.js**
```javascript
import {AppRegistry} from 'react-native';
const App = require('./config/setup');

AppRegistry.registerComponent('MyApp', () => App);
```

Except for a _ref_ used on a TextInput, defined on a component with state, I do not use any other _refs_. Removing codepush() makes this warning disappear.

### Additional Information

* react-native-code-push version: **1.17.2-beta**
* react-native version: **0.42.0**
* iOS/Android/Windows version: **iOS 10.2**
* Does this reproduce on a debug build or release build? **Debug**
* Does this reproduce on a simulator, or only on a physical device? **Both**

**Comment by sergey-akhalkov** [comment] 2017-03-21 13:01
Hi @diegocouto, thank you for reporting the issue. Also please sorry for late reply.
The issue is caused by [this line of code](https://github.com/Microsoft/react-native-code-push/blob/master/CodePush.js#L430). But the root cause of the issue is that stateless component is in use. Our demo app [extends React.Component](https://github.com/Microsoft/react-native-code-push/blob/master/Examples/CodePushDemoApp/demo.js#L14) `class CodePushDemoApp extends Component {` and use it further with [codePush decorator](https://github.com/Microsoft/react-native-code-push/blob/master/Examples/CodePushDemoApp/demo.js#L160): `CodePushDemoApp = CodePush(codePushOptions)(CodePushDemoApp);` 
To fix the issue could you please try [the following](https://github.com/reactjs/react-redux/blob/master/docs/api.md#vanilla-react):
**setup.js**
```javascript
class MyRoot extends Component {
    ...
    render() {
        return <div />
    }
}

MyRoot = codePush(MyRoot);

let App = () => (
  <Provider store={store}>
    <MyRoot />
  </Provider>
);

module.exports = App;
```
[Here is](https://github.com/reactjs/react-redux/blob/master/test/components/Provider.spec.js#L11) I've found the code sample that uses the same approach.

Please let me know if it helps or if you have any issues.

**Comment by sergey-akhalkov** [comment] 2017-03-28 13:33
@diegocouto, just a friendly ping.

**Comment by diegocouto** [comment] 2017-03-29 00:42
Hi, @sergey-akhalkov! Thank you for your detailed response. 😄  I'll be working on this tomorrow and, as soon as I finish this and some other changes I'll update this issue, ok?

Thanks again! 😉

**Comment by sergey-akhalkov** [comment] 2017-03-29 12:23
@diegocouto, great! Closing this, please feel free to reopen if needed.

**Closed by sergey-akhalkov** 2017-03-29 12:23 UTC
Labels: waiting-for-clarification
