### ISSUE TITLE
App crashing while restarting after downloading update 

### ISSUE THREAD

**Issue by vidyuthd** [Microsoft/react-native-code-push#852] opened 2017-05-22 10:59 UTC
**App crashes on restart whenever new update is downloaded**

App is crashing with following exception on restarting after downloading the update
`05-22 12:56:22.258 13131-13529/com.paisool.internal E/ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)
05-22 12:56:22.314 13131-13533/com.paisool.internal E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
                                                                      Process: com.paisool.internal, PID: 13131
                                                                      com.facebook.react.common.JavascriptException: Module AppRegistry is not a registered callable module (calling runApplication), stack:
                                                                      value@53:2637
                                                                      <unknown>@53:1013
                                                                      <unknown>@53:106
                                                                      value@53:985
                                                                      
                                                                          at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:97)
                                                                          at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:81)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
                                                                          at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
                                                                          at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                          at java.lang.Thread.run(Thread.java:818)`

See this from Code push logs : 
```
12:56:06.817 13131-13131/? D/ReactNative: [CodePush] Loading JS bundle from "assets://index.android.bundle".
12:56:18.600 13131-13190/com.paisool.internal I/ReactNativeJS: [CodePush] Checking for update.
12:56:18.645 13131-13190/com.paisool.internal I/ReactNativeJS: [CodePush] Reporting binary update (0.0.17). 05-22 12:56:20.129 13131-13190/com.paisool.internal I/ReactNativeJS: [CodePush] Downloading package.  12:56:21.882 13131-13190/com.paisool.internal I/ReactNativeJS: [CodePush] Installing update. 
12:56:21.894 13131-13191/com.paisool.internal D/ReactNative: [CodePush] Loading JS bundle from "/data/user/0/com.paisool.internal/files/CodePush/ad2e484fa9a7eaa783c8803d52844cfa3f462f18636fc49b4830e9a4dd0977e4/CodePush/index.android.bundle". 
12:56:21.897 13131-13190/com.paisool.internal I/ReactNativeJS: [CodePush] Restarting app
```

Full contents of the logs : 

```
S: [CodePush] Downloading package.
05-22 12:56:21.882 13131-13190/com.paisool.internal I/ReactNativeJS: [CodePush] Installing update.
05-22 12:56:21.894 13131-13191/com.paisool.internal D/ReactNative: [CodePush] Loading JS bundle from "/data/user/0/com.paisool.internal/files/CodePush/ad2e484fa9a7eaa783c8803d52844cfa3f462f18636fc49b4830e9a4dd0977e4/CodePush/index.android.bundle"
05-22 12:56:21.897 13131-13190/com.paisool.internal I/ReactNativeJS: [CodePush] Restarting app
05-22 12:56:21.897 13131-13190/com.paisool.internal W/unknown:React: Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
05-22 12:56:21.897 13131-13190/com.paisool.internal W/MessageQueue: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {b8c9459} sending message to a Handler on a dead thread
                                                                    java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {b8c9459} sending message to a Handler on a dead thread
                                                                        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
                                                                        at android.os.Handler.enqueueMessage(Handler.java:631)
                                                                        at android.os.Handler.sendMessageAtTime(Handler.java:600)
                                                                        at android.os.Handler.sendMessageDelayed(Handler.java:570)
                                                                        at android.os.Handler.post(Handler.java:326)
                                                                        at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:61)
                                                                        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                        at java.lang.Thread.run(Thread.java:818)
05-22 12:56:21.898 13131-13190/com.paisool.internal W/unknown:React: Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
05-22 12:56:21.899 13131-13190/com.paisool.internal W/MessageQueue: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {b8c9459} sending message to a Handler on a dead thread
                                                                    java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {b8c9459} sending message to a Handler on a dead thread
                                                                        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
                                                                        at android.os.Handler.enqueueMessage(Handler.java:631)
                                                                        at android.os.Handler.sendMessageAtTime(Handler.java:600)
                                                                        at android.os.Handler.sendMessageDelayed(Handler.java:570)
                                                                        at android.os.Handler.post(Handler.java:326)
                                                                        at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:61)
                                                                        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                        at java.lang.Thread.run(Thread.java:818)
05-22 12:56:21.904 13131-13190/com.paisool.internal W/unknown:React: Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
05-22 12:56:21.904 13131-13190/com.paisool.internal W/MessageQueue: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {b8c9459} sending message to a Handler on a dead thread
                                                                    java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {b8c9459} sending message to a Handler on a dead thread
                                                                        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
                                                                        at android.os.Handler.enqueueMessage(Handler.java:631)
                                                                        at android.os.Handler.sendMessageAtTime(Handler.java:600)
                                                                        at android.os.Handler.sendMessageDelayed(Handler.java:570)
                                                                        at android.os.Handler.post(Handler.java:326)
                                                                        at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:61)
                                                                        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                        at java.lang.Thread.run(Thread.java:818)
05-22 12:56:21.904 13131-13190/com.paisool.internal W/unknown:React: Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
05-22 12:56:21.905 13131-13190/com.paisool.internal W/MessageQueue: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {b8c9459} sending message to a Handler on a dead thread
                                                                    java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {b8c9459} sending message to a Handler on a dead thread
                                                                        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
                                                                        at android.os.Handler.enqueueMessage(Handler.java:631)
                                                                        at android.os.Handler.sendMessageAtTime(Handler.java:600)
                                                                        at android.os.Handler.sendMessageDelayed(Handler.java:570)
                                                                        at android.os.Handler.post(Handler.java:326)
                                                                        at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:61)
                                                                        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                        at java.lang.Thread.run(Thread.java:818)
05-22 12:56:22.089 13131-13529/com.paisool.internal I/ReactNativeJS: Promise based runtime ready
05-22 12:56:22.089 13131-13529/com.paisool.internal I/ReactNativeJS: Callback based runtime ready
05-22 12:56:22.137 13131-13543/com.paisool.internal D/DatabaseModule: QueueItem Created Identifier: 35 query: NumQ: 1 first: SELECT versionId from Version LIMIT 1
05-22 12:56:22.160 13131-13543/com.paisool.internal D/DatabaseModule: QueueItem Created Identifier: 36 query: NumQ: 1 first: select u._id as _id, u.id as id, u.mobile as mobile, u.settings as settings from USERS u, misc m where m.key = ? and m.value = u.id 
05-22 12:56:22.258 13131-13529/com.paisool.internal E/ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)
05-22 12:56:22.314 13131-13533/com.paisool.internal E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
                                                                      Process: com.paisool.internal, PID: 13131
                                                                      com.facebook.react.common.JavascriptException: Module AppRegistry is not a registered callable module (calling runApplication), stack:
                                                                      value@53:2637
                                                                      <unknown>@53:1013
                                                                      <unknown>@53:106
                                                                      value@53:985
                                                                      
                                                                          at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:97)
                                                                          at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:81)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
                                                                          at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
                                                                          at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                          at java.lang.Thread.run(Thread.java:818)
05-22 12:56:22.316 1545-1693/system_process W/ActivityManager:   Force finishing activity com.paisool.internal/com.reactnativenavigation.controllers.NavigationActivity
05-22 12:56:22.320 1226-1301/? D/gralloc_ranchu: gralloc_alloc: format 1 and usage 0x333 imply creation of host color buffer
                                                 
                                                 [ 05-22 12:56:22.325  1545: 1693 D/         ]
                                                 HostConnection::get() New Host Connection established 0x7ffc50942de0, tid 1693
05-22 12:56:22.335 1226-1226/? E/EGL_emulation: tid 1226: eglCreateSyncKHR(1660): error 0x3004 (EGL_BAD_ATTRIBUTE)
05-22 12:56:22.429 1545-1693/system_process D/gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
05-22 12:56:22.434 1545-1545/system_process W/art: Long monitor contention event with owner method=void com.android.server.am.ActivityManagerService.crashApplication(com.android.server.am.ProcessRecord, android.app.ApplicationErrorReport$CrashInfo) from ActivityManagerService.java:12502 waiters=0 for 110ms
05-22 12:56:22.499 13131-13529/com.paisool.internal W/unknown:React: Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
05-22 12:56:22.499 13131-13529/com.paisool.internal W/MessageQueue: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {f0f66b4} sending message to a Handler on a dead thread
                                                                    java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {f0f66b4} sending message to a Handler on a dead thread
                                                                        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
                                                                        at android.os.Handler.enqueueMessage(Handler.java:631)
                                                                        at android.os.Handler.sendMessageAtTime(Handler.java:600)
                                                                        at android.os.Handler.sendMessageDelayed(Handler.java:570)
                                                                        at android.os.Handler.post(Handler.java:326)
                                                                        at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:61)
                                                                        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                        at java.lang.Thread.run(Thread.java:818)
05-22 12:56:22.501 13131-13529/com.paisool.internal W/unknown:React: Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
05-22 12:56:22.501 13131-13529/com.paisool.internal W/MessageQueue: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {f0f66b4} sending message to a Handler on a dead thread
                                                                    java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {f0f66b4} sending message to a Handler on a dead thread
                                                                        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
                                                                        at android.os.Handler.enqueueMessage(Handler.java:631)
                                                                        at android.os.Handler.sendMessageAtTime(Handler.java:600)
                                                                        at android.os.Handler.sendMessageDelayed(Handler.java:570)
                                                                        at android.os.Handler.post(Handler.java:326)
                                                                        at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:61)
                                                                        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                        at java.lang.Thread.run(Thread.java:818)
```

We have used [Wix Navigation](https://github.com/wix/react-native-navigation) instead of the standard navigation which actually abstracts out the AppRegistry.registerComponent part, so don't know if this is specific to wix navigation.

### Reproduction

I think this is reproducible with any app which uses react-native-navigation as the method of showing up views changes compared to standard react. Trying to try a simple project which has just code-push and react-native-navigation, will update reproducabiliity once I tryout with sample app.

### Additional Information

* react-native-code-push version: 1.17.0-beta
* react-native version: 0.41.1
* Android version:  Marshmellow(6.0), Nougat(7)
* Does this reproduce on a debug build or release build? Reproduces only on Release build not on debug build
* Does this reproduce on a simulator, or only on a physical device? This gets reproduced both on simulator as well as device but only on release build and not on debug build.

**Comment by sergey-cherednichenko** [comment] 2017-05-30 14:34
Hi vidyuthd, thank you for your question!
Unfortunately i can't reproduce this bug.
Could you please try the following [example](https://github.com/sergey-cherednichenko/react-native-code-push/raw/a6f74a6d5c56601ac662a269f593a31269f82cfd/example.zip).
Some files in project changed by react-native-code-push on the link phase, and some of them required to be manually changed when installing react-native-navigation. Therefore you may see merge conflicts between react-native-navigation and react-native-code-push. You may use files from example mentioned above or compare these files with corresponding files of your project and resolve possible conflicts manually.
Please see list of files below:
```
android\settings.gradle
android\app\src\main\java\com\yourProjectName\MainApplication.java
android\app\build.gradle
```
Please let me know the results

**Comment by sergey-akhalkov** [comment] 2017-06-02 10:43
@vidyuthd, just a friendly ping.

**Comment by vidyuthd** [comment] 2017-06-02 15:33
@sergey-akhalkov , I have a tried on my machine with sample app which has both React Native Navigation and Code Push, and was not able to reproduce this issue. I will look further and seek your help in case its needed.

Thanks

**Comment by max-mironov** [comment] 2017-06-02 15:41
Thanks for the update @vidyuthd , I believe this way we could close the issue for now, feel free to reopen if you will see this again.

**Closed by max-mironov** 2017-06-02 15:41 UTC
Labels: no-repro, waiting-for-clarification

**Comment by lslima91** [comment] 2017-06-22 17:24
@vidyuthd having the same problem with Release and IMMEDIATE. Did you manage to fin the issue?
