### ISSUE TITLE
[iOS] Third-party libraries not found for "staging" config: Solution!

### ISSUE THREAD

**Issue by danieldunderfelt** [Microsoft/react-native-code-push#426] opened 2016-07-12 10:58 UTC
Hi!

I installed CodePush in my app today and followed the instructions for multi-environments, where the docs say to create a "staging" project configuration. After doing that, the project would not build at all when the scheme was set to "staging", complaining that no libraries could be found. Re-linking with rnpm didn't help, but I figured out that the issue was that no third-party libraries (including code-push!) include the staging configuration, making the build fail.

The solution was this stackoverflow answer: http://stackoverflow.com/questions/30884778/how-to-compile-a-project-with-app-and-library-in-the-same-workspace-with-differe/30884779#30884779

I had to change it a bit, using the same string for "header search paths" as "framework search paths" (functionally omitting the `/include` part of that string), but now everything works.

I think this should be mentioned in the documentation right where the user is instructed to create the "staging" configuration.

**Comment by geof90** [comment] 2016-07-12 18:29
@danieldunderfelt Thanks for the feedback. I will see how we can improve the documentation.

When you created the staging project configuration, did you also manually create a Staging scheme?

**Comment by danieldunderfelt** [comment] 2016-07-12 21:43
Hi!

No, that was created when I copied the release config and made the staging config.

**Comment by geof90** [comment] 2016-07-13 22:47
@danieldunderfelt Unfortunately I was unable to repro the error you were seeing. Are you using CocoaPods for dependency management?

**Comment by danieldunderfelt** [comment] 2016-07-14 06:46
@geof90 No, not using CocoaPods. Does it manage these things for me?

When I figured out why my builds weren't working, that the third-party packages didn't have a staging config, I thought having cocoapods wouldn't matter.

**Comment by geof90** [comment] 2016-07-14 06:49
@danieldunderfelt no I only asked because I wasn't using CocoaPods and I was wondering if you were.

**Comment by danieldunderfelt** [comment] 2016-07-14 06:52
@geof90 oh, good good!

Maybe your xcode made staging config for your third-party packages, and my xcode glitched out and didn't?

**Comment by Thorbenandresen** [comment] 2016-07-15 21:59
Nice, this did also fix it for me. I omitted the Step 3 (changing the project.pbxproj) and my Fabric.framework does still work fine. 

However when I use different PRODUCT_NAMES for the different build environment, I am getting now a build error. I am have setup the names according to [this article](https://engineering.circle.com/different-app-icons-for-your-ios-beta-dev-and-release-builds-af4d209cdbfd#.quncr6nt6)

![screen shot 2016-07-15 at 1 20 49 pm](https://cloud.githubusercontent.com/assets/8238976/16885195/72c6bf66-4a9b-11e6-8d80-666401bd04e7.png)

When i build my `release` config everything works, but not when I build the `debug` or `staging` config. In these cases I get the following errors: 

![screen shot 2016-07-15 at 11 22 42 am](https://cloud.githubusercontent.com/assets/8238976/16884573/2983eb60-4a98-11e6-9395-1a7169f5635c.png)

I have tried to fix it by

- set Target => Info => Executable file to `$(PRODUCT_NAME)`
- set Target => Bundler Loader to => $(BUILT_PRODUCTS_DIR)/$(PRODUCT_NAME).app/$(PRODUCT_NAME)

I have cleaned my build folder before each build. 

This did not happen before, so it could be related to this issue. 

(For now my workaround is to use different app icons in order to distinguish my different build environment - as outlines in the article above)

**Comment by FernandoMorais** [comment] 2016-07-19 00:26
Here I solved the staging problem by correcting the TEST_HOST which is pointing to a fixed value despite the new PRODUCT_NAME.

I've changed the scheme to use the staging variation for tests builds.

I hope it helps!

**Comment by huitsing** [comment] 2016-07-29 06:48
Our solution might be helpful here as well: https://zeemee.engineering/how-to-set-up-multiple-schemes-configurations-in-xcode-for-your-react-native-ios-app-7da4b5237966#.pxa41apg1

**Comment by FernandoMorais** [comment] 2016-08-16 02:06
really nice @huitsing! Much more complete solution!

**Comment by jm555jm** [comment] 2016-08-18 09:43
I have the same issue, too. I use xcode 8 beta 6.
library not found for -lCodePush in the schema named "Staging"

**Comment by flavordaaave** [comment] 2016-11-14 23:08
@jm555jm THX for the hint. I had quite a few external libraries and I was desperately trying to unlink and re-link them without any luck. But manually removing and re-adding them in the `Link Binary with Libraries` section finally solved the issue and my builds are succeeding again.

**Comment by bernatfortet** [comment] 2017-02-01 16:11
@jm555jm @flavordaaave thanks for the tip! 
It took me a couple minutes to figure out exactly how to do that, so for others:
1. Select your app `target`
2. Make sure you are in the `General` Tab
3. Scroll down until `Link Binary with Libraries`
4. Select `libCodePush`
5. Press `-` minus button at the bottom left
6. Press `+` plus button and search for `libCodePush`
👍

**Comment by bernatfortet** [comment] 2017-02-01 16:35
Actually after trying that I found that I was still with the Release scheme.
After changing it to staging, and after removing and re-adding the library it still doesn't work 😞 
Same exact error.

**Comment by Amurmurmur** [comment] 2017-02-02 09:17
+1 Same error, with the header, when on Staging Scheme :(

**Comment by sergey-akhalkov** [comment] 2017-02-08 09:25
@bernatfortet, could please look try to apply instructions from this PR https://github.com/Microsoft/react-native-code-push/pull/690 and let me know if it helps?

**Comment by sergey-akhalkov** [comment] 2017-02-13 14:13
Closing this due to https://github.com/Microsoft/react-native-code-push/pull/690 has been merged and fixed similar issue https://github.com/Microsoft/react-native-code-push/issues/688, please feel free to reopen in case of any questions or issues.

**Closed by sergey-akhalkov** 2017-02-13 14:13 UTC

**Comment by ndbroadbent** [comment] 2017-04-19 17:36
Hi, I also ran into an issue, and came straight here. But for me, I just had to run `pod install`, and then everything worked after that.

**Comment by ndbroadbent** [comment] 2017-04-19 21:27
Argh I still struggled with this for quite a while, but then I realized that you need to build a Release version first, before building Staging. (Because I changed the 'build products path' to `$(BUILD_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)`.)

**Comment by fannt** [comment] 2017-05-24 15:53
I had a trouble with cocoapods overriding this config settings, used this as a workaround:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'YourTarget'
      target.build_configurations.each do |config|
        if config.name == 'STAGING'
          config.build_settings['CONFIGURATION_TEMP_DIR'] = '$(PROJECT_TEMP_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)'
          config.build_settings['CONFIGURATION_BUILD_DIR'] = '$(PROJECT_TEMP_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)'
        end
      end
    end
  end
end
```

**Comment by mtt87** [comment] 2017-09-16 16:39
In my case after following the instructions on the official documentation I had to change this as well to be `$PODS_BUILD_DIR/Release$(EFFECTIVE_PLATFORM_NAME)`
<img width="711" alt="screen shot 2017-09-16 at 17 38 37" src="https://user-images.githubusercontent.com/2150927/30514040-f0a81fea-9b05-11e7-9800-edeef0840b67.png">

**Comment by wprater** [comment] 2017-11-19 02:09
These fixes don't seem to work on CI servers, since the Release build path won't have any build or header files in it.  

Any thoughts on fixes or running on a CI (Buddy Build or MSFT App Center?)

**Comment by jpaolini** [comment] 2018-01-02 19:27
After spending some time trying all the different ideas shared here, it turned out my problem was related to the generated [pods project](https://github.com/CocoaPods/CocoaPods/issues/7081).  I followed the instructions [here](https://github.com/Microsoft/react-native-code-push/blob/master/docs/multi-deployment-testing-ios.md) then updated cocoa pods to `1.4.0.rc.1` and everything worked without issue.

**Comment by MyGuySi** [comment] 2018-02-06 15:32
@wprater I'm having the same issue, it works fine if I build Release first. Did you happen to get it working?

**Comment by aligfl** [comment] 2018-05-10 21:45
@wprater did you get it working on your CI system ? aka buddybuild or App Center?
Did you try the solution proposed by @huitsing ?

aka: https://zeemee.engineering/how-to-set-up-multiple-schemes-configurations-in-xcode-for-your-react-native-ios-app-7da4b5237966

**Comment by jpaolini** [comment] 2018-05-11 05:53
Not sure if this helps, but I had to do something similar to @fannt.  Cocopods was overwriting the configurations:
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name.downcase == 'YourTargetName
      target.build_configurations.each do |config|
        if config.name.downcase == 'staging'
          config.build_settings['CONFIGURATION_BUILD_DIR'] = '$(BUILD_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)'
        end
      end
    end
  end
end
```

**Comment by aligfl** [comment] 2018-05-11 10:17
Someone posted a solution on another thread. Which has worked for me locally + CI (buddybuild)

Solution: https://github.com/facebook/react-native/issues/11813#issuecomment-310029148

**Comment by Amurmurmur** [comment] 2018-06-23 15:50
Any one having an issue when using tipsi-stripe and having multiple deployments?
My pod file
```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

workspace 'appname'

target 'targetNameTests' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for targetName
  pod 'AppCenter/Crashes', '~> 1.6.1'
  pod 'AppCenter/Analytics', '~> 1.6.1'
  pod 'AppCenterReactNativeShared', '~> 1.5.1'
  # Stripe
  pod 'Stripe', '~> 11.2.0'

    target 'targetNameTests' do
        inherit! :search_paths
        # Pods for testing
    end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'targetName'
        target.build_configurations.each do |config|
          if config.name == 'Staging'
            config.build_settings['CONFIGURATION_TEMP_DIR'] = '$(PROJECT_TEMP_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)'
            config.build_settings['CONFIGURATION_BUILD_DIR'] = '$(PROJECT_TEMP_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)'
          end
        end
      end
    end
  end
```
I've set `Per-configuration Build Products Path` for Staging to `$(BUILD_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)`
Also I've updated` PODS_CONFIGURATION_BUILD_DIR` for Staging to `${PODS_BUILD_DIR}/Release$(EFFECTIVE_PLATFORM_NAME)`

**Comment by NickToropov** [comment] 2018-06-25 09:22
Hi @Amurmurmur, I'm sure that problem is still in `CONFIGURATION_BUILD_DIR` and `CONFIGURATION_TEMP_DIR` settings. I've just created new ReactNative application, copied your Podfile, actualized it to this:
```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

workspace 'appname'

target 'Issue426' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # React Native requirements
pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
 ]
 # Explicitly include Yoga if you are using RN >= 0.42.0
 pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
 pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
 pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
 pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # Pods for targetName
  pod 'AppCenter/Crashes', '~> 1.6.1'
  pod 'AppCenter/Analytics', '~> 1.6.1'
  pod 'AppCenterReactNativeShared', '~> 1.5.1'
  # Stripe
  pod 'Stripe', '~> 11.2.0'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'Issue426'
            target.build_configurations.each do |config|
                if config.name == 'Staging'
                    config.build_settings['CONFIGURATION_TEMP_DIR'] = '$(PROJECT_TEMP_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)'
                    config.build_settings['CONFIGURATION_BUILD_DIR'] = '$(PROJECT_TEMP_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)'
                end
            end
        end
    end
end
```
then executed `pod install`, opened generated `appname.xcworkspace` in XCode, added new  `Staging` configuration (based on Release configuration), added new `Staging` scheme, updated `Pre-configuration Build Files Path` and `Pre-configuration Intermediate Build Files Path` for both Issue426 and Pods project. After this steps my demo project built successfully. 

Please try my steps and if the issue won't be solved provide me with sample project that I could able to reproduce your situation and help to fix it.

**Comment by jerson** [comment] 2018-07-07 02:59
for me worked with 

```ruby

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
              if config.name == 'Staging'
                  config.build_settings['CONFIGURATION_TEMP_DIR'] = '$(PROJECT_TEMP_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)'
                  config.build_settings['CONFIGURATION_BUILD_DIR'] = '$(BUILD_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)'
              end
  end
  installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              if config.name == 'Staging'
                  config.build_settings['CONFIGURATION_TEMP_DIR'] = '$(PROJECT_TEMP_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)'
                  config.build_settings['PODS_CONFIGURATION_BUILD_DIR'] = '${PODS_BUILD_DIR}/Release$(EFFECTIVE_PLATFORM_NAME)'
              end
          end
  end
end
```

**Comment by MrPluto** [comment] 2018-11-10 11:47
for me i just need set like this
```
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        if config.name == 'Staging'
            config.build_settings['CONFIGURATION_BUILD_DIR'] = '$(BUILD_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)'
        end
    end
end

```

**Comment by mhdnp** [comment] 2019-02-27 02:38
> In my case after following the instructions on the official documentation I had to change this as well to be `$PODS_BUILD_DIR/Release$(EFFECTIVE_PLATFORM_NAME)`
> <img alt="screen shot 2017-09-16 at 17 38 37" width="711" src="https://user-images.githubusercontent.com/2150927/30514040-f0a81fea-9b05-11e7-9800-edeef0840b67.png">

When i did this, it has solved my build problem. But it seems it is taking my production deployment from codepush. so it seems it is taking release codepush key value instead of staging. Not sure why.

**Comment by AlgirdasVZ** [comment] 2019-04-05 10:54
If anybody is still struggling with this issue - there is a simple way to differentiate between Codepush staging and release keys using the same "Release" configuration if you already do your builds with Fastlane.

You basically need to have these lines in your Info.plist:

```
<key>CodePushDeploymentKey</key>  
<string>$(CODEPUSH_KEY)</string>
```

and then, assuming you already have different Fastlane lanes for staging and release, add appropriate Codepush key for each lane in form of a gym param:

```
xcargs: "CODEPUSH_KEY=<your staging/release key>"
```

The key will be inserted during build process and that's about it!
This approach definitely does not cover all cases, but could be useful for those who are searching for a simplified solution without the need to edit your xcode project file.

**Comment by nikopolidi** [comment] 2019-08-30 17:17
I got it solved and implemented for several projects.
Here is what I did:

1.  add that snippet to the end of Podfile:

```
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
              if config.name == 'Staging'
                  config.build_settings['CONFIGURATION_TEMP_DIR'] = '$(PROJECT_TEMP_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)'
                  config.build_settings['CONFIGURATION_BUILD_DIR'] = '$(BUILD_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)'
              end
  end
  installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              if config.name == 'Staging'
                  config.build_settings['CONFIGURATION_TEMP_DIR'] = '$(PROJECT_TEMP_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)'
                  config.build_settings['PODS_CONFIGURATION_BUILD_DIR'] = '${PODS_BUILD_DIR}/Release$(EFFECTIVE_PLATFORM_NAME)'
              end
          end
  end
end
```

2. Update build paths:

Set Staging value for **Per-configuration Build Products Path** and **Per-configuration intermediate Build Files path** to `$(BUILD_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)` so it looks the same as Release one
3. re-install pods. From project root: `cd ios && pod deintegrate && pod install`
4. done. Try to archive with that target to test

**NOTE:** In AppCenter I was having build failures when it's archiving successfully locally for staging target. I got it solved by removing build config from that branch and adding it back, seems like it has some kind of caching issues idk

**Comment by JimmyDLA** [comment] 2019-12-10 04:36
can anyone tell me where I can find my` BUILD_DIR` and `EFFECTIVE_PLATFORM_NAME`?

**Comment by Amurmurmur** [comment] 2019-12-11 11:44
@JimmyDLA You can find it in Xcode
https://stackoverflow.com/a/11657874

**Comment by chj-damon** [comment] 2020-06-10 10:46
none of these answers solve my problem.

**Comment by TwR-Slice** [comment] 2020-08-19 10:07
Just an FYI what worked in my case:

After creating the new configuration Staging, simply run `pod deintegrate && pod install` inside the `ios` folder of your Project. CocoaPods will then create all configurations on its own.

Staging Build -> Success
Staging Archive -> Success

Release Build -> Success
Release Archive -> Success

**Comment by tabrindle** [comment] 2021-04-16 14:40
For what it's worth, there are a few easier ways to handle this issue, after attempting without success to add a configuration, I decided it was overkill for a single value change. 

Method 1: Use info.plist variable substitution, xcargs a and a default value
- Set the deployment key to  `$(CODEPUSH_KEY:default=209348572039487520934875)` in info.plist 
- We use fastlane, so calling gym/build_app with xcargs injected in from env looks like this:

```build_app(scheme: "Release", export_method: "app-store", xcargs: "CODEPUSH_KEY='#{ENV["CODEPUSH_KEY"]}'"```

Method 2: Use a Run Script
-   Target ->  Build Phases -> Click plus -> New Run Script Phase.
- add something like this: `plutil -replace CodePushDeploymentKey -string $CODEPUSH_KEY ./APPNAME/Info.plist`

Method 3: Set in JavaScript
- did you know there is a setDeploymentKey method in the plugin for both iOS and Android? No? Cool, wasn't just me. 
- Turns out you can just pass in some configuration when starting your app, like this. This way the keys can live in your code, or however you are dealing with env vars on the javascript side. We use react-native-config, and have a staging and production env file. 
```
const Application = __DEV__
  ? App
  : codePush({
      deploymentKey:
        Platform.OS === 'ios'
          ? config.IOS_CODE_PUSH_DEPLOYMENT_KEY
          : config.ANDROID_CODE_PUSH_DEPLOYMENT_KEY,
    })(App);

export default Application;
```

Voila, it works. And you can go back to hating Apple, Xcode and everything associated with them in peace.

**Comment by MRezaBaiat** [comment] 2022-02-01 12:09
i had the same problem but went away after i ran `pod install --repo-update`

**Comment by Gamote** [comment] 2023-05-31 15:56
> Just an FYI what worked in my case:
> 
> After creating the new configuration Staging, simply run `pod deintegrate && pod install` inside the `ios` folder of your Project. CocoaPods will then create all configurations on its own.
> 
> Staging Build -> Success Staging Archive -> Success
> 
> Release Build -> Success Release Archive -> Success

After following this guide [](https://learn.microsoft.com/en-us/appcenter/distribution/codepush/rn-deployment#multi-deployment-testing) we encounter similar errors. They were fixed by `pod deintegrate && pod install`. Thank you.
