### ISSUE TITLE
CocoaPod React Native module is going to be deprecated very soon, and it's moving to npm subsystem

### ISSUE THREAD

**Issue by eugenehp** [Microsoft/react-native-code-push#284] opened 2016-04-10 18:54 UTC
see more here https://github.com/facebook/react-native/issues/6125

<img width="354" alt="screen shot 2016-04-10 at 20 53 25" src="https://cloud.githubusercontent.com/assets/1857263/14412249/55d8b496-ff5e-11e5-8cf3-a73db9cbdd4f.png">

**Comment by lostintangent** [comment] 2016-04-10 20:44
@eugenehp Thanks for the heads up! Do you know if the recommended solution for 3rd party modules is to update their pod spec to reference React via a ":path" dependency similar to how a podfile is expected to reference it?

**Comment by eugenehp** [comment] 2016-04-10 21:19
@lostintangent I'm not sure why you had React dependency in the first place. The RN migrated to different Xcode project template several versions ago.

If you still need it, maybe you can go with this idea – https://github.com/facebook/react-native/issues/6125#issuecomment-188246761

**Comment by lostintangent** [comment] 2016-04-10 21:34
Are you running into an issue using CodePush with CocoaPods or where you just filing this issue as an FYI?

**Comment by eugenehp** [comment] 2016-04-10 21:36
Hey Jonathan,

Just a heads up.
It doesn't break anything big. But I used a manual integration instead of
cocoa pod based one.
So maybe it makes sense to put this migration in your roadmap?

Thanks.

**Comment by lostintangent** [comment] 2016-04-10 21:49
OK cool. Since the CocoaPods-hosted version of RN is being deprecated, but yet they will still be shipping their pod spec with the NPM package, it seems like we could just simply update the CodePush pod spec to refer to the RN pod within the node_modules folder since it would always be at a fixed location. That way, anyone that wants to use CocoaPods to link their projects can continue to do so, and it will work with their local RN version.

We're working with the RNPM team to simplify our installation with it, but I want to make sure our CocoaPods experience works for the folks being native iOS apps with embedded RN views.

**Comment by lostintangent** [comment] 2016-04-25 15:02
@eugenehp I confirmed this morning that CodePush will use whatever version of React that the host app is configured with, so as long as folks use the recommended solution of pointing the React dependency at the folder in node_modules, then we should be resilient to the deprecation of the React package in the CocoaPods registry.

We definitely want to leave our CocoaPods installation instructions for users building native iOS apps with embedded RN views, so I'm going to close this since I believe there aren't any pending issues with our Podspec as is.

Please re-open this if I missed something or you had another thought in mind. I wasn't sure if you were thinking we should remove our CocoaPods docs entirely, which we don't want to do for the aforementioned reason.

Thanks!

**Closed by lostintangent** 2016-04-25 15:02 UTC

**Comment by eugenehp** [comment] 2016-04-25 22:43
Thanks @lostintangent this totally makes sense. Good job!

**Comment by eugenehp** [comment] 2016-05-05 00:56
_Just a note to myself:_

`ios/Podfile` must contain `pod 'React', :path => '../node_modules/react-native'` 
to avoid 
> React has been deprecated

**Comment by lostintangent** [comment] 2016-05-05 01:26
@eugenehp I just updated our [CocoaPods install docs](https://github.com/Microsoft/react-native-code-push/blob/master/README.md#plugin-installation-ios---cocoapods) to reference the need to define the `React` dependency to point at the local NPM installation. Let me know if you think it should be tweaked.

**Comment by eugenehp** [comment] 2016-05-05 01:28
thanks @lostintangent 
I might missed that at the first place. Now it's all good. 👍

**Comment by jeodiong** [comment] 2018-03-23 02:29
pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
