### ISSUE TITLE
Installmode immediate app restart results in black screen.

### ISSUE THREAD

**Issue by jjdp** [Microsoft/react-native-code-push#793] opened 2017-04-12 14:51 UTC
### Description

I have set mine as `App = codePush({installMode: codePush.InstallMode.IMMEDIATE})(App);` so the app will restart when the update is downloaded and installed. The problem is that I'm getting a black screen accompanied with these continuous errors in adb logcat until i manually close the app and then it is fine afterwards when i reopen...

```
04-12 10:43:41.494  3249  3298 I ReactNativeJS: [CodePush] Executing pending restart
04-12 10:43:41.495  3249  3298 I ReactNativeJS: [CodePush] Restarting app
04-12 10:43:41.527  3249  3249 D InCallManager: onPause()
04-12 10:43:41.528  3249  3249 D InCallManager: onDestroy()
04-12 10:43:41.531  3249  3249 D InCallManager: onResume()
04-12 10:43:41.532  3249  3249 D ReactNative: [CodePush] Loading bundle on resume
04-12 10:43:41.533  3249  3330 I FA      : Tag Manager is not found and thus will not be used
04-12 10:43:41.549  3249  3289 E Surface : getSlotFromBufferLocked: unknown buffer: 0xdff66340
04-12 10:43:41.575  3249  3289 W EGL_emulation: eglSurfaceAttrib not implemented
04-12 10:43:41.575  3249  3289 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xf3da0ba0, error=EGL_SUCCESS
04-12 10:43:41.591  3249  3249 D InCallManager: onPause()
04-12 10:43:41.592  3249  3249 D InCallManager: onDestroy()
04-12 10:43:41.595  3249  3249 D InCallManager: onResume()
04-12 10:43:41.595  3249  3249 D ReactNative: [CodePush] Loading bundle on resume
04-12 10:43:41.603  3249  3289 E Surface : getSlotFromBufferLocked: unknown buffer: 0xdff66340
04-12 10:43:41.610  3249  3249 D InCallManager: onPause()
04-12 10:43:41.610  3249  3298 I ReactNativeJS: Running application "sclubber" with appParams: {"initialProps":{},"rootTag":11}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
04-12 10:43:41.611  3249  3298 I ReactNativeJS: [CodePush] Disallowing restarts
04-12 10:43:41.640  3249  3289 W EGL_emulation: eglSurfaceAttrib not implemented
04-12 10:43:41.640  3249  3289 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xf3da0ba0, error=EGL_SUCCESS
04-12 10:43:41.654  3249  3249 D InCallManager: onDestroy()
04-12 10:43:41.656  3249  3249 D InCallManager: onResume()
04-12 10:43:41.657  3249  3249 D ReactNative: [CodePush] Loading bundle on resume
04-12 10:43:41.663  3249  3289 E Surface : getSlotFromBufferLocked: unknown buffer: 0xdff66340
04-12 10:43:41.670  3249  3249 D InCallManager: onPause()
04-12 10:43:41.671  3249  3249 D InCallManager: onDestroy()

```

![video-1492003233](https://cloud.githubusercontent.com/assets/5244520/24964439/dc7e427c-1fd3-11e7-99a8-e9aa73c9a821.gif)

### Additional Information

* react-native-code-push version: v2.0
* react-native version: 0.43.3
* iOS/Android/Windows version: Android
* Does this reproduce on a debug build or release build? BOTH
* Does this reproduce on a simulator, or only on a physical device? BOTH

**Comment by max-mironov** [comment] 2017-04-13 07:41
Hey @jjdp, thanks for reaching us. 
Can you try to reproduce this issue on [our basic sample,](https://github.com/Microsoft/react-native-code-push/tree/master/Examples/CodePushDemoApp), so we've updated it recently and didn't see such kind of problem here.  
Otherwise it would be great if you provide us more info on how you instantiate code-push or other special conditions met in your app.

**Comment by max-mironov** [comment] 2017-04-20 05:05
@jjdp - hi, do you have a chance to look at this?

**Comment by jjdp** [comment] 2017-04-20 06:24
@max-mironov i will take a look at it next week when i have time. it probably is because of other libraries

**Comment by jjdp** [comment] 2017-04-27 11:11
it seems to be caused by proguard because of this warning: `com.facebook.fbui.textlayoutbuilder.proxy.StaticLayoutProxy: can't find referenced method 'StaticLayout(java.lang.CharSequence,int,int,android.text.TextPaint,int,android.text.Layout$Alignment,android.text.TextDirectionHeuristic,float,float,boolean,android.text.TextUtils$TruncateAt,int,int)' in library class android.text.StaticLayout

I have to use one of these:

```
-dontwarn com.facebook.fbui.textlayoutbuilder.proxy.StaticLayoutProxy
-dontwarn android.text.StaticLayout
```

yet i can't build a release version if I don't keep the above. and

```
-keep class com.facebook.fbui.textlayoutbuilder.proxy.StaticLayoutProxy
-keep class android.text.StaticLayout
```

somehow still warns me when i build

**Comment by max-mironov** [comment] 2017-04-27 11:25
@jjdp - thanks for this. Do I get it right that this is related to 3rd party library and not related to code-push and therefore we can close it (as far as it is discussed in another thread)?

**Comment by jjdp** [comment] 2017-04-27 11:38
it isn't related to any 3rd party libs at all. it seems to be an issue with RN or the code-push lib compatibility with the `StaticLayout `or `StaticLayoutProxy`

**Comment by max-mironov** [comment] 2017-04-27 11:49
@jjdp so have you tried to reproduce this without CodePush? Or you have started seen this issue only after CodePush was added to your app?

**Comment by jjdp** [comment] 2017-04-27 11:58
i cant reproduce it without codepush since the api has function to reload RN's bundle

**Comment by jjdp** [comment] 2017-04-27 12:00
the simplest solution i guess would be to turn off proguard but that would be disappointing

**Comment by max-mironov** [comment] 2017-04-27 12:14
@jjdp we are not using `StaticLayoutProxy` dependency at CodePush source code at all unlike RN have [this one](https://github.com/facebook/react-native/search?utf8=%E2%9C%93&q=staticlayoutproxy&type=), so probably the only way to avoid it is to use solution provided by you [above](https://github.com/facebook/react-native/issues/11891). So I believe this issue relates to RN only because [in this example](https://github.com/facebook/react-native/issues/11891) it is reproduced without CodePush.

**Comment by jjdp** [comment] 2017-04-27 12:36
i see. thank you for the info

**Closed** 2017-04-27 12:58 UTC
Labels: waiting-for-clarification
