### ISSUE TITLE
ios codepush error CodePushDownloadProgress

### ISSUE THREAD

**Issue by xlj44400** [Microsoft/react-native-code-push#516] opened 2016-09-16 04:55 UTC
2016-09-16 12:43:04.486 [warn][tid:com.facebook.react.CodePushQueue][RCTEventEmitter.m:54] Sending `CodePushDownloadProgress` with no listeners registered.
2016-09-16 12:43:04.621 [error][tid:com.facebook.react.CodePushQueue][RCTEventEmitter.m:46] `CodePushDownloadProgress` is not a supported event type for CodePush. Supported events are: `(null)`

**Comment by silhouettes** [comment] 2016-09-19 23:51
Which version of RN/CodePush/iOS are you running? We will try to look at this within the next two days.

**Comment by iZaL** [comment] 2016-09-23 05:19
+1

**Comment by silhouettes** [comment] 2016-09-23 17:47
@xlj44400, @iZaL - which versions of RN, CodePush, and iOS are you seeing this on?

**Comment by silhouettes** [comment] 2016-09-24 00:24
@xlj44400, @iZal - I think I've found the code causing the problem and fixed it in #526.

The bug was merged into master but not yet released to npm. Can you confirm that you found this issue while running the CodePush version on our master branch, possibly with the example app? We've traditionally done most of our testing before npm releases, but in future we will aim to do more up-front so that our master branch is stable.

**Comment by silhouettes** [comment] 2016-09-24 00:35
Also, note that once you've synced to the latest commit, you'll need to delete the `react-native-code-push` folder in your app's `node_modules` (`rm -r <AppName>/node_modules/react-native-code-push`), and then run `npm install` again, because npm doesn't automatically detect changes in local file dependencies.

**Comment by hojberg** [comment] 2017-01-13 19:58
Is this supposed to be fixed in 1.16.1-beta ?

**Comment by sergey-akhalkov** [comment] 2017-01-17 13:24
@hojberg - hi! [Changes fixing the issue](https://github.com/Microsoft/react-native-code-push/pull/526/files) are already in [CodePush.m](https://github.com/Microsoft/react-native-code-push/blob/v1.16.1-beta/ios/CodePush/CodePush.m) and [package-mixins.js](https://github.com/Microsoft/react-native-code-push/blob/v1.16.1-beta/package-mixins.js) files belong to `react-native-code-push` having version `1.16.1-beta`.

**Comment by jaggerwang** [comment] 2017-01-23 09:09
Still there!

![image](https://cloud.githubusercontent.com/assets/1255011/22197755/5a2d1812-e18e-11e6-98fc-13192434f679.png)

```javascript
codePush.sync({deploymentKey});
```

I'm using pull #670 , because my RN version is 0.40.0.

**Comment by sergey-akhalkov** [comment] 2017-01-26 17:06
@jaggerwang - hi! I've got the same issue while using `react-native@0.40.0` and `react-native-code-push@1.17.0-beta`, so I've started investigation.

**Comment by jonrh** [comment] 2017-01-26 23:36
@sergey-akhalkov Just to confirm or chime in. I'm new to CodePush but I have the same error running `react-native@0.40.0` and `react-native-code-push@1.17.0-beta`.

I was following the [Plugin Usage](https://github.com/Microsoft/react-native-code-push#plugin-usage) guide (awesome docs btw, good job!). Fetching a new bundle works on app restart but it doesn't work on app resume.

```javascript
// Works correctly after app restarts
MyApp = codePush(MyApp);
```

```javascript
// Doesn't work on app resume, but I may be missing or doing something wrong
let codePushOptions = { checkFrequency: codePush.CheckFrequency.ON_APP_RESUME };
MyApp = codePush(codePushOptions)(MyApp);
```

**Comment by sergey-akhalkov** [comment] 2017-01-27 15:14
@jaggerwang, I've found the place where the warning occurs: https://github.com/facebook/react-native/blob/master/React/Modules/RCTEventEmitter.m#L54
It happens when there are no event listeners registered for `CodePushDownloadProgress` event.
So to go it away you could just implement realization of `codePushDownloadDidProgress` method:
```JavaScript
export default class myapp extends Component {
  codePushDownloadDidProgress(progress) {
        console.log(progress.receivedBytes + " of " + progress.totalBytes + " received.");
  }
  ...
  }
}
```
Please let me know if there are any issues like this one
>2016-09-16 12:43:04.621 [error][tid:com.facebook.react.CodePushQueue][RCTEventEmitter.m:46] CodePushDownloadProgress is not a supported event type for CodePush. Supported events are: (null)

or if I could help you.

**Comment by sergey-akhalkov** [comment] 2017-02-01 09:17
@jonrh, 
>// Doesn't work on app resume, but I may be missing or doing something wrong
let codePushOptions = { checkFrequency: codePush.CheckFrequency.ON_APP_RESUME };
MyApp = codePush(codePushOptions)(MyApp);

Hmm, I've tried this option and it works well for me. Could you please try our [demo app](https://github.com/Microsoft/react-native-code-push/tree/master/Examples/CodePushDemoApp)? It prints CodePush statuses on the screen, so you could see if the option works. Let me know if you have any questions or see any issue.

**Comment by LiuC520** [comment] 2017-02-08 07:21
Me too，

> [CodePush] Disallowing restarts
> [CodePush] Re-allowing restarts
> [CodePush] Checking for update.
> [CodePush] Downloading package.
> Sending `CodePushDownloadProgress` with no listeners registered.
> [CodePush] An unknown error occurred.
> [CodePush] The folder “unzipped” doesn’t exist.

```
let codePushOptions = { checkFrequency: CodePush.CheckFrequency.ON_APP_RESUME };
componentWillMount() {
		CodePush.disallowRestart();//页面加载的禁止重启，在加载完了可以允许重启
	}
	
	componentDidMount(){
		CodePush.allowRestart();//允许重启，否则热更新不会生效
		CodePush.sync({ 
			installMode: CodePush.InstallMode.IMMEDIATE,
			updateDialog: false,
		})
	}
...
Main = CodePush(codePushOptions)(Main);

```

**Comment by sergey-akhalkov** [comment] 2017-02-08 09:10
@LiuC520, seems like it's the issue of another kind. I believe that the root of the problem is not in `Sending CodePushDownloadProgress with no listeners registered.` warning, but you could try to add `codePushDownloadDidProgress` event listener as I've described above and verify if it works. 
In case the error still reproduces, could you please create separate issue and provide us additional info?

**Comment by LiuC520** [comment] 2017-02-08 11:13
Thank you for your suggestion.
I've add codePushDownloadDidProgress event listener,but there is a  new problem:
[](https://github.com/Microsoft/react-native-code-push/issues/695)

**Comment by sergey-akhalkov** [comment] 2017-02-08 12:04
Closing this for now, please feel free to reopen.

**Closed by sergey-akhalkov** 2017-02-08 12:04 UTC
Labels: investigating

**Comment by sospedra** [comment] 2017-11-23 15:17
I've the same problem with 5.2.0-beta and the workaround didn't seems to work.
Tho, honestly I'm not sure were to place it?

**Comment by ruslan-bikkinin** [comment] 2017-11-23 15:51
Hi @sospedra. Please fill new issue as we could discuss your particular case and help you.

**Comment by SudoPlz** [comment] 2018-02-12 11:54
If you're using `CodePush.sync` then the third parameter is what causes that issue (particularly leaving the 3rd param empty)

```
CodePush.sync(
      {}, // codepush options
      (syncStatus) => { // status callback
            // do smthing with the sync status
      },
      (progress) => { // progress callback (Specify a function here otherwise you'll get a warning)
            // do smthing with the progress value
      }
);
```

**Comment by igorferst** [comment] 2018-08-16 13:18
I see the warning in question (`Sending CodePushDownloadProgress with no listeners registered`) with `react-native@0.55.4` and `react-native-code-push@5.4.0`. The suggestion to implement `codePushDownloadDidProgress` indeed removed the warning. Please consider adding a note about this to the setup or troubleshooting instructions.

**Comment by s349856186** [comment] 2018-09-06 01:04
![image](https://user-images.githubusercontent.com/2498958/45129000-a3319c80-b1b3-11e8-9ed4-e15e1640c915.png)
@LiuC520,  @sergey-akhalkov can you help me? It's '[CodePush] The folder “unzipped” doesn’t exist.'

**Comment by chenlongwill** [comment] 2019-03-14 18:26
[CodePush] Downloading package.
YellowBox.js:67 Sending `CodePushDownloadProgress` with no listeners registered.
console.warn @ YellowBox.js:67
logToConsole @ RCTLog.js:47
logIfNoNativeHook @ RCTLog.js:30
__callFunction @ MessageQueue.js:349
(anonymous) @ MessageQueue.js:106
__guard @ MessageQueue.js:297
callFunctionReturnFlushedQueue @ MessageQueue.js:105
(anonymous) @ debuggerWorker.js:72
logging.js:3 [CodePush] An unknown error occurred.
logging.js:3 [CodePush] The update contents failed the data integrity check.

 The update contents failed the data integrity check.

**Comment by faisal-aym** [comment] 2019-03-20 11:35
Hi,

I am getting this error on app install when checking for update. Its coming randomly not on each and every install. I have implemented 
`codePushDownloadDidProgress`

What could cause this error? 

<img width="586" alt="codepush error" src="https://user-images.githubusercontent.com/46099206/54681391-125a5700-4b2e-11e9-83f7-cf5d6406ed24.png">

**Comment by yasirtrimulabs** [comment] 2021-03-22 10:42
How can I remove this warning if my main app is a functional component?
PS: I can't convert it to class component. Thanks

**Comment by kirgy** [comment] 2022-08-22 08:51
Also facing this issue with a functional component.
```log
Sending `CodePushDownloadProgress` with no listeners registered.
```

```ts
const useCodePushSync = (dispatch: ReturnType<typeof useAppDispatch>) => {
  codePush.sync(
    { installMode: codePush.InstallMode.ON_NEXT_RESTART },
    status => {
      let isPending = false;
      if (status === codePush.SyncStatus.UPDATE_INSTALLED) {
        dispatch(setMetaIsPendingRestart(true));
        isPending = true;
      }
      codePush.getUpdateMetadata().then(metadata => {
        dispatch(
          setMeta(
            !metadata
              ? null
              : {
                  label: metadata.label,
                  version: metadata.appVersion,
                  description: metadata.description,
                  isPending: isPending,
                },
          ),
        );
      }),
        (progress: DownloadProgress) => {
          console.log({ progress }); // adding this 3rd param does not resolve the warning
        };
    },
  );
};
```

**Comment by bonnmh** [comment] 2022-08-23 08:06
<img width="986" alt="image" src="https://user-images.githubusercontent.com/48821705/186105944-c8511608-e031-4829-9491-74e08d11ac62.png">
the same problem :(

**Comment by bonnmh** [comment] 2022-08-23 08:07
react-native: 0.64.2
react-native-code-push: 7.0.5
```
   codePush.sync(
            {deploymentKey: CODE_PUSH_DEV_KEY_FINAL},
            (status) => codePushStatusDidChange(status, timeoutSync),
            codePushDownloadDidProgress,
        );
```

**Comment by bonnmh** [comment] 2022-08-23 08:49
<img width="983" alt="image" src="https://user-images.githubusercontent.com/48821705/186115147-5bb03bdb-f683-41b1-a535-2ad5296de016.png">
App has been updated, but status and progress is not working

**Comment by parthindia47** [comment] 2023-04-18 03:54
Is there any update on this ?

**Comment by parthindia47** [comment] 2023-04-18 03:54
> <img alt="image" width="983" src="https://user-images.githubusercontent.com/48821705/186115147-5bb03bdb-f683-41b1-a535-2ad5296de016.png">
> 
> App has been updated, but status and progress is not working

I am having same issue

**Comment by tdinckaya** [comment] 2024-11-11 21:13
same issue
