### ISSUE TITLE
SIGSEGV MainActivity Segmentation violation (invalid memory reference)

### ISSUE THREAD

**Issue by tradebulls** [microsoft/react-native-code-push#2284] opened 2022-06-10 09:46 UTC
We have integrated CodePush and Bugsnag Library in our project. Whenever we rollout a update via CodePush we see there are few crash logs available in Bugsnag(error monitoring tool) which says that the error occurred while CodePush was installing the update.
Below Snapshot is of Breadcrumbs in Bugsnag
<img width="1726" alt="Screenshot 2022-06-10 at 3 14 36 PM" src="https://user-images.githubusercontent.com/54740738/173038815-9f6ed1ab-63e9-4d1b-bae7-45a9bd47c8cf.png">

**Stacktrace for the error given in Bugsnag is** 
SIGSEGV Segmentation violation (invalid memory reference) 
    /apex/com.android.art/lib64/libart.so:3983600 art::JNI<false>::CallStaticObjectMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)
    /apex/com.android.art/lib64/libart.so:3983496 art::JavaVMExt::JniAbort(char const*, char const*)
    /apex/com.android.art/lib64/libart.so:5893052 art::JNI<false>::GetObjectClass(_JNIEnv*, _jobject*)
    /data/app/~~Zhlz-9TNHuujETqo9eTNUQ==/in.tradebulls.trading-gbUKQ3iJdMZWbibcN-UROA==/split_config.arm64_v8a.apk!/lib/arm64-v8a/libreanimated.so:475014607220 _JNIEnv::GetObjectClass(_jobject*)

Sometimes in Stacktrace the error is related to lib-0/libhermes.so:299460 0x7c6c3ce1c4 as well.

We tried to investigate the same at our end but couldn't find anything conclusive. Any help? Thanks in advance

**Comment by jesperjohansson** [comment] 2022-06-17 09:39
Also experiencing this exact issue after upgrading from RN v0.65 to RN v0.68. Looks like RN v0.68 is not officially supported yet though according to readme 😞

**Comment by tradebulls** [comment] 2022-06-28 03:39
Last update of RN Code Push was on 12 October 2021 - v7.04, not sure when can we expect a new update fixing this issue. Any help?

**Comment by tradebulls** [comment] 2022-07-29 03:13
Any update on this issue? Can anyone help?

**Comment by simonmasinde** [comment] 2022-12-16 08:42
We are getting this

**Comment by momguide** [comment] 2023-02-03 02:43
I have the same issue when i have update app with using code push

**Comment by johnny-washswat** [comment] 2023-02-13 06:27
we are also facing the same issue, is there any update please?

**Comment by chakravarthi-bb** [comment] 2023-04-24 14:28
Can someone from Microsoft open the issue please

**Comment by johnny-washswat** [comment] 2023-05-10 10:02
> Last update of RN Code Push was on 12 October 2021 - v7.04, not sure when can we expect a new update fixing this issue. Any help?

@tradebulls have you tried to upgrade the RN version to the maybe over 0.71 something like that?

**Comment by paryanihitesh** [comment] 2023-07-06 08:02
We are on RN 0.69.6 and facing the same issue

**Comment by VietTekmedi** [comment] 2023-09-10 18:36
We are on RN 0.72.3 and facing the same issue

**Comment by daniel-covelli** [comment] 2023-09-14 20:36
Experiencing this on RN 0.70.8

**Comment by DmitriyKirakosyan** [comment] 2023-09-27 07:47
Folks, could you please share more information about the version you are using (RN, CodePush) and the CodePush configuration in your JS and native code.
It would be greatly appreciated if someone could create a minimal demo app that replicates this error.

**Comment by DmitriyKirakosyan** [comment] 2023-10-16 08:53
I'm going to close this issue for now. Please let me know if anyone could create a demo app reproducing the issue.

**Closed by DmitriyKirakosyan** 2023-10-16 08:53 UTC

**Comment by tyson90** [comment] 2024-07-11 13:20
Error still occurs. Looks like "randomly" (about ~10% users in my case)

**Comment by Phong-TH** [comment] 2024-07-19 10:30
@DmitriyKirakosyan We are on RN 0.73.0 and facing the same issue. Crash occurs after the update is installed and the app opens. Trying to open it next time works fine, reinstall works fine. It happens randomly. Here is the stack trace:
```
Crashed: null pointer dereference #1
SIGSEGV 0x00000000000000c0
null pointer dereference: SIGSEGV  0x00000000000000c0
#00 pc 0xc07f4 libhermes.so (BuildId: 4a58d6f9a6461b9da34bc745758a86daa80ee0da)
#01 pc 0xc07e8 libhermes.so (BuildId: 4a58d6f9a6461b9da34bc745758a86daa80ee0da)
#02 pc 0x79430 libhermes.so (BuildId: 4a58d6f9a6461b9da34bc745758a86daa80ee0da)
#03 pc 0x79338 libhermes.so (BuildId: 4a58d6f9a6461b9da34bc745758a86daa80ee0da)
#04 pc 0x243e4 libhermes_executor.so (BuildId: c021a27734493ec1)
#05 pc 0x23734 libhermes_executor.so (BuildId: c021a27734493ec1)
#06 pc 0x1551e8 libwatermelondb-jsi.so (BuildId: a5c514539567624db6fb26ff074902026633be7e)
#07 pc 0x155410 libwatermelondb-jsi.so (BuildId: a5c514539567624db6fb26ff074902026633be7e)
#08 pc 0x7669f772d4
#09 pc 0x766a61ffd8
#10 pc 0x766a10af58
#11 pc 0x766a105b60
#12 pc 0x3cc850 libart.so (BuildId: ddcc440d4609d2099db9d20895487a78)
#13 pc 0xc15ffc libart.so (BuildId: ddcc440d4609d2099db9d20895487a78)
#14 pc 0x766a10468c
#15 pc 0x71c2d278
#16 pc 0x49dd0 libc.so (BuildId: c74277f481a383c87215b672f6465e24)
#17 pc 0x33b3a4 libart.so (BuildId: ddcc440d4609d2099db9d20895487a78)
#18 pc 0x23a5d0 libart.so (BuildId: ddcc440d4609d2099db9d20895487a78)
#19 pc 0x539b64 libart.so (BuildId: ddcc440d4609d2099db9d20895487a78)
#20 pc 0x539bf4 libart.so (BuildId: ddcc440d4609d2099db9d20895487a78)
#21 pc 0x99808 libc.so (BuildId: c74277f481a383c87215b672f6465e24)
#22 pc 0xbe6a8 libc.so (BuildId: c74277f481a383c87215b672f6465e24)
#23 pc 0x527ffc libc.so (BuildId: c74277f481a383c87215b672f6465e24)
#24 pc 0x5b21c libc.so (BuildId: c74277f481a383c87215b672f6465e24)
#25 pc 0xbe5d4 libc.so (BuildId: c74277f481a383c87215b672f6465e24)
#26 pc 0x14f4f4 ld-android.so (BuildId: 0ce2ac9b377b3e85f5e2c9e4d47c652c)
#27 pc 0x14f7f4 ld-android.so (BuildId: 0ce2ac9b377b3e85f5e2c9e4d47c652c)
#28 pc 0x5395b0 libart.so (BuildId: ddcc440d4609d2099db9d20895487a78)
```
Other stack trace in the same device (Pixel 5)
```
null pointer dereference: SIGSEGV  0x00000000000000c0
#00 pc 0x9509c libhermes.so (BuildId: 4a58d6f9a6461b9da34bc745758a86daa80ee0da)
#01 pc 0xc0d70 libhermes.so (BuildId: 4a58d6f9a6461b9da34bc745758a86daa80ee0da)
#02 pc 0xc0d70 libhermes.so (BuildId: 4a58d6f9a6461b9da34bc745758a86daa80ee0da)
#03 pc 0xad540 libhermes.so (BuildId: 4a58d6f9a6461b9da34bc745758a86daa80ee0da)
#04 pc 0x78174 libhermes.so (BuildId: 4a58d6f9a6461b9da34bc745758a86daa80ee0da)
#05 pc 0x25d04 libhermes_executor.so (BuildId: c021a27734493ec1)
#06 pc 0xdd94 libreact_render_runtimescheduler.so (BuildId: e497a78099fdf966)
#07 pc 0x84ab4 libreactnativejni.so (BuildId: 7b860da6d6cadc8b)
#08 pc 0xabe80 libreactnativejni.so (BuildId: 7b860da6d6cadc8b)
#09 pc 0xb49f4 libreactnativejni.so (BuildId: 7b860da6d6cadc8b)
#10 pc 0x89c18 libreactnativejni.so (BuildId: 7b860da6d6cadc8b)
#11 pc 0x17eb0 libfbjni.so (BuildId: 957a087554a7dd659c148d0560674b789d2844d0)
#12 pc 0x17e00 libfbjni.so (BuildId: 957a087554a7dd659c148d0560674b789d2844d0)
```
