### ISSUE TITLE
> Task :react-native-code-push:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by faustoct** [microsoft/react-native-code-push#2199] opened 2021-12-28 17:52 UTC
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
with this package.json run `yarn android`

### Expected Behavior
run on android device 

### Actual Behavior
What actually happens?
```
> Task :react-native-code-push:compileDebugJavaWithJavac FAILED

> Task :react-native-community_geolocation:compileDebugJavaWithJavac

> Task :react-native-admob_admob:compileDebugJavaWithJavac

> Task :react-native-admob-native-ads:compileDebugJavaWithJavac

> Task :react-native-async-storage_async-storage:compileDebugJavaWithJavac

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8.1/userguide/command_line_interface.html#sec:command_line_warnings
652 actionable tasks: 652 executed
An exception has occurred in the compiler (1.8.0_265). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
java.lang.AssertionError: annotationType(): unrecognized Attribute name MODULE (class com.sun.tools.javac.util.UnsharedNameTable$NameImpl)
```

### Reproducible Demo

* Download https://github.com/microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version: ^7.0.4
* react-native version: 0.63.4
* iOS/Android/Windows version: 15.0
* Does this reproduce on a debug build or release build? debug build
* Does this reproduce on a simulator, or only on a physical device? physical device

package.json
````
{
  "name": "BlaBla",
  "main": "index.js",
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@gorhom/bottom-sheet": "^4",
    "@react-native-admob/admob": "^2.0.0",
    "@react-native-async-storage/async-storage": "~1.15.0",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/netinfo": "6.0.0",
    "@react-native-community/slider": "3.0.3",
    "@react-native-firebase/analytics": "^14.1.0",
    "@react-native-firebase/app": "^14.1.0",
    "@react-native-firebase/auth": "^14.1.0",
    "@react-native-firebase/database": "^14.1.0",
    "@react-native-firebase/dynamic-links": "^14.1.0",
    "@react-native-firebase/firestore": "^14.1.0",
    "@react-native-firebase/functions": "^14.1.0",
    "@react-native-firebase/in-app-messaging": "^14.1.0",
    "@react-native-firebase/messaging": "^14.1.0",
    "@react-native-firebase/remote-config": "^14.1.0",
    "@react-native-firebase/storage": "^14.1.0",
    "@react-navigation/bottom-tabs": "^6.0.9",
    "@react-navigation/core": "^6.1.0",
    "@react-navigation/elements": "^1.2.1",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/native-stack": "^6.2.5",
    "@stripe/stripe-react-native": "^0.2.3",
    "algoliasearch": "^4.9.1",
    "appcenter": "^4.2.0",
    "appcenter-analytics": "^4.2.0",
    "appcenter-crashes": "^4.2.0",
    "expo": "^42.0.0",
    "expo-ads-facebook": "~10.1.2",
    "expo-contacts": "~9.2.5",
    "expo-image-picker": "~10.2.2",
    "expo-in-app-purchases": "~11.0.1",
    "expo-linear-gradient": "^9.2.0",
    "expo-location": "~12.1.2",
    "expo-media-library": "~12.1.2",
    "expo-notifications": "~0.12.3",
    "expo-permissions": "^12.1.1",
    "expo-splash-screen": "~0.11.2",
    "expo-status-bar": "~1.0.4",
    "expo-updates": "~0.8.1",
    "firebase-admin": "^9.5.0",
    "geofire-common": "^5.2.0",
    "getstream": "^7.2.10",
    "html-entities": "^2.3.2",
    "jetifier": "^2.0.0",
    "moment": "^2.29.1",
    "native-base": "^2.15.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-instantsearch-native": "^6.11.0",
    "react-native": "0.63.4",
    "react-native-admob-native-ads": "^0.5.0",
    "react-native-cheerio": "^1.0.0-rc.4",
    "react-native-code-push": "^7.0.4",
    "react-native-device-settings": "^1.2.0",
    "react-native-emoji": "^1.8.0",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-gps-state": "git+https://github.com/neuberoliveira/react-native-gps-state#290c8e73cb565d5e858a541ec50e9a65884ee2b6",
    "react-native-reanimated": "~2.2.0",
    "react-native-safe-area-context": "3.2.0",
    "react-native-screens": "^3.10.1",
    "react-native-share": "^5.1.4",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-swipe-cards-deck": "^0.3.0",
    "react-native-swipe-list-view": "^3.2.9",
    "react-native-unimodules": "~0.14.5",
    "react-native-view-shot": "^3.1.2",
    "react-native-web": "~0.13.12",
    "react-native-webview": "11.6.2",
    "spotify-web-api-node": "^5.0.2",
    "stream-analytics": "^3.4.3"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "babel-jest": "~25.2.6",
    "jest": "~25.2.6",
    "react-test-renderer": "~16.13.1"
  },
  "jest": {
    "preset": "react-native"
  },
  "private": true
}
````

**Comment by doomkit** [comment] 2022-01-04 09:46
Duplicate of [#2184](https://github.com/microsoft/react-native-code-push/issues/2184)

**Closed by doomkit** 2022-01-04 09:46 UTC
Labels: duplicate
