### ISSUE TITLE
Use of undeclared identifier 'CodePush

### ISSUE THREAD

**Issue by ma569322307** [microsoft/react-native-code-push#1897] opened 2020-07-02 09:03 UTC
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.
2. 
3.

### Expected Behavior
What you expected to happen?

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

* Download https://github.com/microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version:
* react-native version:
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by alexandergoncharov** [comment] 2020-07-03 11:07
Hi @ma569322307 ,
Thanks for reporting!

Could you please fill description of the issue and provide some details like logs or/and demo app with reproducing issue and reprosteps that help us reproduce and investigate the issue?

**Comment by Shashank2406** [comment] 2020-07-09 12:27
+ 1 
Facing the same issue, created on POC on the following version  

-  "react": "16.13.1",
-  "react-native": "0.63.0",
-  "react-native-code-push": "^6.2.1"

Error
Use of undeclared identifier 'CodePush'

**Comment by Shashank2406** [comment] 2020-07-09 15:16
I have managed to fix it 

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <CodePush/CodePush.h>. ----> Import should be above the #ifdef FB_SONARKIT_ENABLED

**Comment by lchenfox** [comment] 2020-07-30 10:45
@Shashank2406 It works for me. I came to the same issue. It was resolved by moving all `header files` before the line `#ifdef FB_SONARKIT_ENABLED`.

`Error when archiving on iOS`

![error](https://user-images.githubusercontent.com/22851821/88913949-70f02300-d294-11ea-929b-0d3142b6a7b6.png)

Before `moving`

```
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#ifdef FB_SONARKIT_ENABLED
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

#import <RCTJPushModule.h>
#ifdef NSFoundationVersionNumber_iOS_9_x_Max
#import <UserNotifications/UserNotifications.h>
#endif

#import "Orientation.h"
#import <CodePush/CodePush.h>
#import "RNSplashScreen.h"

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif
``` 

After `moving`

```
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#import <RCTJPushModule.h>
#ifdef NSFoundationVersionNumber_iOS_9_x_Max
#import <UserNotifications/UserNotifications.h>
#endif

#import "Orientation.h"
#import <CodePush/CodePush.h>
#import "RNSplashScreen.h"

#ifdef FB_SONARKIT_ENABLED
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif
```

Thanks so much.

**Comment by alexandergoncharov** [comment] 2020-08-07 12:56
Hi all,

Unfortunately, I can't reproduce it but I see that you found a solution.
So, I'm going to close this issue as the issue was resolved.
Please feel free to reopen it if you have any questions.

**Closed** 2020-08-07 12:57 UTC
Labels: resolved
