### ISSUE TITLE
[Q]/[I] How to terminate current process of code-push?

### ISSUE THREAD

**Issue by AlirezaAkbarix** [Microsoft/react-native-code-push#1353] opened 2018-07-18 07:48 UTC
Bad behave when device is disconnected.
### Expected Behavior
Check if is not connected, avoid change status of `codePushStatusDidChange` or at least set `CodePush.SyncStatus.UNKNOWN_ERROR`.

### Actual Behavior
Changes status of `codePushStatusDidChange` to `CodePush.SyncStatus.CHECKING_FOR_UPDATE` and stuck on it.
### [Q]
How to terminate current process (for example for this above situation, be able to terminate after 10s)?

### Environment
OS: macOS High Sierra 10.13
  Node: 8.9.4
  Yarn: 1.7.0
  npm: 6.2.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: ^16.4.1 => 16.4.1
  react-native: 0.55.4 => 0.55.4

**Comment by alexandergoncharov** [comment] 2018-07-19 14:34
Hi @AlirezaAkbarix ,
Thanks for reporting! 

I reproduce this issue only for this case: Started downloading, Lost internet connection(for test I used airplane mode), Stuck on it with `CodePush.SyncStatus.CHECKING_FOR_UPDATE`.

But I can't reproduce your case with stuck on  `CodePush.SyncStatus.CHECKING_FOR_UPDATE`. In this case I got correct error with internet connection.

I'll investigate this issue with stuck on `CodePush.SyncStatus.CHECKING_FOR_UPDATE`.
About `CodePush.SyncStatus.CHECKING_FOR_UPDATE`: Could you please provide detailed repro steps for getting error in this case?

Also please let me know you have any question.

Thanks,
Alexander

**Comment by AlirezaAkbarix** [comment] 2018-07-19 17:49
@alexandergoncharov, Thanks for attention, Beside the problem you mentioned, if user's connection is not stable and reachable (connected to wi-fi, but wi-fi hasn't internet), it stuck again.
For reproducing you can use emulator, turn your mac wi-fi off and then try to `sync`. In such a situation, your emulator has connection, but hasn't internet.

**Comment by alexandergoncharov** [comment] 2018-07-23 19:50
@AlirezaAkbarix , Yeah, I reproduced it. This for described repro steps.

I'll investigate it a little later and let you know. 

Thanks,
Alexander

**Comment by NickToropov** [comment] 2018-07-24 15:14
Hi @AlirezaAkbarix 

> [Q]
> How to terminate current process (for example for this above situation, be able to terminate after 10s)?

Now it's impossible to terminate current process/request. As a workaround you can manually check connection and then call `sync` method.

**Comment by AlirezaAkbarix** [comment] 2018-07-25 03:21
Hi @NickToropov 

> As a workaround you can manually check connection and then call sync method.

I'm doing such a thing already, the problem occurs when device has connection, but the connection hasn't connection to the internet (I mentioned above).

**Comment by NickToropov** [comment] 2018-07-25 12:57
@AlirezaAkbarix, to check if device is connected to the Internet you should make a request and check its status. Any other approaches just say that you have turned on some interfaces and that doesn't guarantee access to required Internet services.

**Comment by NickToropov** [comment] 2018-07-30 10:19
Hi @AlirezaAkbarix, I'll close the issue but if you have any question fill free to reopen this issue or create new one.

**Closed by NickToropov** 2018-07-30 10:19 UTC
Labels: bug, investigating
